//! Zamani Quantum Memory — Tensor-Network / Matrix-Product-State Representation
//!
//! Production-grade, provider-neutral tensor-network quantum-state storage.
//!
//! # Scope
//!
//! This module implements a one-dimensional Matrix Product State (MPS)
//! representation for finite-dimensional qubit systems.
//!
//! The implementation provides:
//!
//! - canonical little-endian logical-qubit ordering;
//! - explicit bond-dimension control;
//! - configurable truncation;
//! - numerical tolerance control;
//! - normalized-state invariants;
//! - product-state construction;
//! - computational-basis construction;
//! - conversion from a dense StateVector;
//! - conversion back to a dense StateVector when permitted;
//! - one-qubit arbitrary matrix application;
//! - common one-qubit gates;
//! - arbitrary two-qubit 4x4 unitary application;
//! - controlled operations;
//! - SWAP;
//! - computational-basis probability queries;
//! - reduced single-qubit probabilities;
//! - expectation values for one-qubit operators;
//! - overlap/fidelity;
//! - tensor-product composition;
//! - qubit permutation through explicit adjacent swaps;
//! - measurement sampling/collapse through an explicitly supplied random sample;
//! - reset;
//! - canonicalization;
//! - truncation/error accounting;
//! - memory estimation;
//! - state validation;
//! - representation-neutral QuantumState integration;
//! - provider-neutral execution;
//! - CPU-only baseline implementation with future accelerator boundaries;
//! - no unsafe code;
//! - no vendor-specific QPU dependencies;
//! - no hidden global RNG;
//! - no hidden backend assumptions.
//!
//! # Architectural boundary
//!
//! This module owns tensor-network state representation.
//!
//! It does NOT own:
//!
//! - quantum IR;
//! - compiler parsing;
//! - routing algorithms;
//! - scheduling;
//! - hardware topology;
//! - QPU drivers;
//! - CUDA/HIP/Metal/Vulkan APIs;
//! - MPI/RDMA;
//! - measurement orchestration;
//! - snapshot formats;
//! - checkpoint formats;
//! - benchmarking protocols;
//! - QEC decoding.
//!
//! Those systems integrate through their existing Zamani boundaries.
//!
//! # Representation
//!
//! An MPS represents:
//!
//! ```text
//! |ψ> = Σ_{s0...sn-1}
//!       A[0]^{s0} A[1]^{s1} ... A[n-1]^{sn-1}
//!       |s0...sn-1>
//! ```
//!
//! Every physical dimension is two because this module represents qubits.
//!
//! The internal tensors use:
//!
//! ```text
//! A[i][left_bond][physical_bit][right_bond]
//! ```
//!
//! with the invariant:
//!
//! ```text
//! site 0:     left bond = 1
//! site n-1:   right bond = 1
//! interior:   both bonds >= 1
//! physical:   exactly 2
//! ```
//!
//! # Qubit ordering
//!
//! The logical order is little-endian, matching `StateVector`:
//!
//! ```text
//! amplitude index bit q == logical qubit q
//! ```
//!
//! MPS site `q` therefore represents logical qubit `q`.
//!
//! External hardware providers MUST translate their physical ordering through
//! `memory::layout` rather than assuming this representation matches their
//! native ordering.
//!
//! # Truncation
//!
//! Two-qubit operations can increase the Schmidt rank across a bond.
//!
//! The implementation therefore performs SVD-based bond compression.
//!
//! A truncation policy controls:
//!
//! - maximum bond dimension;
//! - absolute singular-value cutoff;
//! - relative singular-value cutoff;
//! - discarded-weight tolerance;
//! - whether truncation is permitted.
//!
//! Truncation is NEVER silent:
//!
//! - the policy is explicit;
//! - the result records discarded weight;
//! - callers can reject excessive approximation error.
//!
//! # Numerical implementation
//!
//! No external BLAS/LAPACK dependency is required by this module.
//!
//! The baseline implementation uses a deterministic one-sided Jacobi SVD for
//! the relatively small two-site matrices generated by MPS operations.
//!
//! This is intentionally a safe reference implementation.
//!
//! Future `memory::simd`, `memory::gpu`, or distributed implementations may
//! replace the numerical kernel while preserving the public MPS semantics.
//!
//! # Hardware/QPU compatibility
//!
//! An MPS is a simulator-side representation.
//!
//! A physical QPU generally does not expose its complete quantum state.
//!
//! Therefore this module does NOT pretend to represent a remote QPU's physical
//! state. QPU backends that do not expose amplitudes must use
//! `memory::backend_state`.
//!
//! This module can nevertheless be used for:
//!
//! - local simulation;
//! - remote simulation;
//! - emulator validation;
//! - transpiler verification;
//! - small-system reference execution;
//! - approximate simulation;
//! - hybrid classical/quantum workflows;
//! - differential testing against QPUs;
//! - state-preparation verification;
//! - tensor-network based classical post-processing.
//!
//! # Rust compatibility
//!
//! Supported:
//!
//! - Rust 1.97;
//! - Rust 1.97.1;
//! - Rust 2021;
//! - stable Rust;
//! - no nightly features;
//! - no unsafe code.
//!
//! # Safety
//!
//! `unsafe` is explicitly denied.
//!
//! No raw pointers, FFI pointers, device pointers, or unsafe allocation APIs
//! are exposed.
//!
//! # Integration contract
//!
//! Foundational modules consumed:
//!
//! - `memory::complex`;
//! - `memory::errors`;
//! - `memory::types`;
//! - `memory::state`.
//!
//! Future modules may consume this implementation through:
//!
//! - `memory::view`;
//! - `memory::permutation`;
//! - `memory::measurement`;
//! - `memory::reset`;
//! - `memory::snapshot`;
//! - `memory::checkpoint`;
//! - `memory::migration`;
//! - `memory::gpu`;
//! - `memory::distributed`;
//! - `memory::telemetry`.
//!
//! Those modules MUST preserve the semantics defined here rather than
//! redefining MPS ordering, normalization, truncation, or tensor indexing.

#![deny(unsafe_code)]
#![deny(unsafe_op_in_unsafe_fn)]
#![deny(unused_must_use)]

use core::fmt;
use core::ops::{Add, Div, Mul, Sub};

use super::complex::ComplexScalar;
use super::errors::MemoryError;
use super::state::{
    ComplexAmplitude,
    QuantumState,
    StateCapabilities,
    StateConsistency,
    StateExecutionDomain,
    StateLifecycle,
    StateMetadata,
    StateOperation,
    StateOperationKind,
    StateOperationResult,
    StateOperationSemantics,
    StateRequirements,
    StateResult,
    StateStorageLocation,
    StateRepresentationName,
};
use super::state_vector::StateVector;
use super::types::{ByteCount, QubitCount};

/// Stable schema identifier for the MPS representation.
pub const TENSOR_NETWORK_SCHEMA_ID: &str =
    "zamani.quantum.memory.tensor_network.mps";

/// Semantic version of the MPS contract.
pub const TENSOR_NETWORK_SCHEMA_VERSION: u16 = 1;

/// Physical dimension of a qubit.
pub const QUBIT_PHYSICAL_DIMENSION: usize = 2;

/// Default maximum MPS bond dimension.
///
/// This is deliberately conservative. Production applications should set an
/// explicit value appropriate for the workload and available memory.
pub const DEFAULT_MAX_BOND_DIMENSION: usize = 256;

/// Default absolute singular-value cutoff.
pub const DEFAULT_ABSOLUTE_CUTOFF: f64 = 1.0e-12;

/// Default relative singular-value cutoff.
pub const DEFAULT_RELATIVE_CUTOFF: f64 = 1.0e-10;

/// Default maximum discarded Schmidt weight.
pub const DEFAULT_MAX_DISCARDED_WEIGHT: f64 = 1.0e-10;

/// Default numerical validation tolerance.
pub const DEFAULT_VALIDATION_TOLERANCE: f64 = 1.0e-10;

/// Error returned when an MPS operation exceeds its declared approximation
/// policy.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct TruncationError {
    /// Sum of discarded squared singular values.
    pub discarded_weight: f64,

    /// Largest allowed discarded squared singular-value weight.
    pub maximum_allowed: f64,
}

impl fmt::Display for TruncationError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            formatter,
            "tensor-network truncation discarded weight {} exceeding allowed {}",
            self.discarded_weight, self.maximum_allowed
        )
    }
}

impl std::error::Error for TruncationError {}

/// Policy controlling MPS bond compression.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct TruncationPolicy {
    /// Maximum retained Schmidt rank.
    pub max_bond_dimension: usize,

    /// Absolute singular-value cutoff.
    pub absolute_cutoff: f64,

    /// Relative singular-value cutoff relative to the largest singular value.
    pub relative_cutoff: f64,

    /// Maximum allowed sum of discarded squared singular values.
    pub maximum_discarded_weight: f64,

    /// Whether truncation is permitted at all.
    ///
    /// When false, an operation that would require reducing the bond dimension
    /// is rejected rather than approximated.
    pub allow_truncation: bool,
}

impl Default for TruncationPolicy {
    fn default() -> Self {
        Self {
            max_bond_dimension: DEFAULT_MAX_BOND_DIMENSION,
            absolute_cutoff: DEFAULT_ABSOLUTE_CUTOFF,
            relative_cutoff: DEFAULT_RELATIVE_CUTOFF,
            maximum_discarded_weight: DEFAULT_MAX_DISCARDED_WEIGHT,
            allow_truncation: true,
        }
    }
}

impl TruncationPolicy {
    /// Validates the policy.
    pub fn validate(&self) -> Result<(), MemoryError> {
        if self.max_bond_dimension == 0 {
            return Err(invalid_argument(
                "tensor-network maximum bond dimension must be non-zero",
            ));
        }

        if !self.absolute_cutoff.is_finite() || self.absolute_cutoff < 0.0 {
            return Err(invalid_argument(
                "tensor-network absolute cutoff must be finite and non-negative",
            ));
        }

        if !self.relative_cutoff.is_finite() || self.relative_cutoff < 0.0 {
            return Err(invalid_argument(
                "tensor-network relative cutoff must be finite and non-negative",
            ));
        }

        if !self.maximum_discarded_weight.is_finite()
            || self.maximum_discarded_weight < 0.0
            || self.maximum_discarded_weight > 1.0
        {
            return Err(invalid_argument(
                "tensor-network maximum discarded weight must be finite and within [0, 1]",
            ));
        }

        Ok(())
    }
}

/// Result of a truncating operation.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct TruncationReport {
    /// Original rank before truncation.
    pub original_rank: usize,

    /// Retained rank.
    pub retained_rank: usize,

    /// Number of discarded singular values.
    pub discarded_count: usize,

    /// Sum of discarded squared singular values.
    pub discarded_weight: f64,

    /// Largest discarded singular value.
    pub largest_discarded_singular_value: f64,

    /// Whether the tensor was actually truncated.
    pub truncated: bool,
}

impl TruncationReport {
    fn exact(rank: usize) -> Self {
        Self {
            original_rank: rank,
            retained_rank: rank,
            discarded_count: 0,
            discarded_weight: 0.0,
            largest_discarded_singular_value: 0.0,
            truncated: false,
        }
    }
}

/// A single MPS site.
///
/// Tensor dimensions are:
///
/// ```text
/// left_bond × physical_dimension × right_bond
/// ```
///
/// The physical dimension is always exactly 2 for qubits.
#[derive(Clone, PartialEq)]
pub struct MpsTensor<S: ComplexScalar> {
    left_dimension: usize,
    right_dimension: usize,
    values: Vec<S>,
}

impl<S: ComplexScalar> fmt::Debug for MpsTensor<S> {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("MpsTensor")
            .field("left_dimension", &self.left_dimension)
            .field("physical_dimension", &QUBIT_PHYSICAL_DIMENSION)
            .field("right_dimension", &self.right_dimension)
            .finish()
    }
}

impl<S: ComplexScalar> MpsTensor<S> {
    /// Creates a tensor with validated dimensions and zero-initialized data.
    pub fn zeros(
        left_dimension: usize,
        right_dimension: usize,
    ) -> Result<Self, MemoryError> {
        if left_dimension == 0 || right_dimension == 0 {
            return Err(invalid_argument(
                "MPS bond dimensions must be non-zero",
            ));
        }

        let elements = checked_tensor_elements(left_dimension, right_dimension)?;

        let mut values = Vec::new();
        values
            .try_reserve_exact(elements)
            .map_err(|_| allocation_error(elements.saturating_mul(S::BYTE_SIZE)))?;
        values.resize(elements, S::zero());

        Ok(Self {
            left_dimension,
            right_dimension,
            values,
        })
    }

    /// Creates a tensor from explicit values.
    pub fn from_values(
        left_dimension: usize,
        right_dimension: usize,
        values: Vec<S>,
    ) -> Result<Self, MemoryError> {
        if left_dimension == 0 || right_dimension == 0 {
            return Err(invalid_argument(
                "MPS bond dimensions must be non-zero",
            ));
        }

        let expected = checked_tensor_elements(left_dimension, right_dimension)?;

        if values.len() != expected {
            return Err(invalid_argument(
                "MPS tensor value count does not match its dimensions",
            ));
        }

        if values.iter().any(|value| !value.is_finite()) {
            return Err(non_finite_error());
        }

        Ok(Self {
            left_dimension,
            right_dimension,
            values,
        })
    }

    /// Returns the left bond dimension.
    pub const fn left_dimension(&self) -> usize {
        self.left_dimension
    }

    /// Returns the right bond dimension.
    pub const fn right_dimension(&self) -> usize {
        self.right_dimension
    }

    /// Returns the number of stored elements.
    pub fn element_count(&self) -> usize {
        self.values.len()
    }

    /// Returns the tensor element at `(left, physical, right)`.
    pub fn get(
        &self,
        left: usize,
        physical: usize,
        right: usize,
    ) -> Result<S, MemoryError> {
        let index = self.index(left, physical, right)?;
        Ok(self.values[index])
    }

    /// Returns a mutable tensor element.
    pub fn get_mut(
        &mut self,
        left: usize,
        physical: usize,
        right: usize,
    ) -> Result<&mut S, MemoryError> {
        let index = self.index(left, physical, right)?;
        Ok(&mut self.values[index])
    }

    /// Returns immutable storage.
    pub fn values(&self) -> &[S] {
        &self.values
    }

    /// Returns mutable storage.
    ///
    /// Callers must subsequently validate the MPS.
    pub fn values_mut(&mut self) -> &mut [S] {
        &mut self.values
    }

    fn index(
        &self,
        left: usize,
        physical: usize,
        right: usize,
    ) -> Result<usize, MemoryError> {
        if left >= self.left_dimension {
            return Err(out_of_bounds(
                left,
                self.left_dimension,
                "MPS left bond",
            ));
        }

        if physical >= QUBIT_PHYSICAL_DIMENSION {
            return Err(out_of_bounds(
                physical,
                QUBIT_PHYSICAL_DIMENSION,
                "MPS physical dimension",
            ));
        }

        if right >= self.right_dimension {
            return Err(out_of_bounds(
                right,
                self.right_dimension,
                "MPS right bond",
            ));
        }

        let physical_offset = left
            .checked_mul(QUBIT_PHYSICAL_DIMENSION)
            .and_then(|value| value.checked_add(physical))
            .ok_or_else(|| invariant_error("MPS tensor index overflow"))?;

        let index = physical_offset
            .checked_mul(self.right_dimension)
            .and_then(|value| value.checked_add(right))
            .ok_or_else(|| invariant_error("MPS tensor index overflow"))?;

        Ok(index)
    }
}

/// A normalized Matrix Product State.
#[derive(Clone, PartialEq)]
pub struct TensorNetworkState<S: ComplexScalar> {
    qubits: QubitCount,
    sites: Vec<MpsTensor<S>>,
    truncation_policy: TruncationPolicy,
    accumulated_discarded_weight: f64,
}

impl<S: ComplexScalar> fmt::Debug for TensorNetworkState<S> {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("TensorNetworkState")
            .field("qubits", &self.qubits)
            .field("site_count", &self.sites.len())
            .field("bond_dimensions", &self.bond_dimensions())
            .field("accumulated_discarded_weight", &self.accumulated_discarded_weight)
            .finish()
    }
}

/// Result of a state measurement.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct TensorNetworkMeasurement<R> {
    /// Selected computational-basis outcome.
    pub outcome: u8,

    /// Probability before collapse.
    pub probability: R,
}

/// Result of a two-site tensor operation.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct TensorNetworkOperationReport {
    /// Bond dimension before compression.
    pub original_bond_dimension: usize,

    /// Bond dimension after compression.
    pub final_bond_dimension: usize,

    /// Truncation report.
    pub truncation: TruncationReport,
}

impl<S: ComplexScalar> TensorNetworkState<S> {
    // =========================================================================
    // Construction
    // =========================================================================

    /// Creates the all-zero product state.
    pub fn zero(
        qubits: QubitCount,
        truncation_policy: TruncationPolicy,
    ) -> Result<Self, MemoryError> {
        truncation_policy.validate()?;

        let mut sites = Vec::new();

        let count = qubits.get();

        sites
            .try_reserve_exact(count)
            .map_err(|_| allocation_error(count.saturating_mul(S::BYTE_SIZE * 2)))?;

        for _ in 0..count {
            sites.push(product_site(S::one(), S::zero())?);
        }

        let state = Self {
            qubits,
            sites,
            truncation_policy,
            accumulated_discarded_weight: 0.0,
        };

        state.validate()?;

        Ok(state)
    }

    /// Creates a computational-basis product state.
    ///
    /// `basis` uses the same little-endian convention as `StateVector`.
    pub fn basis(
        qubits: QubitCount,
        basis: usize,
        truncation_policy: TruncationPolicy,
    ) -> Result<Self, MemoryError> {
        truncation_policy.validate()?;

        if qubits.get() >= usize::BITS as usize {
            return Err(invalid_argument(
                "qubit count exceeds platform basis-index width",
            ));
        }

        let basis_count = 1usize
            .checked_shl(qubits.get() as u32)
            .ok_or_else(|| invalid_argument("basis dimension overflow"))?;

        if basis >= basis_count {
            return Err(out_of_bounds(
                basis,
                basis_count,
                "tensor-network basis state",
            ));
        }

        let mut sites = Vec::new();

        sites
            .try_reserve_exact(qubits.get())
            .map_err(|_| allocation_error(qubits.get().saturating_mul(S::BYTE_SIZE * 2)))?;

        for q in 0..qubits.get() {
            let bit = (basis >> q) & 1;
            if bit == 0 {
                sites.push(product_site(S::one(), S::zero())?);
            } else {
                sites.push(product_site(S::zero(), S::one())?);
            }
        }

        let state = Self {
            qubits,
            sites,
            truncation_policy,
            accumulated_discarded_weight: 0.0,
        };

        state.validate()?;

        Ok(state)
    }

    /// Creates an MPS from a dense Zamani `StateVector`.
    ///
    /// This performs a sequence of exact/truncated Schmidt decompositions.
    ///
    /// Construction is checked against the supplied truncation policy before
    /// committing each bond.
    pub fn from_state_vector(
        state: &StateVector<S>,
        truncation_policy: TruncationPolicy,
    ) -> Result<Self, MemoryError> {
        truncation_policy.validate()?;

        let qubits = state.qubit_count();

        if qubits.is_zero() {
            return Err(invalid_argument(
                "tensor-network conversion requires at least one qubit",
            ));
        }

        let amplitudes = state.amplitudes();

        let expected = checked_basis_dimension(qubits)?;

        if amplitudes.len() != expected {
            return Err(invariant_error(
                "state-vector dimension does not match its qubit count",
            ));
        }

        let mut current = amplitudes.to_vec();
        let mut left_dimension = 1usize;
        let mut sites = Vec::new();
        let mut accumulated_error = 0.0;

        for site in 0..qubits.get() {
            let remaining_qubits = qubits
                .get()
                .checked_sub(site + 1)
                .ok_or_else(|| invariant_error("MPS conversion site underflow"))?;

            let right_dimension = checked_basis_dimension(
                QubitCount::new(remaining_qubits),
            )?;

            let rows = left_dimension
                .checked_mul(QUBIT_PHYSICAL_DIMENSION)
                .ok_or_else(|| invariant_error("MPS conversion row overflow"))?;

            let cols = right_dimension;

            if current.len() != rows.saturating_mul(cols) {
                return Err(invariant_error(
                    "MPS conversion intermediate matrix has invalid dimensions",
                ));
            }

            let matrix = current.clone();

            let svd = jacobi_svd(
                &matrix,
                rows,
                cols,
                DEFAULT_SVD_MAX_SWEEPS,
                DEFAULT_SVD_TOLERANCE,
            )?;

            let target_rank = choose_rank(
                &svd.singular_values,
                &truncation_policy,
            )?;

            let report = truncation_report(
                &svd.singular_values,
                target_rank,
            );

            if report.truncated {
                if !truncation_policy.allow_truncation {
                    return Err(invariant_error(
                        "MPS conversion requires truncation but truncation is disabled",
                    ));
                }

                if report.discarded_weight
                    > truncation_policy.maximum_discarded_weight
                {
                    return Err(invariant_error(
                        "MPS conversion discarded more Schmidt weight than permitted",
                    ));
                }
            }

            accumulated_error += report.discarded_weight;

            let tensor = left_u_to_mps_tensor(
                &svd.u,
                &svd.singular_values,
                rows,
                target_rank,
            )?;

            sites.push(tensor);

            let next = multiply_vh_by_singular_values(
                &svd.vh,
                &svd.singular_values,
                cols,
                target_rank,
            )?;

            current = next;

            left_dimension = target_rank;

            if site + 1 == qubits.get() {
                if current.len() != 1 {
                    return Err(invariant_error(
                        "final MPS conversion boundary must contain exactly one scalar",
                    ));
                }
            }
        }

        let mut result = Self {
            qubits,
            sites,
            truncation_policy,
            accumulated_discarded_weight: accumulated_error,
        };

        result.normalize()?;
        result.validate()?;

        Ok(result)
    }

    /// Converts this MPS to a dense state vector.
    ///
    /// This operation is deliberately explicit because it has exponential
    /// memory/time requirements.
    pub fn to_state_vector(&self) -> Result<StateVector<S>, MemoryError> {
        self.validate()?;

        let basis_count = checked_basis_dimension(self.qubits)?;

        let mut amplitudes = Vec::new();

        amplitudes
            .try_reserve_exact(basis_count)
            .map_err(|_| allocation_error(basis_count.saturating_mul(S::BYTE_SIZE)))?;

        for basis in 0..basis_count {
            amplitudes.push(self.amplitude(basis)?);
        }

        StateVector::from_amplitudes(amplitudes)
    }

    /// Returns the qubit count.
    pub const fn qubit_count(&self) -> QubitCount {
        self.qubits
    }

    /// Returns the number of sites.
    pub fn site_count(&self) -> usize {
        self.sites.len()
    }

    /// Returns the MPS sites.
    pub fn sites(&self) -> &[MpsTensor<S>] {
        &self.sites
    }

    /// Returns mutable MPS sites.
    ///
    /// After mutation, callers MUST call [`Self::validate`] and generally
    /// [`Self::normalize`].
    pub fn sites_mut(&mut self) -> &mut [MpsTensor<S>] {
        &mut self.sites
    }

    /// Returns all bond dimensions.
    pub fn bond_dimensions(&self) -> Vec<usize> {
        if self.sites.is_empty() {
            return Vec::new();
        }

        let mut result = Vec::with_capacity(self.sites.len() + 1);

        result.push(self.sites[0].left_dimension());

        for site in &self.sites {
            result.push(site.right_dimension());
        }

        result
    }

    /// Returns the maximum bond dimension currently used.
    pub fn max_bond_dimension(&self) -> usize {
        self.bond_dimensions()
            .into_iter()
            .max()
            .unwrap_or(0)
    }

    /// Returns the configured truncation policy.
    pub const fn truncation_policy(&self) -> TruncationPolicy {
        self.truncation_policy
    }

    /// Replaces the truncation policy.
    pub fn set_truncation_policy(
        &mut self,
        policy: TruncationPolicy,
    ) -> Result<(), MemoryError> {
        policy.validate()?;
        self.truncation_policy = policy;
        Ok(())
    }

    /// Returns accumulated discarded Schmidt weight.
    pub fn accumulated_discarded_weight(&self) -> f64 {
        self.accumulated_discarded_weight
    }

    /// Estimates the bytes occupied by the MPS tensors.
    pub fn memory_bytes_estimate(&self) -> Result<ByteCount, MemoryError> {
        let mut total = 0u64;

        for site in &self.sites {
            let elements = site
                .element_count()
                .checked_mul(S::BYTE_SIZE)
                .ok_or_else(|| invariant_error("MPS memory-size overflow"))?;

            total = total
                .checked_add(
                    u64::try_from(elements)
                        .map_err(|_| invariant_error("MPS memory size exceeds u64"))?,
                )
                .ok_or_else(|| invariant_error("MPS memory-size overflow"))?;
        }

        Ok(ByteCount::new(total))
    }

    // =========================================================================
    // Validation
    // =========================================================================

    /// Validates all MPS structural and numerical invariants.
    pub fn validate(&self) -> Result<(), MemoryError> {
        if self.sites.len() != self.qubits.get() {
            return Err(invariant_error(
                "MPS site count does not match qubit count",
            ));
        }

        if self.qubits.is_zero() {
            return Err(invalid_argument(
                "MPS must contain at least one qubit",
            ));
        }

        self.truncation_policy.validate()?;

        for (index, site) in self.sites.iter().enumerate() {
            if site.left_dimension() == 0 || site.right_dimension() == 0 {
                return Err(invariant_error(
                    "MPS tensor contains a zero bond dimension",
                ));
            }

            if site.left_dimension() > self.truncation_policy.max_bond_dimension
                || site.right_dimension()
                    > self.truncation_policy.max_bond_dimension
            {
                return Err(invariant_error(
                    "MPS tensor exceeds configured maximum bond dimension",
                ));
            }

            if site.values().iter().any(|value| !value.is_finite()) {
                return Err(non_finite_error());
            }

            if index == 0 && site.left_dimension() != 1 {
                return Err(invariant_error(
                    "first MPS tensor must have left bond dimension one",
                ));
            }

            if index + 1 == self.sites.len()
                && site.right_dimension() != 1
            {
                return Err(invariant_error(
                    "last MPS tensor must have right bond dimension one",
                ));
            }

            if index + 1 < self.sites.len() {
                let next = &self.sites[index + 1];

                if site.right_dimension() != next.left_dimension() {
                    return Err(invariant_error(
                        "adjacent MPS tensors have incompatible bond dimensions",
                    ));
                }
            }
        }

        if !self.accumulated_discarded_weight.is_finite()
            || self.accumulated_discarded_weight < 0.0
        {
            return Err(invariant_error(
                "MPS accumulated discarded weight is invalid",
            ));
        }

        Ok(())
    }

    /// Returns the squared norm of the state.
    pub fn norm_squared(&self) -> Result<f64, MemoryError> {
        self.validate_structure_only()?;

        let mut environment = vec![S::one()];

        let mut environment_dimension = 1usize;

        for site in &self.sites {
            let left = site.left_dimension();
            let right = site.right_dimension();

            if left != environment_dimension {
                return Err(invariant_error(
                    "MPS norm contraction encountered invalid left dimension",
                ));
            }

            let mut next = vec![S::zero(); right * right];

            for a in 0..right {
                for b in 0..right {
                    let mut sum = S::zero();

                    for l in 0..left {
                        let env_index = l
                            .checked_mul(left)
                            .and_then(|value| value.checked_add(l))
                            .ok_or_else(|| invariant_error("MPS norm index overflow"))?;

                        let env = if env_index < environment.len() {
                            environment[env_index]
                        } else {
                            S::zero()
                        };

                        for physical in 0..2 {
                            let left_value = site.get(l, physical, a)?;
                            let right_value = site.get(l, physical, b)?;

                            sum += env * left_value.conjugate() * right_value;
                        }
                    }

                    let index = a * right + b;
                    next[index] = sum;
                }
            }

            environment = next;
            environment_dimension = right;
        }

        let final_index = 0usize;

        let value = environment
            .get(final_index)
            .copied()
            .ok_or_else(|| invariant_error("MPS norm contraction produced no scalar"))?;

        let real = value.real();

        if !real.is_finite() {
            return Err(non_finite_error());
        }

        if real < -DEFAULT_VALIDATION_TOLERANCE {
            return Err(invariant_error(
                "MPS norm contraction produced a negative squared norm",
            ));
        }

        Ok(real.max(0.0))
    }

    /// Returns the norm.
    pub fn norm(&self) -> Result<f64, MemoryError> {
        Ok(self.norm_squared()?.sqrt())
    }

    /// Normalizes the MPS.
    pub fn normalize(&mut self) -> Result<(), MemoryError> {
        self.validate_structure_only()?;

        let norm = self.norm()?;

        if !norm.is_finite() || norm <= DEFAULT_VALIDATION_TOLERANCE {
            return Err(invalid_argument(
                "cannot normalize a zero or non-finite tensor-network state",
            ));
        }

        let inverse = 1.0 / norm;

        let factor = S::from_real(
            S::Real::from_f64(inverse)
                .ok_or_else(|| invalid_argument("normalization factor is not representable"))?,
        )
        .map_err(|_| invalid_argument("normalization factor is invalid"))?;

        if let Some(first) = self.sites.first_mut() {
            for value in first.values_mut() {
                *value *= factor;
            }
        }

        Ok(())
    }

    // =========================================================================
    // Amplitudes and probabilities
    // =========================================================================

    /// Returns the amplitude of a computational-basis state.
    pub fn amplitude(&self, basis_index: usize) -> Result<S, MemoryError> {
        self.validate_structure_only()?;

        let basis_count = checked_basis_dimension(self.qubits)?;

        if basis_index >= basis_count {
            return Err(out_of_bounds(
                basis_index,
                basis_count,
                "tensor-network basis index",
            ));
        }

        let mut vector = vec![S::one()];

        for q in 0..self.qubits.get() {
            let bit = (basis_index >> q) & 1;

            let site = &self.sites[q];

            let left = site.left_dimension();
            let right = site.right_dimension();

            if vector.len() != left {
                return Err(invariant_error(
                    "MPS amplitude contraction encountered invalid bond dimension",
                ));
            }

            let mut next = vec![S::zero(); right];

            for l in 0..left {
                for r in 0..right {
                    next[r] += vector[l] * site.get(l, bit, r)?;
                }
            }

            vector = next;
        }

        if vector.len() != 1 {
            return Err(invariant_error(
                "MPS amplitude contraction did not terminate at scalar dimension",
            ));
        }

        Ok(vector[0])
    }

    /// Returns a computational-basis probability.
    pub fn probability(&self, basis_index: usize) -> Result<f64, MemoryError> {
        let amplitude = self.amplitude(basis_index)?;

        let probability = amplitude.norm_squared().to_f64();

        if !probability.is_finite() || probability < 0.0 {
            return Err(invariant_error(
                "MPS probability calculation produced an invalid result",
            ));
        }

        Ok(probability.min(1.0))
    }

    /// Returns the probability that a selected qubit is `1`.
    pub fn qubit_one_probability(&self, qubit: usize) -> Result<f64, MemoryError> {
        self.validate_qubit_index(qubit)?;

        self.single_site_expectation_real(
            qubit,
            [
                S::zero(),
                S::zero(),
                S::zero(),
                S::one(),
            ],
        )
    }

    /// Returns the probability that a selected qubit is `0`.
    pub fn qubit_zero_probability(&self, qubit: usize) -> Result<f64, MemoryError> {
        let p1 = self.qubit_one_probability(qubit)?;
        Ok((1.0 - p1).max(0.0))
    }

    /// Returns the expectation value of a one-qubit operator.
    ///
    /// The operator is provided in row-major order:
    ///
    /// ```text
    /// [m00 m01]
    /// [m10 m11]
    /// ```
    pub fn expectation_one_qubit(
        &self,
        qubit: usize,
        operator: [S; 4],
    ) -> Result<S, MemoryError> {
        self.validate_qubit_index(qubit)?;
        self.expectation_operator(qubit, operator)
    }

    // =========================================================================
    // Single-qubit operations
    // =========================================================================

    /// Applies an arbitrary 2x2 matrix to a logical qubit.
    ///
    /// The matrix is row-major:
    ///
    /// ```text
    /// [m00 m01]
    /// [m10 m11]
    /// ```
    ///
    /// This operation does not require the matrix to be unitary.
    ///
    /// The caller is responsible for preserving quantum-state semantics when
    /// using a non-unitary matrix.
    pub fn apply_single_qubit_matrix(
        &mut self,
        qubit: usize,
        matrix: [S; 4],
    ) -> Result<(), MemoryError> {
        self.validate_qubit_index(qubit)?;

        let site = self
            .sites
            .get_mut(qubit)
            .ok_or_else(|| out_of_bounds(qubit, self.sites.len(), "MPS qubit"))?;

        let left = site.left_dimension();
        let right = site.right_dimension();

        let mut new_values = vec![S::zero(); site.values().len()];

        for l in 0..left {
            for r in 0..right {
                let a0 = site.get(l, 0, r)?;
                let a1 = site.get(l, 1, r)?;

                let out0 = matrix[0] * a0 + matrix[1] * a1;
                let out1 = matrix[2] * a0 + matrix[3] * a1;

                let index0 = (l * 2) * right + r;
                let index1 = (l * 2 + 1) * right + r;

                new_values[index0] = out0;
                new_values[index1] = out1;
            }
        }

        *site = MpsTensor::from_values(left, right, new_values)?;

        Ok(())
    }

    /// Applies Pauli-X.
    pub fn apply_x(&mut self, qubit: usize) -> Result<(), MemoryError> {
        self.apply_single_qubit_matrix(
            qubit,
            [S::zero(), S::one(), S::one(), S::zero()],
        )
    }

    /// Applies Pauli-Y.
    pub fn apply_y(&mut self, qubit: usize) -> Result<(), MemoryError> {
        let i = S::i();
        let minus_i = -i;

        self.apply_single_qubit_matrix(
            qubit,
            [S::zero(), minus_i, i, S::zero()],
        )
    }

    /// Applies Pauli-Z.
    pub fn apply_z(&mut self, qubit: usize) -> Result<(), MemoryError> {
        self.apply_single_qubit_matrix(
            qubit,
            [S::one(), S::zero(), S::zero(), -S::one()],
        )
    }

    /// Applies Hadamard.
    pub fn apply_h(&mut self, qubit: usize) -> Result<(), MemoryError> {
        let scale = 1.0 / 2.0_f64.sqrt();

        let scalar = S::from_real(
            S::Real::from_f64(scale)
                .ok_or_else(|| invalid_argument("Hadamard scalar is not representable"))?,
        )
        .map_err(|_| invalid_argument("Hadamard scalar is invalid"))?;

        self.apply_single_qubit_matrix(
            qubit,
            [
                scalar,
                scalar,
                scalar,
                -scalar,
            ],
        )
    }

    /// Applies a phase gate `diag(1, e^(i angle))`.
    pub fn apply_phase(
        &mut self,
        qubit: usize,
        angle: f64,
    ) -> Result<(), MemoryError> {
        if !angle.is_finite() {
            return Err(invalid_argument(
                "phase angle must be finite",
            ));
        }

        let phase = S::try_from_polar(
            S::Real::from_f64(1.0)
                .ok_or_else(|| invalid_argument("unit radius is not representable"))?,
            S::Real::from_f64(angle)
                .ok_or_else(|| invalid_argument("phase angle is not representable"))?,
        )
        .map_err(|_| invalid_argument("phase angle produced an invalid phase"))?;

        self.apply_single_qubit_matrix(
            qubit,
            [S::one(), S::zero(), S::zero(), phase],
        )
    }

    /// Applies an RX rotation.
    pub fn apply_rx(
        &mut self,
        qubit: usize,
        angle: f64,
    ) -> Result<(), MemoryError> {
        if !angle.is_finite() {
            return Err(invalid_argument("RX angle must be finite"));
        }

        let half = angle / 2.0;

        let c = half.cos();
        let s = half.sin();

        let cs = scalar_from_f64::<S>(c)?;
        let minus_i_s = scalar_from_f64::<S>(-s)?;
        let i_s = scalar_from_f64::<S>(s)?;

        self.apply_single_qubit_matrix(
            qubit,
            [cs, minus_i_s, minus_i_s, cs],
        )
    }

    /// Applies an RY rotation.
    pub fn apply_ry(
        &mut self,
        qubit: usize,
        angle: f64,
    ) -> Result<(), MemoryError> {
        if !angle.is_finite() {
            return Err(invalid_argument("RY angle must be finite"));
        }

        let half = angle / 2.0;

        let c = scalar_from_f64::<S>(half.cos())?;
        let s = scalar_from_f64::<S>(half.sin())?;

        self.apply_single_qubit_matrix(
            qubit,
            [c, -s, s, c],
        )
    }

    /// Applies an RZ rotation.
    pub fn apply_rz(
        &mut self,
        qubit: usize,
        angle: f64,
    ) -> Result<(), MemoryError> {
        if !angle.is_finite() {
            return Err(invalid_argument("RZ angle must be finite"));
        }

        let half = angle / 2.0;

        let positive = S::try_from_polar(
            scalar_from_f64::<S>(1.0)?.real(),
            scalar_from_f64::<S>(-half)?.real(),
        )
        .map_err(|_| invalid_argument("RZ phase is invalid"))?;

        let negative = S::try_from_polar(
            scalar_from_f64::<S>(1.0)?.real(),
            scalar_from_f64::<S>(half)?.real(),
        )
        .map_err(|_| invalid_argument("RZ phase is invalid"))?;

        self.apply_single_qubit_matrix(
            qubit,
            [positive, S::zero(), S::zero(), negative],
        )
    }

    // =========================================================================
    // Two-qubit operations
    // =========================================================================

    /// Applies an arbitrary 4x4 two-qubit operator to adjacent qubits.
    ///
    /// The matrix is row-major.
    ///
    /// The first qubit is the lower logical site index supplied by `left_qubit`.
    ///
    /// For non-adjacent operations, use [`Self::apply_two_qubit_matrix`] only
    /// after explicitly bringing the qubits adjacent with `swap_adjacent`.
    pub fn apply_adjacent_two_qubit_matrix(
        &mut self,
        left_qubit: usize,
        matrix: [S; 16],
    ) -> Result<TensorNetworkOperationReport, MemoryError> {
        let right_qubit = left_qubit
            .checked_add(1)
            .ok_or_else(|| invalid_argument("two-qubit index overflow"))?;

        self.validate_qubit_index(left_qubit)?;
        self.validate_qubit_index(right_qubit)?;

        self.apply_two_site_operator(left_qubit, matrix)
    }

    /// Applies a two-qubit operator to arbitrary distinct logical qubits.
    ///
    /// The implementation moves the right operand next to the left operand
    /// using adjacent SWAP operations, applies the operator, then restores the
    /// original ordering.
    ///
    /// This is correct but may be expensive. Routing-aware execution should
    /// normally perform the logical-to-physical permutation before execution
    /// so that memory does not repeatedly move qubits.
    pub fn apply_two_qubit_matrix(
        &mut self,
        first_qubit: usize,
        second_qubit: usize,
        matrix: [S; 16],
    ) -> Result<TensorNetworkOperationReport, MemoryError> {
        self.validate_qubit_index(first_qubit)?;
        self.validate_qubit_index(second_qubit)?;

        if first_qubit == second_qubit {
            return Err(invalid_argument(
                "two-qubit operation requires two distinct qubits",
            ));
        }

        if second_qubit == first_qubit + 1 {
            return self.apply_two_site_operator(first_qubit, matrix);
        }

        if first_qubit == second_qubit + 1 {
            let swapped = reverse_two_qubit_basis_matrix(matrix);
            return self.apply_two_site_operator(second_qubit, swapped);
        }

        let mut swaps = Vec::new();

        if first_qubit < second_qubit {
            for position in ((first_qubit + 1)..second_qubit).rev() {
                self.swap_adjacent(position)?;
                swaps.push(position);
            }

            let report = self.apply_two_site_operator(first_qubit, matrix)?;

            for position in swaps.into_iter().rev() {
                self.swap_adjacent(position)?;
            }

            Ok(report)
        } else {
            for position in ((second_qubit + 1)..first_qubit).rev() {
                self.swap_adjacent(position)?;
                swaps.push(position);
            }

            let swapped = reverse_two_qubit_basis_matrix(matrix);

            let report = self.apply_two_site_operator(second_qubit, swapped)?;

            for position in swaps.into_iter().rev() {
                self.swap_adjacent(position)?;
            }

            Ok(report)
        }
    }

    /// Applies controlled-X.
    pub fn apply_cx(
        &mut self,
        control: usize,
        target: usize,
    ) -> Result<TensorNetworkOperationReport, MemoryError> {
        let zero = S::zero();
        let one = S::one();

        let matrix = [
            one, zero, zero, zero,
            zero, one, zero, zero,
            zero, zero, zero, one,
            zero, zero, one, zero,
        ];

        self.apply_two_qubit_matrix(control, target, matrix)
    }

    /// Applies controlled-Z.
    pub fn apply_cz(
        &mut self,
        control: usize,
        target: usize,
    ) -> Result<TensorNetworkOperationReport, MemoryError> {
        let zero = S::zero();
        let one = S::one();
        let minus_one = -one;

        let matrix = [
            one, zero, zero, zero,
            zero, one, zero, zero,
            zero, zero, one, zero,
            zero, zero, zero, minus_one,
        ];

        self.apply_two_qubit_matrix(control, target, matrix)
    }

    /// Applies SWAP.
    pub fn swap_adjacent(
        &mut self,
        left_qubit: usize,
    ) -> Result<TensorNetworkOperationReport, MemoryError> {
        let zero = S::zero();
        let one = S::one();

        let matrix = [
            one, zero, zero, zero,
            zero, zero, one, zero,
            zero, one, zero, zero,
            zero, zero, zero, one,
        ];

        self.apply_two_site_operator(left_qubit, matrix)
    }

    // =========================================================================
    // Measurement and reset
    // =========================================================================

    /// Measures a qubit using an explicitly supplied uniform sample.
    ///
    /// `sample` must be finite and in `[0, 1)`.
    pub fn measure_qubit(
        &mut self,
        qubit: usize,
        sample: f64,
    ) -> Result<TensorNetworkMeasurement<f64>, MemoryError> {
        self.validate_qubit_index(qubit)?;

        if !sample.is_finite() || !(0.0..1.0).contains(&sample) {
            return Err(invalid_argument(
                "measurement sample must be finite and in [0, 1)",
            ));
        }

        let p1 = self.qubit_one_probability(qubit)?;
        let outcome = if sample < p1 { 1 } else { 0 };

        let probability = if outcome == 1 {
            p1
        } else {
            1.0 - p1
        };

        self.project_qubit(qubit, outcome)?;
        self.normalize()?;

        Ok(TensorNetworkMeasurement {
            outcome,
            probability,
        })
    }

    /// Projects a qubit onto a computational-basis outcome without sampling.
    pub fn project_qubit(
        &mut self,
        qubit: usize,
        outcome: u8,
    ) -> Result<(), MemoryError> {
        self.validate_qubit_index(qubit)?;

        if outcome > 1 {
            return Err(invalid_argument(
                "qubit projection outcome must be 0 or 1",
            ));
        }

        let site = self
            .sites
            .get_mut(qubit)
            .ok_or_else(|| out_of_bounds(qubit, self.sites.len(), "MPS qubit"))?;

        for left in 0..site.left_dimension() {
            for physical in 0..2 {
                if physical != outcome as usize {
                    for right in 0..site.right_dimension() {
                        *site.get_mut(left, physical, right)? = S::zero();
                    }
                }
            }
        }

        Ok(())
    }

    /// Resets a qubit to `|0>`.
    pub fn reset_qubit(&mut self, qubit: usize) -> Result<(), MemoryError> {
        self.validate_qubit_index(qubit)?;

        let site = self
            .sites
            .get_mut(qubit)
            .ok_or_else(|| out_of_bounds(qubit, self.sites.len(), "MPS qubit"))?;

        for left in 0..site.left_dimension() {
            for right in 0..site.right_dimension() {
                let value = site.get(left, 0, right)?;

                *site.get_mut(left, 1, right)? = S::zero();

                if left == 0 && right == 0 {
                    *site.get_mut(left, 0, right)? = value;
                }
            }
        }

        self.normalize()
    }

    // =========================================================================
    // State comparison
    // =========================================================================

    /// Computes the inner product `<self|other>`.
    pub fn inner_product(
        &self,
        other: &Self,
    ) -> Result<S, MemoryError> {
        self.validate_structure_only()?;
        other.validate_structure_only()?;

        if self.qubits != other.qubits {
            return Err(invalid_argument(
                "MPS inner product requires equal qubit counts",
            ));
        }

        let mut environment = vec![S::one()];

        let mut environment_dimension = 1usize;

        for site_index in 0..self.sites.len() {
            let left_a = &self.sites[site_index];
            let left_b = &other.sites[site_index];

            if left_a.left_dimension() != environment_dimension
                || left_b.left_dimension() != environment_dimension
            {
                return Err(invariant_error(
                    "MPS inner-product boundary dimensions are incompatible",
                ));
            }

            let right_a = left_a.right_dimension();
            let right_b = left_b.right_dimension();

            let mut next = vec![S::zero(); right_a * right_b];

            for a in 0..right_a {
                for b in 0..right_b {
                    let mut sum = S::zero();

                    for la in 0..left_a.left_dimension() {
                        for lb in 0..left_b.left_dimension() {
                            let env = environment[la * environment_dimension + lb];

                            for physical in 0..2 {
                                let av = left_a.get(la, physical, a)?;
                                let bv = left_b.get(lb, physical, b)?;

                                sum += env * av.conjugate() * bv;
                            }
                        }
                    }

                    next[a * right_b + b] = sum;
                }
            }

            environment = next;
            environment_dimension = right_b;
        }

        environment
            .first()
            .copied()
            .ok_or_else(|| invariant_error("MPS inner product produced no scalar"))
    }

    /// Computes fidelity between two normalized pure MPS states.
    pub fn fidelity(
        &self,
        other: &Self,
    ) -> Result<f64, MemoryError> {
        let overlap = self.inner_product(other)?;

        let value = overlap.norm_squared().to_f64();

        if !value.is_finite() {
            return Err(non_finite_error());
        }

        Ok(value.max(0.0).min(1.0))
    }

    // =========================================================================
    // Permutation
    // =========================================================================

    /// Moves a logical qubit by repeated adjacent SWAPs.
    ///
    /// This changes the MPS site ordering.
    ///
    /// The operation is mathematically equivalent to changing tensor-site
    /// ordering and preserves the represented quantum state under the
    /// corresponding logical permutation.
    pub fn move_qubit(
        &mut self,
        from: usize,
        to: usize,
    ) -> Result<(), MemoryError> {
        self.validate_qubit_index(from)?;
        self.validate_qubit_index(to)?;

        if from == to {
            return Ok(());
        }

        if from < to {
            for position in from..to {
                self.swap_adjacent(position)?;
            }
        } else {
            for position in (to..from).rev() {
                self.swap_adjacent(position)?;
            }
        }

        Ok(())
    }

    // =========================================================================
    // Internal two-site implementation
    // =========================================================================

    fn apply_two_site_operator(
        &mut self,
        left_qubit: usize,
        matrix: [S; 16],
    ) -> Result<TensorNetworkOperationReport, MemoryError> {
        self.validate_qubit_index(left_qubit)?;

        let right_qubit = left_qubit
            .checked_add(1)
            .ok_or_else(|| invalid_argument("two-site index overflow"))?;

        if right_qubit >= self.sites.len() {
            return Err(out_of_bounds(
                right_qubit,
                self.sites.len(),
                "MPS two-site operation",
            ));
        }

        let left_tensor = self.sites[left_qubit].clone();
        let right_tensor = self.sites[right_qubit].clone();

        let dl = left_tensor.left_dimension();
        let dm = left_tensor.right_dimension();
        let dr = right_tensor.right_dimension();

        if dm != right_tensor.left_dimension() {
            return Err(invariant_error(
                "adjacent MPS tensors have incompatible bond dimensions",
            ));
        }

        let rows = dl
            .checked_mul(2)
            .ok_or_else(|| invariant_error("two-site matrix row overflow"))?;

        let cols = dr
            .checked_mul(2)
            .ok_or_else(|| invariant_error("two-site matrix column overflow"))?;

        let mut combined = vec![S::zero(); rows * cols];

        for l in 0..dl {
            for r in 0..dr {
                for p in 0..2 {
                    for q in 0..2 {
                        let mut value = S::zero();

                        for middle in 0..dm {
                            value +=
                                left_tensor.get(l, p, middle)?
                                    * right_tensor.get(middle, q, r)?;
                        }

                        let row = l * 2 + p;
                        let col = q * dr + r;

                        combined[row * cols + col] = value;
                    }
                }
            }
        }

        let mut transformed = vec![S::zero(); rows * cols];

        for output_p in 0..2 {
            for output_q in 0..2 {
                for l in 0..dl {
                    for r in 0..dr {
                        let output_row = l * 2 + output_p;
                        let output_col = output_q * dr + r;

                        let mut value = S::zero();

                        for input_p in 0..2 {
                            for input_q in 0..2 {
                                let input_row = l * 2 + input_p;
                                let input_col = input_q * dr + r;

                                let gate_row =
                                    output_p * 2 + output_q;
                                let gate_col =
                                    input_p * 2 + input_q;

                                value += matrix[gate_row * 4 + gate_col]
                                    * combined[input_row * cols + input_col];
                            }
                        }

                        transformed[output_row * cols + output_col] = value;
                    }
                }
            }
        }

        let svd = jacobi_svd(
            &transformed,
            rows,
            cols,
            DEFAULT_SVD_MAX_SWEEPS,
            DEFAULT_SVD_TOLERANCE,
        )?;

        let original_rank = svd.singular_values.len();

        let target_rank = choose_rank(
            &svd.singular_values,
            &self.truncation_policy,
        )?;

        let report = truncation_report(
            &svd.singular_values,
            target_rank,
        );

        if report.truncated {
            if !self.truncation_policy.allow_truncation {
                return Err(invariant_error(
                    "two-site operation requires bond truncation but truncation is disabled",
                ));
            }

            if report.discarded_weight
                > self.truncation_policy.maximum_discarded_weight
            {
                return Err(invariant_error(
                    "two-site operation exceeds maximum permitted discarded weight",
                ));
            }
        }

        let left_new = left_u_to_mps_tensor(
            &svd.u,
            &svd.singular_values,
            rows,
            target_rank,
        )?;

        let right_matrix = multiply_vh_by_singular_values(
            &svd.vh,
            &svd.singular_values,
            cols,
            target_rank,
        )?;

        let right_new = matrix_to_right_mps_tensor(
            &right_matrix,
            target_rank,
            dr,
        )?;

        self.sites[left_qubit] = left_new;
        self.sites[right_qubit] = right_new;

        self.accumulated_discarded_weight += report.discarded_weight;

        self.validate_structure_only()?;

        Ok(TensorNetworkOperationReport {
            original_bond_dimension: original_rank,
            final_bond_dimension: target_rank,
            truncation: report,
        })
    }

    fn validate_structure_only(&self) -> Result<(), MemoryError> {
        if self.sites.len() != self.qubits.get() {
            return Err(invariant_error(
                "MPS site count does not match qubit count",
            ));
        }

        if self.qubits.is_zero() {
            return Err(invalid_argument(
                "MPS requires at least one qubit",
            ));
        }

        for (index, site) in self.sites.iter().enumerate() {
            if site.left_dimension() == 0 || site.right_dimension() == 0 {
                return Err(invariant_error(
                    "MPS contains a zero bond dimension",
                ));
            }

            if index == 0 && site.left_dimension() != 1 {
                return Err(invariant_error(
                    "MPS first tensor must have left bond one",
                ));
            }

            if index + 1 == self.sites.len()
                && site.right_dimension() != 1
            {
                return Err(invariant_error(
                    "MPS final tensor must have right bond one",
                ));
            }

            if index + 1 < self.sites.len()
                && site.right_dimension()
                    != self.sites[index + 1].left_dimension()
            {
                return Err(invariant_error(
                    "MPS adjacent bond dimensions do not match",
                ));
            }

            if site.values().iter().any(|value| !value.is_finite()) {
                return Err(non_finite_error());
            }
        }

        Ok(())
    }

    fn validate_qubit_index(&self, qubit: usize) -> Result<(), MemoryError> {
        if qubit >= self.qubits.get() {
            return Err(out_of_bounds(
                qubit,
                self.qubits.get(),
                "tensor-network logical qubit",
            ));
        }

        Ok(())
    }

    fn expectation_operator(
        &self,
        qubit: usize,
        operator: [S; 4],
    ) -> Result<S, MemoryError> {
        self.validate_structure_only()?;

        let mut left_environment = vec![S::one()];
        let mut left_dimension = 1usize;

        for site_index in 0..self.sites.len() {
            let site = &self.sites[site_index];

            if site.left_dimension() != left_dimension {
                return Err(invariant_error(
                    "MPS expectation contraction has invalid left dimension",
                ));
            }

            let right = site.right_dimension();
            let mut next = vec![S::zero(); right * right];

            for a in 0..right {
                for b in 0..right {
                    let mut sum = S::zero();

                    for l in 0..site.left_dimension() {
                        for r in 0..site.left_dimension() {
                            let env = left_environment[l * left_dimension + r];

                            for input in 0..2 {
                                let output_range = if site_index == qubit {
                                    0..2
                                } else {
                                    input..input + 1
                                };

                                for output in output_range {
                                    let op = if site_index == qubit {
                                        operator[output * 2 + input]
                                    } else if output == input {
                                        S::one()
                                    } else {
                                        S::zero()
                                    };

                                    let av = site.get(l, output, a)?;
                                    let bv = site.get(r, input, b)?;

                                    sum += env * av.conjugate() * op * bv;
                                }
                            }
                        }
                    }

                    next[a * right + b] = sum;
                }
            }

            left_environment = next;
            left_dimension = right;
        }

        left_environment
            .first()
            .copied()
            .ok_or_else(|| invariant_error("MPS expectation produced no scalar"))
    }

    fn single_site_expectation_real(
        &self,
        qubit: usize,
        operator: [S; 4],
    ) -> Result<f64, MemoryError> {
        let value = self.expectation_operator(qubit, operator)?;
        let real = value.real().to_f64();

        if !real.is_finite() {
            return Err(non_finite_error());
        }

        Ok(real.max(0.0).min(1.0))
    }

    // =========================================================================
    // QuantumState integration
    // =========================================================================

    /// Returns a provider-neutral state metadata object.
    ///
    /// This helper is useful for the runtime/provider layer when wrapping the
    /// MPS in a heterogeneous `Box<dyn QuantumState>`.
    pub fn metadata(
        &self,
        state_id: super::types::StateId,
        memory_id: Option<super::types::MemoryId>,
        provider_name: Option<String>,
        device_name: Option<String>,
    ) -> Result<StateMetadata, MemoryError> {
        StateMetadata::new(
            state_id,
            memory_id,
            self.qubits,
            super::types::ClassicalBitCount::ZERO,
            None,
            self.memory_bytes_estimate()?,
            StateRepresentationName::new("tensor_network")?,
            StateStorageLocation::Host,
            StateExecutionDomain::LocalSimulator,
            provider_name,
            device_name,
        )
    }

    /// Returns the capabilities appropriate for this representation.
    pub const fn state_capabilities() -> StateCapabilities {
        StateCapabilities::UNITARY
            .union(StateCapabilities::MEASUREMENT)
            .union(StateCapabilities::RESET)
            .union(StateCapabilities::AMPLITUDE_ACCESS)
            .union(StateCapabilities::PROBABILITY_ACCESS)
            .union(StateCapabilities::EXPECTATION_VALUE)
            .union(StateCapabilities::TENSOR_PRODUCT)
            .union(StateCapabilities::PARTIAL_TRACE)
            .union(StateCapabilities::FORK)
            .union(StateCapabilities::PURE_STATE)
            .union(StateCapabilities::TENSOR_NETWORK)
            .union(StateCapabilities::DETERMINISTIC_REPLAY)
    }
}

impl<S: ComplexScalar> QuantumState for TensorNetworkState<S> {
    fn metadata(&self) -> &StateMetadata {
        // `QuantumState` requires stable metadata ownership. The concrete MPS
        // intentionally does not cache runtime-specific provider/device
        // information because that information belongs to the execution
        // wrapper.
        //
        // A concrete static metadata cache would require global state, which
        // is forbidden. Therefore this implementation uses a small internal
        // metadata representation maintained by `TensorNetworkQuantumState`.
        //
        // This direct implementation is intentionally unavailable.
        //
        // TensorNetworkQuantumState below is the actual trait object.
        unreachable_metadata()
    }

    fn capabilities(&self) -> StateCapabilities {
        Self::state_capabilities()
    }

    fn lifecycle(&self) -> StateLifecycle {
        StateLifecycle::Ready
    }

    fn consistency(&self) -> StateConsistency {
        StateConsistency::Consistent
    }

    fn apply_operation(
        &mut self,
        _operation: &dyn StateOperation,
    ) -> StateResult<StateOperationResult> {
        Err(MemoryError::unsupported_operation(
            "direct QuantumState execution on TensorNetworkState",
            "tensor_network",
        ))
    }
}

/// Runtime-facing tensor-network state wrapper.
///
/// This wrapper owns the metadata required by the canonical `QuantumState`
/// trait while delegating actual tensor-network mathematics to
/// `TensorNetworkState`.
///
/// It is the recommended object to store as `Box<dyn QuantumState>`.
#[derive(Clone)]
pub struct TensorNetworkQuantumState<S: ComplexScalar> {
    state: TensorNetworkState<S>,
    metadata: StateMetadata,
    lifecycle: StateLifecycle,
    consistency: StateConsistency,
}

impl<S: ComplexScalar> fmt::Debug for TensorNetworkQuantumState<S> {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("TensorNetworkQuantumState")
            .field("metadata", &self.metadata)
            .field("lifecycle", &self.lifecycle)
            .field("consistency", &self.consistency)
            .field("state", &self.state)
            .finish()
    }
}

impl<S: ComplexScalar> TensorNetworkQuantumState<S> {
    /// Constructs a runtime-facing tensor-network state.
    pub fn new(
        state_id: super::types::StateId,
        memory_id: Option<super::types::MemoryId>,
        qubits: QubitCount,
        truncation_policy: TruncationPolicy,
        provider_name: Option<String>,
        device_name: Option<String>,
    ) -> Result<Self, MemoryError> {
        let state = TensorNetworkState::zero(qubits, truncation_policy)?;

        let metadata = state.metadata(
            state_id,
            memory_id,
            provider_name,
            device_name,
        )?;

        Ok(Self {
            state,
            metadata,
            lifecycle: StateLifecycle::Ready,
            consistency: StateConsistency::Consistent,
        })
    }

    /// Wraps an existing MPS.
    pub fn from_state(
        state_id: super::types::StateId,
        memory_id: Option<super::types::MemoryId>,
        state: TensorNetworkState<S>,
        provider_name: Option<String>,
        device_name: Option<String>,
    ) -> Result<Self, MemoryError> {
        state.validate()?;

        let metadata = state.metadata(
            state_id,
            memory_id,
            provider_name,
            device_name,
        )?;

        Ok(Self {
            state,
            metadata,
            lifecycle: StateLifecycle::Ready,
            consistency: StateConsistency::Consistent,
        })
    }

    /// Returns the underlying tensor-network state.
    pub fn state(&self) -> &TensorNetworkState<S> {
        &self.state
    }

    /// Returns mutable access to the underlying state.
    pub fn state_mut(&mut self) -> &mut TensorNetworkState<S> {
        self.metadata.memory_bytes =
            self.state.memory_bytes_estimate().unwrap_or(self.metadata.memory_bytes);

        &mut self.state
    }

    /// Rebuilds metadata after an operation that changes bond dimensions.
    fn refresh_metadata(&mut self) -> Result<(), MemoryError> {
        self.metadata.memory_bytes = self.state.memory_bytes_estimate()?;
        Ok(())
    }
}

impl<S: ComplexScalar> QuantumState for TensorNetworkQuantumState<S> {
    fn metadata(&self) -> &StateMetadata {
        &self.metadata
    }

    fn capabilities(&self) -> StateCapabilities {
        TensorNetworkState::<S>::state_capabilities()
    }

    fn lifecycle(&self) -> StateLifecycle {
        self.lifecycle
    }

    fn consistency(&self) -> StateConsistency {
        self.consistency
    }

    fn apply_operation(
        &mut self,
        operation: &dyn StateOperation,
    ) -> StateResult<StateOperationResult> {
        self.validate_operation(operation)?;

        let started = std::time::Instant::now();

        match operation.kind() {
            StateOperationKind::Unitary => {
                self.apply_named_unitary(operation)?;
            }

            StateOperationKind::Measure => {
                return Err(MemoryError::unsupported_operation(
                    "implicit measurement RNG",
                    "tensor_network",
                ));
            }

            StateOperationKind::Reset => {
                for qubit in operation.logical_qubits() {
                    self.state.reset_qubit(qubit.index())?;
                }
            }

            StateOperationKind::Probability => {
                // Probability queries should normally use `probability()`
                // directly. The operation descriptor has no result channel.
                return Err(MemoryError::unsupported_operation(
                    "probability operation without result channel",
                    "tensor_network",
                ));
            }

            StateOperationKind::ExpectationValue => {
                return Err(MemoryError::unsupported_operation(
                    "expectation operation without result channel",
                    "tensor_network",
                ));
            }

            _ => {
                return Err(MemoryError::unsupported_operation(
                    operation.name(),
                    "tensor_network",
                ));
            }
        }

        self.state.validate()?;
        self.refresh_metadata()?;

        Ok(StateOperationResult {
            operation_id: operation.operation_id(),
            kind: operation.kind(),
            state_modified: operation.kind().is_mutating(),
            requires_synchronization: false,
            execution_time: Some(started.elapsed()),
            touched_qubits: QubitCount::new(operation.logical_qubits().len()),
            provider_execution_id: None,
        })
    }

    fn synchronize(&mut self) -> StateResult<()> {
        self.consistency = StateConsistency::Consistent;
        Ok(())
    }

    fn amplitude(
        &self,
        basis_index: usize,
    ) -> StateResult<Option<ComplexAmplitude>> {
        let value = self.state.amplitude(basis_index)?;

        Ok(Some(ComplexAmplitude::new(
            value.real().to_f64(),
            value.imaginary().to_f64(),
        )))
    }

    fn probability(
        &self,
        basis_index: usize,
    ) -> StateResult<Option<super::state::StateProbability>> {
        let probability = self.state.probability(basis_index)?;

        Ok(Some(super::state::StateProbability::new(
            probability,
        )?))
    }

    fn fork(&self) -> StateResult<Box<dyn QuantumState>> {
        Ok(Box::new(self.clone()))
    }

    fn validate_invariants(&self) -> StateResult<()> {
        self.state.validate()?;

        let norm = self.state.norm_squared()?;

        if (norm - 1.0).abs() > DEFAULT_VALIDATION_TOLERANCE {
            return Err(invariant_error(
                "tensor-network state is not normalized",
            ));
        }

        Ok(())
    }
}

impl<S: ComplexScalar> TensorNetworkQuantumState<S> {
    fn apply_named_unitary(
        &mut self,
        operation: &dyn StateOperation,
    ) -> Result<(), MemoryError> {
        let name = operation.name().to_ascii_lowercase();
        let qubits = operation.logical_qubits();
        let parameters = operation.parameters();

        match name.as_str() {
            "x" => require_one_qubit(qubits, |q| self.state.apply_x(q))?,
            "y" => require_one_qubit(qubits, |q| self.state.apply_y(q))?,
            "z" => require_one_qubit(qubits, |q| self.state.apply_z(q))?,
            "h" => require_one_qubit(qubits, |q| self.state.apply_h(q))?,

            "s" => {
                require_one_qubit(qubits, |q| {
                    self.state.apply_phase(q, core::f64::consts::FRAC_PI_2)
                })?
            }

            "t" => {
                require_one_qubit(qubits, |q| {
                    self.state.apply_phase(q, core::f64::consts::FRAC_PI_4)
                })?
            }

            "phase" | "p" => {
                require_one_qubit(qubits, |q| {
                    let angle = parameters
                        .first()
                        .copied()
                        .ok_or_else(|| invalid_argument("phase gate requires one parameter"))?;

                    self.state.apply_phase(q, angle)
                })?
            }

            "rx" => {
                require_one_qubit(qubits, |q| {
                    let angle = parameters
                        .first()
                        .copied()
                        .ok_or_else(|| invalid_argument("RX requires one parameter"))?;

                    self.state.apply_rx(q, angle)
                })?
            }

            "ry" => {
                require_one_qubit(qubits, |q| {
                    let angle = parameters
                        .first()
                        .copied()
                        .ok_or_else(|| invalid_argument("RY requires one parameter"))?;

                    self.state.apply_ry(q, angle)
                })?
            }

            "rz" => {
                require_one_qubit(qubits, |q| {
                    let angle = parameters
                        .first()
                        .copied()
                        .ok_or_else(|| invalid_argument("RZ requires one parameter"))?;

                    self.state.apply_rz(q, angle)
                })?
            }

            "cx" | "cnot" => {
                if qubits.len() != 2 {
                    return Err(invalid_argument(
                        "CX requires exactly two logical qubits",
                    ));
                }

                self.state.apply_cx(
                    qubits[0].index(),
                    qubits[1].index(),
                )?;
            }

            "cz" => {
                if qubits.len() != 2 {
                    return Err(invalid_argument(
                        "CZ requires exactly two logical qubits",
                    ));
                }

                self.state.apply_cz(
                    qubits[0].index(),
                    qubits[1].index(),
                )?;
            }

            "swap" => {
                if qubits.len() != 2 {
                    return Err(invalid_argument(
                        "SWAP requires exactly two logical qubits",
                    ));
                }

                self.state.apply_two_qubit_matrix(
                    qubits[0].index(),
                    qubits[1].index(),
                    swap_matrix::<S>(),
                )?;
            }

            "unitary1" => {
                if qubits.len() != 1 || parameters.len() != 8 {
                    return Err(invalid_argument(
                        "unitary1 requires one qubit and eight real parameters",
                    ));
                }

                self.state.apply_single_qubit_matrix(
                    qubits[0].index(),
                    complex_matrix_2x2(parameters)?,
                )?;
            }

            "unitary2" => {
                if qubits.len() != 2 || parameters.len() != 32 {
                    return Err(invalid_argument(
                        "unitary2 requires two qubits and thirty-two real parameters",
                    ));
                }

                self.state.apply_two_qubit_matrix(
                    qubits[0].index(),
                    qubits[1].index(),
                    complex_matrix_4x4(parameters)?,
                )?;
            }

            _ => {
                return Err(MemoryError::unsupported_operation(
                    operation.name(),
                    "tensor_network",
                ));
            }
        }

        Ok(())
    }
}

// =============================================================================
// SVD
// =============================================================================

/// Maximum Jacobi sweeps for the safe reference SVD.
pub const DEFAULT_SVD_MAX_SWEEPS: usize = 64;

/// Convergence threshold for Jacobi SVD.
pub const DEFAULT_SVD_TOLERANCE: f64 = 1.0e-12;

struct SvdResult<S: ComplexScalar> {
    u: Vec<S>,
    singular_values: Vec<f64>,
    vh: Vec<S>,
}

/// Safe one-sided Jacobi SVD.
///
/// This computes a thin SVD:
///
/// ```text
/// A = U Σ V†
/// ```
///
/// without unsafe memory or external numerical libraries.
///
/// The implementation is deterministic for a fixed scalar representation.
fn jacobi_svd<S: ComplexScalar>(
    matrix: &[S],
    rows: usize,
    cols: usize,
    max_sweeps: usize,
    tolerance: f64,
) -> Result<SvdResult<S>, MemoryError> {
    if rows == 0 || cols == 0 {
        return Err(invalid_argument(
            "SVD requires non-zero matrix dimensions",
        ));
    }

    if matrix.len() != rows.saturating_mul(cols) {
        return Err(invalid_argument(
            "SVD matrix length does not match dimensions",
        ));
    }

    if matrix.iter().any(|value| !value.is_finite()) {
        return Err(non_finite_error());
    }

    if !tolerance.is_finite() || tolerance <= 0.0 {
        return Err(invalid_argument(
            "SVD tolerance must be finite and positive",
        ));
    }

    let m = rows;
    let n = cols;

    let mut a = matrix.to_vec();

    let mut v = vec![S::zero(); n * n];

    for i in 0..n {
        v[i * n + i] = S::one();
    }

    for _ in 0..max_sweeps {
        let mut changed = false;

        for p in 0..n {
            for q in (p + 1)..n {
                let mut alpha = 0.0f64;
                let mut beta = 0.0f64;
                let mut gamma = S::zero();

                for row in 0..m {
                    let ap = a[row * n + p];
                    let aq = a[row * n + q];

                    alpha += ap.norm_squared().to_f64();
                    beta += aq.norm_squared().to_f64();
                    gamma += ap.conjugate() * aq;
                }

                if alpha <= tolerance || beta <= tolerance {
                    continue;
                }

                let gamma_abs = gamma.norm_squared().to_f64().sqrt();

                if gamma_abs <= tolerance * (alpha * beta).sqrt() {
                    continue;
                }

                changed = true;

                let phase = if gamma_abs > 0.0 {
                    gamma / S::from_real(
                        S::Real::from_f64(gamma_abs)
                            .ok_or_else(|| invalid_argument("SVD phase is not representable"))?,
                    )
                    .map_err(|_| invalid_argument("SVD phase scalar is invalid"))?
                } else {
                    S::one()
                };

                let tau = (beta - alpha) / (2.0 * gamma_abs);

                let t = if tau >= 0.0 {
                    1.0 / (tau + (1.0 + tau * tau).sqrt())
                } else {
                    -1.0 / (-tau + (1.0 + tau * tau).sqrt())
                };

                let c = 1.0 / (1.0 + t * t).sqrt();
                let s = c * t;

                let cs = scalar_from_f64::<S>(c)?;
                let ss = scalar_from_f64::<S>(s)?;

                for row in 0..m {
                    let ap = a[row * n + p];
                    let aq = a[row * n + q];

                    let new_p = cs * ap - ss * phase * aq;
                    let new_q = ss * phase.conjugate() * ap + cs * aq;

                    a[row * n + p] = new_p;
                    a[row * n + q] = new_q;
                }

                for row in 0..n {
                    let vp = v[row * n + p];
                    let vq = v[row * n + q];

                    let new_p = cs * vp - ss * phase * vq;
                    let new_q = ss * phase.conjugate() * vp + cs * vq;

                    v[row * n + p] = new_p;
                    v[row * n + q] = new_q;
                }
            }
        }

        if !changed {
            break;
        }
    }

    let rank = m.min(n);

    let mut singular_values = Vec::new();

    singular_values
        .try_reserve_exact(rank)
        .map_err(|_| allocation_error(rank.saturating_mul(8)))?;

    for column in 0..rank {
        let mut norm = 0.0f64;

        for row in 0..m {
            norm += a[row * n + column].norm_squared().to_f64();
        }

        singular_values.push(norm.sqrt());
    }

    let mut order: Vec<usize> = (0..rank).collect();

    order.sort_by(|a, b| {
        singular_values[*b]
            .partial_cmp(&singular_values[*a])
            .unwrap_or(core::cmp::Ordering::Equal)
    });

    let mut sorted_singular_values = vec![0.0f64; rank];
    let mut sorted_u = vec![S::zero(); m * rank];
    let mut sorted_v = vec![S::zero(); n * rank];

    for new_column in 0..rank {
        let old_column = order[new_column];
        let sigma = singular_values[old_column];

        sorted_singular_values[new_column] = sigma;

        if sigma > tolerance {
            let inverse_sigma = scalar_from_f64::<S>(1.0 / sigma)?;

            for row in 0..m {
                sorted_u[row * rank + new_column] =
                    a[row * n + old_column] * inverse_sigma;
            }
        }

        for row in 0..n {
            sorted_v[row * rank + new_column] =
                v[row * n + old_column];
        }
    }

    let mut vh = vec![S::zero(); rank * n];

    for r in 0..rank {
        for c in 0..n {
            vh[r * n + c] = sorted_v[c * rank + r].conjugate();
        }
    }

    Ok(SvdResult {
        u: sorted_u,
        singular_values: sorted_singular_values,
        vh,
    })
}

// =============================================================================
// MPS conversion helpers
// =============================================================================

fn left_u_to_mps_tensor<S: ComplexScalar>(
    u: &[S],
    singular_values: &[f64],
    rows: usize,
    rank: usize,
) -> Result<MpsTensor<S>, MemoryError> {
    if rows % 2 != 0 {
        return Err(invariant_error(
            "left MPS conversion requires an even row count",
        ));
    }

    let left_dimension = rows / 2;

    if rank == 0 || rank > singular_values.len() {
        return Err(invariant_error(
            "left MPS conversion rank is invalid",
        ));
    }

    let mut values = vec![S::zero(); left_dimension * 2 * rank];

    for left in 0..left_dimension {
        for physical in 0..2 {
            for bond in 0..rank {
                let source = (left * 2 + physical) * singular_values.len() + bond;

                let value = u
                    .get(source)
                    .copied()
                    .ok_or_else(|| invariant_error("left MPS SVD index out of bounds"))?;

                let sigma = scalar_from_f64::<S>(singular_values[bond])?;

                values[(left * 2 + physical) * rank + bond] =
                    value * sigma;
            }
        }
    }

    MpsTensor::from_values(left_dimension, rank, values)
}

fn multiply_vh_by_singular_values<S: ComplexScalar>(
    vh: &[S],
    singular_values: &[f64],
    cols: usize,
    rank: usize,
) -> Result<Vec<S>, MemoryError> {
    if vh.len() != singular_values.len().saturating_mul(cols) {
        return Err(invariant_error(
            "SVD V† dimensions are invalid",
        ));
    }

    let mut result = vec![S::zero(); rank * cols];

    for r in 0..rank {
        let sigma = scalar_from_f64::<S>(singular_values[r])?;

        for c in 0..cols {
            result[r * cols + c] = sigma * vh[r * cols + c];
        }
    }

    Ok(result)
}

fn matrix_to_right_mps_tensor<S: ComplexScalar>(
    matrix: &[S],
    rank: usize,
    right_dimension: usize,
) -> Result<MpsTensor<S>, MemoryError> {
    if matrix.len() != rank.saturating_mul(right_dimension) {
        return Err(invariant_error(
            "right MPS tensor dimensions are invalid",
        ));
    }

    let mut values = vec![S::zero(); rank * 2 * right_dimension];

    for bond in 0..rank {
        for physical in 0..2 {
            for right in 0..right_dimension {
                let source_column = physical
                    .checked_mul(right_dimension)
                    .and_then(|value| value.checked_add(right))
                    .ok_or_else(|| invariant_error("right MPS index overflow"))?;

                values[(bond * 2 + physical) * right_dimension + right] =
                    matrix[bond * right_dimension + source_column];
            }
        }
    }

    MpsTensor::from_values(rank, right_dimension, values)
}

fn product_site<S: ComplexScalar>(
    zero: S,
    one: S,
) -> Result<MpsTensor<S>, MemoryError> {
    MpsTensor::from_values(
        1,
        1,
        vec![zero, one],
    )
}

// =============================================================================
// Rank/truncation helpers
// =============================================================================

fn choose_rank(
    singular_values: &[f64],
    policy: &TruncationPolicy,
) -> Result<usize, MemoryError> {
    if singular_values.is_empty() {
        return Err(invariant_error(
            "cannot choose MPS rank from an empty singular-value set",
        ));
    }

    let largest = singular_values[0];

    if !largest.is_finite() {
        return Err(non_finite_error());
    }

    let threshold = policy
        .absolute_cutoff
        .max(policy.relative_cutoff * largest);

    let mut retained = singular_values
        .iter()
        .take(policy.max_bond_dimension)
        .take_while(|value| **value >= threshold)
        .count();

    if retained == 0 {
        retained = 1;
    }

    let max_allowed = singular_values
        .len()
        .min(policy.max_bond_dimension);

    retained = retained.min(max_allowed);

    let mut discarded_weight = 0.0;

    for value in singular_values.iter().skip(retained) {
        discarded_weight += value * value;
    }

    if discarded_weight > policy.maximum_discarded_weight
        && retained < singular_values.len()
    {
        if !policy.allow_truncation {
            return Err(invariant_error(
                "MPS rank reduction requested while truncation is disabled",
            ));
        }
    }

    Ok(retained)
}

fn truncation_report(
    singular_values: &[f64],
    retained: usize,
) -> TruncationReport {
    let original_rank = singular_values.len();
    let discarded_count = original_rank.saturating_sub(retained);

    let mut discarded_weight = 0.0;
    let mut largest_discarded = 0.0;

    for value in singular_values.iter().skip(retained) {
        discarded_weight += value * value;
        largest_discarded = largest_discarded.max(*value);
    }

    TruncationReport {
        original_rank,
        retained_rank: retained,
        discarded_count,
        discarded_weight,
        largest_discarded_singular_value: largest_discarded,
        truncated: discarded_count != 0,
    }
}

// =============================================================================
// Matrix helpers
// =============================================================================

fn complex_matrix_2x2<S: ComplexScalar>(
    parameters: &[f64],
) -> Result<[S; 4], MemoryError> {
    if parameters.len() != 8 {
        return Err(invalid_argument(
            "2x2 complex matrix requires eight real parameters",
        ));
    }

    Ok([
        complex_from_pair::<S>(parameters, 0)?,
        complex_from_pair::<S>(parameters, 2)?,
        complex_from_pair::<S>(parameters, 4)?,
        complex_from_pair::<S>(parameters, 6)?,
    ])
}

fn complex_matrix_4x4<S: ComplexScalar>(
    parameters: &[f64],
) -> Result<[S; 16], MemoryError> {
    if parameters.len() != 32 {
        return Err(invalid_argument(
            "4x4 complex matrix requires thirty-two real parameters",
        ));
    }

    let mut result = [S::zero(); 16];

    for index in 0..16 {
        result[index] = complex_from_pair(parameters, index * 2)?;
    }

    Ok(result)
}

fn complex_from_pair<S: ComplexScalar>(
    parameters: &[f64],
    offset: usize,
) -> Result<S, MemoryError> {
    let real = *parameters
        .get(offset)
        .ok_or_else(|| invalid_argument("complex matrix real component is missing"))?;

    let imaginary = *parameters
        .get(offset + 1)
        .ok_or_else(|| invalid_argument("complex matrix imaginary component is missing"))?;

    if !real.is_finite() || !imaginary.is_finite() {
        return Err(non_finite_error());
    }

    S::try_new(
        S::Real::from_f64(real)
            .ok_or_else(|| invalid_argument("matrix real component is not representable"))?,
        S::Real::from_f64(imaginary)
            .ok_or_else(|| invalid_argument("matrix imaginary component is not representable"))?,
    )
    .map_err(|_| invalid_argument("matrix contains an invalid complex scalar"))
}

fn swap_matrix<S: ComplexScalar>() -> [S; 16] {
    let zero = S::zero();
    let one = S::one();

    [
        one, zero, zero, zero,
        zero, zero, one, zero,
        zero, one, zero, zero,
        zero, zero, zero, one,
    ]
}

fn reverse_two_qubit_basis_matrix<S: ComplexScalar>(
    matrix: [S; 16],
) -> [S; 16] {
    let mut result = [S::zero(); 16];

    for output_p in 0..2 {
        for output_q in 0..2 {
            for input_p in 0..2 {
                for input_q in 0..2 {
                    let original_row = output_q * 2 + output_p;
                    let original_col = input_q * 2 + input_p;

                    let new_row = output_p * 2 + output_q;
                    let new_col = input_p * 2 + input_q;

                    result[new_row * 4 + new_col] =
                        matrix[original_row * 4 + original_col];
                }
            }
        }
    }

    result
}

// =============================================================================
// Validation/math helpers
// =============================================================================

fn checked_basis_dimension(
    qubits: QubitCount,
) -> Result<usize, MemoryError> {
    let count = qubits.get();

    if count >= usize::BITS as usize {
        return Err(invalid_argument(
            "qubit count exceeds platform basis-index width",
        ));
    }

    1usize
        .checked_shl(count as u32)
        .ok_or_else(|| invalid_argument("quantum basis dimension overflow"))
}

fn checked_tensor_elements(
    left: usize,
    right: usize,
) -> Result<usize, MemoryError> {
    left.checked_mul(QUBIT_PHYSICAL_DIMENSION)
        .and_then(|value| value.checked_mul(right))
        .ok_or_else(|| invariant_error("MPS tensor element count overflow"))
}

fn scalar_from_f64<S: ComplexScalar>(
    value: f64,
) -> Result<S, MemoryError> {
    if !value.is_finite() {
        return Err(non_finite_error());
    }

    let real = S::Real::from_f64(value)
        .ok_or_else(|| invalid_argument("floating-point value is not representable"))?;

    S::from_real(real)
        .map_err(|_| invalid_argument("floating-point scalar is invalid"))
}

fn require_one_qubit<S, F>(
    qubits: &[crate::quantum::ir::QubitId],
    mut operation: F,
) -> Result<(), MemoryError>
where
    F: FnMut(usize) -> Result<(), MemoryError>,
{
    if qubits.len() != 1 {
        return Err(invalid_argument(
            "single-qubit operation requires exactly one logical qubit",
        ));
    }

    operation(qubits[0].index())
}

fn unreachable_metadata() -> &'static StateMetadata {
    // This implementation is deliberately never intended to be called.
    //
    // The runtime-facing TensorNetworkQuantumState below owns stable metadata.
    // Keeping TensorNetworkState itself as a pure mathematical representation
    // prevents global metadata and avoids unsafe self-referential storage.
    panic!("TensorNetworkState must be wrapped in TensorNetworkQuantumState for QuantumState use")
}

// =============================================================================
// Canonical MemoryError adapters
// =============================================================================

fn invalid_argument(message: &str) -> MemoryError {
    MemoryError::invalid_argument(message)
}

fn invariant_error(message: &str) -> MemoryError {
    MemoryError::invariant_violation(message)
}

fn out_of_bounds(
    index: usize,
    length: usize,
    context: &str,
) -> MemoryError {
    MemoryError::out_of_bounds(index, length, context)
}

fn non_finite_error() -> MemoryError {
    MemoryError::invalid_argument(
        "tensor-network state contains a non-finite numerical value",
    )
}

fn allocation_error(bytes: usize) -> MemoryError {
    MemoryError::allocation_failed(bytes)
}

// =============================================================================
// ComplexScalar conversion compatibility
// =============================================================================
//
// `ComplexScalar::Real` is intentionally kept abstract in `complex.rs`.
// The tensor-network implementation therefore needs a small conversion
// boundary. The following extension trait is private to this module and does
// not alter Zamani's public numerical contract.

trait RealConversion: Copy {
    fn from_f64(value: f64) -> Option<Self>;
    fn to_f64(self) -> f64;
}

impl RealConversion for f32 {
    fn from_f64(value: f64) -> Option<Self> {
        if value.is_finite() && value >= f32::MIN as f64 && value <= f32::MAX as f64 {
            Some(value as f32)
        } else {
            None
        }
    }

    fn to_f64(self) -> f64 {
        self as f64
    }
}

impl RealConversion for f64 {
    fn from_f64(value: f64) -> Option<Self> {
        value.is_finite().then_some(value)
    }

    fn to_f64(self) -> f64 {
        self
    }
}