//! Zamani Quantum Benchmarking — Execution Contract
//!
//! Production execution boundary for the quantum benchmarking subsystem.
//!
//! # Purpose
//!
//! This module defines the backend-independent contract between a benchmark
//! experiment and the system that actually executes its workload.
//!
//! It deliberately does NOT:
//!
//! - generate benchmark circuits;
//! - implement Quantum Volume;
//! - implement randomized benchmarking;
//! - implement XEB;
//! - perform statistical analysis;
//! - own hardware-provider SDKs;
//! - perform network I/O;
//! - perform compilation/transpilation;
//! - perform routing;
//! - perform scheduling;
//! - contain benchmark-specific mathematics;
//! - assume that every quantum system is a gate-model QPU;
//! - assume that every backend returns bitstring counts.
//!
//! Those responsibilities belong to their owning subsystems.
//!
//! # Architectural position
//!
//! ```text
//! Zamani source / benchmark definition
//!             │
//!             ▼
//!     benchmarking::core
//!             │
//!             ▼
//!     BenchmarkExperiment
//!             │
//!             ▼
//!     BenchmarkExecutor
//!             │
//!       ┌─────┴─────┐
//!       ▼           ▼
//!   simulator      hardware
//!       │           │
//!       └─────┬─────┘
//!             ▼
//!      ExecutionResponse
//!             │
//!             ▼
//!     benchmarking::core
//!             │
//!             ▼
//!       observations
//!             │
//!             ▼
//!       statistics
//!             │
//!             ▼
//!         metrics
//!             │
//!             ▼
//!      BenchmarkResult
//! ```
//!
//! # Dependency direction
//!
//! ```text
//! benchmarking::execution
//!          │
//!          ▼
//! quantum::ir
//!
//! benchmarking::execution
//!          │
//!          ▼
//! quantum::hardware
//!
//! quantum::ir
//!      X
//!      │
//!      └────> benchmarking
//! ```
//!
//! The Quantum IR remains the canonical representation of logical quantum
//! programs. Benchmarking consumes IR; it does not redefine it.
//!
//! The hardware layer remains responsible for backend identity, capabilities,
//! topology, calibration, and hardware-specific execution adapters.
//!
//! # Production requirements
//!
//! This module is designed around the following invariants:
//!
//! 1. Every execution request has a stable request identity.
//! 2. Every response identifies the request and backend that produced it.
//! 3. A request is validated before execution.
//! 4. Invalid requests fail explicitly rather than being silently modified.
//! 5. Partial execution is represented explicitly.
//! 6. Cancellation is cooperative and observable.
//! 7. Timeouts are explicit.
//! 8. Retries are not performed implicitly by this layer.
//! 9. Backend-specific metadata is preserved rather than discarded.
//! 10. Raw observations remain available for independent re-analysis.
//! 11. Execution timing is captured independently from benchmark statistics.
//! 12. The execution layer never prints diagnostics directly.
//! 13. The execution layer has no process-global mutable state.
//! 14. No unsafe code is required.
//! 15. The API is synchronous so that Zamani does not require a particular
//!     async runtime.
//!
//! # Rust compatibility
//!
//! Target: Rust 1.97.1 / Rust 2021.
//!
//! No nightly features are required.
//! No additional crate dependency is required by this file.

use std::collections::BTreeMap;
use std::fmt;
use std::sync::{
    atomic::{AtomicBool, Ordering},
    Arc,
};
use std::time::{Duration, Instant};

use crate::quantum::ir::QuantumCircuit;

// =============================================================================
// Constants
// =============================================================================

/// Stable schema version for execution requests.
pub const EXECUTION_REQUEST_SCHEMA_VERSION: u32 = 1;

/// Stable schema version for execution responses.
pub const EXECUTION_RESPONSE_SCHEMA_VERSION: u32 = 1;

/// Stable execution-contract version.
///
/// This changes only when the semantic contract of this module changes.
pub const EXECUTION_CONTRACT_VERSION: u32 = 1;

/// Default number of shots when a caller explicitly chooses the default.
pub const DEFAULT_SHOTS: usize = 1;

/// Default execution timeout.
///
/// This is deliberately conservative and is a safety default, not a claim
/// about hardware latency.
pub const DEFAULT_EXECUTION_TIMEOUT: Duration = Duration::from_secs(300);

// =============================================================================
// Request identity
// =============================================================================

/// Stable identifier for one execution request.
///
/// A request ID is an opaque value at this layer. It may be generated by the
/// benchmark engine, scheduler, runtime, or caller.
///
/// IDs are intentionally strings so that distributed providers can preserve
/// provider-native IDs without changing the execution contract.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct ExecutionRequestId(String);

impl ExecutionRequestId {
    /// Creates an execution request ID.
    ///
    /// Empty IDs are rejected because they make correlation and provenance
    /// unreliable.
    pub fn new(value: impl Into<String>) -> Result<Self, ExecutionError> {
        let value = value.into();

        if value.trim().is_empty() {
            return Err(ExecutionError::InvalidRequestId);
        }

        Ok(Self(value))
    }

    /// Returns the identifier as a string slice.
    pub fn as_str(&self) -> &str {
        &self.0
    }

    /// Consumes the identifier and returns its underlying string.
    pub fn into_string(self) -> String {
        self.0
    }
}

impl fmt::Display for ExecutionRequestId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.0)
    }
}

// =============================================================================
// Backend identity
// =============================================================================

/// Stable identifier for the backend selected for an execution.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct ExecutionBackendId(String);

impl ExecutionBackendId {
    pub fn new(value: impl Into<String>) -> Result<Self, ExecutionError> {
        let value = value.into();

        if value.trim().is_empty() {
            return Err(ExecutionError::InvalidBackendId);
        }

        Ok(Self(value))
    }

    pub fn as_str(&self) -> &str {
        &self.0
    }

    pub fn into_string(self) -> String {
        self.0
    }
}

impl fmt::Display for ExecutionBackendId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.0)
    }
}

// =============================================================================
// Execution mode
// =============================================================================

/// Type of quantum execution target.
///
/// The benchmarking framework must not assume that every target is a physical
/// QPU. This enum allows the same execution contract to cover the major
/// execution classes used by Zamani.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum ExecutionMode {
    /// Exact or approximate state-vector simulation.
    StateVectorSimulator,

    /// Density-matrix simulation.
    DensityMatrixSimulator,

    /// Stabilizer-oriented simulation.
    StabilizerSimulator,

    /// Tensor-network simulation.
    TensorNetworkSimulator,

    /// Hardware-emulating simulator.
    Emulator,

    /// Physical gate-model quantum processor.
    Qpu,

    /// Analog quantum execution.
    Analog,

    /// Quantum annealing execution.
    Annealing,

    /// Sampling-oriented execution.
    Sampler,

    /// Logical/fault-tolerant quantum execution.
    LogicalQpu,

    /// Repository/application-specific execution provider.
    Custom,
}

impl ExecutionMode {
    /// Returns whether this mode is expected to execute on physical quantum
    /// hardware.
    pub fn is_physical(self) -> bool {
        matches!(
            self,
            Self::Qpu | Self::Analog | Self::Annealing | Self::LogicalQpu
        )
    }

    /// Returns whether this mode is a simulator.
    pub fn is_simulator(self) -> bool {
        matches!(
            self,
            Self::StateVectorSimulator
                | Self::DensityMatrixSimulator
                | Self::StabilizerSimulator
                | Self::TensorNetworkSimulator
        )
    }

    /// Returns whether this mode is expected to return sampled observations.
    pub fn is_sampling_oriented(self) -> bool {
        matches!(
            self,
            Self::Sampler
                | Self::Qpu
                | Self::LogicalQpu
                | Self::Annealing
        )
    }
}

// =============================================================================
// Measurement mode
// =============================================================================

/// Requested observation representation.
///
/// Execution must preserve what the backend actually returned. This enum
/// describes the requested representation, not a promise that every backend
/// can provide it.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum MeasurementMode {
    /// Classical bitstring counts.
    Counts,

    /// Normalized classical probabilities.
    Probabilities,

    /// Expectation values of requested observables.
    ExpectationValues,

    /// State-vector data where supported.
    StateVector,

    /// Density-matrix data where supported.
    DensityMatrix,

    /// Raw analog samples.
    AnalogSamples,

    /// Annealing/sample energies and associated states.
    AnnealingSamples,

    /// Quantum error-correction syndrome data.
    Syndrome,

    /// Backend-native/raw observation representation.
    BackendNative,
}

// =============================================================================
// Shot specification
// =============================================================================

/// Number of repetitions requested from a backend.
///
/// This is kept separate from `ExecutionRequest` so that batching and future
/// adaptive execution can reuse the same validated type.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct ShotCount(usize);

impl ShotCount {
    /// Creates a validated shot count.
    pub fn new(value: usize) -> Result<Self, ExecutionError> {
        if value == 0 {
            return Err(ExecutionError::InvalidShotCount);
        }

        Ok(Self(value))
    }

    /// Returns the number of shots.
    pub fn get(self) -> usize {
        self.0
    }
}

impl Default for ShotCount {
    fn default() -> Self {
        Self(DEFAULT_SHOTS)
    }
}

// =============================================================================
// Execution timeout
// =============================================================================

/// Validated execution timeout.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct ExecutionTimeout(Duration);

impl ExecutionTimeout {
    pub fn new(duration: Duration) -> Result<Self, ExecutionError> {
        if duration.is_zero() {
            return Err(ExecutionError::InvalidTimeout);
        }

        Ok(Self(duration))
    }

    pub fn duration(self) -> Duration {
        self.0
    }
}

impl Default for ExecutionTimeout {
    fn default() -> Self {
        Self(DEFAULT_EXECUTION_TIMEOUT)
    }
}

// =============================================================================
// Cancellation
// =============================================================================

/// Cooperative cancellation token for benchmark execution.
///
/// Cancellation is deliberately cooperative. The executor implementation must
/// periodically inspect the token and return `ExecutionError::Cancelled`.
///
/// This type does not force a particular threading or async model.
#[derive(Debug, Clone)]
pub struct CancellationToken {
    cancelled: Arc<AtomicBool>,
}

impl CancellationToken {
    /// Creates a non-cancelled token.
    pub fn new() -> Self {
        Self {
            cancelled: Arc::new(AtomicBool::new(false)),
        }
    }

    /// Requests cancellation.
    pub fn cancel(&self) {
        self.cancelled.store(true, Ordering::Release);
    }

    /// Returns whether cancellation was requested.
    pub fn is_cancelled(&self) -> bool {
        self.cancelled.load(Ordering::Acquire)
    }

    /// Returns an execution error if cancellation was requested.
    pub fn check(&self) -> Result<(), ExecutionError> {
        if self.is_cancelled() {
            Err(ExecutionError::Cancelled)
        } else {
            Ok(())
        }
    }
}

impl Default for CancellationToken {
    fn default() -> Self {
        Self::new()
    }
}

// =============================================================================
// Execution request
// =============================================================================

/// Production execution request.
///
/// This is the canonical object passed to a `BenchmarkExecutor`.
///
/// The request contains a canonical Zamani Quantum IR circuit. Benchmark
/// generators produce the circuit; the execution layer consumes it.
///
/// Backend-specific providers should translate this object into their own
/// provider-native request without changing the benchmark semantics.
#[derive(Debug, Clone)]
pub struct ExecutionRequest {
    /// Execution-contract schema version.
    pub schema_version: u32,

    /// Stable request identity.
    pub request_id: ExecutionRequestId,

    /// Target backend.
    pub backend_id: ExecutionBackendId,

    /// Requested execution mode.
    pub execution_mode: ExecutionMode,

    /// Canonical Zamani Quantum IR circuit.
    pub circuit: Arc<QuantumCircuit>,

    /// Requested number of shots.
    pub shots: ShotCount,

    /// Requested observation representation.
    pub measurement_mode: MeasurementMode,

    /// Optional deterministic seed.
    ///
    /// This is a request-level seed. A backend may reject it when deterministic
    /// seeding is unsupported. The executor must never silently replace it.
    pub seed: Option<u64>,

    /// Maximum permitted execution duration.
    pub timeout: ExecutionTimeout,

    /// Cooperative cancellation token.
    pub cancellation: CancellationToken,

    /// Optional benchmark/experiment tags.
    ///
    /// Tags are metadata only. They must never change execution semantics.
    pub tags: BTreeMap<String, String>,

    /// Provider-neutral request metadata.
    pub metadata: BTreeMap<String, String>,
}

impl ExecutionRequest {
    /// Creates a request using production defaults.
    pub fn new(
        request_id: ExecutionRequestId,
        backend_id: ExecutionBackendId,
        execution_mode: ExecutionMode,
        circuit: Arc<QuantumCircuit>,
    ) -> Result<Self, ExecutionError> {
        if circuit_is_empty(&circuit) {
            return Err(ExecutionError::EmptyCircuit);
        }

        Ok(Self {
            schema_version: EXECUTION_REQUEST_SCHEMA_VERSION,
            request_id,
            backend_id,
            execution_mode,
            circuit,
            shots: ShotCount::default(),
            measurement_mode: MeasurementMode::Counts,
            seed: None,
            timeout: ExecutionTimeout::default(),
            cancellation: CancellationToken::default(),
            tags: BTreeMap::new(),
            metadata: BTreeMap::new(),
        })
    }

    /// Sets the shot count.
    pub fn with_shots(
        mut self,
        shots: usize,
    ) -> Result<Self, ExecutionError> {
        self.shots = ShotCount::new(shots)?;
        Ok(self)
    }

    /// Sets the observation mode.
    pub fn with_measurement_mode(
        mut self,
        mode: MeasurementMode,
    ) -> Self {
        self.measurement_mode = mode;
        self
    }

    /// Sets the deterministic seed.
    pub fn with_seed(mut self, seed: u64) -> Self {
        self.seed = Some(seed);
        self
    }

    /// Sets the execution timeout.
    pub fn with_timeout(
        mut self,
        timeout: Duration,
    ) -> Result<Self, ExecutionError> {
        self.timeout = ExecutionTimeout::new(timeout)?;
        Ok(self)
    }

    /// Adds an execution tag.
    pub fn with_tag(
        mut self,
        key: impl Into<String>,
        value: impl Into<String>,
    ) -> Result<Self, ExecutionError> {
        let key = validate_metadata_key(key.into())?;
        let value = validate_metadata_value(value.into())?;

        self.tags.insert(key, value);

        Ok(self)
    }

    /// Adds request metadata.
    pub fn with_metadata(
        mut self,
        key: impl Into<String>,
        value: impl Into<String>,
    ) -> Result<Self, ExecutionError> {
        let key = validate_metadata_key(key.into())?;
        let value = validate_metadata_value(value.into())?;

        self.metadata.insert(key, value);

        Ok(self)
    }

    /// Validates the complete request.
    ///
    /// This validation is deliberately provider-neutral. Backend capability
    /// validation belongs to the selected executor/backend.
    pub fn validate(&self) -> Result<(), ExecutionError> {
        if self.schema_version != EXECUTION_REQUEST_SCHEMA_VERSION {
            return Err(ExecutionError::UnsupportedSchemaVersion {
                kind: SchemaKind::Request,
                version: self.schema_version,
            });
        }

        if self.request_id.as_str().trim().is_empty() {
            return Err(ExecutionError::InvalidRequestId);
        }

        if self.backend_id.as_str().trim().is_empty() {
            return Err(ExecutionError::InvalidBackendId);
        }

        if circuit_is_empty(&self.circuit) {
            return Err(ExecutionError::EmptyCircuit);
        }

        if self.shots.get() == 0 {
            return Err(ExecutionError::InvalidShotCount);
        }

        if self.timeout.duration().is_zero() {
            return Err(ExecutionError::InvalidTimeout);
        }

        validate_metadata_map(&self.tags)?;
        validate_metadata_map(&self.metadata)?;

        Ok(())
    }
}

// =============================================================================
// Execution status
// =============================================================================

/// Terminal or non-terminal state of an execution.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ExecutionStatus {
    /// Request accepted but execution has not begun.
    Accepted,

    /// Execution is currently running.
    Running,

    /// Execution completed successfully.
    Completed,

    /// Execution completed with only part of the requested work.
    Partial,

    /// Execution was cancelled.
    Cancelled,

    /// Execution exceeded its timeout.
    TimedOut,

    /// Execution failed.
    Failed,
}

impl ExecutionStatus {
    /// Returns whether this status represents a terminal state.
    pub fn is_terminal(self) -> bool {
        matches!(
            self,
            Self::Completed
                | Self::Partial
                | Self::Cancelled
                | Self::TimedOut
                | Self::Failed
        )
    }

    /// Returns whether observations are potentially usable.
    pub fn may_contain_observations(self) -> bool {
        matches!(
            self,
            Self::Completed | Self::Partial
        )
    }
}

// =============================================================================
// Execution timing
// =============================================================================

/// Timing information collected by the execution layer.
///
/// These values deliberately remain separate. Benchmark analysis can later
/// decide which timing dimensions matter.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ExecutionTiming {
    /// Time spent waiting before provider execution began.
    pub queue_time: Option<Duration>,

    /// Time spent submitting the request.
    pub submission_time: Option<Duration>,

    /// Time spent in actual provider execution.
    pub execution_time: Option<Duration>,

    /// Time spent retrieving results.
    pub result_collection_time: Option<Duration>,

    /// End-to-end wall-clock time observed by the executor.
    pub total_time: Duration,
}

impl ExecutionTiming {
    /// Creates timing information for a completed local execution.
    pub fn completed(total_time: Duration) -> Self {
        Self {
            queue_time: None,
            submission_time: None,
            execution_time: Some(total_time),
            result_collection_time: None,
            total_time,
        }
    }
}

// =============================================================================
// Observation model
// =============================================================================

/// Generic raw execution observation.
///
/// The execution layer intentionally preserves multiple quantum-computing
/// observation models instead of forcing everything into bitstrings.
#[derive(Debug, Clone, PartialEq)]
pub enum ExecutionObservation {
    /// Classical measurement counts.
    Counts(BTreeMap<String, usize>),

    /// Classical probability distribution.
    Probabilities(BTreeMap<String, f64>),

    /// Expectation values keyed by observable identifier.
    ExpectationValues(BTreeMap<String, f64>),

    /// State-vector amplitudes represented as real/imaginary pairs.
    StateVector(Vec<(f64, f64)>),

    /// Density-matrix entries represented as row-major real/imaginary pairs.
    DensityMatrix(Vec<(f64, f64)>),

    /// Raw analog values.
    AnalogSamples(Vec<f64>),

    /// Annealing/sampling observations.
    AnnealingSamples(Vec<AnnealingSample>),

    /// Quantum-error-correction syndrome observations.
    Syndrome(SyndromeObservation),

    /// Provider-native observation.
    BackendNative {
        format: String,
        payload: Vec<u8>,
    },
}

impl ExecutionObservation {
    /// Returns the observation kind.
    pub fn kind(&self) -> ObservationKind {
        match self {
            Self::Counts(_) => ObservationKind::Counts,
            Self::Probabilities(_) => ObservationKind::Probabilities,
            Self::ExpectationValues(_) => ObservationKind::ExpectationValues,
            Self::StateVector(_) => ObservationKind::StateVector,
            Self::DensityMatrix(_) => ObservationKind::DensityMatrix,
            Self::AnalogSamples(_) => ObservationKind::AnalogSamples,
            Self::AnnealingSamples(_) => ObservationKind::AnnealingSamples,
            Self::Syndrome(_) => ObservationKind::Syndrome,
            Self::BackendNative { .. } => ObservationKind::BackendNative,
        }
    }
}

/// Stable observation classification.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ObservationKind {
    Counts,
    Probabilities,
    ExpectationValues,
    StateVector,
    DensityMatrix,
    AnalogSamples,
    AnnealingSamples,
    Syndrome,
    BackendNative,
}

/// One annealing/sample observation.
#[derive(Debug, Clone, PartialEq)]
pub struct AnnealingSample {
    /// Returned state representation.
    pub state: String,

    /// Optional objective/energy value.
    pub energy: Option<f64>,

    /// Optional backend-provided occurrence count.
    pub occurrences: Option<usize>,
}

/// Raw QEC syndrome observation.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SyndromeObservation {
    /// Syndrome samples.
    pub samples: Vec<String>,

    /// Number of rounds represented by each sample, when known.
    pub rounds: Option<usize>,
}

// =============================================================================
// Execution response
// =============================================================================

/// Raw execution response returned by a backend executor.
///
/// This is intentionally not a benchmark result. No fidelity, error rate,
/// Quantum Volume, XEB score, or other benchmark metric belongs here.
#[derive(Debug, Clone, PartialEq)]
pub struct ExecutionResponse {
    /// Execution-contract schema version.
    pub schema_version: u32,

    /// Request that produced this response.
    pub request_id: ExecutionRequestId,

    /// Backend that produced this response.
    pub backend_id: ExecutionBackendId,

    /// Backend execution mode.
    pub execution_mode: ExecutionMode,

    /// Terminal execution status.
    pub status: ExecutionStatus,

    /// Number of shots requested.
    pub requested_shots: usize,

    /// Number of shots actually completed.
    pub completed_shots: usize,

    /// Raw observations.
    pub observations: Vec<ExecutionObservation>,

    /// Timing measurements.
    pub timing: ExecutionTiming,

    /// Backend metadata.
    pub backend_metadata: BTreeMap<String, String>,

    /// Provider-neutral response metadata.
    pub metadata: BTreeMap<String, String>,

    /// Structured warnings that do not invalidate the response.
    pub warnings: Vec<String>,
}

impl ExecutionResponse {
    /// Creates a successful response.
    pub fn completed(
        request: &ExecutionRequest,
        observations: Vec<ExecutionObservation>,
        timing: ExecutionTiming,
    ) -> Result<Self, ExecutionError> {
        let completed_shots =
            infer_completed_shots(&observations).unwrap_or(request.shots.get());

        if completed_shots > request.shots.get() {
            return Err(ExecutionError::InvalidCompletedShotCount {
                requested: request.shots.get(),
                completed: completed_shots,
            });
        }

        let status = if completed_shots == request.shots.get() {
            ExecutionStatus::Completed
        } else {
            ExecutionStatus::Partial
        };

        Ok(Self {
            schema_version: EXECUTION_RESPONSE_SCHEMA_VERSION,
            request_id: request.request_id.clone(),
            backend_id: request.backend_id.clone(),
            execution_mode: request.execution_mode,
            status,
            requested_shots: request.shots.get(),
            completed_shots,
            observations,
            timing,
            backend_metadata: BTreeMap::new(),
            metadata: BTreeMap::new(),
            warnings: Vec::new(),
        })
    }

    /// Creates an explicit cancelled response.
    pub fn cancelled(
        request: &ExecutionRequest,
        timing: ExecutionTiming,
    ) -> Self {
        Self {
            schema_version: EXECUTION_RESPONSE_SCHEMA_VERSION,
            request_id: request.request_id.clone(),
            backend_id: request.backend_id.clone(),
            execution_mode: request.execution_mode,
            status: ExecutionStatus::Cancelled,
            requested_shots: request.shots.get(),
            completed_shots: 0,
            observations: Vec::new(),
            timing,
            backend_metadata: BTreeMap::new(),
            metadata: BTreeMap::new(),
            warnings: Vec::new(),
        }
    }

    /// Validates correlation and response invariants.
    pub fn validate_against(
        &self,
        request: &ExecutionRequest,
    ) -> Result<(), ExecutionError> {
        if self.schema_version != EXECUTION_RESPONSE_SCHEMA_VERSION {
            return Err(ExecutionError::UnsupportedSchemaVersion {
                kind: SchemaKind::Response,
                version: self.schema_version,
            });
        }

        if self.request_id != request.request_id {
            return Err(ExecutionError::RequestResponseMismatch {
                expected: request.request_id.clone(),
                actual: self.request_id.clone(),
            });
        }

        if self.backend_id != request.backend_id {
            return Err(ExecutionError::BackendResponseMismatch {
                expected: request.backend_id.clone(),
                actual: self.backend_id.clone(),
            });
        }

        if self.requested_shots != request.shots.get() {
            return Err(ExecutionError::RequestedShotMismatch {
                expected: request.shots.get(),
                actual: self.requested_shots,
            });
        }

        if self.completed_shots > self.requested_shots {
            return Err(ExecutionError::InvalidCompletedShotCount {
                requested: self.requested_shots,
                completed: self.completed_shots,
            });
        }

        Ok(())
    }

    /// Adds a warning without changing execution semantics.
    pub fn with_warning(
        mut self,
        warning: impl Into<String>,
    ) -> Self {
        let warning = warning.into();

        if !warning.trim().is_empty() {
            self.warnings.push(warning);
        }

        self
    }

    /// Adds backend metadata.
    pub fn with_backend_metadata(
        mut self,
        key: impl Into<String>,
        value: impl Into<String>,
    ) -> Result<Self, ExecutionError> {
        let key = validate_metadata_key(key.into())?;
        let value = validate_metadata_value(value.into())?;

        self.backend_metadata.insert(key, value);

        Ok(self)
    }

    /// Adds response metadata.
    pub fn with_metadata(
        mut self,
        key: impl Into<String>,
        value: impl Into<String>,
    ) -> Result<Self, ExecutionError> {
        let key = validate_metadata_key(key.into())?;
        let value = validate_metadata_value(value.into())?;

        self.metadata.insert(key, value);

        Ok(self)
    }
}

// =============================================================================
// Backend capability contract
// =============================================================================

/// Capabilities required by an execution request.
///
/// Benchmark protocols use this to perform capability negotiation before
/// execution instead of discovering incompatibility after submitting work.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub struct ExecutionRequirements {
    pub requires_measurement: bool,
    pub requires_reset: bool,
    pub requires_mid_circuit_measurement: bool,
    pub requires_classical_control: bool,
    pub requires_dynamic_circuits: bool,
    pub requires_parameterized_circuits: bool,
    pub requires_state_vector: bool,
    pub requires_density_matrix: bool,
    pub requires_expectation_values: bool,
    pub requires_analog_sampling: bool,
    pub requires_qec_syndrome: bool,
}

impl ExecutionRequirements {
    /// Requirements for ordinary sampled gate-model benchmarking.
    pub fn sampled_circuit() -> Self {
        Self {
            requires_measurement: true,
            ..Self::default()
        }
    }

    /// Checks this requirement set against a backend capability profile.
    pub fn validate(
        &self,
        capabilities: &ExecutionCapabilities,
    ) -> Result<(), ExecutionError> {
        if self.requires_measurement && !capabilities.measurement {
            return Err(ExecutionError::UnsupportedCapability {
                capability: "measurement",
            });
        }

        if self.requires_reset && !capabilities.reset {
            return Err(ExecutionError::UnsupportedCapability {
                capability: "reset",
            });
        }

        if self.requires_mid_circuit_measurement
            && !capabilities.mid_circuit_measurement
        {
            return Err(
                ExecutionError::UnsupportedCapability {
                    capability: "mid_circuit_measurement",
                },
            );
        }

        if self.requires_classical_control
            && !capabilities.classical_control
        {
            return Err(
                ExecutionError::UnsupportedCapability {
                    capability: "classical_control",
                },
            );
        }

        if self.requires_dynamic_circuits
            && !capabilities.dynamic_circuits
        {
            return Err(
                ExecutionError::UnsupportedCapability {
                    capability: "dynamic_circuits",
                },
            );
        }

        if self.requires_parameterized_circuits
            && !capabilities.parameterized_circuits
        {
            return Err(
                ExecutionError::UnsupportedCapability {
                    capability: "parameterized_circuits",
                },
            );
        }

        if self.requires_state_vector
            && !capabilities.state_vector
        {
            return Err(
                ExecutionError::UnsupportedCapability {
                    capability: "state_vector",
                },
            );
        }

        if self.requires_density_matrix
            && !capabilities.density_matrix
        {
            return Err(
                ExecutionError::UnsupportedCapability {
                    capability: "density_matrix",
                },
            );
        }

        if self.requires_expectation_values
            && !capabilities.expectation_values
        {
            return Err(
                ExecutionError::UnsupportedCapability {
                    capability: "expectation_values",
                },
            );
        }

        if self.requires_analog_sampling
            && !capabilities.analog_sampling
        {
            return Err(
                ExecutionError::UnsupportedCapability {
                    capability: "analog_sampling",
                },
            );
        }

        if self.requires_qec_syndrome
            && !capabilities.qec_syndrome
        {
            return Err(
                ExecutionError::UnsupportedCapability {
                    capability: "qec_syndrome",
                },
            );
        }

        Ok(())
    }
}

/// Provider-neutral execution capabilities.
///
/// This deliberately overlaps conceptually with the existing hardware
/// capability layer but does not replace it. The hardware subsystem owns
/// persistent backend capabilities; this structure represents the subset
/// relevant to one execution contract.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ExecutionCapabilities {
    pub measurement: bool,
    pub reset: bool,
    pub mid_circuit_measurement: bool,
    pub classical_control: bool,
    pub dynamic_circuits: bool,
    pub parameterized_circuits: bool,
    pub state_vector: bool,
    pub density_matrix: bool,
    pub expectation_values: bool,
    pub analog_sampling: bool,
    pub qec_syndrome: bool,
    pub supported_measurement_modes: Vec<MeasurementMode>,
}

impl Default for ExecutionCapabilities {
    fn default() -> Self {
        Self {
            measurement: true,
            reset: true,
            mid_circuit_measurement: false,
            classical_control: false,
            dynamic_circuits: false,
            parameterized_circuits: false,
            state_vector: false,
            density_matrix: false,
            expectation_values: false,
            analog_sampling: false,
            qec_syndrome: false,
            supported_measurement_modes: vec![
                MeasurementMode::Counts,
            ],
        }
    }
}

// =============================================================================
// Executor metadata
// =============================================================================

/// Stable metadata exposed by an executor.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ExecutorMetadata {
    /// Executor implementation identifier.
    pub id: String,

    /// Human-readable name.
    pub name: String,

    /// Executor implementation version.
    pub version: String,

    /// Backend identity.
    pub backend_id: ExecutionBackendId,

    /// Execution mode.
    pub execution_mode: ExecutionMode,

    /// Capability profile.
    pub capabilities: ExecutionCapabilities,

    /// Arbitrary provider-neutral metadata.
    pub metadata: BTreeMap<String, String>,
}

impl ExecutorMetadata {
    pub fn new(
        id: impl Into<String>,
        name: impl Into<String>,
        version: impl Into<String>,
        backend_id: ExecutionBackendId,
        execution_mode: ExecutionMode,
        capabilities: ExecutionCapabilities,
    ) -> Result<Self, ExecutionError> {
        let id = validate_identifier(id.into(), "executor ID")?;
        let name = validate_identifier(name.into(), "executor name")?;
        let version = validate_identifier(version.into(), "executor version")?;

        Ok(Self {
            id,
            name,
            version,
            backend_id,
            execution_mode,
            capabilities,
            metadata: BTreeMap::new(),
        })
    }

    pub fn with_metadata(
        mut self,
        key: impl Into<String>,
        value: impl Into<String>,
    ) -> Result<Self, ExecutionError> {
        let key = validate_metadata_key(key.into())?;
        let value = validate_metadata_value(value.into())?;

        self.metadata.insert(key, value);

        Ok(self)
    }
}

// =============================================================================
// Executor trait
// =============================================================================

/// Stable production execution interface.
///
/// Implementations belong outside this module and may wrap:
///
/// - local simulators;
/// - GPU simulators;
/// - tensor-network engines;
/// - hardware SDKs;
/// - remote services;
/// - annealers;
/// - logical-QPU runtimes;
/// - custom Zamani execution providers.
///
/// The trait intentionally remains synchronous. Async execution can be
/// implemented above or below this boundary without forcing Zamani's quantum
/// benchmark core to select an async runtime.
pub trait BenchmarkExecutor {
    /// Returns executor metadata and capabilities.
    fn metadata(&self) -> &ExecutorMetadata;

    /// Performs provider-neutral request validation.
    ///
    /// Implementations may perform additional provider-specific validation
    /// after this method succeeds.
    fn validate(
        &self,
        request: &ExecutionRequest,
    ) -> Result<(), ExecutionError> {
        request.validate()?;

        if request.backend_id != self.metadata().backend_id {
            return Err(ExecutionError::BackendMismatch {
                expected: self.metadata().backend_id.clone(),
                actual: request.backend_id.clone(),
            });
        }

        if request.execution_mode != self.metadata().execution_mode {
            return Err(ExecutionError::ExecutionModeMismatch {
                expected: self.metadata().execution_mode,
                actual: request.execution_mode,
            });
        }

        Ok(())
    }

    /// Executes one benchmark request.
    ///
    /// Implementations MUST:
    ///
    /// - validate before execution;
    /// - honor cancellation where possible;
    /// - enforce timeout semantics;
    /// - preserve request identity;
    /// - preserve partial results where they are safe and meaningful;
    /// - never silently retry;
    /// - never silently alter shots or seeds;
    /// - return structured errors.
    fn execute(
        &self,
        request: &ExecutionRequest,
    ) -> Result<ExecutionResponse, ExecutionError>;

    /// Requests cancellation of an in-flight provider operation.
    ///
    /// The default implementation is cooperative cancellation only. Provider
    /// adapters with native cancellation should override this method.
    fn cancel(
        &self,
        request_id: &ExecutionRequestId,
    ) -> Result<(), ExecutionError> {
        if request_id.as_str().trim().is_empty() {
            return Err(ExecutionError::InvalidRequestId);
        }

        Ok(())
    }
}

// =============================================================================
// Execution guard
// =============================================================================

/// Lightweight timing/cancellation guard for executor implementations.
///
/// It is deliberately independent of an async runtime.
#[derive(Debug)]
pub struct ExecutionGuard {
    started: Instant,
    timeout: Duration,
    cancellation: CancellationToken,
}

impl ExecutionGuard {
    /// Starts an execution guard.
    pub fn start(
        timeout: ExecutionTimeout,
        cancellation: CancellationToken,
    ) -> Self {
        Self {
            started: Instant::now(),
            timeout: timeout.duration(),
            cancellation,
        }
    }

    /// Returns elapsed execution time.
    pub fn elapsed(&self) -> Duration {
        self.started.elapsed()
    }

    /// Checks cancellation and timeout.
    pub fn check(&self) -> Result<(), ExecutionError> {
        if self.cancellation.is_cancelled() {
            return Err(ExecutionError::Cancelled);
        }

        let elapsed = self.elapsed();

        if elapsed >= self.timeout {
            return Err(ExecutionError::TimedOut {
                timeout: self.timeout,
                elapsed,
            });
        }

        Ok(())
    }

    /// Returns whether the timeout has elapsed.
    pub fn is_timed_out(&self) -> bool {
        self.elapsed() >= self.timeout
    }
}

// =============================================================================
// Error model
// =============================================================================

/// Kind of serialized execution schema.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum SchemaKind {
    Request,
    Response,
}

/// Errors produced by the execution contract.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ExecutionError {
    /// Request ID is empty or otherwise invalid.
    InvalidRequestId,

    /// Backend ID is empty or otherwise invalid.
    InvalidBackendId,

    /// Executor metadata contains an invalid identifier.
    InvalidExecutorIdentifier {
        field: &'static str,
    },

    /// Executor/backend mismatch.
    BackendMismatch {
        expected: ExecutionBackendId,
        actual: ExecutionBackendId,
    },

    /// Requested execution mode does not match the executor.
    ExecutionModeMismatch {
        expected: ExecutionMode,
        actual: ExecutionMode,
    },

    /// Request or response schema version is unsupported.
    UnsupportedSchemaVersion {
        kind: SchemaKind,
        version: u32,
    },

    /// Circuit contains no executable quantum work.
    EmptyCircuit,

    /// Number of shots is zero.
    InvalidShotCount,

    /// Timeout is zero.
    InvalidTimeout,

    /// Completed shots exceed requested shots.
    InvalidCompletedShotCount {
        requested: usize,
        completed: usize,
    },

    /// Request and response IDs do not match.
    RequestResponseMismatch {
        expected: ExecutionRequestId,
        actual: ExecutionRequestId,
    },

    /// Request and response backend IDs do not match.
    BackendResponseMismatch {
        expected: ExecutionBackendId,
        actual: ExecutionBackendId,
    },

    /// Request and response shot counts do not match.
    RequestedShotMismatch {
        expected: usize,
        actual: usize,
    },

    /// Backend cannot satisfy a requested capability.
    UnsupportedCapability {
        capability: &'static str,
    },

    /// Backend execution was cancelled.
    Cancelled,

    /// Backend execution exceeded its timeout.
    TimedOut {
        timeout: Duration,
        elapsed: Duration,
    },

    /// Backend reports that execution cannot currently be performed.
    Unavailable {
        backend_id: ExecutionBackendId,
    },

    /// Provider execution failed.
    BackendFailure {
        backend_id: ExecutionBackendId,
        message: String,
    },

    /// Provider returned malformed data.
    MalformedResponse {
        message: String,
    },

    /// Observation contains an invalid probability.
    InvalidProbability {
        value: f64,
    },

    /// Observation contains an invalid count.
    InvalidObservationCount,

    /// Metadata key is invalid.
    InvalidMetadataKey,

    /// Metadata value is invalid.
    InvalidMetadataValue,

    /// Execution request cannot be executed because the selected backend does
    /// not implement the execution operation.
    ExecutionNotImplemented,

    /// Internal execution invariant was violated.
    InvariantViolation {
        message: String,
    },
}

impl fmt::Display for ExecutionError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::InvalidRequestId => {
                write!(f, "execution request ID cannot be empty")
            }

            Self::InvalidBackendId => {
                write!(f, "execution backend ID cannot be empty")
            }

            Self::InvalidExecutorIdentifier { field } => {
                write!(f, "invalid executor {}", field)
            }

            Self::BackendMismatch {
                expected,
                actual,
            } => write!(
                f,
                "execution backend mismatch: expected '{}', got '{}'",
                expected, actual
            ),

            Self::ExecutionModeMismatch {
                expected,
                actual,
            } => write!(
                f,
                "execution mode mismatch: expected {:?}, got {:?}",
                expected, actual
            ),

            Self::UnsupportedSchemaVersion {
                kind,
                version,
            } => write!(
                f,
                "unsupported {:?} execution schema version {}",
                kind, version
            ),

            Self::EmptyCircuit => {
                write!(f, "execution request contains an empty circuit")
            }

            Self::InvalidShotCount => {
                write!(f, "execution shot count must be greater than zero")
            }

            Self::InvalidTimeout => {
                write!(f, "execution timeout must be greater than zero")
            }

            Self::InvalidCompletedShotCount {
                requested,
                completed,
            } => write!(
                f,
                "completed shots {} exceed requested shots {}",
                completed, requested
            ),

            Self::RequestResponseMismatch {
                expected,
                actual,
            } => write!(
                f,
                "execution request/response mismatch: expected '{}', got '{}'",
                expected, actual
            ),

            Self::BackendResponseMismatch {
                expected,
                actual,
            } => write!(
                f,
                "execution backend mismatch: expected '{}', got '{}'",
                expected, actual
            ),

            Self::RequestedShotMismatch {
                expected,
                actual,
            } => write!(
                f,
                "execution response shot mismatch: expected {}, got {}",
                expected, actual
            ),

            Self::UnsupportedCapability { capability } => {
                write!(
                    f,
                    "execution backend does not support capability '{}'",
                    capability
                )
            }

            Self::Cancelled => write!(f, "quantum execution was cancelled"),

            Self::TimedOut { timeout, elapsed } => write!(
                f,
                "quantum execution timed out after {:?} (elapsed {:?})",
                timeout, elapsed
            ),

            Self::Unavailable { backend_id } => write!(
                f,
                "execution backend '{}' is unavailable",
                backend_id
            ),

            Self::BackendFailure {
                backend_id,
                message,
            } => write!(
                f,
                "backend '{}' execution failed: {}",
                backend_id, message
            ),

            Self::MalformedResponse { message } => {
                write!(f, "malformed execution response: {}", message)
            }

            Self::InvalidProbability { value } => {
                write!(f, "invalid execution probability {}", value)
            }

            Self::InvalidObservationCount => {
                write!(f, "invalid execution observation count")
            }

            Self::InvalidMetadataKey => {
                write!(f, "execution metadata key is invalid")
            }

            Self::InvalidMetadataValue => {
                write!(f, "execution metadata value is invalid")
            }

            Self::ExecutionNotImplemented => {
                write!(f, "backend execution is not implemented")
            }

            Self::InvariantViolation { message } => {
                write!(f, "execution invariant violation: {}", message)
            }
        }
    }
}

impl std::error::Error for ExecutionError {}

// =============================================================================
// Validation helpers
// =============================================================================

fn validate_identifier(
    value: String,
    field: &'static str,
) -> Result<String, ExecutionError> {
    if value.trim().is_empty() {
        return Err(ExecutionError::InvalidExecutorIdentifier { field });
    }

    Ok(value)
}

fn validate_metadata_key(
    value: String,
) -> Result<String, ExecutionError> {
    if value.trim().is_empty() {
        return Err(ExecutionError::InvalidMetadataKey);
    }

    Ok(value)
}

fn validate_metadata_value(
    value: String,
) -> Result<String, ExecutionError> {
    if value.contains('\0') {
        return Err(ExecutionError::InvalidMetadataValue);
    }

    Ok(value)
}

fn validate_metadata_map(
    values: &BTreeMap<String, String>,
) -> Result<(), ExecutionError> {
    for (key, value) in values {
        validate_metadata_key(key.clone())?;
        validate_metadata_value(value.clone())?;
    }

    Ok(())
}

/// The execution layer deliberately does not inspect private internals of the
/// Quantum IR here.
///
/// This helper is intentionally isolated so that if the canonical IR later
/// exposes an `is_empty()` API, only this helper needs to be adapted.
///
/// For the current production contract, an `Arc<QuantumCircuit>` itself is
/// considered a valid circuit object. Canonical IR validation remains the
/// responsibility of `quantum::ir::validation`.
#[inline]
fn circuit_is_empty(_circuit: &Arc<QuantumCircuit>) -> bool {
    false
}

/// Attempts to infer completed shots from observations.
///
/// Counts and annealing observations expose explicit occurrence information.
/// Probability/state observations do not necessarily encode a shot count, so
/// those return `None` and the caller may use the request's declared count.
fn infer_completed_shots(
    observations: &[ExecutionObservation],
) -> Option<usize> {
    for observation in observations {
        match observation {
            ExecutionObservation::Counts(counts) => {
                let total = counts.values().try_fold(
                    0usize,
                    |acc, value| acc.checked_add(*value),
                );

                if let Some(total) = total {
                    return Some(total);
                }

                return None;
            }

            ExecutionObservation::AnnealingSamples(samples) => {
                let mut total = 0usize;

                for sample in samples {
                    if let Some(occurrences) = sample.occurrences {
                        total = total.checked_add(occurrences)?;
                    }
                }

                if total > 0 {
                    return Some(total);
                }
            }

            _ => {}
        }
    }

    None
}

// =============================================================================
// Response validation helpers
// =============================================================================

/// Validates a probability distribution.
///
/// The function deliberately does not require the probabilities to sum exactly
/// to one because floating-point serialization and backend rounding can make
/// exact equality inappropriate. The tolerance is explicit.
pub fn validate_probability_distribution(
    distribution: &BTreeMap<String, f64>,
) -> Result<(), ExecutionError> {
    if distribution.is_empty() {
        return Err(ExecutionError::MalformedResponse {
            message: "probability distribution is empty".to_owned(),
        });
    }

    let mut sum = 0.0f64;

    for probability in distribution.values() {
        if !probability.is_finite()
            || *probability < 0.0
            || *probability > 1.0
        {
            return Err(ExecutionError::InvalidProbability {
                value: *probability,
            });
        }

        sum += *probability;
    }

    const NORMALIZATION_TOLERANCE: f64 = 1.0e-9;

    if (sum - 1.0).abs() > NORMALIZATION_TOLERANCE {
        return Err(ExecutionError::MalformedResponse {
            message: format!(
                "probability distribution is not normalized: sum={}",
                sum
            ),
        });
    }

    Ok(())
}

/// Validates a count distribution and returns the total number of observations.
pub fn validate_count_distribution(
    distribution: &BTreeMap<String, usize>,
) -> Result<usize, ExecutionError> {
    if distribution.is_empty() {
        return Err(ExecutionError::MalformedResponse {
            message: "count distribution is empty".to_owned(),
        });
    }

    distribution.values().try_fold(0usize, |acc, count| {
        acc.checked_add(*count)
            .ok_or(ExecutionError::InvalidObservationCount)
    })
}

// =============================================================================
// Tests
// =============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    fn request() -> ExecutionRequest {
        let request_id =
            ExecutionRequestId::new("test-request-1").unwrap();

        let backend_id =
            ExecutionBackendId::new("local-simulator").unwrap();

        let circuit =
            Arc::new(QuantumCircuit::default());

        ExecutionRequest::new(
            request_id,
            backend_id,
            ExecutionMode::StateVectorSimulator,
            circuit,
        )
        .unwrap()
    }

    #[test]
    fn request_id_rejects_empty_values() {
        assert_eq!(
            ExecutionRequestId::new(""),
            Err(ExecutionError::InvalidRequestId)
        );

        assert_eq!(
            ExecutionRequestId::new("   "),
            Err(ExecutionError::InvalidRequestId)
        );
    }

    #[test]
    fn backend_id_rejects_empty_values() {
        assert_eq!(
            ExecutionBackendId::new(""),
            Err(ExecutionError::InvalidBackendId)
        );
    }

    #[test]
    fn shot_count_rejects_zero() {
        assert_eq!(
            ShotCount::new(0),
            Err(ExecutionError::InvalidShotCount)
        );

        assert_eq!(ShotCount::new(1).unwrap().get(), 1);
    }

    #[test]
    fn timeout_rejects_zero() {
        assert_eq!(
            ExecutionTimeout::new(Duration::ZERO),
            Err(ExecutionError::InvalidTimeout)
        );
    }

    #[test]
    fn cancellation_is_observable() {
        let token = CancellationToken::new();

        assert!(!token.is_cancelled());
        assert!(token.check().is_ok());

        token.cancel();

        assert!(token.is_cancelled());
        assert_eq!(
            token.check(),
            Err(ExecutionError::Cancelled)
        );
    }

    #[test]
    fn sampled_requirements_require_measurement() {
        let requirements =
            ExecutionRequirements::sampled_circuit();

        let mut capabilities =
            ExecutionCapabilities::default();

        capabilities.measurement = true;

        assert!(requirements.validate(&capabilities).is_ok());

        capabilities.measurement = false;

        assert_eq!(
            requirements.validate(&capabilities),
            Err(
                ExecutionError::UnsupportedCapability {
                    capability: "measurement",
                }
            )
        );
    }

    #[test]
    fn probability_distribution_is_validated() {
        let mut distribution = BTreeMap::new();

        distribution.insert("00".to_owned(), 0.5);
        distribution.insert("11".to_owned(), 0.5);

        assert!(
            validate_probability_distribution(&distribution)
                .is_ok()
        );
    }

    #[test]
    fn probability_distribution_rejects_invalid_probability() {
        let mut distribution = BTreeMap::new();

        distribution.insert("00".to_owned(), 1.2);

        assert_eq!(
            validate_probability_distribution(&distribution),
            Err(ExecutionError::InvalidProbability {
                value: 1.2
            })
        );
    }

    #[test]
    fn count_distribution_returns_total() {
        let mut distribution = BTreeMap::new();

        distribution.insert("00".to_owned(), 30);
        distribution.insert("11".to_owned(), 70);

        assert_eq!(
            validate_count_distribution(&distribution)
                .unwrap(),
            100
        );
    }

    #[test]
    fn execution_response_preserves_request_identity() {
        let request = request();

        let response = ExecutionResponse::completed(
            &request,
            vec![],
            ExecutionTiming::completed(
                Duration::from_millis(10),
            ),
        )
        .unwrap();

        assert_eq!(
            response.request_id,
            request.request_id
        );

        assert_eq!(
            response.backend_id,
            request.backend_id
        );

        assert_eq!(
            response.requested_shots,
            request.shots.get()
        );

        assert!(
            response
                .validate_against(&request)
                .is_ok()
        );
    }

    #[test]
    fn response_rejects_request_id_mismatch() {
        let request = request();

        let mut response = ExecutionResponse::completed(
            &request,
            vec![],
            ExecutionTiming::completed(
                Duration::from_millis(10),
            ),
        )
        .unwrap();

        response.request_id =
            ExecutionRequestId::new("different").unwrap();

        assert!(matches!(
            response.validate_against(&request),
            Err(
                ExecutionError::RequestResponseMismatch {
                    ..
                }
            )
        ));
    }

    #[test]
    fn execution_guard_detects_cancellation() {
        let token = CancellationToken::new();

        let guard = ExecutionGuard::start(
            ExecutionTimeout::new(
                Duration::from_secs(10),
            )
            .unwrap(),
            token.clone(),
        );

        assert!(guard.check().is_ok());

        token.cancel();

        assert_eq!(
            guard.check(),
            Err(ExecutionError::Cancelled)
        );
    }

    #[test]
    fn execution_status_terminal_semantics_are_stable() {
        assert!(!ExecutionStatus::Accepted.is_terminal());
        assert!(!ExecutionStatus::Running.is_terminal());

        assert!(ExecutionStatus::Completed.is_terminal());
        assert!(ExecutionStatus::Partial.is_terminal());
        assert!(ExecutionStatus::Cancelled.is_terminal());
        assert!(ExecutionStatus::TimedOut.is_terminal());
        assert!(ExecutionStatus::Failed.is_terminal());
    }

    #[test]
    fn execution_modes_distinguish_physical_and_simulated_targets() {
        assert!(
            ExecutionMode::Qpu.is_physical()
        );

        assert!(
            ExecutionMode::StateVectorSimulator
                .is_simulator()
        );

        assert!(
            ExecutionMode::Sampler
                .is_sampling_oriented()
        );
    }

    #[test]
    fn executor_metadata_rejects_empty_identifiers() {
        let backend =
            ExecutionBackendId::new("sim").unwrap();

        assert!(
            ExecutorMetadata::new(
                "",
                "Simulator",
                "1.0",
                backend,
                ExecutionMode::StateVectorSimulator,
                ExecutionCapabilities::default(),
            )
            .is_err()
        );
    }
}