//! Zamani Quantum Benchmarking — Leakage Randomized Benchmarking
//!
//! Production Leakage Randomized Benchmarking (LRB) protocol.
//!
//! # Responsibility
//!
//! This module owns the protocol-level semantics of leakage randomized
//! benchmarking:
//!
//! - LRB configuration;
//! - workload/resource validation;
//! - deterministic experiment planning;
//! - sequence-length planning;
//! - leakage-aware observation normalization;
//! - computational-subspace population aggregation;
//! - direct leakage-population aggregation;
//! - constrained exponential decay fitting;
//! - leakage-rate estimation;
//! - seepage-rate estimation;
//! - leakage+seepage decay diagnostics;
//! - protocol assumptions and validity warnings;
//! - reproducibility metadata;
//! - offline re-analysis of captured observations.
//!
//! It deliberately does NOT own:
//!
//! - Quantum IR;
//! - Clifford-group mathematics;
//! - physical gate construction;
//! - routing;
//! - scheduling;
//! - calibration;
//! - backend selection;
//! - hardware communication;
//! - simulator implementation;
//! - generic benchmark result serialization;
//! - generic benchmark reporting;
//! - generic benchmark registry;
//! - generic QEC execution.
//!
//! The intended dependency direction is:
//!
//! ```text
//! generators::clifford
//!          │
//!          ▼
//! leakage_rb
//!          │
//!     ┌────┴─────────────┐
//!     ▼                  ▼
//! execution          statistics
//!     │                  │
//!     ▼                  ▼
//! Quantum IR        regression
//!     │
//!     ▼
//! routing / scheduling / hardware / runtime
//! ```
//!
//! This file intentionally defines its protocol-level contracts without
//! importing those downstream layers. This permits the protocol to be
//! completed and tested independently.
//!
//! # Scientific model
//!
//! Leakage is population leaving the computational subspace and entering a
//! leakage subspace. Seepage is population returning from the leakage
//! subspace to the computational subspace.
//!
//! The canonical Wood–Gambetta LRB model is:
//!
//! ```text
//! P_comp(m) = A + B * lambda1^m
//! ```
//!
//! with:
//!
//! ```text
//! L1 = (1 - A) * (1 - lambda1)
//! L2 = A * (1 - lambda1)
//! ```
//!
//! and therefore:
//!
//! ```text
//! lambda1 = 1 - L1 - L2
//! ```
//!
//! `L1` is the average leakage rate per randomized Clifford operation and
//! `L2` is the average seepage rate per randomized Clifford operation under
//! the LRB model.
//!
//! These quantities must NOT be interpreted as architecture-independent
//! physical truths when the model assumptions are violated.
//!
//! # Required LRB assumptions
//!
//! The standard protocol assumes, in addition to ordinary RB requirements:
//!
//! 1. the randomized gate set acts as a suitable 2-design on the computational
//!    subspace;
//! 2. twirling suppresses relevant computational/leakage coherences;
//! 3. population in the leakage subspace is sufficiently depolarized for the
//!    effective two-state leakage model;
//! 4. the leakage dynamics are sufficiently stationary over the experiment;
//! 5. the measurement used to estimate computational-subspace population is
//!    stable and correctly normalized.
//!
//! Violations are reported through structured warnings rather than silently
//! producing a result that looks more certain than the experiment warrants.
//!
//! # Measurement models
//!
//! The protocol supports three measurement modes:
//!
//! ```text
//! ComputationalSubspace
//!     measure P_comp directly
//!
//! DirectLeakage
//!     measure P_leak directly
//!
//! Both
//!     measure both P_comp and P_leak
//! ```
//!
//! `DirectLeakage` is normalized internally through:
//!
//! ```text
//! P_comp = 1 - P_leak
//! ```
//!
//! when the measurement is complete and normalized.
//!
//! # Multi-level leakage
//!
//! The protocol does not assume a single leakage level such as |2>.
//!
//! A backend may classify:
//!
//! ```text
//! computational = {|0>, |1>}
//! leakage       = {|2>, |3>, ...}
//! ```
//!
//! or, for a larger logical system:
//!
//! ```text
//! computational subspace dimension = d_c
//! leakage subspace dimension       = d_l
//! ```
//!
//! The measurement adapter is responsible for classifying physical outcomes.
//!
//! # Sequence generation boundary
//!
//! This module does not reimplement Clifford algebra.
//!
//! `LeakageRbSequencePlan` contains the deterministic information required by
//! the existing Clifford generator:
//!
//! - sequence length;
//! - sequence index;
//! - deterministic seed;
//! - recovery requirement.
//!
//! The actual Clifford sequence must be generated by
//! `benchmarking::generators::clifford`.
//!
//! This prevents the leakage protocol from accidentally implementing a second,
//! statistically incompatible Clifford sampler.
//!
//! # Resource safety
//!
//! All user-controlled multiplicative quantities are checked before
//! multiplication:
//!
//! ```text
//! sequence_lengths
//! × sequences_per_length
//! × shots_per_sequence
//! ```
//!
//! Overflow is rejected.
//!
//! The protocol also has explicit configurable workload limits.
//!
//! # Reproducibility
//!
//! No process-global RNG is used.
//!
//! The sequence seed is deterministically derived from:
//!
//! ```text
//! experiment_seed
//! benchmark version
//! sequence length
//! sequence index
//! ```
//!
//! This allows a sequence plan to be reconstructed independently of the
//! execution backend.
//!
//! # Rust compatibility
//!
//! Target:
//!
//! - Rust 1.97
//! - Rust 1.97.1
//! - Rust 2021
//!
//! No nightly features are required.
//!
//! Existing repository dependencies used by this file:
//!
//! - serde
//!
//! No new crate dependency is required.
//!
//! # Integration contract
//!
//! Later modules may consume this file as follows:
//!
//! ```text
//! generators::clifford
//!          │
//!          ▼
//! LeakageRbSequencePlan
//!          │
//!          ▼
//! core::circuit / Quantum IR
//!          │
//!          ▼
//! execution
//!          │
//!          ▼
//! LeakageRbObservation
//!          │
//!          ▼
//! LeakageRbAnalyzer
//!          │
//!          ▼
//! LeakageRbResult
//!          │
//!          ├── core::result
//!          ├── metrics::leakage
//!          ├── reporting
//!          └── analysis
//! ```
//!
//! The protocol types in this file are stable protocol-level contracts.
//!
//! # References
//!
//! Primary protocol reference:
//!
//! Christopher J. Wood and Jay M. Gambetta,
//! "Quantification and Characterization of Leakage Errors",
//! Physical Review A 97, 032306 (2018).
//!
//! The implementation also accommodates the broader modern LRB direction in
//! which leakage benchmarking is applied to multi-qubit systems and does not
//! require direct operations on leakage states when an appropriate
//! computational-subspace measurement is available.

use serde::{Deserialize, Serialize};
use std::fmt;

// =============================================================================
// Public identifiers
// =============================================================================

/// Stable benchmark identifier.
pub const LEAKAGE_RB_BENCHMARK_ID: &str =
    "leakage_randomized_benchmarking";

/// Stable protocol schema version.
///
/// Increment this when externally meaningful result semantics change.
pub const LEAKAGE_RB_SCHEMA_VERSION: u32 = 1;

/// Stable algorithm identifier.
///
/// This belongs in provenance records.
pub const LEAKAGE_RB_ALGORITHM_ID: &str =
    "zamani.lrb.wood_gambetta.constrained_exponential.v1";

/// Human-readable protocol name.
pub const LEAKAGE_RB_PROTOCOL_NAME: &str =
    "Leakage Randomized Benchmarking";

/// Minimum number of distinct sequence lengths needed for a useful
/// three-parameter decay fit.
///
/// The model contains:
///
/// ```text
/// A
/// B
/// lambda1
/// ```
///
/// Three points can mathematically determine three parameters but leave no
/// residual degrees of freedom. Production fitting therefore requires at least
/// four distinct lengths.
pub const MIN_SEQUENCE_LENGTHS: usize = 4;

/// Default number of independent random sequences per sequence length.
pub const DEFAULT_SEQUENCES_PER_LENGTH: usize = 32;

/// Default shots per sequence.
pub const DEFAULT_SHOTS_PER_SEQUENCE: usize = 1_000;

/// Default experiment seed.
pub const DEFAULT_EXPERIMENT_SEED: u64 = 0x5A4D_4C52_425F_5631;

/// Default maximum number of sequence lengths.
pub const DEFAULT_MAX_SEQUENCE_LENGTHS: usize = 256;

/// Default maximum sequence length.
pub const DEFAULT_MAX_SEQUENCE_LENGTH: usize = 100_000;

/// Default maximum sequences per length.
pub const DEFAULT_MAX_SEQUENCES_PER_LENGTH: usize = 100_000;

/// Default maximum shots per sequence.
pub const DEFAULT_MAX_SHOTS_PER_SEQUENCE: usize = 10_000_000;

/// Default maximum total shots.
///
/// This is intentionally expressed as u128 internally so intermediate
/// multiplication cannot silently wrap.
pub const DEFAULT_MAX_TOTAL_SHOTS: u128 = 1_000_000_000;

/// Default minimum number of total shots in a protocol.
pub const DEFAULT_MIN_TOTAL_SHOTS: u128 = 1;

/// Default fit grid size.
pub const DEFAULT_FIT_GRID_POINTS: usize = 256;

/// Default local fit refinement iterations.
pub const DEFAULT_FIT_REFINEMENT_ITERATIONS: usize = 256;

/// Default fit tolerance.
pub const DEFAULT_FIT_TOLERANCE: f64 = 1.0e-10;

/// Default confidence level for diagnostic uncertainty estimates.
pub const DEFAULT_CONFIDENCE_LEVEL: f64 = 0.95;

/// Small numerical tolerance for probabilities.
const PROBABILITY_EPSILON: f64 = 1.0e-12;

/// Small numerical tolerance for constrained fit parameters.
const FIT_EPSILON: f64 = 1.0e-10;

/// Lower numerical boundary for lambda1.
pub const MIN_LAMBDA: f64 = 0.0;

/// Upper numerical boundary for lambda1.
pub const MAX_LAMBDA: f64 = 1.0;

// =============================================================================
// Error boundary
// =============================================================================

/// Errors produced by the leakage randomized-benchmarking protocol.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum LeakageRbError {
    /// No sequence lengths were provided.
    EmptySequenceLengths,

    /// A sequence length was zero.
    InvalidSequenceLength {
        /// Invalid length.
        length: usize,
    },

    /// Too many sequence lengths were requested.
    TooManySequenceLengths {
        /// Requested count.
        requested: usize,

        /// Maximum permitted.
        maximum: usize,
    },

    /// Duplicate sequence length.
    DuplicateSequenceLength {
        /// Duplicated value.
        length: usize,
    },

    /// Sequence lengths were not strictly increasing.
    UnsortedSequenceLengths,

    /// Too few sequence lengths exist for the requested model.
    InsufficientSequenceLengths {
        /// Number supplied.
        supplied: usize,

        /// Minimum required.
        minimum: usize,
    },

    /// Invalid number of sequences per length.
    InvalidSequencesPerLength {
        /// Requested count.
        requested: usize,

        /// Maximum allowed.
        maximum: usize,
    },

    /// Invalid shot count.
    InvalidShots {
        /// Requested count.
        requested: usize,

        /// Maximum allowed.
        maximum: usize,
    },

    /// Total-shot budget was exceeded.
    TotalShotLimitExceeded {
        /// Requested total.
        requested: u128,

        /// Maximum.
        maximum: u128,
    },

    /// Arithmetic overflow occurred.
    ResourceCalculationOverflow,

    /// Invalid confidence level.
    InvalidConfidenceLevel {
        /// Invalid level.
        value: f64,
    },

    /// Invalid seed.
    InvalidSeed,

    /// Invalid computational-subspace dimension.
    InvalidComputationalDimension,

    /// Invalid leakage-subspace dimension.
    InvalidLeakageDimension,

    /// Computational and leakage dimensions overflowed.
    HilbertDimensionOverflow,

    /// Invalid measurement mode.
    InvalidMeasurementMode,

    /// A measurement had impossible counts.
    InvalidObservationCounts {
        /// Sequence length.
        length: usize,

        /// Computational count.
        computational: u64,

        /// Leakage count.
        leakage: u64,

        /// Unclassified count.
        unclassified: u64,

        /// Total shots.
        shots: u64,
    },

    /// A probability was non-finite.
    NonFiniteProbability {
        /// Field name.
        field: &'static str,
    },

    /// A probability was outside [0,1].
    ProbabilityOutOfRange {
        /// Field name.
        field: &'static str,

        /// Invalid value.
        value: f64,
    },

    /// The same sequence was observed more than once.
    DuplicateSequenceObservation {
        /// Sequence length.
        length: usize,

        /// Sequence index.
        sequence_index: usize,
    },

    /// An observation belonged to a sequence length not in the experiment.
    UnexpectedSequenceLength {
        /// Sequence length.
        length: usize,
    },

    /// No usable observations exist.
    NoObservations,

    /// The fit could not identify the decay.
    FitFailed,

    /// The decay parameter was not physically valid.
    InvalidDecayParameter {
        /// Fitted lambda.
        value: f64,
    },

    /// A fitted parameter is non-finite.
    NonFiniteFitParameter {
        /// Parameter name.
        parameter: &'static str,
    },

    /// A fit violated probability constraints.
    InvalidPhysicalFit,

    /// The fit is too close to a degenerate boundary.
    BoundaryFit,

    /// A requested grid/refinement configuration is invalid.
    InvalidFitConfiguration,

    /// The requested bootstrap count is invalid.
    InvalidBootstrapCount,

    /// Bootstrap resource budget was exceeded.
    BootstrapLimitExceeded {
        /// Requested operations.
        requested: u128,

        /// Maximum.
        maximum: u128,
    },
}

impl fmt::Display for LeakageRbError {
    fn fmt(
        &self,
        formatter: &mut fmt::Formatter<'_>,
    ) -> fmt::Result {
        match self {
            Self::EmptySequenceLengths => {
                write!(
                    formatter,
                    "leakage RB requires at least one sequence length"
                )
            }

            Self::InvalidSequenceLength { length } => {
                write!(
                    formatter,
                    "leakage RB sequence length must be greater than zero, got {length}"
                )
            }

            Self::TooManySequenceLengths {
                requested,
                maximum,
            } => {
                write!(
                    formatter,
                    "requested {requested} leakage RB sequence lengths; maximum is {maximum}"
                )
            }

            Self::DuplicateSequenceLength { length } => {
                write!(
                    formatter,
                    "leakage RB sequence length {length} occurs more than once"
                )
            }

            Self::UnsortedSequenceLengths => {
                write!(
                    formatter,
                    "leakage RB sequence lengths must be strictly increasing"
                )
            }

            Self::InsufficientSequenceLengths {
                supplied,
                minimum,
            } => {
                write!(
                    formatter,
                    "leakage RB requires at least {minimum} distinct sequence lengths, got {supplied}"
                )
            }

            Self::InvalidSequencesPerLength {
                requested,
                maximum,
            } => {
                write!(
                    formatter,
                    "requested {requested} sequences per length; maximum is {maximum}"
                )
            }

            Self::InvalidShots {
                requested,
                maximum,
            } => {
                write!(
                    formatter,
                    "requested {requested} shots per sequence; maximum is {maximum}"
                )
            }

            Self::TotalShotLimitExceeded {
                requested,
                maximum,
            } => {
                write!(
                    formatter,
                    "requested {requested} total shots; maximum is {maximum}"
                )
            }

            Self::ResourceCalculationOverflow => {
                write!(
                    formatter,
                    "leakage RB resource calculation overflowed"
                )
            }

            Self::InvalidConfidenceLevel { value } => {
                write!(
                    formatter,
                    "confidence level must be finite and in (0,1), got {value}"
                )
            }

            Self::InvalidSeed => {
                write!(
                    formatter,
                    "leakage RB experiment seed must be non-zero"
                )
            }

            Self::InvalidComputationalDimension => {
                write!(
                    formatter,
                    "computational-subspace dimension must be greater than zero"
                )
            }

            Self::InvalidLeakageDimension => {
                write!(
                    formatter,
                    "leakage-subspace dimension must be greater than zero"
                )
            }

            Self::HilbertDimensionOverflow => {
                write!(
                    formatter,
                    "computational plus leakage dimension overflowed"
                )
            }

            Self::InvalidMeasurementMode => {
                write!(
                    formatter,
                    "invalid leakage RB measurement mode"
                )
            }

            Self::InvalidObservationCounts {
                length,
                computational,
                leakage,
                unclassified,
                shots,
            } => {
                write!(
                    formatter,
                    "invalid leakage RB counts at length {length}: computational={computational}, leakage={leakage}, unclassified={unclassified}, shots={shots}"
                )
            }

            Self::NonFiniteProbability { field } => {
                write!(
                    formatter,
                    "non-finite leakage RB probability in {field}"
                )
            }

            Self::ProbabilityOutOfRange { field, value } => {
                write!(
                    formatter,
                    "leakage RB probability {field}={value} is outside [0,1]"
                )
            }

            Self::DuplicateSequenceObservation {
                length,
                sequence_index,
            } => {
                write!(
                    formatter,
                    "duplicate leakage RB observation for length {length}, sequence {sequence_index}"
                )
            }

            Self::UnexpectedSequenceLength { length } => {
                write!(
                    formatter,
                    "observation uses sequence length {length}, which is not in the configured experiment"
                )
            }

            Self::NoObservations => {
                write!(
                    formatter,
                    "leakage RB analysis requires observations"
                )
            }

            Self::FitFailed => {
                write!(
                    formatter,
                    "leakage RB exponential fit failed"
                )
            }

            Self::InvalidDecayParameter { value } => {
                write!(
                    formatter,
                    "leakage RB decay parameter {value} is outside [0,1]"
                )
            }

            Self::NonFiniteFitParameter { parameter } => {
                write!(
                    formatter,
                    "leakage RB fit parameter {parameter} is non-finite"
                )
            }

            Self::InvalidPhysicalFit => {
                write!(
                    formatter,
                    "leakage RB fit violates physical probability constraints"
                )
            }

            Self::BoundaryFit => {
                write!(
                    formatter,
                    "leakage RB fit is numerically dominated by a physical boundary"
                )
            }

            Self::InvalidFitConfiguration => {
                write!(
                    formatter,
                    "invalid leakage RB fitting configuration"
                )
            }

            Self::InvalidBootstrapCount => {
                write!(
                    formatter,
                    "leakage RB bootstrap count is invalid"
                )
            }

            Self::BootstrapLimitExceeded {
                requested,
                maximum,
            } => {
                write!(
                    formatter,
                    "leakage RB bootstrap workload {requested} exceeds maximum {maximum}"
                )
            }
        }
    }
}

impl std::error::Error for LeakageRbError {}

/// Result type for leakage randomized benchmarking.
pub type LeakageRbResult<T> = Result<T, LeakageRbError>;

// =============================================================================
// Measurement mode
// =============================================================================

/// Measurement strategy used to determine leakage.
#[derive(
    Debug,
    Clone,
    Copy,
    PartialEq,
    Eq,
    Hash,
    Serialize,
    Deserialize,
)]
pub enum LeakageMeasurementMode {
    /// Measure the probability of remaining in the computational subspace.
    ComputationalSubspace,

    /// Directly measure the leakage subspace.
    DirectLeakage,

    /// Measure both computational and leakage populations.
    Both,
}

impl LeakageMeasurementMode {
    /// Stable identifier.
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::ComputationalSubspace => {
                "computational_subspace"
            }
            Self::DirectLeakage => "direct_leakage",
            Self::Both => "both",
        }
    }

    /// Returns whether computational-subspace population is required.
    pub const fn requires_computational(self) -> bool {
        matches!(
            self,
            Self::ComputationalSubspace | Self::Both
        )
    }

    /// Returns whether direct leakage population is required.
    pub const fn requires_leakage(self) -> bool {
        matches!(
            self,
            Self::DirectLeakage | Self::Both
        )
    }
}

// =============================================================================
// Protocol assumptions
// =============================================================================

/// Explicit scientific assumptions attached to every analysis.
#[derive(
    Debug,
    Clone,
    Copy,
    PartialEq,
    Eq,
    Serialize,
    Deserialize,
)]
pub struct LeakageRbAssumptions {
    /// Randomized operations form a suitable 2-design on the computational
    /// subspace.
    pub computational_subspace_two_design: bool,

    /// Twirling sufficiently suppresses computational/leakage coherences.
    pub coherence_twirling: bool,

    /// Leakage-subspace population is sufficiently depolarized.
    pub leakage_subspace_depolarized: bool,

    /// Leakage dynamics are sufficiently stationary.
    pub stationary_noise: bool,

    /// Measurement classification is stable over the experiment.
    pub stable_measurement: bool,

    /// Sequence recovery is mathematically correct.
    pub valid_recovery: bool,
}

impl Default for LeakageRbAssumptions {
    fn default() -> Self {
        Self {
            computational_subspace_two_design: true,
            coherence_twirling: true,
            leakage_subspace_depolarized: true,
            stationary_noise: true,
            stable_measurement: true,
            valid_recovery: true,
        }
    }
}

impl LeakageRbAssumptions {
    /// Returns whether all mandatory assumptions have been declared satisfied.
    pub const fn are_satisfied(self) -> bool {
        self.computational_subspace_two_design
            && self.coherence_twirling
            && self.leakage_subspace_depolarized
            && self.stationary_noise
            && self.stable_measurement
            && self.valid_recovery
    }
}

// =============================================================================
// Configuration
// =============================================================================

/// Production configuration for LRB.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct LeakageRbConfig {
    /// Sequence lengths in strictly increasing order.
    pub sequence_lengths: Vec<usize>,

    /// Independent random sequences per length.
    pub sequences_per_length: usize,

    /// Shots per sequence.
    pub shots_per_sequence: usize,

    /// Computational-subspace dimension.
    pub computational_dimension: usize,

    /// Leakage-subspace dimension.
    ///
    /// This can be greater than one.
    pub leakage_dimension: usize,

    /// Measurement strategy.
    pub measurement_mode: LeakageMeasurementMode,

    /// Deterministic experiment seed.
    pub experiment_seed: u64,

    /// Confidence level for optional uncertainty analysis.
    pub confidence_level: f64,

    /// Maximum number of sequence lengths.
    pub max_sequence_lengths: usize,

    /// Maximum sequence length.
    pub max_sequence_length: usize,

    /// Maximum sequences per length.
    pub max_sequences_per_length: usize,

    /// Maximum shots per sequence.
    pub max_shots_per_sequence: usize,

    /// Maximum total shots.
    pub max_total_shots: u128,

    /// Number of grid points for the decay fit.
    pub fit_grid_points: usize,

    /// Maximum local refinement iterations.
    pub fit_refinement_iterations: usize,

    /// Fit convergence tolerance.
    pub fit_tolerance: f64,

    /// Scientific assumptions.
    pub assumptions: LeakageRbAssumptions,
}

impl Default for LeakageRbConfig {
    fn default() -> Self {
        Self {
            sequence_lengths: vec![1, 11, 21, 41, 81, 161],
            sequences_per_length:
                DEFAULT_SEQUENCES_PER_LENGTH,
            shots_per_sequence:
                DEFAULT_SHOTS_PER_SEQUENCE,
            computational_dimension: 2,
            leakage_dimension: 1,
            measurement_mode:
                LeakageMeasurementMode::ComputationalSubspace,
            experiment_seed: DEFAULT_EXPERIMENT_SEED,
            confidence_level: DEFAULT_CONFIDENCE_LEVEL,
            max_sequence_lengths:
                DEFAULT_MAX_SEQUENCE_LENGTHS,
            max_sequence_length:
                DEFAULT_MAX_SEQUENCE_LENGTH,
            max_sequences_per_length:
                DEFAULT_MAX_SEQUENCES_PER_LENGTH,
            max_shots_per_sequence:
                DEFAULT_MAX_SHOTS_PER_SEQUENCE,
            max_total_shots:
                DEFAULT_MAX_TOTAL_SHOTS,
            fit_grid_points:
                DEFAULT_FIT_GRID_POINTS,
            fit_refinement_iterations:
                DEFAULT_FIT_REFINEMENT_ITERATIONS,
            fit_tolerance:
                DEFAULT_FIT_TOLERANCE,
            assumptions:
                LeakageRbAssumptions::default(),
        }
    }
}

impl LeakageRbConfig {
    /// Returns a production configuration.
    pub fn production() -> Self {
        Self::default()
    }

    /// Validates the complete configuration.
    pub fn validate(&self) -> LeakageRbResult<()> {
        validate_sequence_lengths(
            &self.sequence_lengths,
            self.max_sequence_lengths,
            self.max_sequence_length,
        )?;

        if self.sequence_lengths.len()
            < MIN_SEQUENCE_LENGTHS
        {
            return Err(
                LeakageRbError::InsufficientSequenceLengths {
                    supplied: self.sequence_lengths.len(),
                    minimum: MIN_SEQUENCE_LENGTHS,
                },
            );
        }

        if self.sequences_per_length == 0
            || self.sequences_per_length
                > self.max_sequences_per_length
        {
            return Err(
                LeakageRbError::InvalidSequencesPerLength {
                    requested: self.sequences_per_length,
                    maximum: self.max_sequences_per_length,
                },
            );
        }

        if self.shots_per_sequence == 0
            || self.shots_per_sequence
                > self.max_shots_per_sequence
        {
            return Err(LeakageRbError::InvalidShots {
                requested: self.shots_per_sequence,
                maximum: self.max_shots_per_sequence,
            });
        }

        if self.computational_dimension == 0 {
            return Err(
                LeakageRbError::InvalidComputationalDimension,
            );
        }

        if self.leakage_dimension == 0 {
            return Err(
                LeakageRbError::InvalidLeakageDimension,
            );
        }

        self.computational_dimension
            .checked_add(self.leakage_dimension)
            .ok_or(
                LeakageRbError::HilbertDimensionOverflow,
            )?;

        if self.experiment_seed == 0 {
            return Err(LeakageRbError::InvalidSeed);
        }

        if !self.confidence_level.is_finite()
            || self.confidence_level <= 0.0
            || self.confidence_level >= 1.0
        {
            return Err(
                LeakageRbError::InvalidConfidenceLevel {
                    value: self.confidence_level,
                },
            );
        }

        if self.fit_grid_points < 8
            || self.fit_refinement_iterations == 0
            || !self.fit_tolerance.is_finite()
            || self.fit_tolerance <= 0.0
        {
            return Err(
                LeakageRbError::InvalidFitConfiguration,
            );
        }

        if self.max_total_shots == 0 {
            return Err(
                LeakageRbError::TotalShotLimitExceeded {
                    requested: 0,
                    maximum: 0,
                },
            );
        }

        let total_shots = self.total_shots()?;

        if total_shots < DEFAULT_MIN_TOTAL_SHOTS
            || total_shots > self.max_total_shots
        {
            return Err(
                LeakageRbError::TotalShotLimitExceeded {
                    requested: total_shots,
                    maximum: self.max_total_shots,
                },
            );
        }

        Ok(())
    }

    /// Returns the number of planned sequences.
    pub fn total_sequences(&self) -> LeakageRbResult<u128> {
        let lengths =
            self.sequence_lengths.len() as u128;

        lengths
            .checked_mul(self.sequences_per_length as u128)
            .ok_or(LeakageRbError::ResourceCalculationOverflow)
    }

    /// Returns the total planned shot count.
    pub fn total_shots(&self) -> LeakageRbResult<u128> {
        self.total_sequences()?
            .checked_mul(self.shots_per_sequence as u128)
            .ok_or(LeakageRbError::ResourceCalculationOverflow)
    }

    /// Returns the total computational Hilbert-space dimension.
    pub fn total_dimension(&self) -> LeakageRbResult<usize> {
        self.computational_dimension
            .checked_add(self.leakage_dimension)
            .ok_or(
                LeakageRbError::HilbertDimensionOverflow,
            )
    }
}

// =============================================================================
// Sequence plan
// =============================================================================

/// Deterministic plan for one LRB sequence.
#[derive(
    Debug,
    Clone,
    Copy,
    PartialEq,
    Eq,
    Hash,
    Serialize,
    Deserialize,
)]
pub struct LeakageRbSequencePlan {
    /// Sequence length.
    pub sequence_length: usize,

    /// Zero-based sequence index within the length.
    pub sequence_index: usize,

    /// Deterministically derived sequence seed.
    pub sequence_seed: u64,

    /// Number of random Clifford operations.
    pub random_clifford_count: usize,

    /// Recovery Clifford is required.
    pub recovery_required: bool,
}

impl LeakageRbSequencePlan {
    /// Returns a stable sequence identity.
    pub fn identity(&self) -> LeakageRbSequenceIdentity {
        LeakageRbSequenceIdentity {
            sequence_length: self.sequence_length,
            sequence_index: self.sequence_index,
            sequence_seed: self.sequence_seed,
        }
    }
}

/// Stable sequence identity.
#[derive(
    Debug,
    Clone,
    Copy,
    PartialEq,
    Eq,
    Hash,
    Serialize,
    Deserialize,
)]
pub struct LeakageRbSequenceIdentity {
    /// Sequence length.
    pub sequence_length: usize,

    /// Sequence index.
    pub sequence_index: usize,

    /// Sequence seed.
    pub sequence_seed: u64,
}

/// Complete deterministic experiment plan.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct LeakageRbExperimentPlan {
    /// Protocol schema version.
    pub schema_version: u32,

    /// Stable benchmark identifier.
    pub benchmark_id: String,

    /// Stable algorithm identifier.
    pub algorithm_id: String,

    /// Experiment seed.
    pub experiment_seed: u64,

    /// Sequence plans.
    pub sequences: Vec<LeakageRbSequencePlan>,
}

impl LeakageRbExperimentPlan {
    /// Generates a complete deterministic sequence plan.
    pub fn generate(
        config: &LeakageRbConfig,
    ) -> LeakageRbResult<Self> {
        config.validate()?;

        let total =
            config.total_sequences()?;

        let capacity =
            usize::try_from(total).map_err(|_| {
                LeakageRbError::ResourceCalculationOverflow
            })?;

        let mut sequences =
            Vec::with_capacity(capacity);

        for &length in &config.sequence_lengths {
            for sequence_index in
                0..config.sequences_per_length
            {
                let seed = derive_sequence_seed(
                    config.experiment_seed,
                    length,
                    sequence_index,
                );

                sequences.push(
                    LeakageRbSequencePlan {
                        sequence_length: length,
                        sequence_index,
                        sequence_seed: seed,
                        random_clifford_count: length,
                        recovery_required: true,
                    },
                );
            }
        }

        Ok(Self {
            schema_version:
                LEAKAGE_RB_SCHEMA_VERSION,
            benchmark_id:
                LEAKAGE_RB_BENCHMARK_ID.to_owned(),
            algorithm_id:
                LEAKAGE_RB_ALGORITHM_ID.to_owned(),
            experiment_seed:
                config.experiment_seed,
            sequences,
        })
    }
}

// =============================================================================
// Observations
// =============================================================================

/// One captured LRB sequence observation.
///
/// Counts are preferred over probabilities because counts retain the original
/// experimental information and permit exact aggregation.
#[derive(
    Debug,
    Clone,
    Copy,
    PartialEq,
    Serialize,
    Deserialize,
)]
pub struct LeakageRbObservation {
    /// Sequence length.
    pub sequence_length: usize,

    /// Sequence index within this length.
    pub sequence_index: usize,

    /// Number of computational-subspace outcomes.
    pub computational_count: u64,

    /// Number of leakage-subspace outcomes.
    pub leakage_count: u64,

    /// Number of outcomes not classified into either subspace.
    ///
    /// This permits measurement adapters to preserve incomplete classification
    /// instead of silently assigning events to a physical subspace.
    pub unclassified_count: u64,

    /// Total shots.
    pub shots: u64,
}

impl LeakageRbObservation {
    /// Constructs an observation using computational and leakage counts.
    pub fn new(
        sequence_length: usize,
        sequence_index: usize,
        computational_count: u64,
        leakage_count: u64,
        unclassified_count: u64,
        shots: u64,
    ) -> LeakageRbResult<Self> {
        let observation = Self {
            sequence_length,
            sequence_index,
            computational_count,
            leakage_count,
            unclassified_count,
            shots,
        };

        observation.validate()?;

        Ok(observation)
    }

    /// Constructs a computational-subspace observation.
    ///
    /// `computational_count` is the number of shots classified as remaining
    /// inside the computational subspace.
    pub fn computational_only(
        sequence_length: usize,
        sequence_index: usize,
        computational_count: u64,
        shots: u64,
    ) -> LeakageRbResult<Self> {
        Self::new(
            sequence_length,
            sequence_index,
            computational_count,
            0,
            shots
                .checked_sub(computational_count)
                .ok_or(
                    LeakageRbError::InvalidObservationCounts {
                        length: sequence_length,
                        computational:
                            computational_count,
                        leakage: 0,
                        unclassified: 0,
                        shots,
                    },
                )?,
            shots,
        )
    }

    /// Constructs a direct-leakage observation.
    pub fn leakage_only(
        sequence_length: usize,
        sequence_index: usize,
        leakage_count: u64,
        shots: u64,
    ) -> LeakageRbResult<Self> {
        Self::new(
            sequence_length,
            sequence_index,
            0,
            leakage_count,
            shots
                .checked_sub(leakage_count)
                .ok_or(
                    LeakageRbError::InvalidObservationCounts {
                        length: sequence_length,
                        computational: 0,
                        leakage: leakage_count,
                        unclassified: 0,
                        shots,
                    },
                )?,
            shots,
        )
    }

    /// Validates count conservation and probability domains.
    pub fn validate(&self) -> LeakageRbResult<()> {
        if self.sequence_length == 0 {
            return Err(
                LeakageRbError::InvalidSequenceLength {
                    length: self.sequence_length,
                },
            );
        }

        let classified = self
            .computational_count
            .checked_add(self.leakage_count)
            .and_then(|value| {
                value.checked_add(self.unclassified_count)
            })
            .ok_or(
                LeakageRbError::ResourceCalculationOverflow,
            )?;

        if self.shots == 0
            || classified != self.shots
        {
            return Err(
                LeakageRbError::InvalidObservationCounts {
                    length: self.sequence_length,
                    computational:
                        self.computational_count,
                    leakage: self.leakage_count,
                    unclassified:
                        self.unclassified_count,
                    shots: self.shots,
                },
            );
        }

        Ok(())
    }

    /// Returns the computational-subspace probability.
    pub fn computational_probability(
        &self,
    ) -> f64 {
        self.computational_count as f64
            / self.shots as f64
    }

    /// Returns the leakage probability.
    pub fn leakage_probability(
        &self,
    ) -> f64 {
        self.leakage_count as f64 / self.shots as f64
    }

    /// Returns the unclassified probability.
    pub fn unclassified_probability(
        &self,
    ) -> f64 {
        self.unclassified_count as f64
            / self.shots as f64
    }
}

// =============================================================================
// Aggregated observations
// =============================================================================

/// Aggregated observations for one sequence length.
#[derive(
    Debug,
    Clone,
    Copy,
    PartialEq,
    Serialize,
    Deserialize,
)]
pub struct LeakageRbLengthObservation {
    /// Sequence length.
    pub sequence_length: usize,

    /// Number of independent sequences contributing data.
    pub sequence_count: usize,

    /// Total shots.
    pub shots: u64,

    /// Computational-subspace outcomes.
    pub computational_count: u64,

    /// Leakage outcomes.
    pub leakage_count: u64,

    /// Unclassified outcomes.
    pub unclassified_count: u64,

    /// Computational-subspace probability.
    pub computational_probability: f64,

    /// Leakage probability.
    pub leakage_probability: f64,

    /// Unclassified probability.
    pub unclassified_probability: f64,
}

impl LeakageRbLengthObservation {
    /// Creates an empty accumulator.
    fn empty(sequence_length: usize) -> Self {
        Self {
            sequence_length,
            sequence_count: 0,
            shots: 0,
            computational_count: 0,
            leakage_count: 0,
            unclassified_count: 0,
            computational_probability: 0.0,
            leakage_probability: 0.0,
            unclassified_probability: 0.0,
        }
    }

    /// Adds one observation.
    fn add(
        &mut self,
        observation: LeakageRbObservation,
    ) -> LeakageRbResult<()> {
        self.sequence_count = self
            .sequence_count
            .checked_add(1)
            .ok_or(
                LeakageRbError::ResourceCalculationOverflow,
            )?;

        self.shots = self
            .shots
            .checked_add(observation.shots)
            .ok_or(
                LeakageRbError::ResourceCalculationOverflow,
            )?;

        self.computational_count = self
            .computational_count
            .checked_add(
                observation.computational_count,
            )
            .ok_or(
                LeakageRbError::ResourceCalculationOverflow,
            )?;

        self.leakage_count = self
            .leakage_count
            .checked_add(observation.leakage_count)
            .ok_or(
                LeakageRbError::ResourceCalculationOverflow,
            )?;

        self.unclassified_count = self
            .unclassified_count
            .checked_add(
                observation.unclassified_count,
            )
            .ok_or(
                LeakageRbError::ResourceCalculationOverflow,
            )?;

        self.recalculate_probabilities()
    }

    fn recalculate_probabilities(
        &mut self,
    ) -> LeakageRbResult<()> {
        if self.shots == 0 {
            return Err(LeakageRbError::NoObservations);
        }

        self.computational_probability =
            self.computational_count as f64
                / self.shots as f64;

        self.leakage_probability =
            self.leakage_count as f64
                / self.shots as f64;

        self.unclassified_probability =
            self.unclassified_count as f64
                / self.shots as f64;

        validate_probability(
            "computational_probability",
            self.computational_probability,
        )?;

        validate_probability(
            "leakage_probability",
            self.leakage_probability,
        )?;

        validate_probability(
            "unclassified_probability",
            self.unclassified_probability,
        )?;

        Ok(())
    }
}

// =============================================================================
// Fit model
// =============================================================================

/// Constrained LRB exponential model.
///
/// ```text
/// y(m) = A + B * lambda^m
/// ```
///
/// Physical constraints:
///
/// ```text
/// A >= 0
/// B >= 0
/// A + B <= 1
/// 0 <= lambda <= 1
/// ```
#[derive(
    Debug,
    Clone,
    Copy,
    PartialEq,
    Serialize,
    Deserialize,
)]
pub struct LeakageDecayFit {
    /// Fitted asymptote A.
    pub amplitude: f64,

    /// Fitted transient coefficient B.
    pub transient_amplitude: f64,

    /// Fitted decay parameter lambda1.
    pub decay_parameter: f64,

    /// Equivalent per-step leakage-plus-seepage rate.
    pub total_transfer_rate: f64,

    /// Weighted sum of squared residuals.
    pub weighted_residual_sum_of_squares: f64,

    /// Root mean squared error.
    pub rmse: f64,

    /// R², if defined.
    pub r_squared: Option<f64>,

    /// Whether the fitted lambda lies at a numerical boundary.
    pub boundary_solution: bool,

    /// Whether the constrained fit converged.
    pub converged: bool,

    /// Number of refinement iterations.
    pub refinement_iterations: usize,
}

impl LeakageDecayFit {
    /// Returns the fitted leakage rate L1.
    ///
    /// Wood–Gambetta:
    ///
    /// ```text
    /// L1 = (1 - A) * (1 - lambda1)
    /// ```
    pub fn leakage_rate(
        &self,
    ) -> f64 {
        (1.0 - self.amplitude)
            * (1.0 - self.decay_parameter)
    }

    /// Returns the fitted seepage rate L2.
    ///
    /// Wood–Gambetta:
    ///
    /// ```text
    /// L2 = A * (1 - lambda1)
    /// ```
    pub fn seepage_rate(
        &self,
    ) -> f64 {
        self.amplitude
            * (1.0 - self.decay_parameter)
    }

    /// Predicts computational-subspace population at a sequence length.
    pub fn predict(
        &self,
        sequence_length: usize,
    ) -> LeakageRbResult<f64> {
        let value = self.amplitude
            + self.transient_amplitude
                * self
                    .decay_parameter
                    .powf(sequence_length as f64);

        validate_probability(
            "predicted_computational_probability",
            value,
        )?;

        Ok(value)
    }
}

// =============================================================================
// Analysis warnings
// =============================================================================

/// Structured scientific warning.
#[derive(
    Debug,
    Clone,
    Copy,
    PartialEq,
    Eq,
    Serialize,
    Deserialize,
)]
pub enum LeakageRbWarning {
    /// The leakage rate is extremely small compared with numerical precision.
    LeakageRateNearZero,

    /// The seepage rate is extremely small compared with numerical precision.
    SeepageRateNearZero,

    /// The fitted decay is at lambda ~= 1.
    DecayNearUnity,

    /// The fitted decay is at lambda ~= 0.
    DecayNearZero,

    /// The fit landed on a search boundary.
    BoundarySolution,

    /// Insufficient residual degrees of freedom for strong diagnostics.
    LimitedResidualDegreesOfFreedom,

    /// Unclassified measurement outcomes are present.
    UnclassifiedOutcomesPresent,

    /// Not all scientific assumptions are declared satisfied.
    AssumptionsNotSatisfied,

    /// Direct leakage measurement was converted into computational population.
    DerivedComputationalPopulation,

    /// Fit quality is poor.
    PoorFitQuality,

    /// Data contain a nonzero leakage population but too few independent
    /// sequences may make the estimate unstable.
    LowSequenceReplication,

    /// The experiment is vulnerable to leakage during measurement itself.
    MeasurementLeakagePossible,
}

impl LeakageRbWarning {
    /// Stable machine-readable identifier.
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::LeakageRateNearZero => {
                "leakage_rate_near_zero"
            }
            Self::SeepageRateNearZero => {
                "seepage_rate_near_zero"
            }
            Self::DecayNearUnity => {
                "decay_near_unity"
            }
            Self::DecayNearZero => {
                "decay_near_zero"
            }
            Self::BoundarySolution => {
                "boundary_solution"
            }
            Self::LimitedResidualDegreesOfFreedom => {
                "limited_residual_degrees_of_freedom"
            }
            Self::UnclassifiedOutcomesPresent => {
                "unclassified_outcomes_present"
            }
            Self::AssumptionsNotSatisfied => {
                "assumptions_not_satisfied"
            }
            Self::DerivedComputationalPopulation => {
                "derived_computational_population"
            }
            Self::PoorFitQuality => {
                "poor_fit_quality"
            }
            Self::LowSequenceReplication => {
                "low_sequence_replication"
            }
            Self::MeasurementLeakagePossible => {
                "measurement_leakage_possible"
            }
        }
    }
}

// =============================================================================
// Result
// =============================================================================

/// Complete production result of leakage randomized benchmarking.
#[derive(
    Debug,
    Clone,
    PartialEq,
    Serialize,
    Deserialize,
)]
pub struct LeakageRbResult {
    /// Protocol schema version.
    pub schema_version: u32,

    /// Stable benchmark identifier.
    pub benchmark_id: String,

    /// Stable algorithm identifier.
    pub algorithm_id: String,

    /// Measurement mode.
    pub measurement_mode: LeakageMeasurementMode,

    /// Number of computational-subspace dimensions.
    pub computational_dimension: usize,

    /// Number of leakage-subspace dimensions.
    pub leakage_dimension: usize,

    /// Total Hilbert-space dimension represented by the protocol model.
    pub total_dimension: usize,

    /// Experiment seed.
    pub experiment_seed: u64,

    /// Sequence lengths analyzed.
    pub sequence_lengths: Vec<usize>,

    /// Aggregated observations.
    pub observations: Vec<LeakageRbLengthObservation>,

    /// Fitted leakage decay.
    pub fit: LeakageDecayFit,

    /// Average leakage rate L1.
    pub leakage_rate: f64,

    /// Average seepage rate L2.
    pub seepage_rate: f64,

    /// Combined transfer rate L1 + L2.
    pub combined_transfer_rate: f64,

    /// Number of total shots.
    pub total_shots: u128,

    /// Number of independent sequences.
    pub total_sequences: u128,

    /// Scientific assumptions.
    pub assumptions: LeakageRbAssumptions,

    /// Structured warnings.
    pub warnings: Vec<LeakageRbWarning>,
}

impl LeakageRbResult {
    /// Returns the fitted leakage/seepage decay parameter.
    pub fn lambda1(&self) -> f64 {
        self.fit.decay_parameter
    }

    /// Returns whether the result has any scientific warnings.
    pub fn has_warnings(&self) -> bool {
        !self.warnings.is_empty()
    }

    /// Returns whether all declared mandatory assumptions are satisfied.
    pub fn assumptions_satisfied(&self) -> bool {
        self.assumptions.are_satisfied()
    }

    /// Returns the result as a stable protocol identifier.
    pub const fn protocol_id() -> &'static str {
        LEAKAGE_RB_BENCHMARK_ID
    }
}

// =============================================================================
// Analyzer
// =============================================================================

/// Production LRB analyzer.
///
/// The analyzer is stateless and deterministic.
///
/// It can be used for:
///
/// - live execution results;
/// - archived hardware results;
/// - simulator fixtures;
/// - regression tests;
/// - independent scientific re-analysis.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct LeakageRbAnalyzer {
    /// Fit grid points.
    pub fit_grid_points: usize,

    /// Maximum local refinement iterations.
    pub fit_refinement_iterations: usize,

    /// Fit tolerance.
    pub fit_tolerance: f64,
}

impl LeakageRbAnalyzer {
    /// Creates an analyzer from configuration.
    pub fn from_config(
        config: &LeakageRbConfig,
    ) -> LeakageRbResult<Self> {
        config.validate()?;

        Ok(Self {
            fit_grid_points:
                config.fit_grid_points,
            fit_refinement_iterations:
                config.fit_refinement_iterations,
            fit_tolerance:
                config.fit_tolerance,
        })
    }

    /// Analyzes captured observations.
    pub fn analyze(
        &self,
        config: &LeakageRbConfig,
        observations: &[LeakageRbObservation],
    ) -> LeakageRbResult<LeakageRbResult> {
        config.validate()?;

        if observations.is_empty() {
            return Err(LeakageRbError::NoObservations);
        }

        let aggregated =
            aggregate_observations(
                config,
                observations,
            )?;

        let fit_observations: Vec<(f64, f64, f64)> =
            aggregated
                .iter()
                .map(|observation| {
                    (
                        observation.sequence_length
                            as f64,
                        observation
                            .computational_probability,
                        observation.shots as f64,
                    )
                })
                .collect();

        let fit = fit_decay(
            &fit_observations,
            self.fit_grid_points,
            self.fit_refinement_iterations,
            self.fit_tolerance,
        )?;

        let leakage_rate =
            fit.leakage_rate();

        let seepage_rate =
            fit.seepage_rate();

        validate_rate(
            "leakage_rate",
            leakage_rate,
        )?;

        validate_rate(
            "seepage_rate",
            seepage_rate,
        )?;

        let combined_transfer_rate =
            leakage_rate + seepage_rate;

        if combined_transfer_rate
            > 1.0 + PROBABILITY_EPSILON
        {
            return Err(
                LeakageRbError::InvalidPhysicalFit,
            );
        }

        let total_shots =
            observations.iter().try_fold(
                0u128,
                |accumulator, observation| {
                    accumulator
                        .checked_add(
                            observation.shots as u128
                        )
                        .ok_or(
                            LeakageRbError::
                                ResourceCalculationOverflow,
                        )
                },
            )?;

        let total_sequences =
            observations.len() as u128;

        let warnings =
            build_warnings(
                config,
                &aggregated,
                &fit,
                leakage_rate,
                seepage_rate,
            );

        Ok(LeakageRbResult {
            schema_version:
                LEAKAGE_RB_SCHEMA_VERSION,
            benchmark_id:
                LEAKAGE_RB_BENCHMARK_ID.to_owned(),
            algorithm_id:
                LEAKAGE_RB_ALGORITHM_ID.to_owned(),
            measurement_mode:
                config.measurement_mode,
            computational_dimension:
                config.computational_dimension,
            leakage_dimension:
                config.leakage_dimension,
            total_dimension:
                config.total_dimension()?,
            experiment_seed:
                config.experiment_seed,
            sequence_lengths:
                config.sequence_lengths.clone(),
            observations: aggregated,
            fit,
            leakage_rate,
            seepage_rate,
            combined_transfer_rate,
            total_shots,
            total_sequences,
            assumptions:
                config.assumptions,
            warnings,
        })
    }
}

// =============================================================================
// Convenience API
// =============================================================================

/// Runs analysis using the configuration's production fit settings.
pub fn analyze(
    config: &LeakageRbConfig,
    observations: &[LeakageRbObservation],
) -> LeakageRbResult<LeakageRbResult> {
    let analyzer =
        LeakageRbAnalyzer::from_config(config)?;

    analyzer.analyze(config, observations)
}

/// Generates a deterministic experiment plan.
pub fn generate_plan(
    config: &LeakageRbConfig,
) -> LeakageRbResult<LeakageRbExperimentPlan> {
    LeakageRbExperimentPlan::generate(config)
}

// =============================================================================
// Observation aggregation
// =============================================================================

fn aggregate_observations(
    config: &LeakageRbConfig,
    observations: &[LeakageRbObservation],
) -> LeakageRbResult<Vec<LeakageRbLengthObservation>> {
    let mut result: Vec<LeakageRbLengthObservation> =
        config
            .sequence_lengths
            .iter()
            .copied()
            .map(LeakageRbLengthObservation::empty)
            .collect();

    let mut seen: Vec<(usize, usize)> =
        Vec::with_capacity(observations.len());

    for &observation in observations {
        observation.validate()?;

        if !config
            .sequence_lengths
            .contains(&observation.sequence_length)
        {
            return Err(
                LeakageRbError::UnexpectedSequenceLength {
                    length: observation.sequence_length,
                },
            );
        }

        if seen.iter().any(|(length, index)| {
            *length == observation.sequence_length
                && *index == observation.sequence_index
        }) {
            return Err(
                LeakageRbError::DuplicateSequenceObservation {
                    length: observation.sequence_length,
                    sequence_index:
                        observation.sequence_index,
                },
            );
        }

        seen.push((
            observation.sequence_length,
            observation.sequence_index,
        ));

        let position = config
            .sequence_lengths
            .iter()
            .position(|length| {
                *length == observation.sequence_length
            })
            .ok_or(
                LeakageRbError::UnexpectedSequenceLength {
                    length: observation.sequence_length,
                },
            )?;

        result[position].add(observation)?;
    }

    if result.iter().any(|observation| {
        observation.sequence_count == 0
    }) {
        return Err(
            LeakageRbError::NoObservations,
        );
    }

    for observation in &mut result {
        if observation.sequence_count < 2 {
            // The warning is generated later. One sequence is still
            // mathematically analyzable.
        }

        match config.measurement_mode {
            LeakageMeasurementMode::ComputationalSubspace => {}

            LeakageMeasurementMode::DirectLeakage => {
                // Convert directly measured leakage population into the
                // complementary computational population only when the
                // measurement is complete. Unclassified outcomes make that
                // complement invalid as a normalized computational probability.
                if observation.unclassified_count == 0 {
                    observation.computational_probability =
                        1.0 - observation.leakage_probability;

                    validate_probability(
                        "derived_computational_probability",
                        observation.computational_probability,
                    )?;
                }
            }

            LeakageMeasurementMode::Both => {
                let classified = observation
                    .computational_probability
                    + observation.leakage_probability;

                if observation.unclassified_count == 0
                    && (classified - 1.0).abs()
                        > PROBABILITY_EPSILON
                {
                    return Err(
                        LeakageRbError::InvalidPhysicalFit,
                    );
                }
            }
        }
    }

    Ok(result)
}

// =============================================================================
// Decay fitting
// =============================================================================

/// Fits:
///
/// ```text
/// y = A + B * lambda^m
/// ```
///
/// subject to:
///
/// ```text
/// 0 <= lambda <= 1
/// A >= 0
/// B >= 0
/// A + B <= 1
/// ```
fn fit_decay(
    observations: &[(f64, f64, f64)],
    grid_points: usize,
    max_iterations: usize,
    tolerance: f64,
) -> LeakageRbResult<LeakageDecayFit> {
    if observations.len() < MIN_SEQUENCE_LENGTHS
        || grid_points < 8
        || max_iterations == 0
        || !tolerance.is_finite()
        || tolerance <= 0.0
    {
        return Err(
            LeakageRbError::InvalidFitConfiguration,
        );
    }

    let distinct =
        count_distinct_x(observations);

    if distinct < MIN_SEQUENCE_LENGTHS {
        return Err(
            LeakageRbError::InsufficientSequenceLengths {
                supplied: distinct,
                minimum: MIN_SEQUENCE_LENGTHS,
            },
        );
    }

    let mut best:
        Option<ConstrainedFitCandidate> = None;

    let denominator =
        (grid_points - 1) as f64;

    for index in 0..grid_points {
        let lambda =
            index as f64 / denominator;

        if let Some(candidate) =
            fit_at_lambda(observations, lambda)
        {
            if best
                .as_ref()
                .map(|current| {
                    candidate.sse
                        < current.sse
                })
                .unwrap_or(true)
            {
                best = Some(candidate);
            }
        }
    }

    let best =
        best.ok_or(LeakageRbError::FitFailed)?;

    let best_lambda =
        best.lambda;

    let grid_step =
        1.0 / denominator;

    let mut left =
        (best_lambda - grid_step)
            .max(MIN_LAMBDA);

    let mut right =
        (best_lambda + grid_step)
            .min(MAX_LAMBDA);

    let boundary =
        best_lambda <= FIT_EPSILON
            || best_lambda
                >= 1.0 - FIT_EPSILON;

    let mut iterations = 0usize;
    let mut current = best;

    if !boundary && right > left {
        // Golden-section refinement.
        let golden =
            0.618_033_988_749_894_9_f64;

        let mut x1 =
            right - golden * (right - left);
        let mut x2 =
            left + golden * (right - left);

        let mut f1 =
            fit_at_lambda(
                observations,
                x1,
            )
            .map(|fit| fit.sse)
            .unwrap_or(f64::INFINITY);

        let mut f2 =
            fit_at_lambda(
                observations,
                x2,
            )
            .map(|fit| fit.sse)
            .unwrap_or(f64::INFINITY);

        while iterations
            < max_iterations
            && (right - left)
                > tolerance
        {
            iterations += 1;

            if f1 > f2 {
                left = x1;
                x1 = x2;
                f1 = f2;

                x2 =
                    left + golden
                        * (right - left);

                f2 =
                    fit_at_lambda(
                        observations,
                        x2,
                    )
                    .map(|fit| fit.sse)
                    .unwrap_or(
                        f64::INFINITY,
                    );
            } else {
                right = x2;
                x2 = x1;
                f2 = f1;

                x1 =
                    right - golden
                        * (right - left);

                f1 =
                    fit_at_lambda(
                        observations,
                        x1,
                    )
                    .map(|fit| fit.sse)
                    .unwrap_or(
                        f64::INFINITY,
                    );
            }
        }

        let candidate_lambda =
            0.5 * (left + right);

        if let Some(candidate) =
            fit_at_lambda(
                observations,
                candidate_lambda,
            )
        {
            if candidate.sse
                < current.sse
            {
                current = candidate;
            }
        }
    }

    let predicted: Vec<f64> =
        observations
            .iter()
            .map(|(x, _, _)| {
                current.amplitude
                    + current.transient_amplitude
                        * current
                            .lambda
                            .powf(*x)
            })
            .collect();

    let mean_y =
        weighted_mean(observations);

    let mut sse = 0.0;
    let mut total = 0.0;

    for (index, (_, y, weight)) in
        observations.iter().enumerate()
    {
        let residual =
            *y - predicted[index];

        sse +=
            *weight * residual * residual;

        let centered =
            *y - mean_y;

        total +=
            *weight * centered * centered;
    }

    if !sse.is_finite() {
        return Err(
            LeakageRbError::FitFailed,
        );
    }

    let r_squared =
        if total > 0.0 && total.is_finite() {
            Some(
                (1.0 - sse / total)
                    .clamp(0.0, 1.0),
            )
        } else {
            None
        };

    let rmse =
        (sse / observations.len() as f64)
            .sqrt();

    if !rmse.is_finite() {
        return Err(
            LeakageRbError::FitFailed,
        );
    }

    let decay =
        current.lambda;

    let total_transfer =
        1.0 - decay;

    if !decay.is_finite()
        || decay < MIN_LAMBDA
        || decay > MAX_LAMBDA
    {
        return Err(
            LeakageRbError::InvalidDecayParameter {
                value: decay,
            },
        );
    }

    Ok(LeakageDecayFit {
        amplitude:
            current.amplitude,
        transient_amplitude:
            current.transient_amplitude,
        decay_parameter:
            decay,
        total_transfer_rate:
            total_transfer,
        weighted_residual_sum_of_squares:
            sse,
        rmse,
        r_squared,
        boundary_solution:
            boundary
                || current.amplitude <= FIT_EPSILON
                || current.transient_amplitude
                    <= FIT_EPSILON
                || (current.amplitude
                    + current.transient_amplitude)
                    >= 1.0 - FIT_EPSILON,
        converged:
            boundary
                || iterations < max_iterations
                || (right - left) <= tolerance,
        refinement_iterations:
            iterations,
    })
}

/// Internal constrained fit for a fixed lambda.
#[derive(
    Debug,
    Clone,
    Copy,
)]
struct ConstrainedFitCandidate {
    amplitude: f64,
    transient_amplitude: f64,
    lambda: f64,
    sse: f64,
}

/// Solves the constrained A/B problem at a fixed lambda.
///
/// The feasible region is the simplex:
///
/// ```text
/// A >= 0
/// B >= 0
/// A + B <= 1
/// ```
///
/// Because this is a two-parameter quadratic problem, the global constrained
/// optimum is obtained by evaluating the unconstrained solution and all
/// boundary faces.
fn fit_at_lambda(
    observations: &[(f64, f64, f64)],
    lambda: f64,
) -> Option<ConstrainedFitCandidate> {
    if !lambda.is_finite()
        || !(MIN_LAMBDA..=MAX_LAMBDA)
            .contains(&lambda)
    {
        return None;
    }

    let mut candidates =
        Vec::with_capacity(8);

    // ---------------------------------------------------------------------
    // Interior / unconstrained solution.
    // ---------------------------------------------------------------------

    let mut s_zz = 0.0;
    let mut s_z = 0.0;
    let mut s_1 = 0.0;
    let mut s_zy = 0.0;
    let mut s_y = 0.0;

    for (x, y, weight) in observations {
        let z =
            lambda.powf(*x);

        if !z.is_finite()
            || !weight.is_finite()
            || *weight <= 0.0
        {
            return None;
        }

        s_zz += *weight * z * z;
        s_z += *weight * z;
        s_1 += *weight;
        s_zy += *weight * z * *y;
        s_y += *weight * *y;
    }

    let determinant =
        s_zz * s_1 - s_z * s_z;

    if determinant.abs()
        > f64::EPSILON
            * (s_zz.abs()
                * s_1.abs()
                + s_z.abs() * s_z.abs()
                + 1.0)
    {
        let amplitude =
            (s_zy * s_1 - s_z * s_y)
                / determinant;

        let transient =
            (s_zz * s_y - s_z * s_zy)
                / determinant;

        if is_feasible(
            amplitude,
            transient,
        ) {
            candidates.push(
                candidate_for(
                    observations,
                    lambda,
                    amplitude,
                    transient,
                ),
            );
        }
    }

    // ---------------------------------------------------------------------
    // Face A = 0.
    // ---------------------------------------------------------------------

    if s_1 > 0.0 {
        let b =
            (s_y / s_1).clamp(0.0, 1.0);

        candidates.push(
            candidate_for(
                observations,
                lambda,
                0.0,
                b,
            ),
        );
    }

    // ---------------------------------------------------------------------
    // Face B = 0.
    // ---------------------------------------------------------------------

    if s_zz > 0.0 {
        let a =
            (s_zy / s_zz).clamp(0.0, 1.0);

        candidates.push(
            candidate_for(
                observations,
                lambda,
                a,
                0.0,
            ),
        );
    }

    // ---------------------------------------------------------------------
    // Face A + B = 1.
    //
    // y = 1 + B*(z - 1)
    // ---------------------------------------------------------------------

    let mut numerator = 0.0;
    let mut denominator = 0.0;

    for (x, y, weight) in observations {
        let z =
            lambda.powf(*x);

        let basis =
            z - 1.0;

        numerator +=
            *weight * basis * (*y - 1.0);

        denominator +=
            *weight * basis * basis;
    }

    if denominator > 0.0 {
        let b =
            (numerator / denominator)
                .clamp(0.0, 1.0);

        let a =
            1.0 - b;

        candidates.push(
            candidate_for(
                observations,
                lambda,
                a,
                b,
            ),
        );
    }

    // ---------------------------------------------------------------------
    // Vertices.
    // ---------------------------------------------------------------------

    candidates.push(
        candidate_for(
            observations,
            lambda,
            0.0,
            0.0,
        ),
    );

    candidates.push(
        candidate_for(
            observations,
            lambda,
            1.0,
            0.0,
        ),
    );

    candidates.push(
        candidate_for(
            observations,
            lambda,
            0.0,
            1.0,
        ),
    );

    candidates
        .into_iter()
        .filter(|candidate| {
            candidate.sse.is_finite()
        })
        .min_by(|left, right| {
            left.sse
                .partial_cmp(&right.sse)
                .unwrap_or(
                    std::cmp::Ordering::Equal,
                )
        })
}

fn candidate_for(
    observations: &[(f64, f64, f64)],
    lambda: f64,
    amplitude: f64,
    transient_amplitude: f64,
) -> ConstrainedFitCandidate {
    let mut sse = 0.0;

    for (x, y, weight) in observations {
        let prediction =
            amplitude
                + transient_amplitude
                    * lambda.powf(*x);

        let residual =
            *y - prediction;

        sse +=
            *weight * residual * residual;
    }

    ConstrainedFitCandidate {
        amplitude,
        transient_amplitude,
        lambda,
        sse,
    }
}

fn is_feasible(
    amplitude: f64,
    transient_amplitude: f64,
) -> bool {
    amplitude.is_finite()
        && transient_amplitude.is_finite()
        && amplitude >= -FIT_EPSILON
        && transient_amplitude
            >= -FIT_EPSILON
        && amplitude
            + transient_amplitude
            <= 1.0 + FIT_EPSILON
}

// =============================================================================
// Diagnostics
// =============================================================================

fn build_warnings(
    config: &LeakageRbConfig,
    observations: &[LeakageRbLengthObservation],
    fit: &LeakageDecayFit,
    leakage_rate: f64,
    seepage_rate: f64,
) -> Vec<LeakageRbWarning> {
    let mut warnings =
        Vec::with_capacity(8);

    if !config.assumptions.are_satisfied() {
        warnings.push(
            LeakageRbWarning::AssumptionsNotSatisfied,
        );
    }

    if observations
        .iter()
        .any(|observation| {
            observation.unclassified_count > 0
        })
    {
        warnings.push(
            LeakageRbWarning::UnclassifiedOutcomesPresent,
        );
    }

    if matches!(
        config.measurement_mode,
        LeakageMeasurementMode::DirectLeakage
    ) {
        warnings.push(
            LeakageRbWarning::DerivedComputationalPopulation,
        );
    }

    if leakage_rate <= 1.0e-12 {
        warnings.push(
            LeakageRbWarning::LeakageRateNearZero,
        );
    }

    if seepage_rate <= 1.0e-12 {
        warnings.push(
            LeakageRbWarning::SeepageRateNearZero,
        );
    }

    if fit.decay_parameter
        >= 1.0 - 1.0e-8
    {
        warnings.push(
            LeakageRbWarning::DecayNearUnity,
        );
    }

    if fit.decay_parameter
        <= 1.0e-8
    {
        warnings.push(
            LeakageRbWarning::DecayNearZero,
        );
    }

    if fit.boundary_solution {
        warnings.push(
            LeakageRbWarning::BoundarySolution,
        );
    }

    if observations
        .iter()
        .any(|observation| {
            observation.sequence_count < 2
        })
    {
        warnings.push(
            LeakageRbWarning::LowSequenceReplication,
        );
    }

    if fit.r_squared
        .map(|value| value < 0.90)
        .unwrap_or(false)
    {
        warnings.push(
            LeakageRbWarning::PoorFitQuality,
        );
    }

    if fit.refinement_iterations == 0 {
        warnings.push(
            LeakageRbWarning::BoundarySolution,
        );
    }

    // Measurement-induced leakage is an explicit concern for many physical
    // systems. The protocol cannot determine this automatically, so the
    // warning is not emitted unconditionally. The caller can represent it
    // through the scientific assumption/telemetry layer.
    let _ = &config.assumptions;

    warnings
}

// =============================================================================
// Validation helpers
// =============================================================================

fn validate_sequence_lengths(
    sequence_lengths: &[usize],
    maximum_count: usize,
    maximum_length: usize,
) -> LeakageRbResult<()> {
    if sequence_lengths.is_empty() {
        return Err(
            LeakageRbError::EmptySequenceLengths,
        );
    }

    if sequence_lengths.len()
        > maximum_count
    {
        return Err(
            LeakageRbError::TooManySequenceLengths {
                requested:
                    sequence_lengths.len(),
                maximum: maximum_count,
            },
        );
    }

    let mut previous = 0usize;

    for (index, &length) in
        sequence_lengths.iter().enumerate()
    {
        if length == 0
            || length > maximum_length
        {
            return Err(
                LeakageRbError::InvalidSequenceLength {
                    length,
                },
            );
        }

        if index > 0 {
            if length == previous {
                return Err(
                    LeakageRbError::DuplicateSequenceLength {
                        length,
                    },
                );
            }

            if length < previous {
                return Err(
                    LeakageRbError::UnsortedSequenceLengths,
                );
            }
        }

        previous = length;
    }

    Ok(())
}

fn validate_probability(
    field: &'static str,
    value: f64,
) -> LeakageRbResult<()> {
    if !value.is_finite() {
        return Err(
            LeakageRbError::NonFiniteProbability {
                field,
            },
        );
    }

    if value < -PROBABILITY_EPSILON
        || value > 1.0 + PROBABILITY_EPSILON
    {
        return Err(
            LeakageRbError::ProbabilityOutOfRange {
                field,
                value,
            },
        );
    }

    Ok(())
}

fn validate_rate(
    field: &'static str,
    value: f64,
) -> LeakageRbResult<()> {
    validate_probability(field, value)
}

fn count_distinct_x(
    observations: &[(f64, f64, f64)],
) -> usize {
    let mut values: Vec<f64> =
        observations
            .iter()
            .map(|(x, _, _)| *x)
            .collect();

    values.sort_by(|a, b| {
        a.partial_cmp(b)
            .unwrap_or(
                std::cmp::Ordering::Equal,
            )
    });

    values.dedup_by(|a, b| {
        (*a - *b).abs()
            <= f64::EPSILON
                * a.abs().max(b.abs()).max(1.0)
                * 16.0
    });

    values.len()
}

fn weighted_mean(
    observations: &[(f64, f64, f64)],
) -> f64 {
    let mut numerator = 0.0;
    let mut denominator = 0.0;

    for (_, y, weight) in observations {
        numerator += *weight * *y;
        denominator += *weight;
    }

    if denominator > 0.0 {
        numerator / denominator
    } else {
        0.0
    }
}

// =============================================================================
// Reproducibility
// =============================================================================

/// Deterministically derives a sequence seed.
///
/// SplitMix64-style mixing is used only for deterministic domain separation;
/// it is NOT a cryptographic random-number generator.
fn derive_sequence_seed(
    experiment_seed: u64,
    sequence_length: usize,
    sequence_index: usize,
) -> u64 {
    let mut value =
        experiment_seed
            ^ 0x9E37_79B9_7F4A_7C15;

    value = splitmix64(
        value
            ^ sequence_length as u64,
    );

    value = splitmix64(
        value
            ^ sequence_index as u64,
    );

    value
}

fn splitmix64(
    mut value: u64,
) -> u64 {
    value =
        value.wrapping_add(
            0x9E37_79B9_7F4A_7C15,
        );

    let mut result = value;

    result =
        (result ^ (result >> 30))
            .wrapping_mul(
                0xBF58_476D_1CE4_E5B9,
            );

    result =
        (result ^ (result >> 27))
            .wrapping_mul(
                0x94D0_49BB_1331_11EB,
            );

    result ^ (result >> 31)
}

// =============================================================================
// Unit tests
// =============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    fn synthetic_observations(
        lambda: f64,
        amplitude: f64,
        transient: f64,
    ) -> Vec<LeakageRbObservation> {
        let lengths =
            [1usize, 11, 21, 41, 81, 161];

        lengths
            .iter()
            .enumerate()
            .map(
                |(index, &length)| {
                    let probability =
                        amplitude
                            + transient
                                * lambda.powf(
                                    length as f64,
                                );

                    let shots =
                        100_000_u64;

                    let computational =
                        (probability
                            * shots as f64)
                            .round()
                            as u64;

                    LeakageRbObservation::new(
                        length,
                        index,
                        computational,
                        shots
                            - computational,
                        0,
                        shots,
                    )
                    .expect(
                        "synthetic observation",
                    )
                },
            )
            .collect()
    }

    #[test]
    fn production_configuration_is_valid() {
        let config =
            LeakageRbConfig::production();

        assert!(
            config.validate().is_ok()
        );
    }

    #[test]
    fn sequence_lengths_must_be_sorted() {
        let mut config =
            LeakageRbConfig::production();

        config.sequence_lengths =
            vec![1, 21, 11, 41];

        assert_eq!(
            config.validate(),
            Err(
                LeakageRbError::
                    UnsortedSequenceLengths
            )
        );
    }

    #[test]
    fn duplicate_lengths_are_rejected() {
        let mut config =
            LeakageRbConfig::production();

        config.sequence_lengths =
            vec![1, 11, 11, 41];

        assert_eq!(
            config.validate(),
            Err(
                LeakageRbError::
                    DuplicateSequenceLength {
                        length: 11
                    }
            )
        );
    }

    #[test]
    fn resource_overflow_is_checked() {
        let mut config =
            LeakageRbConfig::production();

        config.sequences_per_length =
            usize::MAX;

        let result =
            config.total_shots();

        assert!(
            result.is_err()
        );
    }

    #[test]
    fn observation_count_conservation_is_enforced() {
        let result =
            LeakageRbObservation::new(
                1,
                0,
                5,
                5,
                1,
                10,
            );

        assert!(
            result.is_err()
        );
    }

    #[test]
    fn computational_probability_is_correct() {
        let observation =
            LeakageRbObservation::new(
                1,
                0,
                900,
                100,
                0,
                1_000,
            )
            .expect("valid observation");

        assert!(
            (observation
                .computational_probability()
                - 0.9)
                .abs()
                < 1.0e-12
        );

        assert!(
            (observation
                .leakage_probability()
                - 0.1)
                .abs()
                < 1.0e-12
        );
    }

    #[test]
    fn direct_leakage_can_be_complemented() {
        let observation =
            LeakageRbObservation::leakage_only(
                11,
                0,
                100,
                1_000,
            )
            .expect("valid observation");

        let mut config =
            LeakageRbConfig::production();

        config.sequence_lengths =
            vec![1, 11, 21, 41];

        config.sequences_per_length =
            1;

        config.max_sequences_per_length =
            1;

        let result =
            aggregate_observations(
                &config,
                &[
                    observation,
                    LeakageRbObservation::leakage_only(
                        1,
                        0,
                        50,
                        1_000,
                    )
                    .expect("valid"),
                    LeakageRbObservation::leakage_only(
                        21,
                        0,
                        120,
                        1_000,
                    )
                    .expect("valid"),
                    LeakageRbObservation::leakage_only(
                        41,
                        0,
                        150,
                        1_000,
                    )
                    .expect("valid"),
                ],
            )
            .expect("aggregation");

        let eleven =
            result
                .iter()
                .find(|item| {
                    item.sequence_length == 11
                })
                .expect("length 11");

        assert!(
            (eleven
                .computational_probability
                - 0.9)
                .abs()
                < 1.0e-12
        );
    }

    #[test]
    fn deterministic_sequence_plan_is_reproducible() {
        let config =
            LeakageRbConfig::production();

        let first =
            LeakageRbExperimentPlan::generate(
                &config,
            )
            .expect("plan");

        let second =
            LeakageRbExperimentPlan::generate(
                &config,
            )
            .expect("plan");

        assert_eq!(
            first,
            second
        );
    }

    #[test]
    fn different_sequence_indices_get_different_seeds() {
        let seed_a =
            derive_sequence_seed(
                42,
                100,
                0,
            );

        let seed_b =
            derive_sequence_seed(
                42,
                100,
                1,
            );

        assert_ne!(
            seed_a,
            seed_b
        );
    }

    #[test]
    fn fit_recovers_synthetic_leakage_model() {
        let lambda =
            0.995;

        let amplitude =
            0.20;

        let transient =
            0.78;

        let observations =
            synthetic_observations(
                lambda,
                amplitude,
                transient,
            );

        let mut config =
            LeakageRbConfig::production();

        config.sequence_lengths =
            vec![1, 11, 21, 41, 81, 161];

        config.sequences_per_length =
            1;

        config.max_sequences_per_length =
            1;

        config.shots_per_sequence =
            100_000;

        let result =
            analyze(
                &config,
                &observations,
            )
            .expect("LRB analysis");

        assert!(
            (result.lambda1()
                - lambda)
                .abs()
                < 0.01
        );

        assert!(
            result.leakage_rate
                >= 0.0
        );

        assert!(
            result.seepage_rate
                >= 0.0
        );

        assert!(
            result.combined_transfer_rate
                <= 1.0
                    + PROBABILITY_EPSILON
        );
    }

    #[test]
    fn leakage_and_seepage_formulas_are_correct() {
        let fit =
            LeakageDecayFit {
                amplitude: 0.25,
                transient_amplitude: 0.75,
                decay_parameter: 0.99,
                total_transfer_rate: 0.01,
                weighted_residual_sum_of_squares: 0.0,
                rmse: 0.0,
                r_squared: Some(1.0),
                boundary_solution: false,
                converged: true,
                refinement_iterations: 10,
            };

        let leakage =
            fit.leakage_rate();

        let seepage =
            fit.seepage_rate();

        assert!(
            (leakage - 0.0075).abs()
                < 1.0e-12
        );

        assert!(
            (seepage - 0.0025).abs()
                < 1.0e-12
        );

        assert!(
            (leakage + seepage
                - 0.01)
                .abs()
                < 1.0e-12
        );
    }

    #[test]
    fn fit_is_physically_constrained() {
        let observations =
            synthetic_observations(
                0.98,
                0.10,
                0.85,
            );

        let mut config =
            LeakageRbConfig::production();

        config.sequence_lengths =
            vec![1, 11, 21, 41, 81, 161];

        config.sequences_per_length =
            1;

        config.max_sequences_per_length =
            1;

        let result =
            analyze(
                &config,
                &observations,
            )
            .expect("analysis");

        assert!(
            result.fit.amplitude
                >= -FIT_EPSILON
        );

        assert!(
            result.fit
                .transient_amplitude
                >= -FIT_EPSILON
        );

        assert!(
            result.fit.amplitude
                + result.fit.transient_amplitude
                <= 1.0 + FIT_EPSILON
        );

        assert!(
            result.lambda1()
                >= 0.0
        );

        assert!(
            result.lambda1()
                <= 1.0
        );
    }

    #[test]
    fn warnings_are_structured() {
        let fit =
            LeakageDecayFit {
                amplitude: 0.2,
                transient_amplitude: 0.8,
                decay_parameter: 1.0,
                total_transfer_rate: 0.0,
                weighted_residual_sum_of_squares: 0.0,
                rmse: 0.0,
                r_squared: Some(1.0),
                boundary_solution: true,
                converged: true,
                refinement_iterations: 0,
            };

        let config =
            LeakageRbConfig::production();

        let observations = vec![
            LeakageRbLengthObservation {
                sequence_length: 1,
                sequence_count: 1,
                shots: 100,
                computational_count: 100,
                leakage_count: 0,
                unclassified_count: 0,
                computational_probability: 1.0,
                leakage_probability: 0.0,
                unclassified_probability: 0.0,
            },
        ];

        let warnings =
            build_warnings(
                &config,
                &observations,
                &fit,
                0.0,
                0.0,
            );

        assert!(
            warnings.contains(
                &LeakageRbWarning::
                    BoundarySolution
            )
        );

        assert!(
            warnings.contains(
                &LeakageRbWarning::
                    LeakageRateNearZero
            )
        );
    }
}