//! Zamani Quantum Frontend — OpenQASM exporter.
//!
//! Production OpenQASM 3 exporter from the canonical Zamani Quantum IR.
//!
//! # Architectural boundary
//!
//! ```text
//!                         QuantumCircuit
//!                              │
//!                              ▼
//!                    generic frontend exporter
//!                              │
//!                              ▼
//!                    OpenQASM exporter
//!                              │
//!               ┌──────────────┴──────────────┐
//!               ▼                             ▼
//!        capability check               serialization
//!               │                             │
//!               └──────────────┬──────────────┘
//!                              ▼
//!                     valid OpenQASM 3.x
//! ```
//!
//! This module is deliberately OpenQASM-specific.
//!
//! It MUST NOT:
//!
//! - define an alternative Quantum IR;
//! - mutate `QuantumCircuit`;
//! - perform optimization;
//! - perform routing;
//! - perform scheduling;
//! - perform hardware mapping;
//! - execute a circuit;
//! - access the filesystem;
//! - access the network;
//! - print to stdout/stderr;
//! - silently discard operations;
//! - silently approximate unsupported operations;
//! - invent measurements;
//! - invent qubit operands;
//! - assume `q[i] -> c[i]` measurement mapping;
//! - depend on another frontend format.
//!
//! # Export policy
//!
//! The exporter emits OpenQASM 3.1 by default.
//!
//! The currently supported direct IR subset is:
//!
//! - `I`
//! - `X`
//! - `Y`
//! - `Z`
//! - `H`
//! - `S`
//! - `Sdg`
//! - `T`
//! - `Tdg`
//! - `RX`
//! - `RY`
//! - `RZ`
//! - `Phase`
//! - `U1`
//! - `U2`
//! - `U3`
//! - `CX`
//! - `CY`
//! - `CZ`
//! - `CH`
//! - `CRX`
//! - `CRY`
//! - `CRZ`
//! - `SWAP`
//! - `CCX`
//! - `CSWAP`
//! - `Measure` in the Z basis with a non-destructive measurement mode
//! - `Reset`
//! - `Barrier`
//!
//! The following IR operations are deliberately rejected because OpenQASM
//! `stdgates.inc` does not provide a semantically identical direct operation
//! for the current IR representation:
//!
//! - `V`
//! - `Vdg`
//! - `ISWAP`
//! - `ECR`
//!
//! The exporter also rejects:
//!
//! - X/Y-basis measurements;
//! - destructive measurements;
//! - unsupported measurement metadata;
//! - invalid OpenQASM parameter identifiers;
//! - invalid IR;
//! - unsupported gate parameter arity;
//! - unsupported future IR operations.
//!
//! This is intentional. A production exporter must fail explicitly rather
//! than produce an apparently valid but semantically different program.
//!
//! # Measurement semantics
//!
//! OpenQASM 3 measurement is Z-basis measurement and leaves the qubit
//! available for subsequent computation. Therefore only the IR's
//! non-destructive Z-basis measurement maps directly.
//!
//! If `reset_after` is explicitly requested in the IR, the exporter emits:
//!
//! ```text
//! measure q[i] -> c[j];
//! reset q[i];
//! ```
//!
//! No measurement is ever inserted merely because a qubit exists.
//!
//! # Versioning
//!
//! The exporter supports OpenQASM 3.x versions represented by the generic
//! frontend `FormatVersion` contract. The production constructor selects
//! OpenQASM 3.1.
//!
//! # Rust compatibility
//!
//! Rust 1.97.1 / Rust 2021.
//!
//! No nightly features are required.
//! No additional dependencies are required.

use std::fmt::Write as _;

use crate::quantum::frontend::core::errors::{
    FrontendError,
    FrontendErrorCode,
    FrontendErrorKind,
    FrontendResult,
};
use crate::quantum::frontend::exporter::{
    ExportedArtifact,
    ExportOptions,
    QuantumExporter,
};
use crate::quantum::frontend::format::{
    FormatCapabilities,
    FormatCapability,
    FormatId,
    FormatVersion,
    FrontendFormat,
};
use crate::quantum::ir::{
    Gate,
    GateKind,
    MeasurementBasis,
    MeasurementMode,
    Parameter,
    ParameterExpression,
    QuantumCircuit,
};

/// Canonical OpenQASM format identifier.
pub const OPENQASM_FORMAT_ID: &str = "openqasm";

/// OpenQASM 3.0 version.
pub const OPENQASM_3_0: FormatVersion =
    FormatVersion::new(3, 0, 0);

/// OpenQASM 3.1 version.
pub const OPENQASM_3_1: FormatVersion =
    FormatVersion::new(3, 1, 0);

/// OpenQASM standard-library include.
pub const STANDARD_LIBRARY_INCLUDE: &str =
    "stdgates.inc";

/// OpenQASM textual media type.
pub const OPENQASM_MEDIA_TYPE: &str =
    "text/x-openqasm";

/// Maximum number of characters emitted by one identifier.
const MAX_IDENTIFIER_BYTES: usize = 256;

/// Maximum output line length generated by one operation.
///
/// This is an exporter-local defensive invariant. The global artifact limit
/// remains controlled by `ExportOptions`.
const MAX_OPERATION_LINE_BYTES: usize = 64 * 1024;

/// Stable exporter error codes.
const CODE_FORMAT: &str = "QASM-E001";
const CODE_VERSION: &str = "QASM-E002";
const CODE_GATE: &str = "QASM-E003";
const CODE_PARAMETER: &str = "QASM-E004";
const CODE_MEASUREMENT: &str = "QASM-E005";
const CODE_IDENTIFIER: &str = "QASM-E006";
const CODE_EMPTY_CIRCUIT: &str = "QASM-E007";
const CODE_ARTIFACT: &str = "QASM-E008";

/// Production OpenQASM exporter.
///
/// The exporter is immutable and contains no mutable compilation state.
/// Multiple exporter instances may therefore safely be used concurrently.
#[derive(Clone, Debug)]
pub struct OpenQasmExporter {
    format: FrontendFormat,
}

impl OpenQasmExporter {
    /// Creates the production OpenQASM 3.1 exporter.
    ///
    /// The constructor cannot fail because all format metadata is composed
    /// from compile-time-valid constants and the standard frontend capability
    /// vocabulary.
    pub fn production() -> FrontendResult<Self> {
        Self::new(OPENQASM_3_1)
    }

    /// Creates an OpenQASM exporter for a specific OpenQASM 3.x version.
    ///
    /// Only major version 3 is accepted. This prevents accidentally creating
    /// an OpenQASM 2 exporter under an OpenQASM 3 implementation.
    pub fn new(version: FormatVersion) -> FrontendResult<Self> {
        if version.major() != 3 {
            return Err(export_error(
                FrontendErrorKind::Unsupported,
                CODE_VERSION,
                format!(
                    "OpenQASM exporter supports major version 3.x, \
                     not {}",
                    version
                ),
            ));
        }

        let id = FormatId::new(OPENQASM_FORMAT_ID)
            .map_err(|error| {
                FrontendError::internal(format!(
                    "failed to construct built-in OpenQASM \
                     format identifier: {error}"
                ))
            })?;

        let capabilities = openqasm_capabilities()?;

        Ok(Self {
            format: FrontendFormat::new(
                id,
                version,
                capabilities,
            ),
        })
    }

    /// Returns the configured OpenQASM version.
    #[must_use]
    pub const fn configured_version(&self) -> FormatVersion {
        self.format.version()
    }

    /// Returns the immutable format descriptor.
    #[must_use]
    pub fn descriptor(&self) -> &FrontendFormat {
        &self.format
    }

    /// Exports a circuit using the production default options.
    pub fn export_circuit(
        &self,
        circuit: &QuantumCircuit,
    ) -> FrontendResult<ExportedArtifact> {
        self.export(circuit, &ExportOptions::default())
    }

    /// Builds the OpenQASM program.
    ///
    /// This function assumes the generic exporter validation boundary has
    /// already validated the circuit.
    fn serialize(
        &self,
        circuit: &QuantumCircuit,
    ) -> FrontendResult<String> {
        if circuit.num_qubits() == 0 {
            return Err(export_error(
                FrontendErrorKind::Export,
                CODE_EMPTY_CIRCUIT,
                "OpenQASM requires at least one logical \
                 qubit for the currently supported Zamani \
                 Quantum IR subset",
            ));
        }

        let mut output = String::new();

        write_line(
            &mut output,
            &format!(
                "OPENQASM {}.{};",
                self.format.version().major(),
                self.format.version().minor()
            ),
        )?;

        write_line(
            &mut output,
            &format!(
                "include \"{}\";",
                STANDARD_LIBRARY_INCLUDE
            ),
        )?;

        write_line(
            &mut output,
            &format!(
                "qubit[{}] q;",
                circuit.num_qubits()
            ),
        )?;

        if circuit.num_classical_bits() > 0 {
            write_line(
                &mut output,
                &format!(
                    "bit[{}] c;",
                    circuit.num_classical_bits()
                ),
            )?;
        }

        for gate in circuit.operations() {
            self.validate_gate_for_export(
                gate,
                circuit,
            )?;

            self.write_gate(
                &mut output,
                gate,
            )?;
        }

        Ok(output)
    }

    /// Performs OpenQASM-specific representability validation.
    fn validate_gate_for_export(
        &self,
        gate: &Gate,
        circuit: &QuantumCircuit,
    ) -> FrontendResult<()> {
        let kind = gate.kind();

        /*
         * The canonical IR has already validated operand and parameter
         * cardinality. We still verify them here because this function is
         * the concrete format boundary and must never rely on assumptions
         * about future IR construction paths.
         */
        if !kind
            .operand_count()
            .accepts(gate.qubits().len())
        {
            return Err(export_error(
                FrontendErrorKind::Export,
                CODE_GATE,
                format!(
                    "gate {:?} has {} operands but \
                     OpenQASM export requires {}",
                    kind,
                    gate.qubits().len(),
                    kind.operand_count(),
                ),
            ));
        }

        if gate.parameters().len()
            != kind.parameter_count()
        {
            return Err(export_error(
                FrontendErrorKind::Export,
                CODE_PARAMETER,
                format!(
                    "gate {:?} has {} parameters but \
                     its canonical IR definition requires {}",
                    kind,
                    gate.parameters().len(),
                    kind.parameter_count(),
                ),
            ));
        }

        for parameter in gate.parameters() {
            validate_parameter(parameter)?;
        }

        for qubit in gate.qubits() {
            if qubit.index() >= circuit.num_qubits() {
                return Err(export_error(
                    FrontendErrorKind::Export,
                    CODE_GATE,
                    format!(
                        "gate {:?} references logical qubit \
                         {} outside circuit range 0..{}",
                        kind,
                        qubit.index(),
                        circuit.num_qubits(),
                    ),
                ));
            }
        }

        match kind {
            GateKind::Measure => {
                self.validate_measurement(
                    gate,
                    circuit,
                )?;
            }

            GateKind::V
            | GateKind::Vdg
            | GateKind::ISWAP
            | GateKind::ECR => {
                return Err(export_error(
                    FrontendErrorKind::Unsupported,
                    CODE_GATE,
                    format!(
                        "canonical gate {:?} has no direct \
                         semantically equivalent OpenQASM \
                         stdgates.inc operation",
                        kind
                    ),
                ));
            }

            GateKind::I
            | GateKind::X
            | GateKind::Y
            | GateKind::Z
            | GateKind::H
            | GateKind::S
            | GateKind::Sdg
            | GateKind::T
            | GateKind::Tdg
            | GateKind::RX
            | GateKind::RY
            | GateKind::RZ
            | GateKind::Phase
            | GateKind::U1
            | GateKind::U2
            | GateKind::U3
            | GateKind::CX
            | GateKind::CY
            | GateKind::CZ
            | GateKind::CH
            | GateKind::CRX
            | GateKind::CRY
            | GateKind::CRZ
            | GateKind::SWAP
            | GateKind::CCX
            | GateKind::CSWAP
            | GateKind::Barrier
            | GateKind::Reset => {}
        }

        Ok(())
    }

    /// Validates the additional semantics carried by an IR measurement.
    fn validate_measurement(
        &self,
        gate: &Gate,
        circuit: &QuantumCircuit,
    ) -> FrontendResult<()> {
        let measurement =
            gate.measurement().ok_or_else(|| {
                export_error(
                    FrontendErrorKind::Export,
                    CODE_MEASUREMENT,
                    "measurement gate is missing its \
                     canonical Measurement payload",
                )
            })?;

        if measurement.basis()
            != MeasurementBasis::Z
        {
            return Err(export_error(
                FrontendErrorKind::Unsupported,
                CODE_MEASUREMENT,
                format!(
                    "OpenQASM direct measurement export \
                     supports only the Z basis; IR measurement \
                     uses {} basis",
                    measurement.basis()
                ),
            ));
        }

        if measurement.mode()
            != MeasurementMode::NonDestructive
        {
            return Err(export_error(
                FrontendErrorKind::Unsupported,
                CODE_MEASUREMENT,
                "destructive IR measurements cannot be \
                 represented directly by OpenQASM 3 \
                 measurement semantics",
            ));
        }

        let qubit =
            measurement.qubit().index();

        if qubit >= circuit.num_qubits() {
            return Err(export_error(
                FrontendErrorKind::Export,
                CODE_MEASUREMENT,
                format!(
                    "measurement references qubit {} \
                     outside circuit range 0..{}",
                    qubit,
                    circuit.num_qubits(),
                ),
            ));
        }

        let classical =
            measurement.classical_bit().index();

        if classical
            >= circuit.num_classical_bits()
        {
            return Err(export_error(
                FrontendErrorKind::Export,
                CODE_MEASUREMENT,
                format!(
                    "measurement targets classical bit {} \
                     outside circuit range 0..{}",
                    classical,
                    circuit.num_classical_bits(),
                ),
            ));
        }

        match gate.classical_target() {
            Some(target) if target == classical => {}

            Some(target) => {
                return Err(export_error(
                    FrontendErrorKind::Export,
                    CODE_MEASUREMENT,
                    format!(
                        "measurement has inconsistent classical \
                         destinations: gate target {} differs \
                         from measurement target {}",
                        target,
                        classical,
                    ),
                ));
            }

            None => {
                return Err(export_error(
                    FrontendErrorKind::Export,
                    CODE_MEASUREMENT,
                    "measurement gate has no classical \
                     destination",
                ));
            }
        }

        Ok(())
    }

    /// Serializes one canonical gate.
    fn write_gate(
        &self,
        output: &mut String,
        gate: &Gate,
    ) -> FrontendResult<()> {
        match gate.kind() {
            GateKind::Measure => {
                let measurement =
                    gate.measurement().ok_or_else(|| {
                        export_error(
                            FrontendErrorKind::Export,
                            CODE_MEASUREMENT,
                            "measurement payload disappeared \
                             after validation",
                        )
                    })?;

                let q =
                    measurement.qubit().index();

                let c =
                    measurement.classical_bit().index();

                write_line(
                    output,
                    &format!(
                        "measure q[{}] -> c[{}];",
                        q,
                        c
                    ),
                )?;

                if measurement.reset_after() {
                    write_line(
                        output,
                        &format!("reset q[{}];", q),
                    )?;
                }

                Ok(())
            }

            GateKind::Reset => {
                let q = gate
                    .qubits()
                    .first()
                    .ok_or_else(|| {
                        export_error(
                            FrontendErrorKind::Export,
                            CODE_GATE,
                            "reset operation has no qubit \
                             operand",
                        )
                    })?
                    .index();

                write_line(
                    output,
                    &format!("reset q[{}];", q),
                )
            }

            GateKind::Barrier => {
                let operands =
                    format_qubit_operands(gate)?;

                write_line(
                    output,
                    &format!(
                        "barrier {};",
                        operands
                    ),
                )
            }

            kind => {
                let name =
                    gate_name(kind).ok_or_else(|| {
                        export_error(
                            FrontendErrorKind::Unsupported,
                            CODE_GATE,
                            format!(
                                "gate {:?} cannot be emitted \
                                 as OpenQASM 3",
                                kind
                            ),
                        )
                    })?;

                let operands =
                    format_qubit_operands(gate)?;

                let parameters =
                    format_parameters(
                        gate.parameters(),
                    )?;

                let statement =
                    if parameters.is_empty() {
                        format!(
                            "{} {};",
                            name,
                            operands
                        )
                    } else {
                        format!(
                            "{}({}) {};",
                            name,
                            parameters,
                            operands
                        )
                    };

                write_line(
                    output,
                    &statement,
                )
            }
        }
    }
}

impl QuantumExporter for OpenQasmExporter {
    fn format(&self) -> &FrontendFormat {
        &self.format
    }

    fn export_impl(
        &self,
        circuit: &QuantumCircuit,
        _options: &ExportOptions,
    ) -> FrontendResult<ExportedArtifact> {
        let source =
            self.serialize(circuit)?;

        ExportedArtifact::text(
            self.format.clone(),
            OPENQASM_MEDIA_TYPE,
            source,
        )
        .map_err(|error| {
            export_error(
                FrontendErrorKind::Export,
                CODE_ARTIFACT,
                error.to_string(),
            )
        })
    }
}

/// Constructs the OpenQASM capability declaration.
///
/// This is deliberately local to the OpenQASM implementation. Adding another
/// frontend format never requires modifying this capability list.
fn openqasm_capabilities()
    -> FrontendResult<FormatCapabilities>
{
    let mut capabilities =
        FormatCapabilities::new();

    let supported = [
        FormatCapability::Export,
        FormatCapability::Parameters,
        FormatCapability::Measurements,
        FormatCapability::Reset,
        FormatCapability::Barriers,
        FormatCapability::Includes,
        FormatCapability::SymbolicNames,
        FormatCapability::RegisterDeclarations,
        FormatCapability::Expressions,
    ];

    for capability in supported {
        capabilities
            .insert(capability)
            .map_err(|error| {
                FrontendError::internal(format!(
                    "failed to construct OpenQASM \
                     capability set: {error}"
                ))
            })?;
    }

    Ok(capabilities)
}

/// Maps a canonical IR gate to its OpenQASM standard-library spelling.
///
/// Only operations with a direct semantic equivalent are included.
fn gate_name(kind: GateKind) -> Option<&'static str> {
    match kind {
        GateKind::I => Some("id"),
        GateKind::X => Some("x"),
        GateKind::Y => Some("y"),
        GateKind::Z => Some("z"),
        GateKind::H => Some("h"),
        GateKind::S => Some("s"),
        GateKind::Sdg => Some("sdg"),
        GateKind::T => Some("t"),
        GateKind::Tdg => Some("tdg"),

        GateKind::RX => Some("rx"),
        GateKind::RY => Some("ry"),
        GateKind::RZ => Some("rz"),
        GateKind::Phase => Some("p"),

        GateKind::U1 => Some("u1"),
        GateKind::U2 => Some("u2"),
        GateKind::U3 => Some("u3"),

        GateKind::CX => Some("cx"),
        GateKind::CY => Some("cy"),
        GateKind::CZ => Some("cz"),
        GateKind::CH => Some("ch"),

        GateKind::CRX => Some("crx"),
        GateKind::CRY => Some("cry"),
        GateKind::CRZ => Some("crz"),

        GateKind::SWAP => Some("swap"),

        GateKind::CCX => Some("ccx"),
        GateKind::CSWAP => Some("cswap"),

        GateKind::V
        | GateKind::Vdg
        | GateKind::ISWAP
        | GateKind::ECR
        | GateKind::Measure
        | GateKind::Barrier
        | GateKind::Reset => None,
    }
}

/// Formats logical qubit operands without changing their order.
fn format_qubit_operands(
    gate: &Gate,
) -> FrontendResult<String> {
    if gate.qubits().is_empty() {
        return Err(export_error(
            FrontendErrorKind::Export,
            CODE_GATE,
            format!(
                "gate {:?} requires at least one qubit operand",
                gate.kind()
            ),
        ));
    }

    let mut result =
        String::with_capacity(
            gate.qubits().len() * 8,
        );

    for (index, qubit) in
        gate.qubits().iter().enumerate()
    {
        if index != 0 {
            result.push_str(", ");
        }

        write!(
            &mut result,
            "q[{}]",
            qubit.index()
        )
        .map_err(|_| {
            FrontendError::internal(
                "failed to format OpenQASM qubit operand",
            )
        })?;
    }

    Ok(result)
}

/// Formats all gate parameters in canonical IR order.
fn format_parameters(
    parameters: &[Parameter],
) -> FrontendResult<String> {
    let mut result =
        String::new();

    for (index, parameter) in
        parameters.iter().enumerate()
    {
        if index != 0 {
            result.push_str(", ");
        }

        validate_parameter(parameter)?;

        write!(
            &mut result,
            "{}",
            parameter
        )
        .map_err(|_| {
            FrontendError::internal(
                "failed to format OpenQASM parameter",
            )
        })?;
    }

    Ok(result)
}

/// Validates that an IR parameter can be represented without changing its
/// meaning in OpenQASM.
fn validate_parameter(
    parameter: &Parameter,
) -> FrontendResult<()> {
    match parameter {
        Parameter::Constant(value) => {
            if !value.is_finite() {
                return Err(export_error(
                    FrontendErrorKind::Export,
                    CODE_PARAMETER,
                    "OpenQASM cannot represent a \
                     non-finite floating-point parameter",
                ));
            }
        }

        Parameter::Symbol(name) => {
            validate_identifier(name)?;
        }

        Parameter::Expression(expression) => {
            validate_expression(expression)?;
        }
    }

    Ok(())
}

/// Recursively validates a canonical IR parameter expression.
fn validate_expression(
    expression: &ParameterExpression,
) -> FrontendResult<()> {
    match expression {
        ParameterExpression::Add(
            left,
            right,
        )
        | ParameterExpression::Subtract(
            left,
            right,
        )
        | ParameterExpression::Multiply(
            left,
            right,
        )
        | ParameterExpression::Divide(
            left,
            right,
        ) => {
            validate_parameter(left)?;
            validate_parameter(right)?;
        }

        ParameterExpression::Negate(value) => {
            validate_parameter(value)?;
        }
    }

    Ok(())
}

/// Validates an IR symbolic identifier against the OpenQASM identifier rules
/// relevant to the canonical IR's ASCII-only symbol representation.
///
/// The canonical IR currently permits only ASCII letters, digits, and `_` in
/// parameter symbols, so this validation is deliberately stricter than the
/// complete Unicode OpenQASM identifier grammar.
fn validate_identifier(
    identifier: &str,
) -> FrontendResult<()> {
    if identifier.is_empty() {
        return Err(export_error(
            FrontendErrorKind::Export,
            CODE_IDENTIFIER,
            "OpenQASM identifier must not be empty",
        ));
    }

    if identifier.len()
        > MAX_IDENTIFIER_BYTES
    {
        return Err(export_error(
            FrontendErrorKind::Export,
            CODE_IDENTIFIER,
            format!(
                "OpenQASM identifier exceeds {} bytes",
                MAX_IDENTIFIER_BYTES
            ),
        ));
    }

    let mut chars =
        identifier.chars();

    let first =
        chars.next().ok_or_else(|| {
            export_error(
                FrontendErrorKind::Export,
                CODE_IDENTIFIER,
                "OpenQASM identifier must not be empty",
            )
        })?;

    if !(first == '_'
        || first.is_ascii_alphabetic())
    {
        return Err(export_error(
            FrontendErrorKind::Unsupported,
            CODE_IDENTIFIER,
            format!(
                "IR parameter identifier `{}` \
                 cannot be emitted as an OpenQASM \
                 identifier",
                identifier
            ),
        ));
    }

    if !chars.all(|character| {
        character == '_'
            || character.is_ascii_alphanumeric()
    }) {
        return Err(export_error(
            FrontendErrorKind::Unsupported,
            CODE_IDENTIFIER,
            format!(
                "IR parameter identifier `{}` contains \
                 characters outside the OpenQASM \
                 exporter-supported identifier subset",
                identifier
            ),
        ));
    }

    if is_reserved_openqasm_identifier(
        identifier,
    ) {
        return Err(export_error(
            FrontendErrorKind::Unsupported,
            CODE_IDENTIFIER,
            format!(
                "IR parameter identifier `{}` conflicts \
                 with an OpenQASM reserved/builtin identifier",
                identifier
            ),
        ));
    }

    Ok(())
}

/// OpenQASM reserved keywords and builtin identifiers which cannot safely be
/// emitted as symbolic parameter names.
///
/// This list is intentionally conservative. Rejecting a colliding symbol is
/// safer than emitting a syntactically valid program with changed semantics.
fn is_reserved_openqasm_identifier(
    identifier: &str,
) -> bool {
    matches!(
        identifier,
        "OPENQASM"
            | "include"
            | "defcalgrammar"
            | "def"
            | "cal"
            | "defcal"
            | "gate"
            | "extern"
            | "box"
            | "let"
            | "break"
            | "continue"
            | "if"
            | "else"
            | "end"
            | "return"
            | "for"
            | "while"
            | "in"
            | "switch"
            | "case"
            | "default"
            | "input"
            | "output"
            | "const"
            | "readonly"
            | "mutable"
            | "qreg"
            | "qubit"
            | "creg"
            | "bit"
            | "int"
            | "uint"
            | "float"
            | "angle"
            | "complex"
            | "array"
            | "void"
            | "duration"
            | "stretch"
            | "gphase"
            | "inv"
            | "pow"
            | "ctrl"
            | "negctrl"
            | "measure"
            | "reset"
            | "barrier"
            | "delay"
            | "pragma"
            | "pi"
            | "tau"
            | "euler"
            | "x"
            | "y"
            | "z"
            | "h"
            | "s"
            | "sdg"
            | "t"
            | "tdg"
            | "rx"
            | "ry"
            | "rz"
            | "p"
            | "phase"
            | "cx"
            | "cy"
            | "cz"
            | "ch"
            | "crx"
            | "cry"
            | "crz"
            | "swap"
            | "ccx"
            | "cswap"
            | "id"
            | "u1"
            | "u2"
            | "u3"
            | "CX"
    )
}

/// Adds one bounded line to the generated program.
fn write_line(
    output: &mut String,
    line: &str,
) -> FrontendResult<()> {
    if line.len()
        > MAX_OPERATION_LINE_BYTES
    {
        return Err(export_error(
            FrontendErrorKind::LimitExceeded,
            CODE_ARTIFACT,
            format!(
                "generated OpenQASM line exceeds \
                 {} bytes",
                MAX_OPERATION_LINE_BYTES
            ),
        ));
    }

    output.push_str(line);
    output.push('\n');

    Ok(())
}

/// Creates a frontend export error with a stable code.
fn export_error(
    kind: FrontendErrorKind,
    code: &'static str,
    message: impl Into<String>,
) -> FrontendError {
    FrontendError::with_code(
        kind,
        FrontendErrorCode::new(code),
        message.into(),
    )
    .context("format", OPENQASM_FORMAT_ID)
    .context("stage", "export")
}

#[cfg(test)]
mod tests {
    use super::*;

    use crate::quantum::ir::{
        Gate,
        GateKind,
        Measurement,
        Parameter,
        QubitId,
    };

    fn exporter() -> OpenQasmExporter {
        OpenQasmExporter::production()
            .expect("production OpenQASM exporter must construct")
    }

    #[test]
    fn production_exporter_targets_openqasm_3_1() {
        let exporter = exporter();

        assert_eq!(
            exporter.configured_version(),
            OPENQASM_3_1
        );

        assert_eq!(
            exporter.format().id().as_str(),
            OPENQASM_FORMAT_ID
        );
    }

    #[test]
    fn capability_set_advertises_only_supported_features() {
        let exporter = exporter();
        let capabilities =
            exporter.format().capabilities();

        assert!(
            capabilities
                .supports(FormatCapability::Export)
        );

        assert!(
            capabilities
                .supports(FormatCapability::Parameters)
        );

        assert!(
            capabilities
                .supports(FormatCapability::Measurements)
        );

        assert!(
            capabilities
                .supports(FormatCapability::Reset)
        );

        assert!(
            capabilities
                .supports(FormatCapability::Barriers)
        );

        assert!(
            !capabilities
                .supports(
                    FormatCapability::ClassicalControl
                )
        );

        assert!(
            !capabilities
                .supports(
                    FormatCapability::Calibration
                )
        );
    }

    #[test]
    fn gate_names_are_canonical_openqasm_spellings() {
        assert_eq!(
            gate_name(GateKind::I),
            Some("id")
        );

        assert_eq!(
            gate_name(GateKind::Phase),
            Some("p")
        );

        assert_eq!(
            gate_name(GateKind::CX),
            Some("cx")
        );

        assert_eq!(
            gate_name(GateKind::CCX),
            Some("ccx")
        );

        assert_eq!(
            gate_name(GateKind::V),
            None
        );
    }

    #[test]
    fn identifiers_reject_openqasm_builtins() {
        assert!(
            validate_identifier("theta")
                .is_ok()
        );

        assert!(
            validate_identifier("theta_1")
                .is_ok()
        );

        assert!(
            validate_identifier("pi")
                .is_err()
        );

        assert!(
            validate_identifier("measure")
                .is_err()
        );
    }

    #[test]
    fn identifiers_reject_invalid_first_character() {
        assert!(
            validate_identifier("1theta")
                .is_err()
        );

        assert!(
            validate_identifier("_theta")
                .is_ok()
        );
    }

    #[test]
    fn identifiers_reject_invalid_characters() {
        assert!(
            validate_identifier("theta-value")
                .is_err()
        );

        assert!(
            validate_identifier("theta.value")
                .is_err()
        );
    }

    #[test]
    fn finite_parameter_is_accepted() {
        assert!(
            validate_parameter(
                &Parameter::Constant(
                    1.25
                )
            )
            .is_ok()
        );
    }

    #[test]
    fn non_finite_parameter_is_rejected() {
        assert!(
            validate_parameter(
                &Parameter::Constant(
                    f64::NAN
                )
            )
            .is_err()
        );

        assert!(
            validate_parameter(
                &Parameter::Constant(
                    f64::INFINITY
                )
            )
            .is_err()
        );
    }

    #[test]
    fn qubit_operands_preserve_order() {
        let gate = Gate::new(
            GateKind::CX,
            vec![
                QubitId::new(7),
                QubitId::new(2),
            ],
            Vec::new(),
            None,
            None,
        )
        .expect(
            "valid CX gate should construct",
        );

        assert_eq!(
            format_qubit_operands(&gate)
                .expect(
                    "valid operands should format"
                ),
            "q[7], q[2]"
        );
    }

    #[test]
    fn measurement_does_not_invent_identity_mapping() {
        let measurement =
            Measurement::new(
                QubitId::new(3),
                9usize.into(),
            );

        assert_eq!(
            measurement.qubit().index(),
            3
        );

        assert_eq!(
            measurement
                .classical_bit()
                .index(),
            9
        );
    }

    #[test]
    fn standard_library_include_is_stable() {
        assert_eq!(
            STANDARD_LIBRARY_INCLUDE,
            "stdgates.inc"
        );
    }

    #[test]
    fn media_type_is_stable() {
        assert_eq!(
            OPENQASM_MEDIA_TYPE,
            "text/x-openqasm"
        );
    }

    #[test]
    fn version_three_is_required() {
        assert!(
            OpenQasmExporter::new(
                FormatVersion::new(
                    2,
                    0,
                    0
                )
            )
            .is_err()
        );
    }

    #[test]
    fn supported_measurement_mode_is_z_non_destructive() {
        assert_eq!(
            MeasurementMode::NonDestructive
                .is_non_destructive(),
            true
        );

        assert_eq!(
            MeasurementMode::Destructive
                .is_destructive(),
            true
        );
    }
}