//! Zamani Quantum Hardware — QIR Adapter
//!
//! Production QIR lowering boundary for the canonical Zamani Quantum IR.
//!
//! # Responsibility
//!
//! This module converts a validated [`QuantumCircuit`] into deterministic,
//! textual QIR based on LLVM IR and the QIR v2 Base Profile.
//!
//! The dependency direction is:
//!
//! ```text
//! Zamani source
//!      |
//!      v
//! Quantum Frontend
//!      |
//!      v
//! Zamani Quantum IR
//!      |
//!      v
//! compiler / routing / scheduling
//!      |
//!      v
//! hardware compatibility
//!      |
//!      v
//! adapters/qir.rs
//!      |
//!      v
//! QIR v2 + selected QIS
//!      |
//!      +-----------------------------+
//!      |                             |
//!      v                             v
//! QIR-compatible compiler       QIR-compatible backend
//! ```
//!
//! # What this module owns
//!
//! - QIR version selection;
//! - QIR profile selection;
//! - deterministic LLVM/QIR text generation;
//! - Zamani IR -> QIR gate mapping;
//! - Zamani logical qubit -> QIR opaque pointer mapping;
//! - Zamani measurement -> QIR result mapping;
//! - QIR entry-point attributes;
//! - QIR module flags;
//! - QIR runtime/QIS declarations;
//! - bounded output generation;
//! - representability validation;
//! - QIR-specific diagnostics.
//!
//! # What this module does NOT own
//!
//! - Zamani Quantum IR semantics;
//! - optimization;
//! - routing;
//! - scheduling;
//! - topology;
//! - calibration;
//! - provider authentication;
//! - provider APIs;
//! - job submission;
//! - result retrieval;
//! - simulation;
//! - hardware execution;
//! - provider-specific gate decomposition.
//!
//! Those responsibilities belong to the corresponding quantum/compiler/
//! hardware modules.
//!
//! # QIR interoperability model
//!
//! QIR is an interoperability target, not Zamani's canonical IR.
//!
//! ```text
//! Zamani Quantum IR
//!        |
//!        v
//!   qir.rs
//!        |
//!        v
//! QIR v2 / LLVM IR
//!        |
//!        +------------------+
//!        |                  |
//!        v                  v
//! target-specific       QIR-compatible
//! lowering              tooling
//! ```
//!
//! The canonical Zamani IR remains authoritative.
//!
//! QIR is not used as the internal representation of Zamani.
//!
//! # QIR version
//!
//! This implementation targets QIR v2.0 semantics using LLVM opaque pointers.
//! QIR v2 uses `ptr` rather than typed `%Qubit*` / `%Result*` pointers.
//!
//! QIR v1 output is intentionally not generated by this adapter. A future
//! compatibility adapter can implement QIR v1 separately without weakening
//! the v2 contract.
//!
//! # Profile
//!
//! This implementation generates the QIR Base Profile.
//!
//! Base Profile constraints are intentionally enforced:
//!
//! - straight-line quantum execution;
//! - no dynamic classical branching;
//! - measurements occur in the terminal measurement region;
//! - measurement results are recorded after measurement;
//! - QIS functions return `void`;
//! - measurement QIS functions are marked `irreversible`;
//! - result arguments are `writeonly`;
//! - static qubit/result identities are used;
//! - dynamic resource management is disabled.
//!
//! Unsupported Zamani operations are rejected rather than approximated.
//!
//! # QIS policy
//!
//! QIR itself does not mandate one universal gate set. A QIR program selects
//! a quantum instruction set supported by its target.
//!
//! Consequently this adapter maintains an explicit, auditable mapping from
//! Zamani `GateKind` to QIR QIS functions.
//!
//! The following operations are emitted directly:
//!
//! - `X`
//! - `Y`
//! - `Z`
//! - `H`
//! - `S`
//! - `Sdg`
//! - `T`
//! - `Tdg`
//! - `RX`
//! - `RY`
//! - `RZ`
//! - `CX`
//! - `CY`
//! - `CZ`
//! - `SWAP`
//! - `CCX`
//! - `Measure`
//!
//! The following canonical Zamani operations are intentionally rejected by
//! this Base Profile adapter because no universal direct QIR QIS mapping is
//! assumed here:
//!
//! - `I`
//! - `V`
//! - `Vdg`
//! - `Phase`
//! - `U1`
//! - `U2`
//! - `U3`
//! - `CH`
//! - `ISWAP`
//! - `ECR`
//! - `CRX`
//! - `CRY`
//! - `CRZ`
//! - `CSWAP`
//! - `Barrier`
//! - `Reset`
//!
//! A compiler transformation may decompose those operations before invoking
//! this adapter. This adapter never silently performs such a transformation.
//!
//! # Parameter policy
//!
//! Base Profile QIR requires QIS call arguments to be representable as LLVM
//! constants or valid pointer values. Therefore this adapter accepts only
//! concrete finite `Parameter::Constant` values.
//!
//! Symbolic parameters are rejected.
//!
//! Parameter binding belongs upstream in the compiler pipeline.
//!
//! # Measurement policy
//!
//! QIR's Base Profile measurement model is terminal measurement.
//!
//! The adapter therefore requires:
//!
//! - Z-basis measurement;
//! - non-destructive logical measurement semantics;
//! - an explicit classical destination;
//! - no quantum operation after the first measurement;
//! - no second measurement into the same classical destination if doing so
//!   would make the resulting output contract ambiguous.
//!
//! Each measurement receives a unique QIR result identity.
//!
//! The QIR output label preserves the original Zamani classical-bit identity:
//!
//! ```text
//! Zamani c7
//!     |
//!     v
//! QIR result #N
//!     |
//!     v
//! label "c7"
//! ```
//!
//! # Security
//!
//! This module:
//!
//! - performs no network access;
//! - performs no filesystem access;
//! - performs no process execution;
//! - stores no credentials;
//! - embeds no secrets;
//! - does not accept arbitrary LLVM snippets;
//! - does not allow caller-controlled LLVM identifiers;
//! - bounds generated output;
//! - validates every emitted instruction;
//! - fails closed on unsupported semantics.
//!
//! # Determinism
//!
//! For the same validated circuit and options, the generated QIR is byte-for-
//! byte deterministic.
//!
//! Determinism covers:
//!
//! - declaration ordering;
//! - instruction ordering;
//! - result numbering;
//! - output labels;
//! - module flags;
//! - attributes;
//! - whitespace;
//! - floating-point formatting.
//!
//! # Rust compatibility
//!
//! Supported:
//!
//! - Rust 1.97;
//! - Rust 1.97.1;
//! - Rust 2021.
//!
//! No nightly features are required.
//! No external dependencies are required.
//!
//! # Integration contract
//!
//! This file depends only on the canonical Quantum IR:
//!
//! - `quantum::ir::QuantumCircuit`;
//! - `quantum::ir::Gate`;
//! - `quantum::ir::GateKind`;
//! - `quantum::ir::MeasurementBasis`;
//! - `quantum::ir::MeasurementMode`;
//! - `quantum::ir::Parameter`.
//!
//! It deliberately does not depend on:
//!
//! - `hardware::backend`;
//! - provider adapters;
//! - benchmarking;
//! - routing;
//! - scheduling;
//! - Danga;
//! - frontend parsers.
//!
//! Future `backend.rs` / `backend_trait.rs` integration should consume
//! [`QirArtifact`] as a target representation. The backend layer is responsible
//! for deciding whether the selected provider accepts QIR and for submitting
//! it. Provider-specific transport must never be added here.
//!
//! # Completion guarantee
//!
//! This file is complete independently when:
//!
//! 1. every supported mapping is explicitly documented;
//! 2. unsupported mappings fail deterministically;
//! 3. QIR output is bounded;
//! 4. QIR metadata is deterministic;
//! 5. the Base Profile structural rules are enforced;
//! 6. symbolic parameters cannot leak into invalid QIR;
//! 7. classical measurement identity is preserved;
//! 8. no credentials or provider state are accessed;
//! 9. unit tests cover valid and invalid mappings;
//! 10. later hardware/provider modules can consume the artifact without
//!     changing this module's core semantics.

#![deny(unsafe_code)]
#![deny(unsafe_op_in_unsafe_fn)]
#![deny(unused_must_use)]

use std::collections::BTreeSet;
use std::fmt::{self, Write as _};

use crate::quantum::ir::{
    Gate,
    GateKind,
    MeasurementBasis,
    MeasurementMode,
    Parameter,
    QuantumCircuit,
};

// =============================================================================
// Public constants
// =============================================================================

/// Stable adapter identifier.
pub const QIR_ADAPTER_ID: &str = "zamani.quantum.hardware.adapters.qir";

/// QIR major version emitted by this adapter.
pub const QIR_MAJOR_VERSION: u32 = 2;

/// QIR minor version emitted by this adapter.
pub const QIR_MINOR_VERSION: u32 = 0;

/// QIR textual artifact format identifier.
pub const QIR_FORMAT_ID: &str = "qir";

/// Stable QIR Base Profile identifier.
pub const QIR_BASE_PROFILE: &str = "base_profile";

/// Default QIR entry point.
pub const DEFAULT_ENTRY_POINT: &str = "__zamani_entry";

/// Default output-labeling schema.
///
/// This is a Zamani-defined output labeling contract. QIR defines the
/// mechanism for output recording, while concrete output schemas can be
/// interpreted by the consuming environment.
pub const DEFAULT_OUTPUT_LABELING_SCHEMA: &str = "zamani.classical_bits.v1";

/// Default maximum QIR artifact size.
pub const DEFAULT_MAX_OUTPUT_BYTES: usize = 16 * 1024 * 1024;

/// Maximum length of an externally supplied entry-point identifier.
pub const MAX_ENTRY_POINT_LENGTH: usize = 256;

/// Maximum length of an output schema identifier.
pub const MAX_OUTPUT_SCHEMA_LENGTH: usize = 256;

// =============================================================================
// QIR version
// =============================================================================

/// Supported QIR specification version.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct QirVersion {
    major: u32,
    minor: u32,
}

impl QirVersion {
    /// Creates a QIR version.
    ///
    /// Only QIR 2.0 is currently emitted by this adapter.
    pub const fn new(major: u32, minor: u32) -> Self {
        Self { major, minor }
    }

    /// Returns the QIR major version.
    pub const fn major(self) -> u32 {
        self.major
    }

    /// Returns the QIR minor version.
    pub const fn minor(self) -> u32 {
        self.minor
    }

    /// Returns the production version.
    pub const fn production() -> Self {
        Self::new(QIR_MAJOR_VERSION, QIR_MINOR_VERSION)
    }

    /// Returns whether this is the production version supported by this file.
    pub const fn is_supported(self) -> bool {
        self.major == QIR_MAJOR_VERSION && self.minor == QIR_MINOR_VERSION
    }
}

impl Default for QirVersion {
    fn default() -> Self {
        Self::production()
    }
}

impl fmt::Display for QirVersion {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(formatter, "{}.{}", self.major, self.minor)
    }
}

// =============================================================================
// QIR profile
// =============================================================================

/// QIR execution profile supported by the adapter.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum QirProfile {
    /// QIR Base Profile.
    Base,
}

impl QirProfile {
    /// Returns the QIR profile identifier.
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Base => QIR_BASE_PROFILE,
        }
    }
}

impl Default for QirProfile {
    fn default() -> Self {
        Self::Base
    }
}

// =============================================================================
// Options
// =============================================================================

/// Options controlling deterministic QIR generation.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct QirOptions {
    /// QIR version to emit.
    pub version: QirVersion,

    /// QIR profile.
    pub profile: QirProfile,

    /// LLVM/QIR entry-point identifier.
    pub entry_point: String,

    /// Output-labeling schema identifier.
    pub output_labeling_schema: String,

    /// Maximum generated artifact size in bytes.
    pub max_output_bytes: usize,

    /// Whether output-recording calls should be emitted.
    ///
    /// Production output should normally keep this enabled.
    pub emit_output_recording: bool,
}

impl Default for QirOptions {
    fn default() -> Self {
        Self {
            version: QirVersion::production(),
            profile: QirProfile::Base,
            entry_point: DEFAULT_ENTRY_POINT.to_owned(),
            output_labeling_schema:
                DEFAULT_OUTPUT_LABELING_SCHEMA.to_owned(),
            max_output_bytes: DEFAULT_MAX_OUTPUT_BYTES,
            emit_output_recording: true,
        }
    }
}

impl QirOptions {
    /// Returns the production configuration.
    pub fn production() -> Result<Self, QirError> {
        let options = Self::default();
        options.validate()?;
        Ok(options)
    }

    /// Validates all externally configurable options.
    pub fn validate(&self) -> Result<(), QirError> {
        if !self.version.is_supported() {
            return Err(QirError::UnsupportedVersion {
                requested: self.version,
            });
        }

        if self.max_output_bytes == 0 {
            return Err(QirError::InvalidConfiguration {
                field: "max_output_bytes",
                reason: "must be greater than zero",
            });
        }

        validate_llvm_identifier(
            &self.entry_point,
            MAX_ENTRY_POINT_LENGTH,
            "entry_point",
        )?;

        validate_ascii_identifier(
            &self.output_labeling_schema,
            MAX_OUTPUT_SCHEMA_LENGTH,
            "output_labeling_schema",
        )?;

        if self.profile != QirProfile::Base {
            return Err(QirError::UnsupportedProfile {
                profile: self.profile,
            });
        }

        Ok(())
    }
}

// =============================================================================
// Artifact
// =============================================================================

/// Deterministic QIR artifact produced by [`QirExporter`].
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct QirArtifact {
    /// Generated LLVM/QIR text.
    text: String,

    /// QIR version.
    version: QirVersion,

    /// QIR profile.
    profile: QirProfile,

    /// Entry-point name.
    entry_point: String,

    /// Number of logical qubits required by the circuit.
    required_num_qubits: usize,

    /// Number of QIR measurement-result objects required.
    required_num_results: usize,
}

impl QirArtifact {
    /// Creates a QIR artifact.
    fn new(
        text: String,
        version: QirVersion,
        profile: QirProfile,
        entry_point: String,
        required_num_qubits: usize,
        required_num_results: usize,
    ) -> Self {
        Self {
            text,
            version,
            profile,
            entry_point,
            required_num_qubits,
            required_num_results,
        }
    }

    /// Returns the complete QIR text.
    pub fn text(&self) -> &str {
        &self.text
    }

    /// Consumes the artifact and returns its text.
    pub fn into_text(self) -> String {
        self.text
    }

    /// Returns the QIR version.
    pub const fn version(&self) -> QirVersion {
        self.version
    }

    /// Returns the selected profile.
    pub const fn profile(&self) -> QirProfile {
        self.profile
    }

    /// Returns the entry point.
    pub fn entry_point(&self) -> &str {
        &self.entry_point
    }

    /// Returns the required qubit count.
    pub const fn required_num_qubits(&self) -> usize {
        self.required_num_qubits
    }

    /// Returns the required QIR result count.
    pub const fn required_num_results(&self) -> usize {
        self.required_num_results
    }
}

// =============================================================================
// Errors
// =============================================================================

/// Structured errors produced by the QIR adapter.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum QirError {
    /// QIR version is not supported by this adapter.
    UnsupportedVersion {
        requested: QirVersion,
    },

    /// QIR profile is not supported by this adapter.
    UnsupportedProfile {
        profile: QirProfile,
    },

    /// Adapter configuration is invalid.
    InvalidConfiguration {
        field: &'static str,
        reason: &'static str,
    },

    /// The circuit itself is not valid for QIR export.
    InvalidCircuit {
        reason: String,
    },

    /// A Zamani operation has no supported direct QIR mapping.
    UnsupportedGate {
        gate: GateKind,
    },

    /// A gate has an invalid parameter representation for QIR.
    UnsupportedParameter {
        gate: GateKind,
        index: usize,
        reason: &'static str,
    },

    /// A measurement cannot be represented by the Base Profile.
    UnsupportedMeasurement {
        reason: &'static str,
    },

    /// A gate appears after the terminal measurement region began.
    OperationAfterMeasurement {
        gate: GateKind,
    },

    /// The same classical destination is measured more than once.
    DuplicateClassicalDestination {
        bit: usize,
    },

    /// A logical qubit is outside the circuit namespace.
    InvalidQubit {
        qubit: usize,
        count: usize,
    },

    /// A classical bit is outside the circuit namespace.
    InvalidClassicalBit {
        bit: usize,
        count: usize,
    },

    /// Generated output exceeded the configured limit.
    OutputLimitExceeded {
        attempted: usize,
        maximum: usize,
    },

    /// An internal formatting operation failed.
    Formatting,

    /// An LLVM/QIR identifier is invalid.
    InvalidIdentifier {
        field: &'static str,
        reason: &'static str,
    },
}

impl fmt::Display for QirError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::UnsupportedVersion { requested } => {
                write!(
                    formatter,
                    "unsupported QIR version {requested}; this adapter emits QIR 2.0"
                )
            }

            Self::UnsupportedProfile { profile } => {
                write!(
                    formatter,
                    "unsupported QIR profile {}",
                    profile.as_str()
                )
            }

            Self::InvalidConfiguration { field, reason } => {
                write!(
                    formatter,
                    "invalid QIR configuration `{field}`: {reason}"
                )
            }

            Self::InvalidCircuit { reason } => {
                write!(formatter, "invalid circuit for QIR export: {reason}")
            }

            Self::UnsupportedGate { gate } => {
                write!(
                    formatter,
                    "gate {gate:?} has no supported direct QIR Base Profile mapping"
                )
            }

            Self::UnsupportedParameter {
                gate,
                index,
                reason,
            } => {
                write!(
                    formatter,
                    "parameter {index} of gate {gate:?} cannot be emitted to QIR: {reason}"
                )
            }

            Self::UnsupportedMeasurement { reason } => {
                write!(
                    formatter,
                    "measurement cannot be emitted to QIR Base Profile: {reason}"
                )
            }

            Self::OperationAfterMeasurement { gate } => {
                write!(
                    formatter,
                    "operation {gate:?} occurs after terminal measurement region began"
                )
            }

            Self::DuplicateClassicalDestination { bit } => {
                write!(
                    formatter,
                    "classical destination c{bit} is measured more than once"
                )
            }

            Self::InvalidQubit { qubit, count } => {
                write!(
                    formatter,
                    "logical qubit {qubit} is outside circuit namespace 0..{count}"
                )
            }

            Self::InvalidClassicalBit { bit, count } => {
                write!(
                    formatter,
                    "classical bit {bit} is outside circuit namespace 0..{count}"
                )
            }

            Self::OutputLimitExceeded {
                attempted,
                maximum,
            } => {
                write!(
                    formatter,
                    "QIR artifact exceeds output limit: attempted {attempted} bytes, maximum {maximum}"
                )
            }

            Self::Formatting => {
                formatter.write_str("failed to construct QIR text")
            }

            Self::InvalidIdentifier { field, reason } => {
                write!(
                    formatter,
                    "invalid QIR identifier `{field}`: {reason}"
                )
            }
        }
    }
}

impl std::error::Error for QirError {}

// =============================================================================
// Exporter
// =============================================================================

/// Production QIR exporter.
///
/// The exporter is immutable and contains only configuration. It is therefore
/// safe to share between threads when the surrounding compiler shares the
/// canonical immutable circuit safely.
#[derive(Debug, Clone)]
pub struct QirExporter {
    options: QirOptions,
}

impl QirExporter {
    /// Creates the production exporter.
    pub fn production() -> Result<Self, QirError> {
        Self::new(QirOptions::production()?)
    }

    /// Creates an exporter from explicit validated options.
    pub fn new(options: QirOptions) -> Result<Self, QirError> {
        options.validate()?;

        Ok(Self { options })
    }

    /// Returns the immutable exporter configuration.
    pub fn options(&self) -> &QirOptions {
        &self.options
    }

    /// Exports a canonical Zamani circuit to QIR.
    pub fn export(
        &self,
        circuit: &QuantumCircuit,
    ) -> Result<QirArtifact, QirError> {
        self.validate_circuit(circuit)?;

        let declarations = collect_declarations(circuit)?;

        let measurement_count = circuit
            .operations()
            .iter()
            .filter(|gate| gate.kind() == GateKind::Measure)
            .count();

        let mut output =
            BoundedOutput::new(self.options.max_output_bytes);

        self.write_module_header(
            &mut output,
            circuit,
        )?;

        self.write_declarations(
            &mut output,
            &declarations,
        )?;

        self.write_entry_point(
            &mut output,
            circuit,
        )?;

        self.write_attributes(
            &mut output,
            circuit,
        )?;

        self.write_module_flags(
            &mut output,
        )?;

        /*
         * `measurement_count` is intentionally calculated before construction
         * of the artifact so the artifact metadata is derived from the exact
         * emitted circuit, not from mutable state.
         */
        Ok(QirArtifact::new(
            output.into_string(),
            self.options.version,
            self.options.profile,
            self.options.entry_point.clone(),
            circuit.num_qubits(),
            measurement_count,
        ))
    }

    // -------------------------------------------------------------------------
    // Validation
    // -------------------------------------------------------------------------

    /// Validates the complete QIR representability contract before emitting
    /// output.
    fn validate_circuit(
        &self,
        circuit: &QuantumCircuit,
    ) -> Result<(), QirError> {
        /*
         * QuantumCircuit exposes its canonical validation boundary. The QIR
         * adapter performs an additional format-specific validation pass after
         * that boundary because a structurally valid Zamani circuit may still
         * contain operations that QIR Base Profile cannot represent directly.
         */
        circuit
            .validate()
            .map_err(|error| QirError::InvalidCircuit {
                reason: error.to_string(),
            })?;

        let mut measurement_started = false;
        let mut classical_destinations = BTreeSet::new();

        for gate in circuit.operations() {
            self.validate_gate(
                gate,
                circuit,
                &mut measurement_started,
                &mut classical_destinations,
            )?;
        }

        Ok(())
    }

    fn validate_gate(
        &self,
        gate: &Gate,
        circuit: &QuantumCircuit,
        measurement_started: &mut bool,
        classical_destinations: &mut BTreeSet<usize>,
    ) -> Result<(), QirError> {
        for qubit in gate.qubits() {
            if qubit.index() >= circuit.num_qubits() {
                return Err(QirError::InvalidQubit {
                    qubit: qubit.index(),
                    count: circuit.num_qubits(),
                });
            }
        }

        match gate.kind() {
            GateKind::Measure => {
                if *measurement_started {
                    /*
                     * Multiple terminal measurements are valid. The flag means
                     * the circuit has entered its measurement-only suffix, not
                     * that only one measurement may occur.
                     */
                }

                *measurement_started = true;

                let measurement = gate
                    .measurement()
                    .ok_or(QirError::UnsupportedMeasurement {
                        reason: "measurement payload is missing",
                    })?;

                if measurement.basis() != MeasurementBasis::Z {
                    return Err(QirError::UnsupportedMeasurement {
                        reason: "QIR Base Profile adapter emits only Z-basis measurement",
                    });
                }

                if measurement.mode() != MeasurementMode::NonDestructive {
                    return Err(QirError::UnsupportedMeasurement {
                        reason: "destructive measurement semantics are not emitted by this adapter",
                    });
                }

                let classical =
                    measurement.classical_bit().index();

                if classical >= circuit.num_classical_bits() {
                    return Err(QirError::InvalidClassicalBit {
                        bit: classical,
                        count: circuit.num_classical_bits(),
                    });
                }

                if !classical_destinations.insert(classical) {
                    return Err(
                        QirError::DuplicateClassicalDestination {
                            bit: classical,
                        },
                    );
                }

                if measurement.requests_reset_after() {
                    return Err(QirError::UnsupportedMeasurement {
                        reason: "reset-after-measurement is not part of this Base Profile mapping",
                    });
                }
            }

            _ if *measurement_started => {
                return Err(
                    QirError::OperationAfterMeasurement {
                        gate: gate.kind(),
                    },
                );
            }

            GateKind::I
            | GateKind::V
            | GateKind::Vdg
            | GateKind::Phase
            | GateKind::U1
            | GateKind::U2
            | GateKind::U3
            | GateKind::CH
            | GateKind::ISWAP
            | GateKind::ECR
            | GateKind::CRX
            | GateKind::CRY
            | GateKind::CRZ
            | GateKind::CSWAP
            | GateKind::Barrier
            | GateKind::Reset => {
                return Err(QirError::UnsupportedGate {
                    gate: gate.kind(),
                });
            }

            GateKind::X
            | GateKind::Y
            | GateKind::Z
            | GateKind::H
            | GateKind::S
            | GateKind::Sdg
            | GateKind::T
            | GateKind::Tdg
            | GateKind::RX
            | GateKind::RY
            | GateKind::RZ
            | GateKind::CX
            | GateKind::CY
            | GateKind::CZ
            | GateKind::SWAP
            | GateKind::CCX => {}
        }

        for (index, parameter) in gate.parameters().iter().enumerate() {
            match parameter {
                Parameter::Constant(value) if value.is_finite() => {}

                Parameter::Constant(_) => {
                    return Err(QirError::UnsupportedParameter {
                        gate: gate.kind(),
                        index,
                        reason: "QIR cannot contain non-finite LLVM floating-point constants",
                    });
                }

                Parameter::Symbol(_) => {
                    return Err(QirError::UnsupportedParameter {
                        gate: gate.kind(),
                        index,
                        reason: "symbolic parameters must be bound before QIR lowering",
                    });
                }

                Parameter::Expression(_) => {
                    return Err(QirError::UnsupportedParameter {
                        gate: gate.kind(),
                        index,
                        reason: "parameter expressions must be lowered to constants before QIR Base Profile export",
                    });
                }
            }
        }

        Ok(())
    }

    // -------------------------------------------------------------------------
    // Module generation
    // -------------------------------------------------------------------------

    fn write_module_header(
        &self,
        output: &mut BoundedOutput,
        circuit: &QuantumCircuit,
    ) -> Result<(), QirError> {
        output.line("; Zamani Quantum -> QIR v2.0")?;
        output.line("; Generated by zamani.quantum.hardware.adapters.qir")?;
        output.line("")?;

        output.line("source_filename = \"zamani.quantum.qir\"")?;
        output.line("")?;

        /*
         * QIR v2 uses opaque pointers. There is intentionally no `%Qubit =
         * type opaque` or `%Result = type opaque` declaration.
         */
        output.line(&format!(
            "; required_num_qubits = {}",
            circuit.num_qubits()
        ))?;

        output.line(&format!(
            "; required_num_results = {}",
            circuit
                .operations()
                .iter()
                .filter(|gate| gate.kind() == GateKind::Measure)
                .count()
        ))?;

        output.line("")?;

        Ok(())
    }

    fn write_declarations(
        &self,
        output: &mut BoundedOutput,
        declarations: &DeclarationSet,
    ) -> Result<(), QirError> {
        for declaration in declarations.qis.iter() {
            output.line(declaration)?;
        }

        if !declarations.qis.is_empty() {
            output.line("")?;
        }

        /*
         * Base Profile runtime declarations.
         *
         * `initialize` prepares the execution environment.
         *
         * `tuple_record_output` and `result_record_output` provide the output
         * recording boundary.
         */
        if self.options.emit_output_recording {
            output.line(
                "declare void @__quantum__rt__initialize(ptr)"
            )?;

            output.line(
                "declare void @__quantum__rt__tuple_record_output(i64, ptr)"
            )?;

            output.line(
                "declare void @__quantum__rt__result_record_output(ptr, ptr)"
            )?;

            output.line("")?;
        }

        Ok(())
    }

    fn write_entry_point(
        &self,
        output: &mut BoundedOutput,
        circuit: &QuantumCircuit,
    ) -> Result<(), QirError> {
        output.line(&format!(
            "define i64 @{}() #0 {{",
            self.options.entry_point
        ))?;

        output.line("entry:")?;

        output.line(
            "  call void @__quantum__rt__initialize(ptr null)"
        )?;

        output.line("  br label %body")?;
        output.line("")?;

        output.line("body:")?;

        /*
         * Base Profile permits a straight-line sequence of QIS calls in the
         * non-irreversible region followed by a measurement region.
         */
        let mut measurement_index = 0usize;

        for gate in circuit.operations() {
            if gate.kind() == GateKind::Measure {
                break;
            }

            self.write_gate_call(
                output,
                gate,
            )?;
        }

        output.line("  br label %measurements")?;
        output.line("")?;

        output.line("measurements:")?;

        for gate in circuit.operations() {
            if gate.kind() != GateKind::Measure {
                continue;
            }

            self.write_measurement_call(
                output,
                gate,
                measurement_index,
            )?;

            measurement_index = measurement_index
                .checked_add(1)
                .ok_or(QirError::InvalidCircuit {
                    reason: "measurement index overflow".to_owned(),
                })?;
        }

        output.line("  br label %output")?;
        output.line("")?;

        output.line("output:")?;

        if self.options.emit_output_recording {
            measurement_index = 0;

            for gate in circuit.operations() {
                if gate.kind() != GateKind::Measure {
                    continue;
                }

                self.write_result_output(
                    output,
                    gate,
                    measurement_index,
                )?;

                measurement_index = measurement_index
                    .checked_add(1)
                    .ok_or(QirError::InvalidCircuit {
                        reason: "measurement index overflow".to_owned(),
                    })?;
            }
        }

        output.line("  ret i64 0")?;
        output.line("}")?;
        output.line("")?;

        Ok(())
    }

    fn write_attributes(
        &self,
        output: &mut BoundedOutput,
        circuit: &QuantumCircuit,
    ) -> Result<(), QirError> {
        let measurement_count = circuit
            .operations()
            .iter()
            .filter(|gate| gate.kind() == GateKind::Measure)
            .count();

        output.line(&format!(
            "#0 = {{ \"entry_point\", \
             \"qir_profiles\"=\"{}\", \
             \"output_labeling_schema\"=\"{}\", \
             \"required_num_qubits\"=\"{}\", \
             \"required_num_results\"=\"{}\" }}",
            self.options.profile.as_str(),
            self.options.output_labeling_schema,
            circuit.num_qubits(),
            measurement_count,
        ))?;

        output.line(
            "#1 = { \"irreversible\" }"
        )?;

        output.line("")?;

        Ok(())
    }

    fn write_module_flags(
        &self,
        output: &mut BoundedOutput,
    ) -> Result<(), QirError> {
        /*
         * QIR v2 module flags.
         *
         * Dynamic resource management remains disabled because the Zamani
         * circuit supplied to this adapter has a statically known logical
         * namespace.
         */
        output.line(
            "!llvm.module.flags = !{!0, !1, !2, !3}"
        )?;

        output.line(
            "!0 = !{i32 1, !\"qir_major_version\", i32 2}"
        )?;

        output.line(
            "!1 = !{i32 7, !\"qir_minor_version\", i32 0}"
        )?;

        output.line(
            "!2 = !{i32 1, !\"dynamic_qubit_management\", i1 false}"
        )?;

        output.line(
            "!3 = !{i32 1, !\"dynamic_result_management\", i1 false}"
        )?;

        Ok(())
    }

    // -------------------------------------------------------------------------
    // Gate emission
    // -------------------------------------------------------------------------

    fn write_gate_call(
        &self,
        output: &mut BoundedOutput,
        gate: &Gate,
    ) -> Result<(), QirError> {
        let q = gate.qubits();

        match gate.kind() {
            GateKind::X => {
                output.line(&format!(
                    "  call void @__quantum__qis__x__body(ptr {})",
                    qir_qubit(q[0].index())
                ))?;
            }

            GateKind::Y => {
                output.line(&format!(
                    "  call void @__quantum__qis__y__body(ptr {})",
                    qir_qubit(q[0].index())
                ))?;
            }

            GateKind::Z => {
                output.line(&format!(
                    "  call void @__quantum__qis__z__body(ptr {})",
                    qir_qubit(q[0].index())
                ))?;
            }

            GateKind::H => {
                output.line(&format!(
                    "  call void @__quantum__qis__h__body(ptr {})",
                    qir_qubit(q[0].index())
                ))?;
            }

            GateKind::S => {
                output.line(&format!(
                    "  call void @__quantum__qis__s__body(ptr {})",
                    qir_qubit(q[0].index())
                ))?;
            }

            GateKind::Sdg => {
                output.line(&format!(
                    "  call void @__quantum__qis__s__adj(ptr {})",
                    qir_qubit(q[0].index())
                ))?;
            }

            GateKind::T => {
                output.line(&format!(
                    "  call void @__quantum__qis__t__body(ptr {})",
                    qir_qubit(q[0].index())
                ))?;
            }

            GateKind::Tdg => {
                output.line(&format!(
                    "  call void @__quantum__qis__t__adj(ptr {})",
                    qir_qubit(q[0].index())
                ))?;
            }

            GateKind::RX
            | GateKind::RY
            | GateKind::RZ => {
                let parameter = constant_parameter(
                    gate.kind(),
                    0,
                    gate.parameters(),
                )?;

                let function = match gate.kind() {
                    GateKind::RX => "__quantum__qis__rx__body",
                    GateKind::RY => "__quantum__qis__ry__body",
                    GateKind::RZ => "__quantum__qis__rz__body",
                    _ => unreachable!(),
                };

                output.line(&format!(
                    "  call void @{function}(double {}, ptr {})",
                    llvm_double(parameter),
                    qir_qubit(q[0].index()),
                ))?;
            }

            GateKind::CX => {
                output.line(&format!(
                    "  call void @__quantum__qis__cx__body(ptr {}, ptr {})",
                    qir_qubit(q[0].index()),
                    qir_qubit(q[1].index()),
                ))?;
            }

            GateKind::CY => {
                output.line(&format!(
                    "  call void @__quantum__qis__cy__body(ptr {}, ptr {})",
                    qir_qubit(q[0].index()),
                    qir_qubit(q[1].index()),
                ))?;
            }

            GateKind::CZ => {
                output.line(&format!(
                    "  call void @__quantum__qis__cz__body(ptr {}, ptr {})",
                    qir_qubit(q[0].index()),
                    qir_qubit(q[1].index()),
                ))?;
            }

            GateKind::SWAP => {
                output.line(&format!(
                    "  call void @__quantum__qis__swap__body(ptr {}, ptr {})",
                    qir_qubit(q[0].index()),
                    qir_qubit(q[1].index()),
                ))?;
            }

            GateKind::CCX => {
                output.line(&format!(
                    "  call void @__quantum__qis__ccx__body(ptr {}, ptr {}, ptr {})",
                    qir_qubit(q[0].index()),
                    qir_qubit(q[1].index()),
                    qir_qubit(q[2].index()),
                ))?;
            }

            /*
             * Measurement is emitted by the dedicated measurement routine so
             * that result numbering and `irreversible` semantics remain
             * centralized.
             */
            GateKind::Measure => {
                return Err(QirError::InvalidCircuit {
                    reason:
                        "measurement reached the unitary gate emission path"
                            .to_owned(),
                });
            }

            _ => {
                return Err(QirError::UnsupportedGate {
                    gate: gate.kind(),
                });
            }
        }

        Ok(())
    }

    fn write_measurement_call(
        &self,
        output: &mut BoundedOutput,
        gate: &Gate,
        measurement_index: usize,
    ) -> Result<(), QirError> {
        let measurement =
            gate.measurement().ok_or(
                QirError::UnsupportedMeasurement {
                    reason: "measurement payload is missing",
                },
            )?;

        output.line(&format!(
            "  call void @__quantum__qis__mz__body(ptr {}, ptr {}) #1",
            qir_qubit(measurement.qubit().index()),
            qir_result(measurement_index),
        ))?;

        Ok(())
    }

    fn write_result_output(
        &self,
        output: &mut BoundedOutput,
        gate: &Gate,
        measurement_index: usize,
    ) -> Result<(), QirError> {
        let measurement =
            gate.measurement().ok_or(
                QirError::UnsupportedMeasurement {
                    reason: "measurement payload is missing",
                },
            )?;

        /*
         * The label is generated entirely from the validated logical classical
         * bit index. No user-controlled string enters the LLVM global name or
         * contents.
         */
        let classical =
            measurement.classical_bit().index();

        output.line(&format!(
            "  call void @__quantum__rt__result_record_output(ptr {}, ptr @zamani_c{})",
            qir_result(measurement_index),
            classical,
        ))?;

        Ok(())
    }
}

// =============================================================================
// Declaration collection
// =============================================================================

/// Deterministic QIS declaration set.
#[derive(Debug, Default)]
struct DeclarationSet {
    qis: BTreeSet<String>,
}

fn collect_declarations(
    circuit: &QuantumCircuit,
) -> Result<DeclarationSet, QirError> {
    let mut declarations =
        DeclarationSet::default();

    for gate in circuit.operations() {
        let declaration =
            match gate.kind() {
                GateKind::X =>
                    "declare void @__quantum__qis__x__body(ptr)",
                GateKind::Y =>
                    "declare void @__quantum__qis__y__body(ptr)",
                GateKind::Z =>
                    "declare void @__quantum__qis__z__body(ptr)",
                GateKind::H =>
                    "declare void @__quantum__qis__h__body(ptr)",
                GateKind::S =>
                    "declare void @__quantum__qis__s__body(ptr)",
                GateKind::Sdg =>
                    "declare void @__quantum__qis__s__adj(ptr)",
                GateKind::T =>
                    "declare void @__quantum__qis__t__body(ptr)",
                GateKind::Tdg =>
                    "declare void @__quantum__qis__t__adj(ptr)",
                GateKind::RX =>
                    "declare void @__quantum__qis__rx__body(double, ptr)",
                GateKind::RY =>
                    "declare void @__quantum__qis__ry__body(double, ptr)",
                GateKind::RZ =>
                    "declare void @__quantum__qis__rz__body(double, ptr)",
                GateKind::CX =>
                    "declare void @__quantum__qis__cx__body(ptr, ptr)",
                GateKind::CY =>
                    "declare void @__quantum__qis__cy__body(ptr, ptr)",
                GateKind::CZ =>
                    "declare void @__quantum__qis__cz__body(ptr, ptr)",
                GateKind::SWAP =>
                    "declare void @__quantum__qis__swap__body(ptr, ptr)",
                GateKind::CCX =>
                    "declare void @__quantum__qis__ccx__body(ptr, ptr, ptr)",
                GateKind::Measure =>
                    "declare void @__quantum__qis__mz__body(ptr, ptr writeonly) #1",

                _ => continue,
            };

        declarations.qis.insert(
            declaration.to_owned()
        );
    }

    Ok(declarations)
}

// =============================================================================
// Parameter helpers
// =============================================================================

fn constant_parameter<'a>(
    gate: GateKind,
    index: usize,
    parameters: &'a [Parameter],
) -> Result<f64, QirError> {
    let parameter =
        parameters.get(index).ok_or(
            QirError::UnsupportedParameter {
                gate,
                index,
                reason: "parameter is missing",
            },
        )?;

    match parameter {
        Parameter::Constant(value)
            if value.is_finite() =>
        {
            Ok(*value)
        }

        Parameter::Constant(_) => {
            Err(QirError::UnsupportedParameter {
                gate,
                index,
                reason: "parameter is not finite",
            })
        }

        Parameter::Symbol(_) => {
            Err(QirError::UnsupportedParameter {
                gate,
                index,
                reason: "symbolic parameter is not bound",
            })
        }

        Parameter::Expression(_) => {
            Err(QirError::UnsupportedParameter {
                gate,
                index,
                reason: "parameter expression is not lowered",
            })
        }
    }
}

/// Formats a QIR opaque pointer representing a statically identified qubit.
fn qir_qubit(index: usize) -> String {
    format!(
        "inttoptr (i64 {} to ptr)",
        index
    )
}

/// Formats a QIR opaque pointer representing a statically identified result.
fn qir_result(index: usize) -> String {
    format!(
        "inttoptr (i64 {} to ptr)",
        index
    )
}

/// Formats a finite Rust `f64` as a deterministic LLVM floating-point literal.
///
/// Scientific notation is used to avoid locale-dependent formatting.
fn llvm_double(value: f64) -> String {
    /*
     * `{:e}` is deterministic in Rust and does not depend on process locale.
     *
     * The precision is explicitly fixed so the same Rust value produces the
     * same textual artifact across invocations.
     */
    format!("{value:.17e}")
}

// =============================================================================
// Identifier validation
// =============================================================================

fn validate_llvm_identifier(
    value: &str,
    maximum: usize,
    field: &'static str,
) -> Result<(), QirError> {
    if value.is_empty() {
        return Err(QirError::InvalidIdentifier {
            field,
            reason: "identifier must not be empty",
        });
    }

    if value.len() > maximum {
        return Err(QirError::InvalidIdentifier {
            field,
            reason: "identifier exceeds maximum length",
        });
    }

    let mut characters =
        value.chars();

    let first =
        characters.next().ok_or(
            QirError::InvalidIdentifier {
                field,
                reason: "identifier must not be empty",
            },
        )?;

    if !(first == '_'
        || first.is_ascii_alphabetic())
    {
        return Err(QirError::InvalidIdentifier {
            field,
            reason: "identifier must start with an ASCII letter or underscore",
        });
    }

    for character in characters {
        if !(character == '_'
            || character == '.'
            || character == '$'
            || character == '-'
            || character.is_ascii_alphanumeric())
        {
            return Err(QirError::InvalidIdentifier {
                field,
                reason: "identifier contains an unsupported character",
            });
        }
    }

    Ok(())
}

fn validate_ascii_identifier(
    value: &str,
    maximum: usize,
    field: &'static str,
) -> Result<(), QirError> {
    if value.is_empty() {
        return Err(QirError::InvalidIdentifier {
            field,
            reason: "identifier must not be empty",
        });
    }

    if value.len() > maximum {
        return Err(QirError::InvalidIdentifier {
            field,
            reason: "identifier exceeds maximum length",
        });
    }

    if !value
        .bytes()
        .all(|byte| {
            byte == b'_'
                || byte == b'.'
                || byte == b'-'
                || byte.is_ascii_alphanumeric()
        })
    {
        return Err(QirError::InvalidIdentifier {
            field,
            reason: "identifier must contain only ASCII alphanumeric characters, '_', '.', or '-'",
        });
    }

    Ok(())
}

// =============================================================================
// Bounded output
// =============================================================================

/// Output buffer that enforces its limit before every append.
///
/// This is intentionally implemented independently of the final `String`
/// length check. A post-construction check would allow an attacker-controlled
/// circuit to allocate an oversized artifact before rejection.
struct BoundedOutput {
    buffer: String,
    maximum: usize,
}

impl BoundedOutput {
    fn new(maximum: usize) -> Self {
        Self {
            buffer: String::new(),
            maximum,
        }
    }

    fn line(&mut self, line: &str) -> Result<(), QirError> {
        let additional =
            line.len()
                .checked_add(1)
                .ok_or(QirError::OutputLimitExceeded {
                    attempted: usize::MAX,
                    maximum: self.maximum,
                })?;

        let attempted =
            self.buffer
                .len()
                .checked_add(additional)
                .ok_or(QirError::OutputLimitExceeded {
                    attempted: usize::MAX,
                    maximum: self.maximum,
                })?;

        if attempted > self.maximum {
            return Err(QirError::OutputLimitExceeded {
                attempted,
                maximum: self.maximum,
            });
        }

        self.buffer
            .write_str(line)
            .map_err(|_| QirError::Formatting)?;

        self.buffer
            .write_char('\n')
            .map_err(|_| QirError::Formatting)?;

        Ok(())
    }

    fn into_string(self) -> String {
        self.buffer
    }
}

// =============================================================================
// Tests
// =============================================================================

#[cfg(test)]
mod tests {
    use super::*;
    use crate::quantum::ir::QuantumCircuit;

    #[test]
    fn production_version_is_qir_2_0() {
        let version =
            QirVersion::production();

        assert_eq!(version.major(), 2);
        assert_eq!(version.minor(), 0);
        assert!(version.is_supported());
    }

    #[test]
    fn production_options_are_valid() {
        let options =
            QirOptions::production()
                .expect("production options must be valid");

        assert_eq!(
            options.version,
            QirVersion::new(2, 0)
        );

        assert_eq!(
            options.profile,
            QirProfile::Base
        );
    }

    #[test]
    fn empty_circuit_is_exportable() {
        let circuit =
            QuantumCircuit::new(0, 0)
                .expect("zero-resource circuit must be valid");

        let exporter =
            QirExporter::production()
                .expect("production exporter");

        let artifact =
            exporter
                .export(&circuit)
                .expect("empty circuit should export");

        assert!(
            artifact
                .text()
                .contains("qir_major_version")
        );

        assert!(
            artifact
                .text()
                .contains("dynamic_qubit_management")
        );

        assert!(
            artifact
                .text()
                .contains("@__zamani_entry")
        );
    }

    #[test]
    fn qir_pointer_format_is_deterministic() {
        assert_eq!(
            qir_qubit(7),
            "inttoptr (i64 7 to ptr)"
        );

        assert_eq!(
            qir_result(3),
            "inttoptr (i64 3 to ptr)"
        );
    }

    #[test]
    fn floating_point_format_is_deterministic() {
        let value =
            llvm_double(1.25);

        assert_eq!(
            value,
            "1.25000000000000000e0"
        );
    }

    #[test]
    fn output_limit_is_enforced_before_append() {
        let mut output =
            BoundedOutput::new(4);

        assert!(
            output.line("123").is_ok()
        );

        assert!(
            matches!(
                output.line("x"),
                Err(
                    QirError::OutputLimitExceeded {
                        ..
                    }
                )
            )
        );
    }

    #[test]
    fn invalid_entry_point_is_rejected() {
        let mut options =
            QirOptions::default();

        options.entry_point =
            "123-invalid".to_owned();

        assert!(
            matches!(
                QirExporter::new(options),
                Err(
                    QirError::InvalidIdentifier {
                        field: "entry_point",
                        ..
                    }
                )
            )
        );
    }

    #[test]
    fn symbolic_parameter_is_rejected() {
        let result =
            constant_parameter(
                GateKind::RX,
                0,
                &[
                    Parameter::Symbol(
                        "theta".to_owned()
                    )
                ],
            );

        assert!(
            matches!(
                result,
                Err(
                    QirError::UnsupportedParameter {
                        gate: GateKind::RX,
                        index: 0,
                        ..
                    }
                )
            )
        );
    }

    #[test]
    fn unsupported_gate_is_explicit() {
        let error =
            QirError::UnsupportedGate {
                gate: GateKind::U3,
            };

        assert!(
            error
                .to_string()
                .contains("U3")
        );
    }
}