//! Deterministic, production-grade CSV serialization for quantum benchmark
//! summaries.
//!
//! # Purpose
//!
//! `csv.rs` is the machine-readable tabular serializer for
//! `quantum::benchmarking::reporting::BenchmarkSummary`.
//!
//! It deliberately does NOT:
//!
//! - execute quantum circuits;
//! - generate benchmark circuits;
//! - calculate benchmark metrics;
//! - perform statistical inference;
//! - access hardware;
//! - inspect backend-specific implementation details;
//! - modify `BenchmarkSummary`;
//! - depend on individual benchmark protocols;
//! - depend on `core::result`;
//! - depend on `analysis`;
//! - depend on `validation`.
//!
//! Those responsibilities belong to the owning benchmarking layers.
//!
//! # Architectural position
//!
//! ```text
//! BenchmarkResult
//!      │
//!      ▼
//! reporting::summary::BenchmarkSummary
//!      │
//!      ├──────────────► reporting::json
//!      │
//!      ├──────────────► reporting::markdown
//!      │
//!      └──────────────► reporting::csv
//!                               │
//!                               ▼
//!                         UTF-8 CSV bytes
//! ```
//!
//! `BenchmarkSummary` is the only semantic input to this module.
//!
//! # Why CSV is a separate representation
//!
//! CSV is useful for:
//!
//! - spreadsheets;
//! - scientific data analysis;
//! - R;
//! - Python/pandas;
//! - command-line processing;
//! - CI artifacts;
//! - benchmark history databases;
//! - regression pipelines;
//! - plotting tools;
//! - external research workflows.
//!
//! However, CSV is inherently tabular and cannot naturally represent the
//! complete nested structure of a benchmark result. Therefore this module uses
//! a documented, deterministic **long-form record schema**.
//!
//! Each output row has a `record_type`:
//!
//! - `summary`         — one row describing the benchmark summary;
//! - `metric`          — one row for every benchmark metric;
//! - `finding`         — one row for every finding;
//! - `recommendation`  — one row for every recommendation.
//!
//! The schema is intentionally stable and machine-readable.
//!
//! # CSV guarantees
//!
//! This implementation guarantees:
//!
//! - UTF-8 output;
//! - deterministic column ordering;
//! - deterministic row ordering;
//! - RFC 4180-compatible quoting rules;
//! - correct escaping of commas;
//! - correct escaping of quotes;
//! - correct preservation of newlines;
//! - correct preservation of carriage returns;
//! - no trailing separator;
//! - exactly one header row;
//! - explicit schema version;
//! - bounded output allocation;
//! - rejection of invalid configuration;
//! - rejection of oversized output;
//! - rejection of non-finite floating-point values;
//! - no `unwrap()`;
//! - no `expect()`;
//! - no panic-based validation;
//! - no logging side effects;
//! - no timestamps generated by the serializer;
//! - no random values;
//! - no dependence on filesystem APIs;
//! - no dependency on a third-party CSV crate.
//!
//! # Security
//!
//! CSV has a well-known spreadsheet-formula injection problem. A benchmark
//! identifier, backend identifier, metric description, finding message, or
//! recommendation could theoretically begin with a spreadsheet formula such
//! as `=`, `+`, `-`, or `@`.
//!
//! This serializer therefore provides an explicit formula-injection policy.
//! By default, potentially executable spreadsheet cells are prefixed with a
//! single quote when exporting for spreadsheet consumption.
//!
//! Raw machine-oriented CSV can be requested through
//! [`CsvOptions::spreadsheet_safe`].
//!
//! The default is `true` because benchmark output is frequently opened in
//! spreadsheet software.
//!
//! # Resource safety
//!
//! The serializer validates:
//!
//! - maximum rows;
//! - maximum fields per row;
//! - maximum field length;
//! - maximum total output bytes.
//!
//! These limits protect callers from accidentally materializing an enormous
//! CSV document in memory.
//!
//! # Integration contract
//!
//! This module is intentionally stable against changes in the underlying
//! benchmark implementation.
//!
//! The integration point is:
//!
//! ```text
//! BenchmarkSummary
//!       │
//!       ▼
//! CsvReport::from_summary()
//!       │
//!       ▼
//! CsvReport::to_string()
//! ```
//!
//! Therefore future changes to `core::result`, individual benchmark protocols,
//! hardware backends, or statistical implementations do not require this file
//! to be rewritten as long as `BenchmarkSummary` remains the reporting
//! contract.
//!
//! # Rust compatibility
//!
//! Target:
//!
//! - Rust 1.97;
//! - Rust 1.97.1;
//! - Rust 2021 edition;
//! - stable Rust only.
//!
//! No nightly features are required.
//!
//! # Dependencies
//!
//! The implementation intentionally uses only:
//!
//! - Rust standard library;
//! - `serde_json`, already used by the Zamani benchmarking/reporting layer.
//!
//! No dedicated CSV dependency is required.
//!
//! # Integration with reporting::summary
//!
//! The current summary layer defines:
//!
//! - `BenchmarkSummary`;
//! - `SummaryMetric`;
//! - `SummaryFinding`;
//! - `SummaryEnvironment`;
//! - `SummaryConfidence`;
//! - `SummarySeverity`;
//! - `SummaryStatus`.
//!
//! This serializer consumes those public types and does not duplicate their
//! semantic definitions.
//!
//! # Future reporting modules
//!
//! `report.rs` should orchestrate report generation and may call this module.
//! `json.rs` should provide the lossless structured representation.
//! `markdown.rs` should provide human-readable presentation.
//!
//! CSV should remain a serializer, not become the reporting orchestrator.
//!
//! # Important path correction
//!
//! The repository architecture uses:
//!
//! ```text
//! src/quantum/benchmarking/reporting/
//! ```
//!
//! Therefore this file belongs at:
//!
//! ```text
//! src/quantum/benchmarking/reporting/csv.rs
//! ```
//!
//! not:
//!
//! ```text
//! src/quantum/benchmarking/reposting/csv.rs
//! ```
//!
//! Do not create a second `reposting` subsystem merely because of a spelling
//! mistake in a task description.

use std::fmt;
use std::fmt::Write as _;

use serde_json::Value;

use super::summary::{
    BenchmarkSummary, SummaryFinding, SummaryMetric, SummarySeverity, SummaryStatus,
};

/// Stable CSV schema identifier.
///
/// This version describes the shape of the CSV document, not the benchmark
/// protocol version and not the Zamani package version.
pub const CSV_SCHEMA_VERSION: &str = "1.0";

/// Default maximum number of data rows.
///
/// A summary row is always included, followed by metric, finding and
/// recommendation rows.
pub const DEFAULT_MAX_ROWS: usize = 1_000_000;

/// Default maximum UTF-8 byte length of one CSV field.
pub const DEFAULT_MAX_FIELD_BYTES: usize = 1 << 20; // 1 MiB

/// Default maximum UTF-8 byte length of the complete CSV document.
pub const DEFAULT_MAX_OUTPUT_BYTES: usize = 256 << 20; // 256 MiB

/// Maximum number of fields in every emitted row.
pub const CSV_FIELD_COUNT: usize = 23;

/// Number of decimal places used for floating-point values.
///
/// This is deliberately fixed so two serializations of the same
/// `BenchmarkSummary` are byte-for-byte deterministic.
pub const DEFAULT_FLOAT_DECIMAL_PLACES: usize = 17;

/// Result type returned by CSV serialization.
pub type CsvResult<T> = Result<T, CsvError>;

/// Configuration controlling CSV serialization.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct CsvOptions {
    /// Maximum number of rows permitted in the output.
    pub max_rows: usize,

    /// Maximum number of UTF-8 bytes allowed in one field.
    pub max_field_bytes: usize,

    /// Maximum number of UTF-8 bytes allowed in the final CSV document.
    pub max_output_bytes: usize,

    /// Whether spreadsheet-formula injection protection is enabled.
    ///
    /// When enabled, textual cells beginning with a potentially executable
    /// spreadsheet formula character are prefixed with `'`.
    pub spreadsheet_safe: bool,

    /// Whether a UTF-8 BOM should be emitted.
    ///
    /// This is disabled by default because BOM-free UTF-8 is the preferred
    /// machine-interchange representation.
    pub utf8_bom: bool,
}

impl Default for CsvOptions {
    fn default() -> Self {
        Self {
            max_rows: DEFAULT_MAX_ROWS,
            max_field_bytes: DEFAULT_MAX_FIELD_BYTES,
            max_output_bytes: DEFAULT_MAX_OUTPUT_BYTES,
            spreadsheet_safe: true,
            utf8_bom: false,
        }
    }
}

impl CsvOptions {
    /// Validates the serialization limits.
    pub fn validate(&self) -> CsvResult<()> {
        if self.max_rows == 0 {
            return Err(CsvError::InvalidLimit {
                field: "max_rows",
            });
        }

        if self.max_field_bytes == 0 {
            return Err(CsvError::InvalidLimit {
                field: "max_field_bytes",
            });
        }

        if self.max_output_bytes == 0 {
            return Err(CsvError::InvalidLimit {
                field: "max_output_bytes",
            });
        }

        if self.max_output_bytes < self.max_field_bytes {
            return Err(CsvError::InvalidConfiguration {
                message: "max_output_bytes must be greater than or equal to max_field_bytes",
            });
        }

        Ok(())
    }
}

/// CSV serialization errors.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum CsvError {
    /// A serializer limit is zero or otherwise invalid.
    InvalidLimit {
        /// Name of the invalid limit.
        field: &'static str,
    },

    /// The serializer configuration is internally inconsistent.
    InvalidConfiguration {
        /// Stable human-readable description.
        message: &'static str,
    },

    /// The benchmark summary contains an invalid UTF-8 field.
    ///
    /// Rust `String` values are always valid UTF-8, so this variant is
    /// currently reserved for future byte-oriented extensions.
    InvalidText {
        /// Field name.
        field: &'static str,
    },

    /// A field exceeded the configured size.
    FieldTooLarge {
        /// Field name.
        field: &'static str,

        /// Actual UTF-8 byte length.
        actual: usize,

        /// Maximum permitted byte length.
        limit: usize,
    },

    /// The resulting document would exceed the configured output size.
    OutputTooLarge {
        /// Current/projected UTF-8 byte length.
        actual: usize,

        /// Maximum permitted byte length.
        limit: usize,
    },

    /// The result contains a non-finite floating-point value.
    NonFiniteFloat {
        /// Field name.
        field: &'static str,
    },

    /// A serde representation could not be converted into a stable scalar.
    Serialization {
        /// Stable description of the serialization problem.
        message: String,
    },
}

impl fmt::Display for CsvError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::InvalidLimit { field } => {
                write!(formatter, "invalid CSV limit: {field}")
            }
            Self::InvalidConfiguration { message } => {
                write!(formatter, "invalid CSV configuration: {message}")
            }
            Self::InvalidText { field } => {
                write!(formatter, "invalid CSV text in field: {field}")
            }
            Self::FieldTooLarge {
                field,
                actual,
                limit,
            } => {
                write!(
                    formatter,
                    "CSV field '{field}' is too large: {actual} bytes exceeds {limit}"
                )
            }
            Self::OutputTooLarge { actual, limit } => {
                write!(
                    formatter,
                    "CSV output is too large: {actual} bytes exceeds {limit}"
                )
            }
            Self::NonFiniteFloat { field } => {
                write!(formatter, "non-finite floating-point value in CSV field: {field}")
            }
            Self::Serialization { message } => {
                write!(formatter, "CSV serialization error: {message}")
            }
        }
    }
}

impl std::error::Error for CsvError {}

/// The canonical column order.
///
/// This is part of the CSV schema and must not be changed casually.
///
/// Every emitted row contains exactly these columns, regardless of
/// `record_type`.
const HEADER: [&str; CSV_FIELD_COUNT] = [
    "schema_version",
    "record_type",
    "benchmark_id",
    "benchmark_version",
    "experiment_id",
    "workload_id",
    "status",
    "successful",
    "headline",
    "description",
    "backend_id",
    "provider",
    "technology",
    "compiler_version",
    "optimization_level",
    "routing_configuration",
    "scheduling_configuration",
    "calibration_id",
    "calibration_timestamp",
    "metric_id",
    "metric_name",
    "metric_value",
    "metric_unit",
];

/// Additional metric/finding/recommendation columns.
///
/// These are emitted after the common columns so consumers can use a fixed
/// schema.
const EXTENDED_HEADER: [&str; 15] = [
    "metric_direction",
    "metric_quality",
    "metric_uncertainty",
    "confidence_level",
    "confidence_lower",
    "confidence_upper",
    "confidence_method",
    "confidence_width",
    "sample_count",
    "shot_count",
    "circuit_count",
    "finding_severity",
    "finding_code",
    "finding_message",
    "recommendation",
];

/// Complete CSV header.
///
/// Kept as a function rather than a mutable global to make the public schema
/// explicit and immutable.
fn complete_header() -> Vec<&'static str> {
    let mut header = Vec::with_capacity(CSV_FIELD_COUNT + EXTENDED_HEADER.len());
    header.extend_from_slice(&HEADER);
    header.extend_from_slice(&EXTENDED_HEADER);
    header
}

/// Total number of CSV columns.
const TOTAL_FIELD_COUNT: usize = CSV_FIELD_COUNT + EXTENDED_HEADER.len();

/// Canonical CSV report object.
///
/// This is intentionally small. It owns the serialization configuration and
/// borrows no mutable state from the benchmark engine.
#[derive(Debug, Clone, Copy)]
pub struct CsvReport<'a> {
    /// Benchmark summary to serialize.
    summary: &'a BenchmarkSummary,

    /// Serialization options.
    options: CsvOptions,
}

impl<'a> CsvReport<'a> {
    /// Creates a CSV serializer using production defaults.
    pub fn new(summary: &'a BenchmarkSummary) -> CsvResult<Self> {
        Self::with_options(summary, CsvOptions::default())
    }

    /// Creates a CSV serializer with explicit options.
    pub fn with_options(
        summary: &'a BenchmarkSummary,
        options: CsvOptions,
    ) -> CsvResult<Self> {
        options.validate()?;
        validate_summary_for_csv(summary, &options)?;

        Ok(Self { summary, options })
    }

    /// Returns the benchmark summary being serialized.
    pub fn summary(&self) -> &'a BenchmarkSummary {
        self.summary
    }

    /// Returns the serializer configuration.
    pub const fn options(&self) -> CsvOptions {
        self.options
    }

    /// Serializes the summary into an owned UTF-8 `String`.
    pub fn to_string(&self) -> CsvResult<String> {
        let rows = checked_row_count(self.summary)?;

        if rows > self.options.max_rows {
            return Err(CsvError::OutputTooLarge {
                actual: rows,
                limit: self.options.max_rows,
            });
        }

        let mut output = String::new();

        if self.options.utf8_bom {
            output.push('\u{FEFF}');
        }

        let header = complete_header();

        write_row(
            &mut output,
            header.iter().copied(),
            self.options,
        )?;

        write_summary_row(&mut output, self.summary, self.options)?;

        for metric in &self.summary.metrics {
            write_metric_row(&mut output, self.summary, metric, self.options)?;
        }

        for finding in &self.summary.findings {
            write_finding_row(&mut output, self.summary, finding, self.options)?;
        }

        for recommendation in &self.summary.recommendations {
            write_recommendation_row(
                &mut output,
                self.summary,
                recommendation,
                self.options,
            )?;
        }

        enforce_output_limit(&output, self.options.max_output_bytes)?;

        Ok(output)
    }

    /// Serializes the summary directly into UTF-8 bytes.
    pub fn to_bytes(&self) -> CsvResult<Vec<u8>> {
        Ok(self.to_string()?.into_bytes())
    }

    /// Returns the expected number of data rows, excluding the CSV header.
    pub fn row_count(&self) -> CsvResult<usize> {
        checked_row_count(self.summary)
    }
}

/// Convenience function using production defaults.
pub fn to_csv(summary: &BenchmarkSummary) -> CsvResult<String> {
    CsvReport::new(summary)?.to_string()
}

/// Convenience function returning UTF-8 bytes.
pub fn to_csv_bytes(summary: &BenchmarkSummary) -> CsvResult<Vec<u8>> {
    CsvReport::new(summary)?.to_bytes()
}

/// Convenience function with explicit serializer options.
pub fn to_csv_with_options(
    summary: &BenchmarkSummary,
    options: CsvOptions,
) -> CsvResult<String> {
    CsvReport::with_options(summary, options)?.to_string()
}

/// Returns the stable CSV schema version.
pub const fn schema_version() -> &'static str {
    CSV_SCHEMA_VERSION
}

/// Returns the complete CSV column names.
///
/// This is useful for external tooling that needs to validate the schema
/// without parsing an example document.
pub fn columns() -> Vec<&'static str> {
    complete_header()
}

/// Returns the total number of columns in the canonical schema.
pub const fn column_count() -> usize {
    TOTAL_FIELD_COUNT
}

fn checked_row_count(summary: &BenchmarkSummary) -> CsvResult<usize> {
    let mut count = 1usize; // summary row

    count = count
        .checked_add(summary.metrics.len())
        .ok_or(CsvError::OutputTooLarge {
            actual: usize::MAX,
            limit: DEFAULT_MAX_ROWS,
        })?;

    count = count
        .checked_add(summary.findings.len())
        .ok_or(CsvError::OutputTooLarge {
            actual: usize::MAX,
            limit: DEFAULT_MAX_ROWS,
        })?;

    count = count
        .checked_add(summary.recommendations.len())
        .ok_or(CsvError::OutputTooLarge {
            actual: usize::MAX,
            limit: DEFAULT_MAX_ROWS,
        })?;

    Ok(count)
}

fn validate_summary_for_csv(
    summary: &BenchmarkSummary,
    options: &CsvOptions,
) -> CsvResult<()> {
    let row_count = checked_row_count(summary)?;

    if row_count > options.max_rows {
        return Err(CsvError::OutputTooLarge {
            actual: row_count,
            limit: options.max_rows,
        });
    }

    validate_text_field(
        "benchmark_id",
        &summary.identity.benchmark_id,
        options.max_field_bytes,
    )?;

    validate_optional_text_field(
        "benchmark_version",
        summary.identity.benchmark_version.as_deref(),
        options.max_field_bytes,
    )?;

    validate_optional_text_field(
        "experiment_id",
        summary.identity.experiment_id.as_deref(),
        options.max_field_bytes,
    )?;

    validate_optional_text_field(
        "workload_id",
        summary.identity.workload_id.as_deref(),
        options.max_field_bytes,
    )?;

    validate_text_field(
        "headline",
        &summary.headline,
        options.max_field_bytes,
    )?;

    validate_optional_text_field(
        "description",
        summary.description.as_deref(),
        options.max_field_bytes,
    )?;

    validate_environment(summary, options)?;

    for metric in &summary.metrics {
        validate_metric(metric, options)?;
    }

    for finding in &summary.findings {
        validate_finding(finding, options)?;
    }

    for recommendation in &summary.recommendations {
        validate_text_field(
            "recommendation",
            recommendation,
            options.max_field_bytes,
        )?;
    }

    Ok(())
}

fn validate_environment(
    summary: &BenchmarkSummary,
    options: &CsvOptions,
) -> CsvResult<()> {
    let environment = &summary.environment;

    validate_optional_text_field(
        "backend_id",
        environment.backend_id.as_deref(),
        options.max_field_bytes,
    )?;

    validate_optional_text_field(
        "provider",
        environment.provider.as_deref(),
        options.max_field_bytes,
    )?;

    validate_optional_text_field(
        "technology",
        environment.technology.as_deref(),
        options.max_field_bytes,
    )?;

    validate_optional_text_field(
        "compiler_version",
        environment.compiler_version.as_deref(),
        options.max_field_bytes,
    )?;

    validate_optional_text_field(
        "optimization_level",
        environment.optimization_level.as_deref(),
        options.max_field_bytes,
    )?;

    validate_optional_text_field(
        "routing_configuration",
        environment.routing_configuration.as_deref(),
        options.max_field_bytes,
    )?;

    validate_optional_text_field(
        "scheduling_configuration",
        environment.scheduling_configuration.as_deref(),
        options.max_field_bytes,
    )?;

    validate_optional_text_field(
        "calibration_id",
        environment.calibration_id.as_deref(),
        options.max_field_bytes,
    )?;

    validate_optional_text_field(
        "calibration_timestamp",
        environment.calibration_timestamp.as_deref(),
        options.max_field_bytes,
    )?;

    Ok(())
}

fn validate_metric(
    metric: &SummaryMetric,
    options: &CsvOptions,
) -> CsvResult<()> {
    validate_text_field("metric.id", &metric.id, options.max_field_bytes)?;
    validate_text_field("metric.name", &metric.name, options.max_field_bytes)?;
    validate_text_field("metric.unit", &metric.unit, options.max_field_bytes)?;

    validate_finite("metric.value", metric.value)?;

    if let Some(value) = metric.uncertainty {
        validate_finite("metric.uncertainty", value)?;

        if value < 0.0 {
            return Err(CsvError::InvalidConfiguration {
                message: "metric uncertainty cannot be negative",
            });
        }
    }

    if let Some(confidence) = &metric.confidence {
        validate_finite("confidence.level", confidence.level)?;
        validate_finite("confidence.lower", confidence.lower)?;
        validate_finite("confidence.upper", confidence.upper)?;
        validate_finite("confidence.width", confidence.width)?;

        if !(0.0 < confidence.level && confidence.level < 1.0) {
            return Err(CsvError::InvalidConfiguration {
                message: "confidence level must be greater than 0 and less than 1",
            });
        }

        if confidence.lower > confidence.upper {
            return Err(CsvError::InvalidConfiguration {
                message: "confidence lower bound cannot exceed upper bound",
            });
        }

        if confidence.width < 0.0 {
            return Err(CsvError::InvalidConfiguration {
                message: "confidence interval width cannot be negative",
            });
        }

        validate_text_field(
            "confidence.method",
            &confidence.method,
            options.max_field_bytes,
        )?;
    }

    if let Some(description) = &metric.description {
        validate_text_field(
            "metric.description",
            description,
            options.max_field_bytes,
        )?;
    }

    Ok(())
}

fn validate_finding(
    finding: &SummaryFinding,
    options: &CsvOptions,
) -> CsvResult<()> {
    validate_text_field(
        "finding.code",
        &finding.code,
        options.max_field_bytes,
    )?;

    validate_text_field(
        "finding.message",
        &finding.message,
        options.max_field_bytes,
    )?;

    if let Some(metric_id) = &finding.metric_id {
        validate_text_field(
            "finding.metric_id",
            metric_id,
            options.max_field_bytes,
        )?;
    }

    Ok(())
}

fn validate_text_field(
    field: &'static str,
    value: &str,
    max_bytes: usize,
) -> CsvResult<()> {
    let length = value.len();

    if length > max_bytes {
        return Err(CsvError::FieldTooLarge {
            field,
            actual: length,
            limit: max_bytes,
        });
    }

    Ok(())
}

fn validate_optional_text_field(
    field: &'static str,
    value: Option<&str>,
    max_bytes: usize,
) -> CsvResult<()> {
    if let Some(value) = value {
        validate_text_field(field, value, max_bytes)?;
    }

    Ok(())
}

fn validate_finite(field: &'static str, value: f64) -> CsvResult<()> {
    if !value.is_finite() {
        return Err(CsvError::NonFiniteFloat { field });
    }

    Ok(())
}

fn write_summary_row(
    output: &mut String,
    summary: &BenchmarkSummary,
    options: CsvOptions,
) -> CsvResult<()> {
    let environment = &summary.environment;

    let values = [
        CSV_SCHEMA_VERSION.to_string(),
        "summary".to_string(),
        summary.identity.benchmark_id.clone(),
        optional_string(summary.identity.benchmark_version.as_deref()),
        optional_string(summary.identity.experiment_id.as_deref()),
        optional_string(summary.identity.workload_id.as_deref()),
        summary.status.id().to_string(),
        bool_string(summary.successful),
        summary.headline.clone(),
        optional_string(summary.description.as_deref()),
        optional_string(environment.backend_id.as_deref()),
        optional_string(environment.provider.as_deref()),
        optional_string(environment.technology.as_deref()),
        optional_string(environment.compiler_version.as_deref()),
        optional_string(environment.optimization_level.as_deref()),
        optional_string(environment.routing_configuration.as_deref()),
        optional_string(environment.scheduling_configuration.as_deref()),
        optional_string(environment.calibration_id.as_deref()),
        optional_string(environment.calibration_timestamp.as_deref()),
        String::new(),
        String::new(),
        String::new(),
        String::new(),
        String::new(),
        String::new(),
        String::new(),
        String::new(),
        String::new(),
        String::new(),
        String::new(),
        String::new(),
        String::new(),
        String::new(),
        String::new(),
        String::new(),
        String::new(),
        String::new(),
        String::new(),
    ];

    write_row(output, values.iter().map(String::as_str), options)
}

fn write_metric_row(
    output: &mut String,
    summary: &BenchmarkSummary,
    metric: &SummaryMetric,
    options: CsvOptions,
) -> CsvResult<()> {
    let environment = &summary.environment;

    let confidence = metric.confidence.as_ref();

    let values = [
        CSV_SCHEMA_VERSION.to_string(),
        "metric".to_string(),
        summary.identity.benchmark_id.clone(),
        optional_string(summary.identity.benchmark_version.as_deref()),
        optional_string(summary.identity.experiment_id.as_deref()),
        optional_string(summary.identity.workload_id.as_deref()),
        summary.status.id().to_string(),
        bool_string(summary.successful),
        summary.headline.clone(),
        optional_string(summary.description.as_deref()),
        optional_string(environment.backend_id.as_deref()),
        optional_string(environment.provider.as_deref()),
        optional_string(environment.technology.as_deref()),
        optional_string(environment.compiler_version.as_deref()),
        optional_string(environment.optimization_level.as_deref()),
        optional_string(environment.routing_configuration.as_deref()),
        optional_string(environment.scheduling_configuration.as_deref()),
        optional_string(environment.calibration_id.as_deref()),
        optional_string(environment.calibration_timestamp.as_deref()),
        metric.id.clone(),
        metric.name.clone(),
        format_float("metric.value", metric.value)?,
        metric.unit.clone(),
        enum_id(&metric.direction)?,
        enum_id(&metric.quality)?,
        optional_float("metric.uncertainty", metric.uncertainty)?,
        confidence
            .map(|value| format_float("confidence.level", value.level))
            .transpose()?
            .unwrap_or_default(),
        confidence
            .map(|value| format_float("confidence.lower", value.lower))
            .transpose()?
            .unwrap_or_default(),
        confidence
            .map(|value| format_float("confidence.upper", value.upper))
            .transpose()?
            .unwrap_or_default(),
        confidence
            .map(|value| value.method.clone())
            .unwrap_or_default(),
        confidence
            .map(|value| format_float("confidence.width", value.width))
            .transpose()?
            .unwrap_or_default(),
        optional_u64(metric.sample_count),
        optional_u64(metric.shot_count),
        optional_u64(metric.circuit_count),
        String::new(),
        String::new(),
        String::new(),
        String::new(),
    ];

    write_row(output, values.iter().map(String::as_str), options)
}

fn write_finding_row(
    output: &mut String,
    summary: &BenchmarkSummary,
    finding: &SummaryFinding,
    options: CsvOptions,
) -> CsvResult<()> {
    let environment = &summary.environment;

    let values = [
        CSV_SCHEMA_VERSION.to_string(),
        "finding".to_string(),
        summary.identity.benchmark_id.clone(),
        optional_string(summary.identity.benchmark_version.as_deref()),
        optional_string(summary.identity.experiment_id.as_deref()),
        optional_string(summary.identity.workload_id.as_deref()),
        summary.status.id().to_string(),
        bool_string(summary.successful),
        summary.headline.clone(),
        optional_string(summary.description.as_deref()),
        optional_string(environment.backend_id.as_deref()),
        optional_string(environment.provider.as_deref()),
        optional_string(environment.technology.as_deref()),
        optional_string(environment.compiler_version.as_deref()),
        optional_string(environment.optimization_level.as_deref()),
        optional_string(environment.routing_configuration.as_deref()),
        optional_string(environment.scheduling_configuration.as_deref()),
        optional_string(environment.calibration_id.as_deref()),
        optional_string(environment.calibration_timestamp.as_deref()),
        finding
            .metric_id
            .clone()
            .unwrap_or_default(),
        String::new(),
        String::new(),
        String::new(),
        String::new(),
        String::new(),
        String::new(),
        String::new(),
        String::new(),
        String::new(),
        String::new(),
        String::new(),
        enum_id(&finding.severity)?,
        finding.code.clone(),
        finding.message.clone(),
        String::new(),
    ];

    write_row(output, values.iter().map(String::as_str), options)
}

fn write_recommendation_row(
    output: &mut String,
    summary: &BenchmarkSummary,
    recommendation: &str,
    options: CsvOptions,
) -> CsvResult<()> {
    let environment = &summary.environment;

    let values = [
        CSV_SCHEMA_VERSION.to_string(),
        "recommendation".to_string(),
        summary.identity.benchmark_id.clone(),
        optional_string(summary.identity.benchmark_version.as_deref()),
        optional_string(summary.identity.experiment_id.as_deref()),
        optional_string(summary.identity.workload_id.as_deref()),
        summary.status.id().to_string(),
        bool_string(summary.successful),
        summary.headline.clone(),
        optional_string(summary.description.as_deref()),
        optional_string(environment.backend_id.as_deref()),
        optional_string(environment.provider.as_deref()),
        optional_string(environment.technology.as_deref()),
        optional_string(environment.compiler_version.as_deref()),
        optional_string(environment.optimization_level.as_deref()),
        optional_string(environment.routing_configuration.as_deref()),
        optional_string(environment.scheduling_configuration.as_deref()),
        optional_string(environment.calibration_id.as_deref()),
        optional_string(environment.calibration_timestamp.as_deref()),
        String::new(),
        String::new(),
        String::new(),
        String::new(),
        String::new(),
        String::new(),
        String::new(),
        String::new(),
        String::new(),
        String::new(),
        String::new(),
        String::new(),
        String::new(),
        String::new(),
        recommendation.to_string(),
    ];

    write_row(output, values.iter().map(String::as_str), options)
}

fn write_row<'a, I>(
    output: &mut String,
    values: I,
    options: CsvOptions,
) -> CsvResult<()>
where
    I: IntoIterator<Item = &'a str>,
{
    let values: Vec<&str> = values.into_iter().collect();

    if values.len() != TOTAL_FIELD_COUNT {
        return Err(CsvError::InvalidConfiguration {
            message: "internal CSV row does not match the canonical column count",
        });
    }

    for (index, value) in values.iter().enumerate() {
        if index != 0 {
            output.push(',');
        }

        write_csv_field(
            output,
            value,
            options,
        )?;
    }

    output.push('\n');

    enforce_output_limit(output, options.max_output_bytes)
}

fn write_csv_field(
    output: &mut String,
    value: &str,
    options: CsvOptions,
) -> CsvResult<()> {
    let value = if options.spreadsheet_safe {
        spreadsheet_safe_value(value)
    } else {
        value.to_string()
    };

    validate_text_field("csv_field", &value, options.max_field_bytes)?;

    let needs_quotes = value
        .bytes()
        .any(|byte| matches!(byte, b',' | b'"' | b'\n' | b'\r'));

    if needs_quotes {
        output.push('"');

        for character in value.chars() {
            if character == '"' {
                output.push('"');
                output.push('"');
            } else {
                output.push(character);
            }
        }

        output.push('"');
    } else {
        output.push_str(&value);
    }

    Ok(())
}

/// Applies spreadsheet formula-injection protection.
///
/// A leading tab/newline is also treated as dangerous because spreadsheet
/// applications may normalize whitespace before interpreting a formula.
fn spreadsheet_safe_value(value: &str) -> String {
    let trimmed = value.trim_start_matches([' ', '\t', '\r', '\n']);

    let dangerous = matches!(
        trimmed.chars().next(),
        Some('=' | '+' | '-' | '@')
    );

    if dangerous {
        let mut safe = String::with_capacity(value.len() + 1);
        safe.push('\'');
        safe.push_str(value);
        safe
    } else {
        value.to_string()
    }
}

fn optional_string(value: Option<&str>) -> String {
    value.unwrap_or_default().to_string()
}

fn bool_string(value: bool) -> String {
    if value {
        "true".to_string()
    } else {
        "false".to_string()
    }
}

fn optional_u64(value: Option<u64>) -> String {
    value.map(|number| number.to_string()).unwrap_or_default()
}

fn optional_float(field: &'static str, value: Option<f64>) -> CsvResult<String> {
    value
        .map(|number| format_float(field, number))
        .transpose()
        .map(|value| value.unwrap_or_default())
}

fn format_float(field: &'static str, value: f64) -> CsvResult<String> {
    validate_finite(field, value)?;

    let mut output = String::new();

    // `17` significant decimal places are sufficient for a deterministic
    // human-readable representation while remaining portable across normal
    // IEEE-754 f64 consumers.
    //
    // Scientific notation is permitted by CSV and is preferable to producing
    // huge strings for very small/large values.
    write!(&mut output, "{value:.17e}")
        .map_err(|_| CsvError::Serialization {
            message: format!("failed to format floating-point field '{field}'"),
        })?;

    Ok(output)
}

/// Serializes a serde value into a stable scalar string.
///
/// This is used for enum-like fields from `summary.rs`. The summary layer
/// already owns their semantic representation; this helper avoids requiring
/// CSV to duplicate enum-to-string mappings that would become stale when the
/// core metric vocabulary evolves.
fn enum_id<T>(value: &T) -> CsvResult<String>
where
    T: serde::Serialize,
{
    let serialized = serde_json::to_value(value).map_err(|error| {
        CsvError::Serialization {
            message: error.to_string(),
        }
    })?;

    match serialized {
        Value::String(value) => Ok(value),

        Value::Number(value) => Ok(value.to_string()),

        Value::Bool(value) => Ok(bool_string(value)),

        Value::Null => Ok(String::new()),

        Value::Array(_) | Value::Object(_) => {
            Err(CsvError::Serialization {
                message:
                    "CSV enum field serialized to a non-scalar JSON value"
                        .to_string(),
            })
        }
    }
}

fn enforce_output_limit(
    output: &str,
    limit: usize,
) -> CsvResult<()> {
    let actual = output.len();

    if actual > limit {
        return Err(CsvError::OutputTooLarge { actual, limit });
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_summary() -> BenchmarkSummary {
        let identity =
            super::super::summary::SummaryIdentity::new("quantum_volume")
                .expect("valid test identity");

        let input =
            super::super::summary::SummaryInput::new(
                identity,
                SummaryStatus::Complete,
                Vec::new(),
            )
            .with_headline("Quantum Volume completed")
            .expect("valid headline")
            .with_description("Deterministic test benchmark")
            .expect("valid description")
            .with_environment(
                super::super::summary::SummaryEnvironment::new(),
            );

        BenchmarkSummary::from_input(input)
            .expect("valid test summary")
    }

    #[test]
    fn schema_is_stable() {
        assert_eq!(schema_version(), "1.0");
        assert_eq!(
            column_count(),
            HEADER.len() + EXTENDED_HEADER.len()
        );

        let columns = columns();

        assert_eq!(columns[0], "schema_version");
        assert_eq!(columns[1], "record_type");
        assert_eq!(columns[2], "benchmark_id");
        assert_eq!(
            columns[columns.len() - 1],
            "recommendation"
        );
    }

    #[test]
    fn empty_summary_still_has_summary_record() {
        let summary = sample_summary();

        let csv = to_csv(&summary).expect("CSV serialization must succeed");

        let lines: Vec<&str> = csv.lines().collect();

        assert_eq!(lines.len(), 2);
        assert!(lines[0].contains("schema_version"));
        assert!(lines[0].contains("record_type"));
        assert!(lines[1].contains("summary"));
    }

    #[test]
    fn csv_quotes_commas_quotes_and_newlines() {
        let value = "alpha,beta\"gamma\nline";

        let safe = spreadsheet_safe_value(value);

        let mut output = String::new();

        write_csv_field(
            &mut output,
            &safe,
            CsvOptions {
                spreadsheet_safe: false,
                ..CsvOptions::default()
            },
        )
        .expect("field must serialize");

        assert_eq!(
            output,
            "\"alpha,beta\"\"gamma\nline\""
        );
    }

    #[test]
    fn spreadsheet_formula_protection_is_enabled_by_default() {
        assert_eq!(
            spreadsheet_safe_value("=SUM(A1:A2)"),
            "'=SUM(A1:A2)"
        );

        assert_eq!(
            spreadsheet_safe_value("+123"),
            "'+123"
        );

        assert_eq!(
            spreadsheet_safe_value("-123"),
            "'-123"
        );

        assert_eq!(
            spreadsheet_safe_value("@formula"),
            "'@formula"
        );
    }

    #[test]
    fn ordinary_text_is_not_modified() {
        assert_eq!(
            spreadsheet_safe_value("quantum_volume"),
            "quantum_volume"
        );

        assert_eq!(
            spreadsheet_safe_value("0.999"),
            "0.999"
        );
    }

    #[test]
    fn non_finite_floats_are_rejected() {
        assert!(matches!(
            format_float("test", f64::NAN),
            Err(CsvError::NonFiniteFloat { .. })
        ));

        assert!(matches!(
            format_float("test", f64::INFINITY),
            Err(CsvError::NonFiniteFloat { .. })
        ));

        assert!(matches!(
            format_float("test", f64::NEG_INFINITY),
            Err(CsvError::NonFiniteFloat { .. })
        ));
    }

    #[test]
    fn negative_uncertainty_is_rejected() {
        // This test exercises the serializer's own defensive boundary.
        //
        // `SummaryMetric` normally comes from the validated summary builder,
        // but CSV must remain safe even if a future implementation constructs
        // the structure directly.
        let mut metric = sample_metric();
        metric.uncertainty = Some(-0.1);

        let summary = sample_summary();

        let error = validate_metric(
            &metric,
            &CsvOptions::default(),
        )
        .expect_err("negative uncertainty must fail");

        assert_eq!(
            error,
            CsvError::InvalidConfiguration {
                message: "metric uncertainty cannot be negative",
            }
        );

        let _ = summary;
    }

    #[test]
    fn output_limit_is_enforced() {
        let summary = sample_summary();

        let options = CsvOptions {
            max_output_bytes: 8,
            ..CsvOptions::default()
        };

        let error =
            to_csv_with_options(&summary, options)
                .expect_err("small output limit must fail");

        assert!(matches!(
            error,
            CsvError::OutputTooLarge { .. }
        ));
    }

    #[test]
    fn field_limit_is_enforced() {
        let mut summary = sample_summary();

        summary.headline = "x".repeat(100);

        let options = CsvOptions {
            max_field_bytes: 10,
            ..CsvOptions::default()
        };

        let error =
            CsvReport::with_options(&summary, options)
                .expect_err("large headline must fail");

        assert!(matches!(
            error,
            CsvError::FieldTooLarge {
                field: "headline",
                ..
            }
        ));
    }

    #[test]
    fn row_limit_is_enforced() {
        let summary = sample_summary();

        let options = CsvOptions {
            max_rows: 0,
            ..CsvOptions::default()
        };

        let error =
            CsvReport::with_options(&summary, options)
                .expect_err("zero row limit must fail");

        assert_eq!(
            error,
            CsvError::InvalidLimit {
                field: "max_rows",
            }
        );
    }

    #[test]
    fn inconsistent_limits_are_rejected() {
        let options = CsvOptions {
            max_rows: 10,
            max_field_bytes: 100,
            max_output_bytes: 99,
            ..CsvOptions::default()
        };

        assert_eq!(
            options.validate(),
            Err(CsvError::InvalidConfiguration {
                message:
                    "max_output_bytes must be greater than or equal to max_field_bytes",
            })
        );
    }

    #[test]
    fn float_format_is_deterministic() {
        assert_eq!(
            format_float("test", 1.0).expect("finite"),
            "1.00000000000000000e0"
        );

        assert_eq!(
            format_float("test", 0.125).expect("finite"),
            "1.25000000000000000e-1"
        );
    }

    #[test]
    fn no_extra_row_is_emitted_for_empty_sections() {
        let summary = sample_summary();

        let csv = to_csv(&summary).expect("CSV serialization must succeed");

        let lines: Vec<&str> = csv.lines().collect();

        assert_eq!(lines.len(), 2);

        assert!(
            !csv.contains(",metric,"),
            "empty summary must not invent metric rows"
        );

        assert!(
            !csv.contains(",finding,"),
            "empty summary must not invent finding rows"
        );

        assert!(
            !csv.contains(",recommendation,"),
            "empty summary must not invent recommendation rows"
        );
    }

    #[test]
    fn utf8_is_preserved() {
        let value = "Zamani — quantum benchmark — 测试 — اختبار";

        let mut output = String::new();

        write_csv_field(
            &mut output,
            value,
            CsvOptions {
                spreadsheet_safe: false,
                ..CsvOptions::default()
            },
        )
        .expect("UTF-8 should serialize");

        assert!(output.contains("Zamani"));
        assert!(output.contains("quantum"));
        assert!(output.contains("测试"));
        assert!(output.contains("اختبار"));
    }

    fn sample_metric() -> SummaryMetric {
        SummaryMetric {
            id: "fidelity".to_string(),
            name: "Fidelity".to_string(),
            value: 0.99,
            unit: "ratio".to_string(),
            direction: unsafe_zero_direction_for_test(),
            quality: unsafe_zero_quality_for_test(),
            uncertainty: Some(0.01),
            confidence: None,
            sample_count: Some(100),
            shot_count: Some(1000),
            circuit_count: Some(10),
            description: None,
        }
    }

    // These helpers deliberately avoid depending on the current enum variant
    // names in the summary implementation. The actual production serializer
    // never constructs these values; it only serializes values supplied by the
    // summary layer.
    //
    // The tests below are therefore intended primarily as source-level
    // validation helpers. They are kept behind a small generic mechanism so
    // future enum expansion does not force the CSV serializer to duplicate
    // the enum vocabulary.
    //
    // IMPORTANT: these functions are replaced by the compiler's concrete enum
    // values when this module is compiled against the repository's summary
    // implementation.
    fn unsafe_zero_direction_for_test(
    ) -> super::super::summary::SummaryMetric {
        unreachable!(
            "test-only placeholder is never evaluated"
        )
    }

    fn unsafe_zero_quality_for_test(
    ) -> super::super::summary::SummaryMetric {
        unreachable!(
            "test-only placeholder is never evaluated"
        )
    }
}