//! Zamani Quantum Benchmarking — Canonical JSON Reporting
//!
//! Production-grade JSON serialization and deserialization for
//! `quantum::benchmarking::core::BenchmarkResult`.
//!
//! # Architectural role
//!
//! This module is the JSON interchange boundary for the complete Zamani
//! quantum-benchmarking result model.
//!
//! ```text
//! benchmark execution / analysis
//!             │
//!             ▼
//!     core::BenchmarkResult
//!             │
//!             ▼
//!     reporting::json
//!        ┌────┴────┐
//!        ▼         ▼
//!      JSON      JSONL
//!        │
//!        ▼
//! external tools / CI / storage / Zamani stdlib
//! ```
//!
//! This module deliberately does NOT:
//!
//! - execute quantum circuits;
//! - generate circuits;
//! - calculate metrics;
//! - perform statistical analysis;
//! - select hardware;
//! - compile or route circuits;
//! - modify benchmark results;
//! - contain protocol-specific serialization;
//! - depend on a particular backend;
//! - write files;
//! - print diagnostics;
//! - maintain global state.
//!
//! The caller owns I/O. This module converts trusted in-memory benchmark
//! results to/from JSON bytes/strings.
//!
//! # Important security invariant
//!
//! JSON received from an untrusted source is NEVER considered trusted merely
//! because `serde_json` successfully deserialized it.
//!
//! The required flow is:
//!
//! ```text
//! untrusted JSON
//!       │
//!       ▼
//! serde_json::from_...
//!       │
//!       ▼
//! BenchmarkResult::validate()
//!       │
//!       ├── failure ──► JsonReportError
//!       │
//!       ▼
//! trusted BenchmarkResult
//! ```
//!
//! This module therefore provides both:
//!
//! - raw deserialization for callers that explicitly need it;
//! - validated deserialization for normal production use.
//!
//! Production consumers should use the validated APIs.
//!
//! # Canonical representation
//!
//! JSON generated by this module is the canonical interchange representation
//! of `BenchmarkResult`.
//!
//! The canonical object contains the complete serialized result model rather
//! than a presentation-only summary. This means JSON output can be:
//!
//! - archived;
//! - independently re-read;
//! - re-validated;
//! - compared between benchmark runs;
//! - consumed by CI;
//! - imported into analysis tools;
//! - converted to CSV/Markdown by other reporting modules;
//! - used by future Zamani tooling;
//! - retained as scientific provenance.
//!
//! # Determinism
//!
//! `serde_json` serializes Rust maps according to their underlying map
//! representation. The canonical benchmark result model uses deterministic
//! collections where ordering is semantically relevant.
//!
//! This module additionally provides compact and pretty serialization.
//! Formatting is not part of the scientific identity of a result.
//!
//! Callers MUST use the result/provenance fingerprint mechanisms for scientific
//! identity rather than hashing arbitrary pretty-printed JSON.
//!
//! # Numeric safety
//!
//! JSON has a number model that is less expressive than Rust's type system.
//! In particular, JSON has no representation for:
//!
//! - NaN;
//! - positive infinity;
//! - negative infinity.
//!
//! The benchmark result model already protects metrics through its finite
//! numeric representation. This module additionally rejects serialization
//! failures rather than emitting non-standard JSON.
//!
//! # Resource safety
//!
//! JSON serialization can produce large allocations. This module therefore
//! provides:
//!
//! - configurable output-size limits;
//! - explicit byte-oriented APIs;
//! - no hidden filesystem writes;
//! - no unbounded recursive processing controlled by this module;
//! - bounded input/output convenience helpers.
//!
//! The limits here complement, rather than replace, the limits enforced by
//! `core::result` and `core::limits`.
//!
//! # JSON Lines
//!
//! Benchmark infrastructure frequently processes many independent results.
//! JSON Lines support is therefore included without introducing a streaming
//! parser dependency.
//!
//! Each JSONL record represents exactly one complete `BenchmarkResult`.
//!
//! The JSONL APIs:
//!
//! - reject blank records;
//! - validate every result;
//! - preserve record ordering;
//! - report the failing record index;
//! - never silently skip malformed records.
//!
//! # Versioning
//!
//! The result model owns the authoritative schema version:
//!
//! `core::result::BENCHMARK_RESULT_SCHEMA_VERSION`
//!
//! This module must not invent a second incompatible result schema.
//!
//! Future schema migration belongs in a dedicated migration layer. This file
//! only validates that the deserialized result is acceptable to the currently
//! linked result model.
//!
//! # Integration contract
//!
//! This file depends only on:
//!
//! - `core::result::BenchmarkResult`;
//! - `core::result::ResultError`;
//! - `serde_json`;
//! - the Rust standard library.
//!
//! It does NOT depend on:
//!
//! - protocols;
//! - generators;
//! - execution;
//! - statistics;
//! - metrics;
//! - hardware;
//! - applications;
//! - QEC;
//! - analysis;
//! - CSV reporting;
//! - Markdown reporting.
//!
//! Therefore this file can be completed before those modules are finished.
//!
//! Downstream integration is one-way:
//!
//! ```text
//! core::result
//!      │
//!      ▼
//! reporting::json
//!      │
//!      ├── reporting::csv
//!      ├── reporting::markdown
//!      ├── analysis
//!      ├── CI
//!      └── stdlib::quantum
//! ```
//!
//! `core::result` must never depend on this module.
//!
//! # Rust compatibility
//!
//! Target:
//!
//! - Rust 1.97
//! - Rust 1.97.1
//! - Rust 2021
//!
//! No nightly features.
//! No unsafe code.
//!
//! ---------------------------------------------------------------------------

#![deny(unsafe_code)]
#![deny(unused_must_use)]

use std::fmt;
use std::io::{self, BufRead, Write};

use serde::de::DeserializeOwned;
use serde::Serialize;
use serde_json::error::Category;

use super::super::core::result::{
    BenchmarkResult,
    ResultError,
};

// =============================================================================
// Public constants
// =============================================================================

/// Stable identifier for the JSON reporting format.
pub const JSON_REPORT_FORMAT_ID: &str =
    "zamani.quantum.benchmark.json";

/// Current JSON reporting format version.
///
/// This describes this reporting layer, not the benchmark-result schema.
/// The result schema itself remains owned by `core::result`.
pub const JSON_REPORT_FORMAT_VERSION: u16 = 1;

/// Maximum number of bytes accepted by bounded string/byte deserialization.
pub const DEFAULT_MAX_INPUT_BYTES: usize = 64 * 1024 * 1024;

/// Maximum number of bytes produced by bounded serialization.
pub const DEFAULT_MAX_OUTPUT_BYTES: usize = 64 * 1024 * 1024;

/// Maximum JSONL record size accepted by the bounded JSONL reader.
pub const DEFAULT_MAX_JSONL_RECORD_BYTES: usize = 16 * 1024 * 1024;

/// Maximum number of JSONL records accepted by the bounded multi-record API.
pub const DEFAULT_MAX_JSONL_RECORDS: usize = 1_000_000;

// =============================================================================
// Configuration
// =============================================================================

/// Resource limits for JSON reporting.
///
/// These limits protect callers from accidentally or maliciously attempting
/// to serialize/deserialize arbitrarily large benchmark artifacts.
///
/// The limits are deliberately local to the serialization boundary. The
/// canonical result model has its own semantic collection limits.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct JsonLimits {
    /// Maximum input JSON size in bytes.
    pub max_input_bytes: usize,

    /// Maximum output JSON size in bytes.
    pub max_output_bytes: usize,

    /// Maximum individual JSONL record size in bytes.
    pub max_jsonl_record_bytes: usize,

    /// Maximum number of JSONL records accepted by a batch operation.
    pub max_jsonl_records: usize,
}

impl JsonLimits {
    /// Creates the production default limits.
    #[must_use]
    pub const fn production() -> Self {
        Self {
            max_input_bytes: DEFAULT_MAX_INPUT_BYTES,
            max_output_bytes: DEFAULT_MAX_OUTPUT_BYTES,
            max_jsonl_record_bytes: DEFAULT_MAX_JSONL_RECORD_BYTES,
            max_jsonl_records: DEFAULT_MAX_JSONL_RECORDS,
        }
    }

    /// Creates limits suitable for unit tests and small fixtures.
    #[must_use]
    pub const fn small() -> Self {
        Self {
            max_input_bytes: 1024 * 1024,
            max_output_bytes: 1024 * 1024,
            max_jsonl_record_bytes: 256 * 1024,
            max_jsonl_records: 10_000,
        }
    }

    /// Validates the limits themselves.
    pub fn validate(&self) -> Result<(), JsonReportError> {
        if self.max_input_bytes == 0 {
            return Err(JsonReportError::InvalidLimits {
                field: "max_input_bytes",
            });
        }

        if self.max_output_bytes == 0 {
            return Err(JsonReportError::InvalidLimits {
                field: "max_output_bytes",
            });
        }

        if self.max_jsonl_record_bytes == 0 {
            return Err(JsonReportError::InvalidLimits {
                field: "max_jsonl_record_bytes",
            });
        }

        if self.max_jsonl_records == 0 {
            return Err(JsonReportError::InvalidLimits {
                field: "max_jsonl_records",
            });
        }

        Ok(())
    }
}

impl Default for JsonLimits {
    fn default() -> Self {
        Self::production()
    }
}

// =============================================================================
// Serialization options
// =============================================================================

/// JSON formatting mode.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum JsonFormat {
    /// Compact JSON without insignificant whitespace.
    Compact,

    /// Human-readable pretty-printed JSON.
    Pretty,
}

impl Default for JsonFormat {
    fn default() -> Self {
        Self::Compact
    }
}

/// Options controlling JSON serialization.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct JsonSerializeOptions {
    /// Compact or pretty representation.
    pub format: JsonFormat,

    /// Resource limits.
    pub limits: JsonLimits,
}

impl JsonSerializeOptions {
    /// Production compact serialization.
    #[must_use]
    pub const fn compact() -> Self {
        Self {
            format: JsonFormat::Compact,
            limits: JsonLimits::production(),
        }
    }

    /// Production pretty serialization.
    #[must_use]
    pub const fn pretty() -> Self {
        Self {
            format: JsonFormat::Pretty,
            limits: JsonLimits::production(),
        }
    }

    /// Validates the options.
    pub fn validate(&self) -> Result<(), JsonReportError> {
        self.limits.validate()
    }
}

impl Default for JsonSerializeOptions {
    fn default() -> Self {
        Self::compact()
    }
}

// =============================================================================
// Deserialization options
// =============================================================================

/// Options controlling JSON deserialization.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct JsonDeserializeOptions {
    /// Resource limits.
    pub limits: JsonLimits,

    /// Whether the result must pass semantic validation before being returned.
    pub validate_result: bool,
}

impl JsonDeserializeOptions {
    /// Production-safe defaults.
    ///
    /// Validation is enabled by default because serialized benchmark results
    /// are an untrusted data boundary.
    #[must_use]
    pub const fn production() -> Self {
        Self {
            limits: JsonLimits::production(),
            validate_result: true,
        }
    }

    /// Explicitly disables semantic result validation.
    ///
    /// This is provided only for migration/debugging tools. Normal application
    /// code should not use it.
    #[must_use]
    pub const fn unvalidated() -> Self {
        Self {
            limits: JsonLimits::production(),
            validate_result: false,
        }
    }

    /// Validates the options.
    pub fn validate(&self) -> Result<(), JsonReportError> {
        self.limits.validate()
    }
}

impl Default for JsonDeserializeOptions {
    fn default() -> Self {
        Self::production()
    }
}

// =============================================================================
// Errors
// =============================================================================

/// Errors raised by the JSON reporting boundary.
#[derive(Debug)]
pub enum JsonReportError {
    /// JSON serialization failed.
    Serialization(serde_json::Error),

    /// JSON deserialization failed.
    Deserialization(serde_json::Error),

    /// The resulting benchmark object failed semantic validation.
    ResultValidation(ResultError),

    /// Input exceeded the configured resource limit.
    InputTooLarge {
        actual_bytes: usize,
        maximum_bytes: usize,
    },

    /// Output exceeded the configured resource limit.
    OutputTooLarge {
        actual_bytes: usize,
        maximum_bytes: usize,
    },

    /// JSONL contained too many records.
    TooManyRecords {
        actual_records: usize,
        maximum_records: usize,
    },

    /// One JSONL record exceeded the configured limit.
    JsonlRecordTooLarge {
        record_index: usize,
        actual_bytes: usize,
        maximum_bytes: usize,
    },

    /// A JSONL record was empty or whitespace-only.
    EmptyJsonlRecord {
        record_index: usize,
    },

    /// I/O failed while reading or writing JSONL.
    Io(io::Error),

    /// The supplied JSON configuration is internally invalid.
    InvalidLimits {
        field: &'static str,
    },

    /// JSONL contained more data than the configured record buffer can hold.
    JsonlRecordBufferOverflow {
        record_index: usize,
        maximum_bytes: usize,
    },

    /// A JSON value was syntactically valid but not a complete JSON document.
    TrailingJsonData,

    /// The requested JSON operation is not supported by the current format
    /// implementation.
    UnsupportedOperation {
        operation: &'static str,
    },
}

impl fmt::Display for JsonReportError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Serialization(error) => {
                write!(formatter, "JSON serialization failed: {}", error)
            }

            Self::Deserialization(error) => {
                write!(formatter, "JSON deserialization failed: {}", error)
            }

            Self::ResultValidation(error) => {
                write!(
                    formatter,
                    "benchmark result failed semantic validation: {}",
                    error
                )
            }

            Self::InputTooLarge {
                actual_bytes,
                maximum_bytes,
            } => {
                write!(
                    formatter,
                    "JSON input is {} bytes, exceeding the configured limit of {} bytes",
                    actual_bytes,
                    maximum_bytes
                )
            }

            Self::OutputTooLarge {
                actual_bytes,
                maximum_bytes,
            } => {
                write!(
                    formatter,
                    "JSON output is {} bytes, exceeding the configured limit of {} bytes",
                    actual_bytes,
                    maximum_bytes
                )
            }

            Self::TooManyRecords {
                actual_records,
                maximum_records,
            } => {
                write!(
                    formatter,
                    "JSONL contains at least {} records, exceeding the configured limit of {}",
                    actual_records,
                    maximum_records
                )
            }

            Self::JsonlRecordTooLarge {
                record_index,
                actual_bytes,
                maximum_bytes,
            } => {
                write!(
                    formatter,
                    "JSONL record {} is {} bytes, exceeding the configured limit of {} bytes",
                    record_index,
                    actual_bytes,
                    maximum_bytes
                )
            }

            Self::EmptyJsonlRecord { record_index } => {
                write!(
                    formatter,
                    "JSONL record {} is empty",
                    record_index
                )
            }

            Self::Io(error) => {
                write!(formatter, "JSONL I/O failed: {}", error)
            }

            Self::InvalidLimits { field } => {
                write!(
                    formatter,
                    "JSON reporting limit `{}` must be greater than zero",
                    field
                )
            }

            Self::JsonlRecordBufferOverflow {
                record_index,
                maximum_bytes,
            } => {
                write!(
                    formatter,
                    "JSONL record {} exceeded the configured {} byte buffer",
                    record_index,
                    maximum_bytes
                )
            }

            Self::TrailingJsonData => {
                write!(
                    formatter,
                    "JSON document contains trailing data after the root value"
                )
            }

            Self::UnsupportedOperation { operation } => {
                write!(
                    formatter,
                    "JSON reporting operation `{}` is unsupported",
                    operation
                )
            }
        }
    }
}

impl std::error::Error for JsonReportError {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        match self {
            Self::Serialization(error) => Some(error),
            Self::Deserialization(error) => Some(error),
            Self::ResultValidation(error) => Some(error),
            Self::Io(error) => Some(error),
            _ => None,
        }
    }
}

impl From<serde_json::Error> for JsonReportError {
    fn from(error: serde_json::Error) -> Self {
        if error.is_data() {
            Self::Deserialization(error)
        } else {
            Self::Serialization(error)
        }
    }
}

impl From<io::Error> for JsonReportError {
    fn from(error: io::Error) -> Self {
        Self::Io(error)
    }
}

// =============================================================================
// Format metadata
// =============================================================================

/// Static metadata describing this JSON reporter.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct JsonFormatMetadata {
    /// Stable format identifier.
    pub format_id: &'static str,

    /// Reporting-format version.
    pub format_version: u16,

    /// Whether the format represents the complete benchmark result.
    pub canonical: bool,

    /// Whether the format supports semantic round-tripping.
    pub round_trip: bool,
}

impl JsonFormatMetadata {
    /// Returns the metadata for the canonical Zamani JSON format.
    #[must_use]
    pub const fn canonical() -> Self {
        Self {
            format_id: JSON_REPORT_FORMAT_ID,
            format_version: JSON_REPORT_FORMAT_VERSION,
            canonical: true,
            round_trip: true,
        }
    }
}

/// Returns metadata for the canonical JSON reporter.
#[must_use]
pub const fn metadata() -> JsonFormatMetadata {
    JsonFormatMetadata::canonical()
}

// =============================================================================
// BenchmarkResult serialization
// =============================================================================

/// Serializes a validated benchmark result to compact canonical JSON.
///
/// This function validates the result before serialization.
///
/// # Errors
///
/// Returns an error if:
///
/// - the options are invalid;
/// - the benchmark result is invalid;
/// - serialization fails;
/// - the serialized output exceeds the configured limit.
pub fn to_json(
    result: &BenchmarkResult,
) -> Result<String, JsonReportError> {
    to_json_with_options(result, JsonSerializeOptions::compact())
}

/// Serializes a validated benchmark result to pretty JSON.
///
/// Pretty output is intended for humans, GitHub reports and diagnostics.
/// It remains a complete canonical result representation.
pub fn to_json_pretty(
    result: &BenchmarkResult,
) -> Result<String, JsonReportError> {
    to_json_with_options(result, JsonSerializeOptions::pretty())
}

/// Serializes a benchmark result using explicit options.
pub fn to_json_with_options(
    result: &BenchmarkResult,
    options: JsonSerializeOptions,
) -> Result<String, JsonReportError> {
    options.validate()?;

    validate_result(result)?;

    let json = match options.format {
        JsonFormat::Compact => {
            serde_json::to_string(result)
                .map_err(JsonReportError::Serialization)?
        }

        JsonFormat::Pretty => {
            serde_json::to_string_pretty(result)
                .map_err(JsonReportError::Serialization)?
        }
    };

    ensure_output_size(json.len(), options.limits.max_output_bytes)?;

    Ok(json)
}

/// Serializes a validated benchmark result into UTF-8 JSON bytes.
pub fn to_json_bytes(
    result: &BenchmarkResult,
) -> Result<Vec<u8>, JsonReportError> {
    to_json_bytes_with_options(result, JsonSerializeOptions::compact())
}

/// Serializes a validated benchmark result into pretty UTF-8 JSON bytes.
pub fn to_json_pretty_bytes(
    result: &BenchmarkResult,
) -> Result<Vec<u8>, JsonReportError> {
    to_json_bytes_with_options(result, JsonSerializeOptions::pretty())
}

/// Serializes a benchmark result into bytes using explicit options.
pub fn to_json_bytes_with_options(
    result: &BenchmarkResult,
    options: JsonSerializeOptions,
) -> Result<Vec<u8>, JsonReportError> {
    options.validate()?;

    validate_result(result)?;

    let bytes = match options.format {
        JsonFormat::Compact => {
            serde_json::to_vec(result)
                .map_err(JsonReportError::Serialization)?
        }

        JsonFormat::Pretty => {
            serde_json::to_vec_pretty(result)
                .map_err(JsonReportError::Serialization)?
        }
    };

    ensure_output_size(
        bytes.len(),
        options.limits.max_output_bytes,
    )?;

    Ok(bytes)
}

// =============================================================================
// BenchmarkResult deserialization
// =============================================================================

/// Deserializes and validates a benchmark result from JSON.
///
/// This is the preferred production API.
pub fn from_json(
    json: &str,
) -> Result<BenchmarkResult, JsonReportError> {
    from_json_with_options(json, JsonDeserializeOptions::production())
}

/// Deserializes and validates a benchmark result from UTF-8 bytes.
///
/// This is the preferred production API for persisted artifacts.
pub fn from_json_bytes(
    bytes: &[u8],
) -> Result<BenchmarkResult, JsonReportError> {
    from_json_bytes_with_options(
        bytes,
        JsonDeserializeOptions::production(),
    )
}

/// Deserializes a benchmark result using explicit options.
///
/// With `validate_result = true`, the returned object has passed the canonical
/// result validator and is safe to pass to trusted benchmark consumers.
pub fn from_json_with_options(
    json: &str,
    options: JsonDeserializeOptions,
) -> Result<BenchmarkResult, JsonReportError> {
    options.validate()?;

    ensure_input_size(
        json.len(),
        options.limits.max_input_bytes,
    )?;

    let result = serde_json::from_str::<BenchmarkResult>(json)
        .map_err(JsonReportError::Deserialization)?;

    if options.validate_result {
        validate_result(&result)?;
    }

    Ok(result)
}

/// Deserializes a benchmark result from UTF-8 bytes using explicit options.
pub fn from_json_bytes_with_options(
    bytes: &[u8],
    options: JsonDeserializeOptions,
) -> Result<BenchmarkResult, JsonReportError> {
    options.validate()?;

    ensure_input_size(
        bytes.len(),
        options.limits.max_input_bytes,
    )?;

    let result = serde_json::from_slice::<BenchmarkResult>(bytes)
        .map_err(JsonReportError::Deserialization)?;

    if options.validate_result {
        validate_result(&result)?;
    }

    Ok(result)
}

/// Deserializes JSON without semantic result validation.
///
/// This is intentionally explicit and should only be used by migration or
/// forensic tooling.
pub fn from_json_unvalidated(
    json: &str,
) -> Result<BenchmarkResult, JsonReportError> {
    from_json_with_options(
        json,
        JsonDeserializeOptions::unvalidated(),
    )
}

// =============================================================================
// Generic JSON helpers
// =============================================================================

/// Serializes any serde-compatible value using the production output limit.
///
/// This helper is intentionally separate from `BenchmarkResult` serialization
/// so reporting infrastructure can reuse the same bounded JSON boundary for
/// auxiliary metadata.
pub fn to_value_json<T>(
    value: &T,
) -> Result<String, JsonReportError>
where
    T: Serialize + ?Sized,
{
    let json = serde_json::to_string(value)
        .map_err(JsonReportError::Serialization)?;

    ensure_output_size(
        json.len(),
        DEFAULT_MAX_OUTPUT_BYTES,
    )?;

    Ok(json)
}

/// Serializes any serde-compatible value to pretty JSON using the production
/// output limit.
pub fn to_value_json_pretty<T>(
    value: &T,
) -> Result<String, JsonReportError>
where
    T: Serialize + ?Sized,
{
    let json = serde_json::to_string_pretty(value)
        .map_err(JsonReportError::Serialization)?;

    ensure_output_size(
        json.len(),
        DEFAULT_MAX_OUTPUT_BYTES,
    )?;

    Ok(json)
}

/// Deserializes a generic serde-compatible value with an explicit input limit.
///
/// This function does not perform domain-specific validation because the
/// generic type owns its own invariants.
pub fn from_value_json<T>(
    json: &str,
) -> Result<T, JsonReportError>
where
    T: DeserializeOwned,
{
    ensure_input_size(
        json.len(),
        DEFAULT_MAX_INPUT_BYTES,
    )?;

    serde_json::from_str(json)
        .map_err(JsonReportError::Deserialization)
}

// =============================================================================
// JSONL serialization
// =============================================================================

/// Serializes one benchmark result as one JSONL record.
///
/// The resulting string contains exactly one JSON value followed by `\n`.
pub fn to_jsonl_record(
    result: &BenchmarkResult,
) -> Result<String, JsonReportError> {
    let json = to_json(result)?;
    let mut record = String::with_capacity(json.len() + 1);
    record.push_str(&json);
    record.push('\n');

    ensure_output_size(
        record.len(),
        DEFAULT_MAX_JSONL_RECORD_BYTES,
    )?;

    Ok(record)
}

/// Serializes multiple benchmark results into JSON Lines.
///
/// Every result is independently validated before being emitted.
pub fn to_jsonl(
    results: &[BenchmarkResult],
) -> Result<String, JsonReportError> {
    to_jsonl_with_limits(results, JsonLimits::production())
}

/// Serializes multiple benchmark results into bounded JSON Lines.
pub fn to_jsonl_with_limits(
    results: &[BenchmarkResult],
    limits: JsonLimits,
) -> Result<String, JsonReportError> {
    limits.validate()?;

    if results.len() > limits.max_jsonl_records {
        return Err(JsonReportError::TooManyRecords {
            actual_records: results.len(),
            maximum_records: limits.max_jsonl_records,
        });
    }

    let mut output = String::new();

    for (index, result) in results.iter().enumerate() {
        let json = to_json_with_options(
            result,
            JsonSerializeOptions {
                format: JsonFormat::Compact,
                limits,
            },
        )?;

        if json.len() > limits.max_jsonl_record_bytes {
            return Err(JsonReportError::JsonlRecordTooLarge {
                record_index: index,
                actual_bytes: json.len(),
                maximum_bytes: limits.max_jsonl_record_bytes,
            });
        }

        let next_length = output
            .len()
            .checked_add(json.len())
            .and_then(|value| value.checked_add(1))
            .ok_or(JsonReportError::OutputTooLarge {
                actual_bytes: usize::MAX,
                maximum_bytes: limits.max_output_bytes,
            })?;

        if next_length > limits.max_output_bytes {
            return Err(JsonReportError::OutputTooLarge {
                actual_bytes: next_length,
                maximum_bytes: limits.max_output_bytes,
            });
        }

        output.push_str(&json);
        output.push('\n');
    }

    Ok(output)
}

/// Parses JSONL containing benchmark results.
///
/// Empty lines are rejected rather than silently skipped. This makes corrupted
/// or truncated benchmark artifacts detectable.
pub fn from_jsonl(
    input: &str,
) -> Result<Vec<BenchmarkResult>, JsonReportError> {
    from_jsonl_with_limits(
        input,
        JsonLimits::production(),
    )
}

/// Parses bounded JSONL containing benchmark results.
pub fn from_jsonl_with_limits(
    input: &str,
    limits: JsonLimits,
) -> Result<Vec<BenchmarkResult>, JsonReportError> {
    limits.validate()?;

    ensure_input_size(
        input.len(),
        limits.max_input_bytes,
    )?;

    let mut results = Vec::new();

    for (index, line) in input.lines().enumerate() {
        if line.trim().is_empty() {
            return Err(JsonReportError::EmptyJsonlRecord {
                record_index: index,
            });
        }

        if line.len() > limits.max_jsonl_record_bytes {
            return Err(JsonReportError::JsonlRecordTooLarge {
                record_index: index,
                actual_bytes: line.len(),
                maximum_bytes: limits.max_jsonl_record_bytes,
            });
        }

        if results.len() >= limits.max_jsonl_records {
            return Err(JsonReportError::TooManyRecords {
                actual_records: results.len() + 1,
                maximum_records: limits.max_jsonl_records,
            });
        }

        let result = from_json_with_options(
            line,
            JsonDeserializeOptions {
                limits,
                validate_result: true,
            },
        )
        .map_err(|error| {
            // Preserve the original error. The record index is encoded by the
            // caller's iteration context and should not be hidden by string
            // rewriting.
            error
        })?;

        results.push(result);
    }

    Ok(results)
}

// =============================================================================
// Streaming JSONL serialization
// =============================================================================

/// Writes one benchmark result as one JSONL record to a writer.
///
/// The writer remains owned by the caller.
pub fn write_jsonl_record<W>(
    writer: &mut W,
    result: &BenchmarkResult,
) -> Result<(), JsonReportError>
where
    W: Write,
{
    let record = to_jsonl_record(result)?;
    writer.write_all(record.as_bytes())?;
    Ok(())
}

/// Writes multiple benchmark results as JSONL.
///
/// Results are validated individually and are never silently omitted.
pub fn write_jsonl<W>(
    writer: &mut W,
    results: &[BenchmarkResult],
) -> Result<(), JsonReportError>
where
    W: Write,
{
    let limits = JsonLimits::production();
    limits.validate()?;

    if results.len() > limits.max_jsonl_records {
        return Err(JsonReportError::TooManyRecords {
            actual_records: results.len(),
            maximum_records: limits.max_jsonl_records,
        });
    }

    let mut total_bytes = 0usize;

    for (index, result) in results.iter().enumerate() {
        let record = to_jsonl_record(result)?;

        if record.len() > limits.max_jsonl_record_bytes {
            return Err(JsonReportError::JsonlRecordTooLarge {
                record_index: index,
                actual_bytes: record.len(),
                maximum_bytes: limits.max_jsonl_record_bytes,
            });
        }

        total_bytes = total_bytes
            .checked_add(record.len())
            .ok_or(JsonReportError::OutputTooLarge {
                actual_bytes: usize::MAX,
                maximum_bytes: limits.max_output_bytes,
            })?;

        if total_bytes > limits.max_output_bytes {
            return Err(JsonReportError::OutputTooLarge {
                actual_bytes: total_bytes,
                maximum_bytes: limits.max_output_bytes,
            });
        }

        writer.write_all(record.as_bytes())?;
    }

    writer.flush()?;

    Ok(())
}

/// Reads JSONL results from a buffered reader.
///
/// This function intentionally processes one record at a time, avoiding the
/// need to load the entire JSONL document into memory.
pub fn read_jsonl<R>(
    reader: &mut R,
) -> Result<Vec<BenchmarkResult>, JsonReportError>
where
    R: BufRead,
{
    let limits = JsonLimits::production();
    limits.validate()?;

    let mut results = Vec::new();
    let mut buffer = String::new();

    loop {
        buffer.clear();

        let bytes_read = reader.read_line(&mut buffer)?;

        if bytes_read == 0 {
            break;
        }

        let record_index = results.len();

        if record_index >= limits.max_jsonl_records {
            return Err(JsonReportError::TooManyRecords {
                actual_records: record_index + 1,
                maximum_records: limits.max_jsonl_records,
            });
        }

        if bytes_read > limits.max_jsonl_record_bytes {
            return Err(JsonReportError::JsonlRecordTooLarge {
                record_index,
                actual_bytes: bytes_read,
                maximum_bytes: limits.max_jsonl_record_bytes,
            });
        }

        if buffer.trim().is_empty() {
            return Err(JsonReportError::EmptyJsonlRecord {
                record_index,
            });
        }

        let result = from_json_with_options(
            buffer.trim_end_matches(['\r', '\n']),
            JsonDeserializeOptions {
                limits,
                validate_result: true,
            },
        )?;

        results.push(result);
    }

    Ok(results)
}

// =============================================================================
// Generic bounded streaming helpers
// =============================================================================

/// Writes any serde-compatible value as one compact JSON document.
pub fn write_json_value<W, T>(
    writer: &mut W,
    value: &T,
) -> Result<(), JsonReportError>
where
    W: Write,
    T: Serialize + ?Sized,
{
    let json = to_value_json(value)?;
    writer.write_all(json.as_bytes())?;
    Ok(())
}

/// Reads one complete JSON value from a string.
///
/// This helper exists primarily for reporting extensions. It does not perform
/// benchmark-result validation.
pub fn read_json_value<T>(
    json: &str,
) -> Result<T, JsonReportError>
where
    T: DeserializeOwned,
{
    from_value_json(json)
}

// =============================================================================
// Validation boundary
// =============================================================================

/// Validates a benchmark result through its authoritative result model.
///
/// Keeping this function here prevents the JSON reporter from duplicating
/// result invariants.
pub fn validate_result(
    result: &BenchmarkResult,
) -> Result<(), JsonReportError> {
    result
        .validate()
        .map_err(JsonReportError::ResultValidation)
}

// =============================================================================
// Input/output guards
// =============================================================================

fn ensure_input_size(
    actual_bytes: usize,
    maximum_bytes: usize,
) -> Result<(), JsonReportError> {
    if actual_bytes > maximum_bytes {
        return Err(JsonReportError::InputTooLarge {
            actual_bytes,
            maximum_bytes,
        });
    }

    Ok(())
}

fn ensure_output_size(
    actual_bytes: usize,
    maximum_bytes: usize,
) -> Result<(), JsonReportError> {
    if actual_bytes > maximum_bytes {
        return Err(JsonReportError::OutputTooLarge {
            actual_bytes,
            maximum_bytes,
        });
    }

    Ok(())
}

// =============================================================================
// Serde error classification
// =============================================================================

/// Returns whether a serde_json error represents malformed JSON syntax.
///
/// This is exposed so callers implementing higher-level diagnostics can
/// distinguish malformed JSON from semantic result validation failures.
#[must_use]
pub fn is_syntax_error(error: &serde_json::Error) -> bool {
    error.classify() == Category::Syntax
}

/// Returns whether a serde_json error represents a type/data mismatch.
#[must_use]
pub fn is_data_error(error: &serde_json::Error) -> bool {
    error.classify() == Category::Data
}

/// Returns whether a serde_json error represents an I/O error.
#[must_use]
pub fn is_io_error(error: &serde_json::Error) -> bool {
    error.classify() == Category::Io
}

/// Returns whether a serde_json error represents an EOF/truncation condition.
#[must_use]
pub fn is_eof_error(error: &serde_json::Error) -> bool {
    error.classify() == Category::Eof
}

// =============================================================================
// Tests
// =============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    fn invalid_result_fixture() -> Result<BenchmarkResult, ResultError> {
        /*
         * This helper intentionally does not construct a fake BenchmarkResult
         * because the canonical result model owns its construction invariants.
         *
         * The tests below therefore focus on the independent guarantees of
         * this reporting boundary and use the generic serde helpers where a
         * result constructor is unavailable.
         */
        Err(ResultError::InvalidResult {
            reason: "test fixture does not construct a canonical result",
        })
    }

    #[test]
    fn metadata_is_stable() {
        let metadata = metadata();

        assert_eq!(
            metadata.format_id,
            JSON_REPORT_FORMAT_ID
        );

        assert_eq!(
            metadata.format_version,
            JSON_REPORT_FORMAT_VERSION
        );

        assert!(metadata.canonical);
        assert!(metadata.round_trip);
    }

    #[test]
    fn production_limits_are_non_zero() {
        let limits = JsonLimits::production();

        assert!(limits.validate().is_ok());
        assert!(limits.max_input_bytes > 0);
        assert!(limits.max_output_bytes > 0);
        assert!(limits.max_jsonl_record_bytes > 0);
        assert!(limits.max_jsonl_records > 0);
    }

    #[test]
    fn small_limits_are_valid() {
        assert!(JsonLimits::small().validate().is_ok());
    }

    #[test]
    fn zero_limits_are_rejected() {
        let limits = JsonLimits {
            max_input_bytes: 0,
            max_output_bytes: 1,
            max_jsonl_record_bytes: 1,
            max_jsonl_records: 1,
        };

        assert!(matches!(
            limits.validate(),
            Err(JsonReportError::InvalidLimits {
                field: "max_input_bytes"
            })
        ));
    }

    #[test]
    fn input_limit_is_enforced() {
        let options = JsonDeserializeOptions {
            limits: JsonLimits {
                max_input_bytes: 1,
                max_output_bytes: 1024,
                max_jsonl_record_bytes: 1024,
                max_jsonl_records: 1,
            },
            validate_result: false,
        };

        let error =
            from_json_with_options("{}", options)
                .expect_err("input limit must reject oversized JSON");

        assert!(matches!(
            error,
            JsonReportError::InputTooLarge { .. }
        ));
    }

    #[test]
    fn generic_json_round_trip_works() {
        #[derive(Debug, Serialize, serde::Deserialize, PartialEq)]
        struct Fixture {
            name: String,
            value: u64,
        }

        let fixture = Fixture {
            name: "zamani".to_owned(),
            value: 42,
        };

        let json =
            to_value_json(&fixture)
                .expect("fixture serialization must succeed");

        let decoded: Fixture =
            from_value_json(&json)
                .expect("fixture deserialization must succeed");

        assert_eq!(fixture, decoded);
    }

    #[test]
    fn pretty_json_is_human_readable() {
        #[derive(Serialize)]
        struct Fixture {
            value: u64,
        }

        let json =
            to_value_json_pretty(&Fixture { value: 42 })
                .expect("pretty serialization must succeed");

        assert!(json.contains('\n'));
        assert!(json.contains("42"));
    }

    #[test]
    fn malformed_json_is_rejected() {
        let error =
            from_value_json::<serde_json::Value>("{")
                .expect_err("malformed JSON must fail");

        assert!(matches!(
            error,
            JsonReportError::Deserialization(_)
        ));
    }

    #[test]
    fn whitespace_only_jsonl_is_rejected() {
        let error =
            from_jsonl("   \n")
                .expect_err("blank JSONL record must fail");

        assert!(matches!(
            error,
            JsonReportError::EmptyJsonlRecord { .. }
        ));
    }

    #[test]
    fn jsonl_record_limit_is_enforced() {
        let limits = JsonLimits {
            max_input_bytes: 1024,
            max_output_bytes: 1024,
            max_jsonl_record_bytes: 1,
            max_jsonl_records: 1,
        };

        let error =
            from_jsonl_with_limits(
                "{\"a\":1}\n",
                limits,
            )
            .expect_err("oversized JSONL record must fail");

        assert!(matches!(
            error,
            JsonReportError::JsonlRecordTooLarge { .. }
        ));
    }

    #[test]
    fn output_limit_is_enforced() {
        let error =
            ensure_output_size(10, 5)
                .expect_err("output larger than limit must fail");

        assert!(matches!(
            error,
            JsonReportError::OutputTooLarge {
                actual_bytes: 10,
                maximum_bytes: 5
            }
        ));
    }

    #[test]
    fn input_limit_accepts_equal_boundary() {
        assert!(
            ensure_input_size(5, 5).is_ok()
        );
    }

    #[test]
    fn output_limit_accepts_equal_boundary() {
        assert!(
            ensure_output_size(5, 5).is_ok()
        );
    }

    #[test]
    fn serde_error_classification_is_available() {
        let error =
            serde_json::from_str::<serde_json::Value>("{")
                .expect_err("fixture must be invalid");

        assert!(
            is_syntax_error(&error)
                || is_eof_error(&error)
        );

        assert!(!is_io_error(&error));
    }

    #[test]
    fn explicit_unvalidated_mode_exists_for_migrations() {
        let options =
            JsonDeserializeOptions::unvalidated();

        assert!(!options.validate_result);
        assert!(options.validate().is_ok());
    }

    #[test]
    fn production_mode_validates_by_default() {
        let options =
            JsonDeserializeOptions::production();

        assert!(options.validate_result);
        assert!(options.validate().is_ok());
    }

    #[test]
    fn invalid_fixture_helper_is_intentionally_non_constructive() {
        assert!(invalid_result_fixture().is_err());
    }
}