//! Human- and machine-readable benchmark summaries.
//!
//! # Purpose
//!
//! `summary.rs` is the presentation-level summary model for Zamani's quantum
//! benchmarking subsystem. It converts already-computed benchmark metrics and
//! validation information into a deterministic, bounded, serializable summary.
//!
//! This module deliberately does NOT:
//!
//! - execute quantum circuits;
//! - generate benchmark circuits;
//! - perform statistical inference;
//! - recompute benchmark metrics;
//! - access quantum hardware;
//! - depend on a particular quantum technology;
//! - depend on a particular benchmark protocol;
//! - depend on `core::result`.
//!
//! Those responsibilities belong to the core, execution, statistics, metrics,
//! protocol, and result layers respectively.
//!
//! # Architectural position
//!
//! ```text
//!                         Quantum Benchmark
//!                                │
//!                                ▼
//!                         BenchmarkResult
//!                                │
//!                    normalized metrics/warnings
//!                                │
//!                                ▼
//!                  reporting::summary::BenchmarkSummary
//!                         │             │
//!              ┌──────────┘             └──────────┐
//!              ▼                                   ▼
//!        reporting::report                  markdown/json/csv
//!        reporting orchestration            serializers
//! ```
//!
//! The important dependency direction is:
//!
//! ```text
//! core::metric ───────► reporting::summary
//!                         ▲
//!                         │
//! core::result ──adapter──┘
//! ```
//!
//! `summary.rs` must never depend on `report.rs`, protocol implementations,
//! execution backends, or the Zamani runtime.
//!
//! # Integration contract
//!
//! The stable integration point is:
//!
//! [`BenchmarkSummary::from_metrics`]
//!
//! and the [`SummaryInput`] builder.
//!
//! A future `report.rs` or `core::result` implementation can construct a
//! `SummaryInput` from `BenchmarkResult` without modifying this file.
//!
//! # Determinism
//!
//! Summary output is deterministic:
//!
//! - metric order is preserved from the supplied input;
//! - duplicate metric IDs are rejected;
//! - warnings and recommendations retain insertion order;
//! - no `HashMap` is used for externally visible ordering;
//! - floating-point values are rejected when non-finite;
//! - no timestamps are generated by this module;
//! - no random values are generated by this module.
//!
//! # Resource safety
//!
//! This module does not allocate based on untrusted quantum-result dimensions
//! without bounds. The configurable limits are applied to:
//!
//! - number of metrics;
//! - number of warnings;
//! - number of recommendations;
//! - identifier lengths;
//! - textual field lengths.
//!
//! # Rust compatibility
//!
//! Designed for Rust 1.97 / Rust 1.97.1.
//!
//! # Serialization
//!
//! `serde` is used because it is already part of Zamani's benchmarking
//! foundation. JSON serialization itself belongs in `reporting::json`.
//!
//! # Integration with `core::metric`
//!
//! The canonical metric representation is:
//!
//! `quantum::benchmarking::core::metric::Metric`
//!
//! That type already carries semantic kind, unit, value, uncertainty,
//! confidence, sample counts, quality, direction, provenance and metadata.
//! This module consumes those fields; it does not duplicate them.
//!
//! See also:
//!
//! - `core::metric`
//! - `core::result`
//! - `reporting::report`
//! - `reporting::json`
//! - `reporting::markdown`
//! - `reporting::csv`
//! - `analysis::compare`
//! - `analysis::baseline`
//! - `analysis::regression`
//! - `validation::statistical`
//! - `validation::physical`

use serde::{Deserialize, Serialize};
use std::fmt;

use crate::quantum::benchmarking::core::metric::{
    Metric, MetricDirection, MetricKind, MetricQuality,
};

/// Maximum number of metrics that may be placed into one summary.
///
/// This is deliberately finite so a malformed or adversarial benchmark result
/// cannot cause an unbounded reporting allocation.
pub const DEFAULT_MAX_METRICS: usize = 4_096;

/// Maximum number of warnings in a summary.
pub const DEFAULT_MAX_WARNINGS: usize = 1_024;

/// Maximum number of recommendations in a summary.
pub const DEFAULT_MAX_RECOMMENDATIONS: usize = 512;

/// Maximum length of a benchmark identifier.
pub const DEFAULT_MAX_IDENTIFIER_LENGTH: usize = 512;

/// Maximum length of a human-readable summary field.
pub const DEFAULT_MAX_TEXT_LENGTH: usize = 16 * 1024;

/// Current summary schema version.
///
/// This is independent from the benchmark protocol version and from the
/// repository/package version.
pub const SUMMARY_SCHEMA_VERSION: &str = "1.0";

/// Result type used by summary construction and validation.
pub type SummaryResult<T> = Result<T, SummaryError>;

/// Severity of a summary finding.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum SummarySeverity {
    /// Informational finding.
    Info,

    /// Something requires attention but does not invalidate the result.
    Warning,

    /// The summary or underlying benchmark result cannot be trusted.
    Error,
}

impl SummarySeverity {
    /// Returns a stable machine-readable identifier.
    pub const fn id(self) -> &'static str {
        match self {
            Self::Info => "info",
            Self::Warning => "warning",
            Self::Error => "error",
        }
    }
}

/// Overall status of a benchmark summary.
///
/// This is deliberately separate from a benchmark protocol's pass/fail
/// semantics. For example, a benchmark can be successfully executed but fail
/// its scientific success criterion.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum SummaryStatus {
    /// Benchmark completed and produced valid results.
    Complete,

    /// Benchmark completed, but some results require caution.
    CompleteWithWarnings,

    /// Benchmark execution or analysis failed.
    Failed,

    /// Benchmark did not have enough information to make a determination.
    Inconclusive,

    /// Benchmark was intentionally not applicable to the target.
    NotApplicable,

    /// Benchmark execution was cancelled.
    Cancelled,

    /// Benchmark execution exceeded its configured deadline.
    TimedOut,
}

impl SummaryStatus {
    /// Returns a stable machine-readable identifier.
    pub const fn id(self) -> &'static str {
        match self {
            Self::Complete => "complete",
            Self::CompleteWithWarnings => "complete_with_warnings",
            Self::Failed => "failed",
            Self::Inconclusive => "inconclusive",
            Self::NotApplicable => "not_applicable",
            Self::Cancelled => "cancelled",
            Self::TimedOut => "timed_out",
        }
    }

    /// Whether the status represents a usable completed benchmark.
    pub const fn is_successful(self) -> bool {
        matches!(self, Self::Complete | Self::CompleteWithWarnings)
    }

    /// Whether the status indicates that the benchmark cannot currently be
    /// treated as a valid completed measurement.
    pub const fn is_terminal_failure(self) -> bool {
        matches!(
            self,
            Self::Failed | Self::Cancelled | Self::TimedOut
        )
    }
}

/// A single summary finding.
///
/// Findings are intentionally independent of the validation subsystem. The
/// validation layer decides what happened; this type only carries the result
/// into reporting.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct SummaryFinding {
    /// Finding severity.
    pub severity: SummarySeverity,

    /// Stable machine-readable code.
    pub code: String,

    /// Human-readable message.
    pub message: String,

    /// Optional metric identifier associated with the finding.
    pub metric_id: Option<String>,
}

impl SummaryFinding {
    /// Creates a finding.
    pub fn new(
        severity: SummarySeverity,
        code: impl Into<String>,
        message: impl Into<String>,
    ) -> SummaryResult<Self> {
        let code = code.into();
        let message = message.into();

        validate_identifier("finding.code", &code)?;
        validate_text("finding.message", &message)?;

        Ok(Self {
            severity,
            code,
            message,
            metric_id: None,
        })
    }

    /// Associates a finding with a metric.
    pub fn with_metric_id(mut self, metric_id: impl Into<String>) -> SummaryResult<Self> {
        let metric_id = metric_id.into();

        validate_identifier("finding.metric_id", &metric_id)?;

        self.metric_id = Some(metric_id);
        Ok(self)
    }
}

/// A concise metric entry intended for summary presentation.
///
/// The complete `Metric` remains the canonical measurement object. This type
/// intentionally contains only information useful to a summary and therefore
/// avoids leaking protocol implementation details into reporting.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SummaryMetric {
    /// Stable metric identifier.
    pub id: String,

    /// Human-readable metric name.
    pub name: String,

    /// Metric value.
    pub value: f64,

    /// Stable unit identifier.
    pub unit: String,

    /// Generic optimization direction.
    pub direction: MetricDirection,

    /// Statistical/semantic quality.
    pub quality: MetricQuality,

    /// Optional uncertainty.
    pub uncertainty: Option<f64>,

    /// Optional confidence interval.
    pub confidence: Option<SummaryConfidence>,

    /// Number of observations.
    pub sample_count: Option<u64>,

    /// Number of shots.
    pub shot_count: Option<u64>,

    /// Number of circuits.
    pub circuit_count: Option<u64>,

    /// Optional human-readable description.
    pub description: Option<String>,
}

impl SummaryMetric {
    /// Creates a summary metric from the canonical benchmark metric.
    pub fn from_metric(metric: &Metric) -> SummaryResult<Self> {
        let id = metric.kind.id();

        validate_identifier("metric.id", &id)?;

        let name = human_metric_name(&metric.kind);

        let uncertainty = metric.uncertainty.map(|value| value.get());

        if let Some(value) = uncertainty {
            validate_finite("metric.uncertainty", value)?;
            if value < 0.0 {
                return Err(SummaryError::InvalidUncertainty { value });
            }
        }

        let confidence = metric
            .confidence
            .as_ref()
            .map(SummaryConfidence::from_metric_confidence)
            .transpose()?;

        let description = metric.description.clone();

        if let Some(ref value) = description {
            validate_text("metric.description", value)?;
        }

        Ok(Self {
            id,
            name,
            value: metric.value.get(),
            unit: metric.unit.id(),
            direction: metric.direction,
            quality: metric.quality,
            uncertainty,
            confidence,
            sample_count: metric.sample_count,
            shot_count: metric.shot_count,
            circuit_count: metric.circuit_count,
            description,
        })
    }
}

/// Confidence interval representation suitable for summary output.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SummaryConfidence {
    /// Confidence level as a fraction, e.g. 0.95.
    pub level: f64,

    /// Lower confidence bound.
    pub lower: f64,

    /// Upper confidence bound.
    pub upper: f64,

    /// Stable confidence-method identifier.
    pub method: String,

    /// Width of the interval.
    pub width: f64,
}

impl SummaryConfidence {
    fn from_metric_confidence(
        confidence: &crate::quantum::benchmarking::core::metric::MetricConfidence,
    ) -> SummaryResult<Self> {
        let level = confidence.level.get();
        let lower = confidence.lower.get();
        let upper = confidence.upper.get();

        validate_finite("confidence.level", level)?;
        validate_finite("confidence.lower", lower)?;
        validate_finite("confidence.upper", upper)?;

        if !(0.0 < level && level < 1.0) {
            return Err(SummaryError::InvalidConfidenceLevel { level });
        }

        if lower > upper {
            return Err(SummaryError::InvalidConfidenceInterval { lower, upper });
        }

        let width = upper - lower;

        Ok(Self {
            level,
            lower,
            upper,
            method: confidence_method_id(&confidence.method),
            width,
        })
    }
}

/// Benchmark identity information presented in the summary.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct SummaryIdentity {
    /// Stable benchmark identifier.
    pub benchmark_id: String,

    /// Benchmark protocol/version.
    pub benchmark_version: Option<String>,

    /// Experiment identifier.
    pub experiment_id: Option<String>,

    /// Optional workload identifier.
    pub workload_id: Option<String>,
}

impl SummaryIdentity {
    /// Creates a benchmark identity.
    pub fn new(benchmark_id: impl Into<String>) -> SummaryResult<Self> {
        let benchmark_id = benchmark_id.into();

        validate_identifier("benchmark_id", &benchmark_id)?;

        Ok(Self {
            benchmark_id,
            benchmark_version: None,
            experiment_id: None,
            workload_id: None,
        })
    }

    /// Adds the benchmark protocol version.
    pub fn with_benchmark_version(
        mut self,
        version: impl Into<String>,
    ) -> SummaryResult<Self> {
        let version = version.into();
        validate_identifier("benchmark_version", &version)?;
        self.benchmark_version = Some(version);
        Ok(self)
    }

    /// Adds an experiment identifier.
    pub fn with_experiment_id(
        mut self,
        experiment_id: impl Into<String>,
    ) -> SummaryResult<Self> {
        let experiment_id = experiment_id.into();
        validate_identifier("experiment_id", &experiment_id)?;
        self.experiment_id = Some(experiment_id);
        Ok(self)
    }

    /// Adds a workload identifier.
    pub fn with_workload_id(
        mut self,
        workload_id: impl Into<String>,
    ) -> SummaryResult<Self> {
        let workload_id = workload_id.into();
        validate_identifier("workload_id", &workload_id)?;
        self.workload_id = Some(workload_id);
        Ok(self)
    }
}

/// Optional execution/environment information.
///
/// This is intentionally generic. Provider-specific metadata belongs in
/// `core::provenance` and `hardware::metadata`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, Default)]
pub struct SummaryEnvironment {
    /// Backend identifier.
    pub backend_id: Option<String>,

    /// Backend/provider name.
    pub provider: Option<String>,

    /// Backend technology.
    pub technology: Option<String>,

    /// Compiler version.
    pub compiler_version: Option<String>,

    /// Optimization level.
    pub optimization_level: Option<String>,

    /// Routing configuration identifier.
    pub routing_configuration: Option<String>,

    /// Scheduling configuration identifier.
    pub scheduling_configuration: Option<String>,

    /// Calibration identifier.
    pub calibration_id: Option<String>,

    /// Calibration timestamp represented as an opaque canonical string.
    pub calibration_timestamp: Option<String>,
}

impl SummaryEnvironment {
    /// Creates an empty environment description.
    pub fn new() -> Self {
        Self::default()
    }

    /// Sets the backend identifier.
    pub fn with_backend_id(mut self, value: impl Into<String>) -> SummaryResult<Self> {
        self.backend_id = Some(validated_optional_identifier(
            "backend_id",
            value.into(),
        )?);
        Ok(self)
    }

    /// Sets the provider.
    pub fn with_provider(mut self, value: impl Into<String>) -> SummaryResult<Self> {
        self.provider = Some(validated_optional_text("provider", value.into())?);
        Ok(self)
    }

    /// Sets the technology.
    pub fn with_technology(mut self, value: impl Into<String>) -> SummaryResult<Self> {
        self.technology = Some(validated_optional_text("technology", value.into())?);
        Ok(self)
    }

    /// Sets the compiler version.
    pub fn with_compiler_version(
        mut self,
        value: impl Into<String>,
    ) -> SummaryResult<Self> {
        self.compiler_version = Some(validated_optional_identifier(
            "compiler_version",
            value.into(),
        )?);
        Ok(self)
    }

    /// Sets the optimization level.
    pub fn with_optimization_level(
        mut self,
        value: impl Into<String>,
    ) -> SummaryResult<Self> {
        self.optimization_level = Some(validated_optional_identifier(
            "optimization_level",
            value.into(),
        )?);
        Ok(self)
    }

    /// Sets the routing configuration.
    pub fn with_routing_configuration(
        mut self,
        value: impl Into<String>,
    ) -> SummaryResult<Self> {
        self.routing_configuration = Some(validated_optional_identifier(
            "routing_configuration",
            value.into(),
        )?);
        Ok(self)
    }

    /// Sets the scheduling configuration.
    pub fn with_scheduling_configuration(
        mut self,
        value: impl Into<String>,
    ) -> SummaryResult<Self> {
        self.scheduling_configuration = Some(validated_optional_identifier(
            "scheduling_configuration",
            value.into(),
        )?);
        Ok(self)
    }

    /// Sets the calibration identifier.
    pub fn with_calibration_id(
        mut self,
        value: impl Into<String>,
    ) -> SummaryResult<Self> {
        self.calibration_id = Some(validated_optional_identifier(
            "calibration_id",
            value.into(),
        )?);
        Ok(self)
    }

    /// Sets the calibration timestamp.
    pub fn with_calibration_timestamp(
        mut self,
        value: impl Into<String>,
    ) -> SummaryResult<Self> {
        self.calibration_timestamp = Some(validated_optional_identifier(
            "calibration_timestamp",
            value.into(),
        )?);
        Ok(self)
    }
}

/// Configuration controlling summary resource bounds.
///
/// The defaults are intentionally conservative enough for a library API while
/// still allowing large application benchmark suites.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub struct SummaryLimits {
    /// Maximum number of metrics.
    pub max_metrics: usize,

    /// Maximum number of findings.
    pub max_findings: usize,

    /// Maximum number of recommendations.
    pub max_recommendations: usize,

    /// Maximum identifier length.
    pub max_identifier_length: usize,

    /// Maximum human-readable text length.
    pub max_text_length: usize,
}

impl Default for SummaryLimits {
    fn default() -> Self {
        Self {
            max_metrics: DEFAULT_MAX_METRICS,
            max_findings: DEFAULT_MAX_WARNINGS,
            max_recommendations: DEFAULT_MAX_RECOMMENDATIONS,
            max_identifier_length: DEFAULT_MAX_IDENTIFIER_LENGTH,
            max_text_length: DEFAULT_MAX_TEXT_LENGTH,
        }
    }
}

impl SummaryLimits {
    /// Validates the limits themselves.
    pub fn validate(&self) -> SummaryResult<()> {
        if self.max_metrics == 0 {
            return Err(SummaryError::InvalidLimit {
                field: "max_metrics",
            });
        }

        if self.max_findings == 0 {
            return Err(SummaryError::InvalidLimit {
                field: "max_findings",
            });
        }

        if self.max_recommendations == 0 {
            return Err(SummaryError::InvalidLimit {
                field: "max_recommendations",
            });
        }

        if self.max_identifier_length == 0 {
            return Err(SummaryError::InvalidLimit {
                field: "max_identifier_length",
            });
        }

        if self.max_text_length == 0 {
            return Err(SummaryError::InvalidLimit {
                field: "max_text_length",
            });
        }

        Ok(())
    }
}

/// Input used to build a [`BenchmarkSummary`].
///
/// This is the primary integration boundary for `report.rs`.
///
/// A future `BenchmarkResult` adapter should populate this structure and call
/// [`BenchmarkSummary::from_input`]. No changes to this module should then be
/// necessary when `core::result` evolves.
#[derive(Debug, Clone)]
pub struct SummaryInput {
    /// Benchmark identity.
    pub identity: SummaryIdentity,

    /// Final benchmark status.
    pub status: SummaryStatus,

    /// Optional concise headline supplied by the protocol/analyzer.
    pub headline: Option<String>,

    /// Optional detailed description.
    pub description: Option<String>,

    /// Canonical metrics.
    pub metrics: Vec<Metric>,

    /// Validation/execution/analysis findings.
    pub findings: Vec<SummaryFinding>,

    /// Optional execution environment.
    pub environment: SummaryEnvironment,

    /// Optional explicit recommendations.
    pub recommendations: Vec<String>,

    /// Summary resource limits.
    pub limits: SummaryLimits,
}

impl SummaryInput {
    /// Creates the minimum valid input.
    pub fn new(
        identity: SummaryIdentity,
        status: SummaryStatus,
        metrics: Vec<Metric>,
    ) -> Self {
        Self {
            identity,
            status,
            headline: None,
            description: None,
            metrics,
            findings: Vec::new(),
            environment: SummaryEnvironment::default(),
            recommendations: Vec::new(),
            limits: SummaryLimits::default(),
        }
    }

    /// Sets the headline.
    pub fn with_headline(mut self, headline: impl Into<String>) -> SummaryResult<Self> {
        let headline = headline.into();
        validate_text("headline", &headline)?;
        self.headline = Some(headline);
        Ok(self)
    }

    /// Sets the description.
    pub fn with_description(
        mut self,
        description: impl Into<String>,
    ) -> SummaryResult<Self> {
        let description = description.into();
        validate_text("description", &description)?;
        self.description = Some(description);
        Ok(self)
    }

    /// Sets findings.
    pub fn with_findings(mut self, findings: Vec<SummaryFinding>) -> Self {
        self.findings = findings;
        self
    }

    /// Sets the environment.
    pub fn with_environment(mut self, environment: SummaryEnvironment) -> Self {
        self.environment = environment;
        self
    }

    /// Sets explicit recommendations.
    pub fn with_recommendations(
        mut self,
        recommendations: Vec<String>,
    ) -> SummaryResult<Self> {
        for recommendation in &recommendations {
            validate_text("recommendation", recommendation)?;
        }

        self.recommendations = recommendations;
        Ok(self)
    }

    /// Sets resource limits.
    pub fn with_limits(mut self, limits: SummaryLimits) -> SummaryResult<Self> {
        limits.validate()?;
        self.limits = limits;
        Ok(self)
    }
}

/// Canonical benchmark summary.
///
/// This is the primary output of this module.
///
/// It is deliberately smaller than a complete `BenchmarkResult`. The result
/// contains scientific observations and provenance; the summary contains the
/// decision-ready view of those results.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct BenchmarkSummary {
    /// Summary schema version.
    pub schema_version: String,

    /// Benchmark identity.
    pub identity: SummaryIdentity,

    /// Overall benchmark status.
    pub status: SummaryStatus,

    /// Human-readable headline.
    pub headline: String,

    /// Optional detailed description.
    pub description: Option<String>,

    /// Metrics selected for summary presentation.
    pub metrics: Vec<SummaryMetric>,

    /// Validation and execution findings.
    pub findings: Vec<SummaryFinding>,

    /// Execution environment.
    pub environment: SummaryEnvironment,

    /// Recommendations generated or supplied by the analysis layer.
    pub recommendations: Vec<String>,

    /// Number of metrics represented.
    pub metric_count: usize,

    /// Number of findings represented.
    pub finding_count: usize,

    /// Number of error-severity findings.
    pub error_count: usize,

    /// Number of warning-severity findings.
    pub warning_count: usize,

    /// Number of informational findings.
    pub info_count: usize,

    /// Whether the summary represents a successful benchmark completion.
    pub successful: bool,
}

impl BenchmarkSummary {
    /// Builds a summary from a normalized [`SummaryInput`].
    ///
    /// This is the preferred construction path.
    pub fn from_input(input: SummaryInput) -> SummaryResult<Self> {
        input.limits.validate()?;

        validate_identity(&input.identity)?;

        if let Some(ref headline) = input.headline {
            validate_text_with_limit(
                "headline",
                headline,
                input.limits.max_text_length,
            )?;
        }

        if let Some(ref description) = input.description {
            validate_text_with_limit(
                "description",
                description,
                input.limits.max_text_length,
            )?;
        }

        if input.metrics.len() > input.limits.max_metrics {
            return Err(SummaryError::LimitExceeded {
                field: "metrics",
                limit: input.limits.max_metrics,
                actual: input.metrics.len(),
            });
        }

        if input.findings.len() > input.limits.max_findings {
            return Err(SummaryError::LimitExceeded {
                field: "findings",
                limit: input.limits.max_findings,
                actual: input.findings.len(),
            });
        }

        if input.recommendations.len() > input.limits.max_recommendations {
            return Err(SummaryError::LimitExceeded {
                field: "recommendations",
                limit: input.limits.max_recommendations,
                actual: input.recommendations.len(),
            });
        }

        let mut metrics = Vec::with_capacity(input.metrics.len());
        let mut seen_metric_ids: Vec<String> = Vec::with_capacity(input.metrics.len());

        for metric in &input.metrics {
            let summary_metric = SummaryMetric::from_metric(metric)?;

            if seen_metric_ids
                .iter()
                .any(|existing| existing == &summary_metric.id)
            {
                return Err(SummaryError::DuplicateMetric {
                    metric_id: summary_metric.id,
                });
            }

            seen_metric_ids.push(summary_metric.id.clone());
            metrics.push(summary_metric);
        }

        validate_findings(&input.findings, &input.limits)?;
        validate_recommendations(&input.recommendations, &input.limits)?;

        let finding_count = input.findings.len();

        let error_count = input
            .findings
            .iter()
            .filter(|finding| finding.severity == SummarySeverity::Error)
            .count();

        let warning_count = input
            .findings
            .iter()
            .filter(|finding| finding.severity == SummarySeverity::Warning)
            .count();

        let info_count = input
            .findings
            .iter()
            .filter(|finding| finding.severity == SummarySeverity::Info)
            .count();

        let successful = input.status.is_successful() && error_count == 0;

        let headline = input
            .headline
            .unwrap_or_else(|| generate_headline(&input.identity, input.status, &metrics));

        let recommendations = if input.recommendations.is_empty() {
            generate_recommendations(input.status, &metrics, &input.findings)
        } else {
            input.recommendations
        };

        Ok(Self {
            schema_version: SUMMARY_SCHEMA_VERSION.to_string(),
            identity: input.identity,
            status: input.status,
            headline,
            description: input.description,
            metrics,
            findings: input.findings,
            environment: input.environment,
            recommendations,
            metric_count: metrics.len(),
            finding_count,
            error_count,
            warning_count,
            info_count,
            successful,
        })
    }

    /// Convenience constructor for consumers that already have canonical
    /// metrics and do not yet have a `BenchmarkResult` adapter.
    pub fn from_metrics(
        benchmark_id: impl Into<String>,
        status: SummaryStatus,
        metrics: Vec<Metric>,
    ) -> SummaryResult<Self> {
        let identity = SummaryIdentity::new(benchmark_id)?;
        let input = SummaryInput::new(identity, status, metrics);
        Self::from_input(input)
    }

    /// Adds a finding without mutating the canonical summary in an invalid
    /// state.
    ///
    /// This method returns a new validated summary. It is useful for report
    /// adapters that discover presentation-level warnings after construction.
    pub fn with_finding(mut self, finding: SummaryFinding) -> SummaryResult<Self> {
        self.findings.push(finding);

        if self.findings.len() > DEFAULT_MAX_WARNINGS {
            return Err(SummaryError::LimitExceeded {
                field: "findings",
                limit: DEFAULT_MAX_WARNINGS,
                actual: self.findings.len(),
            });
        }

        self.recalculate_counters();
        Ok(self)
    }

    /// Returns a metric by its stable ID.
    pub fn metric(&self, metric_id: &str) -> Option<&SummaryMetric> {
        self.metrics.iter().find(|metric| metric.id == metric_id)
    }

    /// Returns all metrics with a given direction.
    pub fn metrics_with_direction(
        &self,
        direction: MetricDirection,
    ) -> Vec<&SummaryMetric> {
        self.metrics
            .iter()
            .filter(|metric| metric.direction == direction)
            .collect()
    }

    /// Returns whether a metric exists.
    pub fn contains_metric(&self, metric_id: &str) -> bool {
        self.metric(metric_id).is_some()
    }

    /// Returns the highest-quality metric classification present.
    ///
    /// Quality is ordered conservatively:
    ///
    /// Observed > Derived > Estimated > Fitted > Approximate > Uncertain >
    /// Invalid.
    pub fn minimum_quality(&self) -> Option<MetricQuality> {
        self.metrics
            .iter()
            .map(|metric| metric.quality)
            .min_by_key(metric_quality_rank)
    }

    /// Returns whether the summary contains invalid metrics.
    pub fn has_invalid_metrics(&self) -> bool {
        self.metrics
            .iter()
            .any(|metric| metric.quality == MetricQuality::Invalid)
    }

    /// Returns whether the summary contains warning or error findings.
    pub fn has_findings(&self) -> bool {
        !self.findings.is_empty()
    }

    /// Returns the number of metrics with confidence intervals.
    pub fn metrics_with_confidence(&self) -> usize {
        self.metrics
            .iter()
            .filter(|metric| metric.confidence.is_some())
            .count()
    }

    /// Returns a concise one-line representation.
    ///
    /// This method does not perform serialization and is safe for CLI/logging
    /// use.
    pub fn one_line(&self) -> String {
        format!(
            "{} [{}] metrics={} findings={} successful={}",
            self.identity.benchmark_id,
            self.status.id(),
            self.metric_count,
            self.finding_count,
            self.successful
        )
    }

    /// Produces deterministic Markdown suitable for GitHub/CI reports.
    ///
    /// This method intentionally lives here because Markdown summary rendering
    /// requires only the summary model. The dedicated `reporting::markdown`
    /// module can call this method or provide richer document composition.
    pub fn to_markdown(&self) -> String {
        let mut output = String::new();

        output.push_str("# Benchmark Summary\n\n");

        output.push_str("## Overview\n\n");
        output.push_str("| Field | Value |\n");
        output.push_str("|---|---|\n");
        output.push_str(&format!(
            "| Benchmark | `{}` |\n",
            escape_markdown(&self.identity.benchmark_id)
        ));
        output.push_str(&format!(
            "| Status | `{}` |\n",
            self.status.id()
        ));
        output.push_str(&format!(
            "| Successful | `{}` |\n",
            self.successful
        ));
        output.push_str(&format!(
            "| Metrics | {} |\n",
            self.metric_count
        ));
        output.push_str(&format!(
            "| Findings | {} |\n",
            self.finding_count
        ));

        if let Some(ref version) = self.identity.benchmark_version {
            output.push_str(&format!(
                "| Benchmark version | `{}` |\n",
                escape_markdown(version)
            ));
        }

        if let Some(ref experiment_id) = self.identity.experiment_id {
            output.push_str(&format!(
                "| Experiment | `{}` |\n",
                escape_markdown(experiment_id)
            ));
        }

        output.push('\n');

        output.push_str("## Headline\n\n");
        output.push_str(&self.headline);
        output.push_str("\n\n");

        if let Some(ref description) = self.description {
            output.push_str("## Description\n\n");
            output.push_str(description);
            output.push_str("\n\n");
        }

        if !self.metrics.is_empty() {
            output.push_str("## Metrics\n\n");
            output.push_str(
                "| Metric | Value | Unit | Quality | Uncertainty | Confidence |\n",
            );
            output.push_str(
                "|---|---:|---|---|---:|---|\n",
            );

            for metric in &self.metrics {
                let uncertainty = metric
                    .uncertainty
                    .map(format_f64)
                    .unwrap_or_else(|| "—".to_string());

                let confidence = metric
                    .confidence
                    .as_ref()
                    .map(format_confidence)
                    .unwrap_or_else(|| "—".to_string());

                output.push_str(&format!(
                    "| {} | {} | `{}` | `{}` | {} | {} |\n",
                    escape_markdown(&metric.name),
                    format_f64(metric.value),
                    escape_markdown(&metric.unit),
                    quality_id(metric.quality),
                    uncertainty,
                    confidence
                ));
            }

            output.push('\n');
        }

        if !self.findings.is_empty() {
            output.push_str("## Findings\n\n");

            for finding in &self.findings {
                output.push_str(&format!(
                    "- **{}** `{}`: {}",
                    finding.severity.id(),
                    escape_markdown(&finding.code),
                    finding.message
                ));

                if let Some(ref metric_id) = finding.metric_id {
                    output.push_str(&format!(
                        " (metric `{}`)",
                        escape_markdown(metric_id)
                    ));
                }

                output.push('\n');
            }

            output.push('\n');
        }

        if !self.recommendations.is_empty() {
            output.push_str("## Recommendations\n\n");

            for recommendation in &self.recommendations {
                output.push_str("- ");
                output.push_str(recommendation);
                output.push('\n');
            }

            output.push('\n');
        }

        output
    }

    /// Recomputes counters after a controlled mutation.
    fn recalculate_counters(&mut self) {
        self.finding_count = self.findings.len();

        self.error_count = self
            .findings
            .iter()
            .filter(|finding| finding.severity == SummarySeverity::Error)
            .count();

        self.warning_count = self
            .findings
            .iter()
            .filter(|finding| finding.severity == SummarySeverity::Warning)
            .count();

        self.info_count = self
            .findings
            .iter()
            .filter(|finding| finding.severity == SummarySeverity::Info)
            .count();

        self.successful = self.status.is_successful()
            && self.error_count == 0
            && !self.has_invalid_metrics();
    }
}

/// Errors produced by summary construction and validation.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum SummaryError {
    /// An identifier is empty.
    EmptyIdentifier {
        /// Field that was empty.
        field: &'static str,
    },

    /// Text was empty.
    EmptyText {
        /// Field that was empty.
        field: &'static str,
    },

    /// Identifier exceeded the configured limit.
    IdentifierTooLong {
        /// Field name.
        field: &'static str,

        /// Maximum permitted length.
        limit: usize,

        /// Actual length.
        actual: usize,
    },

    /// Text exceeded the configured limit.
    TextTooLong {
        /// Field name.
        field: &'static str,

        /// Maximum permitted length.
        limit: usize,

        /// Actual length.
        actual: usize,
    },

    /// A floating-point value was not finite.
    NonFiniteValue {
        /// Field name.
        field: &'static str,
    },

    /// Negative uncertainty was supplied.
    InvalidUncertainty {
        /// Invalid uncertainty.
        value: f64,
    },

    /// Confidence level is outside the open interval (0, 1).
    InvalidConfidenceLevel {
        /// Invalid confidence level.
        level: f64,
    },

    /// Confidence interval lower bound exceeds upper bound.
    InvalidConfidenceInterval {
        /// Lower bound.
        lower: f64,

        /// Upper bound.
        upper: f64,
    },

    /// A configurable limit itself is invalid.
    InvalidLimit {
        /// Field name.
        field: &'static str,
    },

    /// A configured collection limit was exceeded.
    LimitExceeded {
        /// Collection name.
        field: &'static str,

        /// Maximum permitted number of elements.
        limit: usize,

        /// Actual number of elements.
        actual: usize,
    },

    /// Two metrics have the same stable identifier.
    DuplicateMetric {
        /// Duplicate identifier.
        metric_id: String,
    },

    /// A finding has an invalid severity/code/message combination.
    InvalidFinding {
        /// Finding code.
        code: String,
    },
}

impl fmt::Display for SummaryError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::EmptyIdentifier { field } => {
                write!(formatter, "{field} must not be empty")
            }

            Self::EmptyText { field } => {
                write!(formatter, "{field} must not be empty")
            }

            Self::IdentifierTooLong {
                field,
                limit,
                actual,
            } => write!(
                formatter,
                "{field} exceeds maximum length {limit}: actual length {actual}"
            ),

            Self::TextTooLong {
                field,
                limit,
                actual,
            } => write!(
                formatter,
                "{field} exceeds maximum length {limit}: actual length {actual}"
            ),

            Self::NonFiniteValue { field } => {
                write!(formatter, "{field} must be finite")
            }

            Self::InvalidUncertainty { value } => {
                write!(formatter, "uncertainty must be non-negative: {value}")
            }

            Self::InvalidConfidenceLevel { level } => {
                write!(
                    formatter,
                    "confidence level must be strictly between 0 and 1: {level}"
                )
            }

            Self::InvalidConfidenceInterval { lower, upper } => {
                write!(
                    formatter,
                    "confidence interval is invalid: lower={lower}, upper={upper}"
                )
            }

            Self::InvalidLimit { field } => {
                write!(formatter, "{field} must be greater than zero")
            }

            Self::LimitExceeded {
                field,
                limit,
                actual,
            } => write!(
                formatter,
                "{field} exceeds configured limit {limit}: actual {actual}"
            ),

            Self::DuplicateMetric { metric_id } => {
                write!(formatter, "duplicate metric identifier: {metric_id}")
            }

            Self::InvalidFinding { code } => {
                write!(formatter, "invalid benchmark finding: {code}")
            }
        }
    }
}

impl std::error::Error for SummaryError {}

/// Validates a benchmark identity.
fn validate_identity(identity: &SummaryIdentity) -> SummaryResult<()> {
    validate_identifier("benchmark_id", &identity.benchmark_id)?;

    if let Some(ref value) = identity.benchmark_version {
        validate_identifier("benchmark_version", value)?;
    }

    if let Some(ref value) = identity.experiment_id {
        validate_identifier("experiment_id", value)?;
    }

    if let Some(ref value) = identity.workload_id {
        validate_identifier("workload_id", value)?;
    }

    Ok(())
}

/// Validates findings.
fn validate_findings(
    findings: &[SummaryFinding],
    limits: &SummaryLimits,
) -> SummaryResult<()> {
    if findings.len() > limits.max_findings {
        return Err(SummaryError::LimitExceeded {
            field: "findings",
            limit: limits.max_findings,
            actual: findings.len(),
        });
    }

    for finding in findings {
        validate_identifier_with_limit(
            "finding.code",
            &finding.code,
            limits.max_identifier_length,
        )?;

        validate_text_with_limit(
            "finding.message",
            &finding.message,
            limits.max_text_length,
        )?;

        if let Some(ref metric_id) = finding.metric_id {
            validate_identifier_with_limit(
                "finding.metric_id",
                metric_id,
                limits.max_identifier_length,
            )?;
        }
    }

    Ok(())
}

/// Validates recommendations.
fn validate_recommendations(
    recommendations: &[String],
    limits: &SummaryLimits,
) -> SummaryResult<()> {
    if recommendations.len() > limits.max_recommendations {
        return Err(SummaryError::LimitExceeded {
            field: "recommendations",
            limit: limits.max_recommendations,
            actual: recommendations.len(),
        });
    }

    for recommendation in recommendations {
        validate_text_with_limit(
            "recommendation",
            recommendation,
            limits.max_text_length,
        )?;
    }

    Ok(())
}

/// Generates a conservative default headline.
///
/// Protocol-specific analysis should provide a richer headline when one is
/// available. This fallback never makes scientific claims that are not encoded
/// in the supplied status.
fn generate_headline(
    identity: &SummaryIdentity,
    status: SummaryStatus,
    metrics: &[SummaryMetric],
) -> String {
    match status {
        SummaryStatus::Complete => format!(
            "{} completed successfully with {} reported metric{}.",
            identity.benchmark_id,
            metrics.len(),
            plural_suffix(metrics.len())
        ),

        SummaryStatus::CompleteWithWarnings => format!(
            "{} completed with warnings and {} reported metric{}.",
            identity.benchmark_id,
            metrics.len(),
            plural_suffix(metrics.len())
        ),

        SummaryStatus::Failed => {
            format!("{} failed.", identity.benchmark_id)
        }

        SummaryStatus::Inconclusive => {
            format!("{} produced an inconclusive result.", identity.benchmark_id)
        }

        SummaryStatus::NotApplicable => {
            format!("{} is not applicable to the selected target.", identity.benchmark_id)
        }

        SummaryStatus::Cancelled => {
            format!("{} was cancelled before completion.", identity.benchmark_id)
        }

        SummaryStatus::TimedOut => {
            format!("{} exceeded its execution deadline.", identity.benchmark_id)
        }
    }
}

/// Generates conservative recommendations from summary-level evidence.
///
/// This deliberately avoids domain-specific scientific conclusions. Protocol
/// analyzers should supply protocol-specific recommendations through
/// `SummaryInput::with_recommendations`.
fn generate_recommendations(
    status: SummaryStatus,
    metrics: &[SummaryMetric],
    findings: &[SummaryFinding],
) -> Vec<String> {
    let mut recommendations = Vec::new();

    if matches!(status, SummaryStatus::Failed | SummaryStatus::TimedOut) {
        recommendations.push(
            "Inspect execution and validation findings before comparing this result with a baseline."
                .to_string(),
        );
    }

    if matches!(status, SummaryStatus::Cancelled) {
        recommendations.push(
            "Re-run the benchmark if a complete measurement is required.".to_string(),
        );
    }

    if matches!(status, SummaryStatus::Inconclusive) {
        recommendations.push(
            "Increase or correct the available evidence before making a performance comparison."
                .to_string(),
        );
    }

    if metrics.iter().any(|metric| {
        matches!(
            metric.quality,
            MetricQuality::Uncertain | MetricQuality::Invalid
        )
    }) {
        recommendations.push(
            "Review uncertain or invalid metrics before using the summary for regression decisions."
                .to_string(),
        );
    }

    if metrics.iter().any(|metric| metric.confidence.is_none()) {
        recommendations.push(
            "Metrics without confidence information should not be treated as statistically equivalent to metrics with explicit uncertainty."
                .to_string(),
        );
    }

    if findings
        .iter()
        .any(|finding| finding.severity == SummarySeverity::Warning)
    {
        recommendations.push(
            "Review benchmark warnings and preserve them with any exported result."
                .to_string(),
        );
    }

    recommendations
}

/// Converts a metric kind to a human-readable presentation name.
fn human_metric_name(kind: &MetricKind) -> String {
    match kind {
        MetricKind::Probability => "Probability".to_string(),
        MetricKind::SuccessProbability => "Success Probability".to_string(),
        MetricKind::StateFidelity => "State Fidelity".to_string(),
        MetricKind::ProcessFidelity => "Process Fidelity".to_string(),
        MetricKind::AverageGateFidelity => "Average Gate Fidelity".to_string(),
        MetricKind::EntanglementFidelity => "Entanglement Fidelity".to_string(),
        MetricKind::HellingerFidelity => "Hellinger Fidelity".to_string(),
        MetricKind::TotalVariationDistance => "Total Variation Distance".to_string(),
        MetricKind::TraceDistance => "Trace Distance".to_string(),
        MetricKind::ClassicalFidelity => "Classical Fidelity".to_string(),
        MetricKind::Fidelity => "Fidelity".to_string(),
        MetricKind::ErrorRate => "Error Rate".to_string(),
        MetricKind::ErrorPerGate => "Error Per Gate".to_string(),
        MetricKind::ErrorPerClifford => "Error Per Clifford".to_string(),
        MetricKind::CycleError => "Cycle Error".to_string(),
        MetricKind::GateInfidelity => "Gate Infidelity".to_string(),
        MetricKind::ProcessInfidelity => "Process Infidelity".to_string(),
        MetricKind::ReadoutFidelity => "Readout Fidelity".to_string(),
        MetricKind::ReadoutError => "Readout Error".to_string(),
        MetricKind::StatePreparationError => "State Preparation Error".to_string(),
        MetricKind::SpamError => "SPAM Error".to_string(),
        MetricKind::LeakageRate => "Leakage Rate".to_string(),
        MetricKind::LogicalErrorRate => "Logical Error Rate".to_string(),
        MetricKind::LogicalFidelity => "Logical Fidelity".to_string(),
        MetricKind::PhysicalErrorRate => "Physical Error Rate".to_string(),
        MetricKind::DecoderFailureProbability => {
            "Decoder Failure Probability".to_string()
        }
        MetricKind::Threshold => "Threshold".to_string(),
        MetricKind::Runtime => "Runtime".to_string(),
        MetricKind::CompilationTime => "Compilation Time".to_string(),
        MetricKind::QueueTime => "Queue Time".to_string(),
        MetricKind::SubmissionTime => "Submission Time".to_string(),
        MetricKind::ExecutionTime => "Execution Time".to_string(),
        MetricKind::ReadoutTime => "Readout Time".to_string(),
        MetricKind::AnalysisTime => "Analysis Time".to_string(),
        MetricKind::TotalWallTime => "Total Wall Time".to_string(),
        MetricKind::Latency => "Latency".to_string(),
        MetricKind::Throughput => "Throughput".to_string(),
        MetricKind::ShotsPerSecond => "Shots Per Second".to_string(),
        MetricKind::CircuitsPerSecond => "Circuits Per Second".to_string(),
        MetricKind::GatesPerSecond => "Gates Per Second".to_string(),
        MetricKind::TwoQubitGatesPerSecond => {
            "Two-Qubit Gates Per Second".to_string()
        }
        MetricKind::LayersPerSecond => "Layers Per Second".to_string(),
        MetricKind::QuantumVolume => "Quantum Volume".to_string(),
        MetricKind::QubitCount => "Qubit Count".to_string(),
        MetricKind::LogicalQubitCount => "Logical Qubit Count".to_string(),
        MetricKind::PhysicalQubitCount => "Physical Qubit Count".to_string(),
        MetricKind::CircuitDepth => "Circuit Depth".to_string(),
        MetricKind::TwoQubitDepth => "Two-Qubit Depth".to_string(),
        MetricKind::GateCount => "Gate Count".to_string(),
        MetricKind::TwoQubitGateCount => "Two-Qubit Gate Count".to_string(),
        MetricKind::MeasurementCount => "Measurement Count".to_string(),
        MetricKind::TGateCount => "T-Gate Count".to_string(),
        MetricKind::ClassicalOperationCount => {
            "Classical Operation Count".to_string()
        }
        MetricKind::Memory => "Memory".to_string(),
        MetricKind::Energy => "Energy".to_string(),
        MetricKind::TimeToSolution => "Time To Solution".to_string(),
        MetricKind::ObjectiveValue => "Objective Value".to_string(),
        MetricKind::ApproximationRatio => "Approximation Ratio".to_string(),
        MetricKind::EstimationError => "Estimation Error".to_string(),
        MetricKind::EnergyError => "Energy Error".to_string(),
        MetricKind::ObservableError => "Observable Error".to_string(),
        MetricKind::SolutionQuality => "Solution Quality".to_string(),
        MetricKind::T1 => "T1".to_string(),
        MetricKind::T2 => "T2".to_string(),
        MetricKind::T2Star => "T2*".to_string(),
        MetricKind::TPhi => "T Phi".to_string(),
        MetricKind::Crosstalk => "Crosstalk".to_string(),
        MetricKind::Drift => "Drift".to_string(),
        MetricKind::Stability => "Stability".to_string(),
        MetricKind::SpaceTimeVolume => "Space-Time Volume".to_string(),
        MetricKind::ResourceOverhead => "Resource Overhead".to_string(),
        MetricKind::Custom(value) => value.clone(),
    }
}

/// Returns a stable confidence-method identifier.
fn confidence_method_id(
    method: &crate::quantum::benchmarking::core::metric::ConfidenceMethod,
) -> String {
    match method {
        crate::quantum::benchmarking::core::metric::ConfidenceMethod::Wilson => {
            "wilson".to_string()
        }
        crate::quantum::benchmarking::core::metric::ConfidenceMethod::ClopperPearson => {
            "clopper_pearson".to_string()
        }
        crate::quantum::benchmarking::core::metric::ConfidenceMethod::NormalApproximation => {
            "normal_approximation".to_string()
        }
        crate::quantum::benchmarking::core::metric::ConfidenceMethod::Bootstrap => {
            "bootstrap".to_string()
        }
        crate::quantum::benchmarking::core::metric::ConfidenceMethod::Bayesian => {
            "bayesian".to_string()
        }
        crate::quantum::benchmarking::core::metric::ConfidenceMethod::BackendProvided => {
            "backend_provided".to_string()
        }
        crate::quantum::benchmarking::core::metric::ConfidenceMethod::Custom(value) => {
            value.clone()
        }
    }
}

/// Converts quality to a stable machine-readable identifier.
fn quality_id(quality: MetricQuality) -> &'static str {
    match quality {
        MetricQuality::Observed => "observed",
        MetricQuality::Derived => "derived",
        MetricQuality::Estimated => "estimated",
        MetricQuality::Fitted => "fitted",
        MetricQuality::Approximate => "approximate",
        MetricQuality::Uncertain => "uncertain",
        MetricQuality::Invalid => "invalid",
    }
}

/// Ranking used by [`BenchmarkSummary::minimum_quality`].
fn metric_quality_rank(quality: &MetricQuality) -> u8 {
    match quality {
        MetricQuality::Observed => 0,
        MetricQuality::Derived => 1,
        MetricQuality::Estimated => 2,
        MetricQuality::Fitted => 3,
        MetricQuality::Approximate => 4,
        MetricQuality::Uncertain => 5,
        MetricQuality::Invalid => 6,
    }
}

/// Returns a plural suffix for a count.
fn plural_suffix(count: usize) -> &'static str {
    if count == 1 {
        ""
    } else {
        "s"
    }
}

/// Validates an identifier using the default production limit.
fn validate_identifier(field: &'static str, value: &str) -> SummaryResult<()> {
    validate_identifier_with_limit(field, value, DEFAULT_MAX_IDENTIFIER_LENGTH)
}

/// Validates an identifier against a caller-supplied limit.
fn validate_identifier_with_limit(
    field: &'static str,
    value: &str,
    limit: usize,
) -> SummaryResult<()> {
    if value.trim().is_empty() {
        return Err(SummaryError::EmptyIdentifier { field });
    }

    let length = value.chars().count();

    if length > limit {
        return Err(SummaryError::IdentifierTooLong {
            field,
            limit,
            actual: length,
        });
    }

    Ok(())
}

/// Validates ordinary text using the default production limit.
fn validate_text(field: &'static str, value: &str) -> SummaryResult<()> {
    validate_text_with_limit(field, value, DEFAULT_MAX_TEXT_LENGTH)
}

/// Validates ordinary text against a caller-supplied limit.
fn validate_text_with_limit(
    field: &'static str,
    value: &str,
    limit: usize,
) -> SummaryResult<()> {
    if value.trim().is_empty() {
        return Err(SummaryError::EmptyText { field });
    }

    let length = value.chars().count();

    if length > limit {
        return Err(SummaryError::TextTooLong {
            field,
            limit,
            actual: length,
        });
    }

    Ok(())
}

/// Validates a finite floating-point value.
fn validate_finite(field: &'static str, value: f64) -> SummaryResult<()> {
    if value.is_finite() {
        Ok(())
    } else {
        Err(SummaryError::NonFiniteValue { field })
    }
}

/// Validates an optional identifier.
fn validated_optional_identifier(
    field: &'static str,
    value: String,
) -> SummaryResult<String> {
    validate_identifier(field, &value)?;
    Ok(value)
}

/// Validates optional text.
fn validated_optional_text(
    field: &'static str,
    value: String,
) -> SummaryResult<String> {
    validate_text(field, &value)?;
    Ok(value)
}

/// Formats a finite floating-point value for human-readable output.
///
/// Scientific notation is deliberately used for very small/large values.
fn format_f64(value: f64) -> String {
    if !value.is_finite() {
        return "invalid".to_string();
    }

    if value == 0.0 {
        return "0".to_string();
    }

    let absolute = value.abs();

    if absolute >= 1.0e6 || absolute < 1.0e-6 {
        format!("{value:.6e}")
    } else {
        format!("{value:.8}")
            .trim_end_matches('0')
            .trim_end_matches('.')
            .to_string()
    }
}

/// Formats confidence information for Markdown.
fn format_confidence(confidence: &SummaryConfidence) -> String {
    format!(
        "{:.2}% [{}, {}] ({})",
        confidence.level * 100.0,
        format_f64(confidence.lower),
        format_f64(confidence.upper),
        confidence.method
    )
}

/// Escapes the minimal Markdown characters required for table-safe output.
fn escape_markdown(value: &str) -> String {
    value
        .replace('\\', "\\\\")
        .replace('|', "\\|")
        .replace('\n', " ")
        .replace('\r', " ")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::quantum::benchmarking::core::metric::{
        ConfidenceMethod, MetricConfidence, MetricKind, MetricUnit,
    };

    fn probability_metric(value: f64) -> Metric {
        Metric::new(
            MetricKind::SuccessProbability,
            MetricUnit::Probability,
            value,
        )
        .expect("valid metric")
    }

    fn quantum_volume_metric(value: f64) -> Metric {
        Metric::observed(
            MetricKind::QuantumVolume,
            MetricUnit::Dimensionless,
            value,
        )
        .expect("valid quantum-volume metric")
    }

    #[test]
    fn constructs_summary_from_metrics() {
        let summary = BenchmarkSummary::from_metrics(
            "quantum_volume",
            SummaryStatus::Complete,
            vec![quantum_volume_metric(64.0)],
        )
        .expect("summary should be valid");

        assert_eq!(summary.schema_version, SUMMARY_SCHEMA_VERSION);
        assert_eq!(summary.metric_count, 1);
        assert_eq!(summary.finding_count, 0);
        assert!(summary.successful);
        assert!(summary.contains_metric("quantum_volume"));
    }

    #[test]
    fn rejects_duplicate_metric_ids() {
        let result = BenchmarkSummary::from_metrics(
            "duplicate_test",
            SummaryStatus::Complete,
            vec![
                probability_metric(0.9),
                probability_metric(0.8),
            ],
        );

        assert!(matches!(
            result,
            Err(SummaryError::DuplicateMetric { .. })
        ));
    }

    #[test]
    fn rejects_non_finite_metric_uncertainty() {
        let mut metric = probability_metric(0.9);

        metric.uncertainty =
            Some(crate::quantum::benchmarking::core::metric::FiniteF64::new(
                0.1,
            ).expect("finite"));

        let confidence = MetricConfidence::new(
            0.95,
            f64::NAN,
            1.0,
            ConfidenceMethod::Wilson,
        );

        assert!(confidence.is_err());
    }

    #[test]
    fn confidence_is_rendered() {
        let mut metric = probability_metric(0.9);

        metric.confidence = Some(
            MetricConfidence::new(
                0.95,
                0.85,
                0.94,
                ConfidenceMethod::Wilson,
            )
            .expect("valid confidence"),
        );

        let summary = BenchmarkSummary::from_metrics(
            "confidence_test",
            SummaryStatus::Complete,
            vec![metric],
        )
        .expect("summary should be valid");

        assert_eq!(summary.metrics_with_confidence(), 1);
        assert!(summary.to_markdown().contains("95.00%"));
    }

    #[test]
    fn warning_status_is_not_reported_as_clean_success() {
        let identity =
            SummaryIdentity::new("warning_test").expect("valid identity");

        let finding = SummaryFinding::new(
            SummarySeverity::Warning,
            "statistical_warning",
            "Confidence interval is wide.",
        )
        .expect("valid finding");

        let input = SummaryInput::new(
            identity,
            SummaryStatus::CompleteWithWarnings,
            vec![probability_metric(0.8)],
        )
        .with_findings(vec![finding]);

        let summary =
            BenchmarkSummary::from_input(input).expect("summary should be valid");

        assert_eq!(summary.warning_count, 1);
        assert!(!summary.error_count.eq(&1));
        assert!(summary.successful);
    }

    #[test]
    fn error_finding_makes_summary_unsuccessful() {
        let identity =
            SummaryIdentity::new("error_test").expect("valid identity");

        let finding = SummaryFinding::new(
            SummarySeverity::Error,
            "invalid_result",
            "The benchmark result failed validation.",
        )
        .expect("valid finding");

        let input = SummaryInput::new(
            identity,
            SummaryStatus::Complete,
            vec![probability_metric(0.8)],
        )
        .with_findings(vec![finding]);

        let summary =
            BenchmarkSummary::from_input(input).expect("summary should be valid");

        assert_eq!(summary.error_count, 1);
        assert!(!summary.successful);
    }

    #[test]
    fn markdown_is_deterministic_and_contains_core_sections() {
        let summary = BenchmarkSummary::from_metrics(
            "quantum_volume",
            SummaryStatus::Complete,
            vec![quantum_volume_metric(128.0)],
        )
        .expect("summary should be valid");

        let first = summary.to_markdown();
        let second = summary.to_markdown();

        assert_eq!(first, second);
        assert!(first.contains("# Benchmark Summary"));
        assert!(first.contains("## Overview"));
        assert!(first.contains("## Metrics"));
    }

    #[test]
    fn markdown_escapes_table_delimiters() {
        assert_eq!(
            escape_markdown("a|b\nc"),
            "a\\|b c"
        );
    }

    #[test]
    fn limits_are_enforced() {
        let limits = SummaryLimits {
            max_metrics: 1,
            ..SummaryLimits::default()
        };

        let identity =
            SummaryIdentity::new("limited").expect("valid identity");

        let input = SummaryInput::new(
            identity,
            SummaryStatus::Complete,
            vec![
                probability_metric(0.5),
                quantum_volume_metric(32.0),
            ],
        )
        .with_limits(limits)
        .expect("valid limits");

        let result = BenchmarkSummary::from_input(input);

        assert!(matches!(
            result,
            Err(SummaryError::LimitExceeded {
                field: "metrics",
                ..
            })
        ));
    }

    #[test]
    fn one_line_is_stable() {
        let summary = BenchmarkSummary::from_metrics(
            "qv",
            SummaryStatus::Complete,
            vec![quantum_volume_metric(16.0)],
        )
        .expect("summary should be valid");

        assert_eq!(
            summary.one_line(),
            "qv [complete] metrics=1 findings=0 successful=true"
        );
    }
}