//! Zamani Quantum Benchmarking — Quantum Volume circuit generator.
//!
//! This module owns **circuit generation only** for Quantum Volume (QV).
//! It deliberately does not execute circuits, calculate heavy-output
//! probabilities, calculate confidence intervals, or decide whether a QV
//! experiment passed. Those responsibilities belong to the QV protocol and
//! statistical/metric layers.
//!
//! # Architecture
//!
//! ```text
//! QuantumVolumeGenerator
//!        │
//!        ├── deterministic RNG (explicit seed)
//!        ├── random permutation per layer
//!        └── versioned portable random-unitary ensemble
//!                     │
//!                     ▼
//!              quantum::ir::QuantumCircuit
//!                     │
//!                     ▼
//!          execution / ideal verification
//! ```
//!
//! The generator has no dependency on a backend, simulator, QPU, topology,
//! calibration, routing, scheduling, or benchmark-result type.
//!
//! # Quantum Volume convention
//!
//! A QV experiment normally uses square circuits whose width and depth are
//! both `m`, partitions logical qubits into random pairs at every layer, and
//! applies a random two-qubit unitary to each pair. Heavy-output analysis is
//! performed by a separate layer against the ideal distribution.
//!
//! Exact Haar-random SU(4) synthesis is not currently a primitive of Zamani's
//! canonical Quantum IR. This implementation therefore defines an explicit,
//! versioned **portable random-unitary ensemble** using `U3` and `CX`, both of
//! which are native logical IR gates. It must not be described as an exact
//! Haar sampler. The ensemble identifier is part of the generated result so
//! that incompatible QV experiments cannot silently be compared.
//!
//! # Reproducibility
//!
//! For the same generator version, width, depth, circuit index, experiment
//! seed, and ensemble, the generated logical circuit is deterministic. No
//! global RNG and no system clock are used. Each circuit derives its own RNG
//! stream, so generating circuit `N` does not depend on whether circuits
//! `0..N-1` were generated first.
//!
//! # Resource safety
//!
//! All caller-controlled dimensions are validated before circuit allocation.
//! Operation estimates use checked arithmetic. Explicit limits protect the
//! library from pathological requests.
//!
//! # Integration contract
//!
//! This file integrates only with the existing canonical Quantum IR:
//!
//! - `quantum::ir::QuantumCircuit`
//! - `quantum::ir::Gate`
//! - `quantum::ir::GateKind`
//! - `quantum::ir::Parameter`
//! - `quantum::ir::QubitId`
//! - `quantum::ir::CircuitId`
//!
//! Future `benchmarking::core`, execution, protocol, provenance, and reporting
//! layers should consume [`QuantumVolumeCircuit`] rather than reimplementing
//! QV circuit construction. This keeps the dependency direction:
//!
//! `benchmarking::generators::qv -> quantum::ir`
//!
//! and never the reverse.
//!
//! Rust compatibility: Rust 1.97.1.

use std::fmt;

use rand::rngs::StdRng;
use rand::{Rng, SeedableRng};

use crate::quantum::ir::{
    CircuitId,
    Gate,
    GateKind,
    Parameter,
    QubitId,
    QuantumCircuit,
    QuantumIrLimits,
};

/// Stable generator implementation identifier.
///
/// This value is part of benchmark provenance. A generation change that can
/// change circuits requires a new identifier/version.
pub const GENERATOR_ID: &str = "zamani.qv.portable-u3-cx.v1";

/// Generator semantic version.
pub const GENERATOR_VERSION: u32 = 1;

/// Default maximum logical width accepted by this generator.
pub const DEFAULT_MAX_QUBITS: usize = 256;

/// Default maximum logical circuit depth.
pub const DEFAULT_MAX_DEPTH: usize = 256;

/// Default maximum generated IR operations per circuit.
pub const DEFAULT_MAX_OPERATIONS: usize = 1_000_000;

/// Default maximum number of circuits generated by one request.
pub const DEFAULT_MAX_CIRCUITS: usize = 10_000;

/// Errors produced by the QV circuit generator.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum QuantumVolumeGenerationError {
    InvalidQubitCount,

    InvalidDepth,

    QubitLimitExceeded {
        requested: usize,
        maximum: usize,
    },

    DepthLimitExceeded {
        requested: usize,
        maximum: usize,
    },

    InvalidCircuitCount,

    CircuitLimitExceeded {
        requested: usize,
        maximum: usize,
    },

    CircuitIndexOutOfRange {
        index: usize,
        count: usize,
    },

    OperationLimitExceeded {
        requested: usize,
        maximum: usize,
    },

    ArithmeticOverflow {
        calculation: &'static str,
    },

    NonFiniteParameter,

    InvalidCircuit(String),
}

impl fmt::Display for QuantumVolumeGenerationError {
    fn fmt(
        &self,
        f: &mut fmt::Formatter<'_>,
    ) -> fmt::Result {
        match self {
            Self::InvalidQubitCount => {
                write!(
                    f,
                    "Quantum Volume requires at least one logical qubit"
                )
            }

            Self::InvalidDepth => {
                write!(
                    f,
                    "Quantum Volume requires a circuit depth greater than zero"
                )
            }

            Self::QubitLimitExceeded {
                requested,
                maximum,
            } => {
                write!(
                    f,
                    "Quantum Volume width {requested} exceeds generator limit {maximum}"
                )
            }

            Self::DepthLimitExceeded {
                requested,
                maximum,
            } => {
                write!(
                    f,
                    "Quantum Volume depth {requested} exceeds generator limit {maximum}"
                )
            }

            Self::InvalidCircuitCount => {
                write!(
                    f,
                    "Quantum Volume circuit count must be greater than zero"
                )
            }

            Self::CircuitLimitExceeded {
                requested,
                maximum,
            } => {
                write!(
                    f,
                    "Quantum Volume circuit count {requested} exceeds generator limit {maximum}"
                )
            }

            Self::CircuitIndexOutOfRange {
                index,
                count,
            } => {
                write!(
                    f,
                    "Quantum Volume circuit index {index} is outside circuit count {count}"
                )
            }

            Self::OperationLimitExceeded {
                requested,
                maximum,
            } => {
                write!(
                    f,
                    "generated operation count {requested} exceeds generator limit {maximum}"
                )
            }

            Self::ArithmeticOverflow {
                calculation,
            } => {
                write!(
                    f,
                    "arithmetic overflow while calculating {calculation}"
                )
            }

            Self::NonFiniteParameter => {
                write!(
                    f,
                    "generated quantum gate parameter was not finite"
                )
            }

            Self::InvalidCircuit(message) => {
                write!(
                    f,
                    "generated Quantum IR circuit is invalid: {message}"
                )
            }
        }
    }
}

impl std::error::Error for QuantumVolumeGenerationError {}

/// The random-unitary ensemble used by this generator.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum QuantumVolumeEnsemble {
    /// Versioned portable ensemble based on the current canonical IR's
    /// `U3` and `CX` gates.
    PortableU3CxV1,
}

impl QuantumVolumeEnsemble {
    /// Stable identifier used in provenance and reports.
    pub const fn id(self) -> &'static str {
        match self {
            Self::PortableU3CxV1 => "portable-u3-cx.v1",
        }
    }

    /// Stable generator implementation identifier.
    pub const fn generator_id(self) -> &'static str {
        GENERATOR_ID
    }
}

impl Default for QuantumVolumeEnsemble {
    fn default() -> Self {
        Self::PortableU3CxV1
    }
}

/// Resource limits for generated QV circuits.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct QuantumVolumeGeneratorLimits {
    /// Maximum logical qubits in one circuit.
    pub max_qubits: usize,

    /// Maximum logical circuit depth.
    pub max_depth: usize,

    /// Maximum generated IR operations in one circuit.
    pub max_operations: usize,

    /// Maximum number of circuits in one generation request.
    pub max_circuits: usize,
}

impl Default for QuantumVolumeGeneratorLimits {
    fn default() -> Self {
        Self {
            max_qubits: DEFAULT_MAX_QUBITS,
            max_depth: DEFAULT_MAX_DEPTH,
            max_operations: DEFAULT_MAX_OPERATIONS,
            max_circuits: DEFAULT_MAX_CIRCUITS,
        }
    }
}

impl QuantumVolumeGeneratorLimits {
    /// Validates the limit configuration itself.
    pub fn validate(
        self,
    ) -> Result<(), QuantumVolumeGenerationError> {
        if self.max_qubits == 0 {
            return Err(
                QuantumVolumeGenerationError::QubitLimitExceeded {
                    requested: 1,
                    maximum: 0,
                },
            );
        }

        if self.max_depth == 0 {
            return Err(
                QuantumVolumeGenerationError::DepthLimitExceeded {
                    requested: 1,
                    maximum: 0,
                },
            );
        }

        if self.max_operations == 0 {
            return Err(
                QuantumVolumeGenerationError::OperationLimitExceeded {
                    requested: 1,
                    maximum: 0,
                },
            );
        }

        if self.max_circuits == 0 {
            return Err(
                QuantumVolumeGenerationError::CircuitLimitExceeded {
                    requested: 1,
                    maximum: 0,
                },
            );
        }

        Ok(())
    }
}

/// Immutable description of one generated QV circuit.
///
/// This is the generation-layer contract for the future QV protocol, executor,
/// ideal verifier, provenance, and reporting layers.
#[derive(Debug, Clone)]
pub struct QuantumVolumeCircuit {
    /// Canonical logical Quantum IR circuit.
    pub circuit: QuantumCircuit,

    /// QV logical width.
    pub width: usize,

    /// QV logical depth.
    pub depth: usize,

    /// Zero-based index within the experiment's circuit sequence.
    pub circuit_index: usize,

    /// Experiment seed supplied by the caller.
    pub seed: u64,

    /// Stable circuit-generation identity.
    pub generator_id: &'static str,

    /// Stable generation algorithm version.
    pub generator_version: u32,

    /// Random-unitary ensemble.
    pub ensemble: QuantumVolumeEnsemble,

    /// Number of generated two-qubit blocks.
    pub two_qubit_blocks: usize,

    /// Number of generated IR operations.
    pub operation_count: usize,
}

impl QuantumVolumeCircuit {
    /// Returns the stable ensemble identifier.
    pub const fn ensemble_id(
        &self,
    ) -> &'static str {
        self.ensemble.id()
    }

    /// Returns the logical circuit identity.
    pub const fn circuit_id(
        &self,
    ) -> CircuitId {
        self.circuit.id()
    }

    /// Validates the generated circuit against canonical Quantum IR.
    pub fn validate(
        &self,
    ) -> Result<(), QuantumVolumeGenerationError> {
        self.circuit
            .validate()
            .map_err(|error| {
                QuantumVolumeGenerationError::InvalidCircuit(
                    error.to_string(),
                )
            })
    }
}

/// Production Quantum Volume circuit generator.
///
/// It contains no mutable RNG. Every circuit gets an independent deterministic
/// stream derived from the explicit experiment seed and circuit identity.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct QuantumVolumeGenerator {
    limits: QuantumVolumeGeneratorLimits,
    ensemble: QuantumVolumeEnsemble,
}

impl Default for QuantumVolumeGenerator {
    fn default() -> Self {
        Self::new()
    }
}

impl QuantumVolumeGenerator {
    /// Creates the production generator with conservative resource limits.
    pub const fn new() -> Self {
        Self {
            limits: QuantumVolumeGeneratorLimits {
                max_qubits: DEFAULT_MAX_QUBITS,
                max_depth: DEFAULT_MAX_DEPTH,
                max_operations: DEFAULT_MAX_OPERATIONS,
                max_circuits: DEFAULT_MAX_CIRCUITS,
            },

            ensemble: QuantumVolumeEnsemble::PortableU3CxV1,
        }
    }

    /// Creates a generator with explicit resource limits.
    pub fn with_limits(
        limits: QuantumVolumeGeneratorLimits,
    ) -> Result<Self, QuantumVolumeGenerationError> {
        limits.validate()?;

        Ok(Self {
            limits,
            ensemble: QuantumVolumeEnsemble::PortableU3CxV1,
        })
    }

    /// Creates a generator with explicit limits and ensemble.
    pub fn with_limits_and_ensemble(
        limits: QuantumVolumeGeneratorLimits,
        ensemble: QuantumVolumeEnsemble,
    ) -> Result<Self, QuantumVolumeGenerationError> {
        limits.validate()?;

        Ok(Self {
            limits,
            ensemble,
        })
    }

    /// Returns configured resource limits.
    pub const fn limits(
        &self,
    ) -> QuantumVolumeGeneratorLimits {
        self.limits
    }

    /// Returns the configured ensemble.
    pub const fn ensemble(
        &self,
    ) -> QuantumVolumeEnsemble {
        self.ensemble
    }

    /// Validates a QV experiment before circuit allocation.
    pub fn validate_experiment(
        &self,
        width: usize,
        depth: usize,
        circuit_count: usize,
    ) -> Result<(), QuantumVolumeGenerationError> {
        self.limits.validate()?;

        if width == 0 {
            return Err(
                QuantumVolumeGenerationError::InvalidQubitCount
            );
        }

        if depth == 0 {
            return Err(
                QuantumVolumeGenerationError::InvalidDepth
            );
        }

        if width > self.limits.max_qubits {
            return Err(
                QuantumVolumeGenerationError::QubitLimitExceeded {
                    requested: width,
                    maximum: self.limits.max_qubits,
                },
            );
        }

        if depth > self.limits.max_depth {
            return Err(
                QuantumVolumeGenerationError::DepthLimitExceeded {
                    requested: depth,
                    maximum: self.limits.max_depth,
                },
            );
        }

        if circuit_count == 0 {
            return Err(
                QuantumVolumeGenerationError::InvalidCircuitCount
            );
        }

        if circuit_count > self.limits.max_circuits {
            return Err(
                QuantumVolumeGenerationError::CircuitLimitExceeded {
                    requested: circuit_count,
                    maximum: self.limits.max_circuits,
                },
            );
        }

        let estimated =
            Self::estimate_operations(width, depth)?;

        if estimated > self.limits.max_operations {
            return Err(
                QuantumVolumeGenerationError::OperationLimitExceeded {
                    requested: estimated,
                    maximum: self.limits.max_operations,
                },
            );
        }

        // Ensure the current production IR policy can represent the
        // generated circuit before allocating it.
        let ir_limits =
            QuantumIrLimits::production();

        ir_limits
            .check_qubits(width)
            .map_err(|error| {
                QuantumVolumeGenerationError::InvalidCircuit(
                    error.to_string(),
                )
            })?;

        ir_limits
            .check_operations(estimated)
            .map_err(|error| {
                QuantumVolumeGenerationError::InvalidCircuit(
                    error.to_string(),
                )
            })?;

        Ok(())
    }

    /// Estimates the number of IR operations emitted by the portable ensemble.
    ///
    /// Each logical qubit receives two `U3` operations per layer and each
    /// complete pair receives one `CX`.
    ///
    /// Therefore:
    ///
    /// `operations = depth * (2 * width + floor(width / 2))`
    pub fn estimate_operations(
        width: usize,
        depth: usize,
    ) -> Result<usize, QuantumVolumeGenerationError> {
        if width == 0 {
            return Err(
                QuantumVolumeGenerationError::InvalidQubitCount
            );
        }

        if depth == 0 {
            return Err(
                QuantumVolumeGenerationError::InvalidDepth
            );
        }

        let single_qubit_ops = width
            .checked_mul(2)
            .and_then(|value| {
                value.checked_mul(depth)
            })
            .ok_or(
                QuantumVolumeGenerationError::ArithmeticOverflow {
                    calculation:
                        "QV single-qubit operation count",
                },
            )?;

        let pair_count =
            width / 2;

        let entangling_ops = pair_count
            .checked_mul(depth)
            .ok_or(
                QuantumVolumeGenerationError::ArithmeticOverflow {
                    calculation:
                        "QV entangling operation count",
                },
            )?;

        single_qubit_ops
            .checked_add(entangling_ops)
            .ok_or(
                QuantumVolumeGenerationError::ArithmeticOverflow {
                    calculation:
                        "QV total operation count",
                },
            )
    }

    /// Generates one deterministic QV circuit.
    pub fn generate(
        &self,
        width: usize,
        depth: usize,
        seed: u64,
        circuit_index: usize,
        circuit_count: usize,
    ) -> Result<
        QuantumVolumeCircuit,
        QuantumVolumeGenerationError,
    > {
        self.validate_experiment(
            width,
            depth,
            circuit_count,
        )?;

        if circuit_index >= circuit_count {
            return Err(
                QuantumVolumeGenerationError::CircuitIndexOutOfRange {
                    index: circuit_index,
                    count: circuit_count,
                },
            );
        }

        let operation_count =
            Self::estimate_operations(
                width,
                depth,
            )?;

        let circuit_id =
            derive_circuit_id(
                seed,
                circuit_index,
                width,
                depth,
            );

        let mut circuit =
            QuantumCircuit::with_identity(
                circuit_id,
                width,
                0,
                QuantumIrLimits::production(),
            )
            .map_err(|error| {
                QuantumVolumeGenerationError::InvalidCircuit(
                    error.to_string(),
                )
            })?;

        circuit
            .set_name(Some(format!(
                "zamani-qv-{width}x{depth}-{circuit_index}"
            )))
            .map_err(|error| {
                QuantumVolumeGenerationError::InvalidCircuit(
                    error.to_string(),
                )
            })?;

        circuit
            .set_source(Some(format!(
                "{GENERATOR_ID}:{}",
                self.ensemble.id()
            )))
            .map_err(|error| {
                QuantumVolumeGenerationError::InvalidCircuit(
                    error.to_string(),
                )
            })?;

        let mut rng =
            circuit_rng(
                seed,
                circuit_index,
                width,
                depth,
            );

        let mut two_qubit_blocks =
            0usize;

        for _layer in 0..depth {
            let permutation =
                random_permutation(
                    width,
                    &mut rng,
                );

            for pair_start
                in (0..width).step_by(2)
            {
                let first =
                    permutation[pair_start];

                if pair_start + 1 < width {
                    let second =
                        permutation[pair_start + 1];

                    append_random_u3(
                        &mut circuit,
                        first,
                        &mut rng,
                    )?;

                    append_random_u3(
                        &mut circuit,
                        second,
                        &mut rng,
                    )?;

                    append_cx(
                        &mut circuit,
                        first,
                        second,
                    )?;

                    append_random_u3(
                        &mut circuit,
                        first,
                        &mut rng,
                    )?;

                    append_random_u3(
                        &mut circuit,
                        second,
                        &mut rng,
                    )?;

                    two_qubit_blocks =
                        two_qubit_blocks
                            .checked_add(1)
                            .ok_or(
                                QuantumVolumeGenerationError::ArithmeticOverflow {
                                    calculation:
                                        "QV two-qubit block count",
                                },
                            )?;
                } else {
                    // Odd-width layers have one unpaired logical qubit.
                    append_random_u3(
                        &mut circuit,
                        first,
                        &mut rng,
                    )?;

                    append_random_u3(
                        &mut circuit,
                        first,
                        &mut rng,
                    )?;
                }
            }
        }

        if circuit.len() != operation_count {
            return Err(
                QuantumVolumeGenerationError::InvalidCircuit(
                    format!(
                        "generator emitted {} operations but resource model predicted {}",
                        circuit.len(),
                        operation_count
                    ),
                ),
            );
        }

        circuit
            .validate()
            .map_err(|error| {
                QuantumVolumeGenerationError::InvalidCircuit(
                    error.to_string(),
                )
            })?;

        Ok(QuantumVolumeCircuit {
            circuit,
            width,
            depth,
            circuit_index,
            seed,
            generator_id: GENERATOR_ID,
            generator_version:
                GENERATOR_VERSION,
            ensemble: self.ensemble,
            two_qubit_blocks,
            operation_count,
        })
    }

    /// Generates every circuit in an experiment deterministically.
    ///
    /// The complete request is validated before the output vector is
    /// allocated. Each circuit is generated independently from the same
    /// experiment seed.
    pub fn generate_all(
        &self,
        width: usize,
        depth: usize,
        seed: u64,
        circuit_count: usize,
    ) -> Result<
        Vec<QuantumVolumeCircuit>,
        QuantumVolumeGenerationError,
    > {
        self.validate_experiment(
            width,
            depth,
            circuit_count,
        )?;

        let mut circuits =
            Vec::with_capacity(circuit_count);

        for circuit_index
            in 0..circuit_count
        {
            circuits.push(
                self.generate(
                    width,
                    depth,
                    seed,
                    circuit_index,
                    circuit_count,
                )?,
            );
        }

        Ok(circuits)
    }
}

/// Creates the deterministic RNG stream for one QV circuit.
fn circuit_rng(
    seed: u64,
    circuit_index: usize,
    width: usize,
    depth: usize,
) -> StdRng {
    let mut material =
        [0u8; 32];

    material[0..8]
        .copy_from_slice(
            &seed.to_le_bytes(),
        );

    material[8..16]
        .copy_from_slice(
            &(circuit_index as u64)
                .to_le_bytes(),
        );

    material[16..24]
        .copy_from_slice(
            &(width as u64)
                .to_le_bytes(),
        );

    material[24..32]
        .copy_from_slice(
            &(depth as u64)
                .to_le_bytes(),
        );

    StdRng::from_seed(material)
}

/// Derives a stable circuit identity without a global counter.
///
/// This is an identity derivation primitive, not a cryptographic hash.
fn derive_circuit_id(
    seed: u64,
    index: usize,
    width: usize,
    depth: usize,
) -> CircuitId {
    let mut x =
        seed
            ^ (index as u64)
                .wrapping_mul(
                    0x9E37_79B9_7F4A_7C15,
                )
            ^ (width as u64)
                .rotate_left(17)
            ^ (depth as u64)
                .rotate_left(31)
            ^ (GENERATOR_VERSION as u64)
                .rotate_left(47);

    x = (x ^ (x >> 30))
        .wrapping_mul(
            0xBF58_476D_1CE4_E5B9,
        );

    x = (x ^ (x >> 27))
        .wrapping_mul(
            0x94D0_49BB_1331_11EB,
        );

    x ^= x >> 31;

    CircuitId::new(x)
}

/// Generates a Fisher-Yates permutation using the circuit-local RNG.
fn random_permutation(
    width: usize,
    rng: &mut StdRng,
) -> Vec<usize> {
    let mut permutation:
        Vec<usize> =
        (0..width).collect();

    for i in (1..width).rev() {
        let j =
            rng.gen_range(0..=i);

        permutation.swap(i, j);
    }

    permutation
}

/// Appends a random portable single-qubit unitary represented by `U3`.
///
/// The angles are sampled uniformly over their coordinate ranges. This is a
/// deliberately defined portable ensemble and is not an exact Haar sampler.
fn append_random_u3(
    circuit: &mut QuantumCircuit,
    qubit: usize,
    rng: &mut StdRng,
) -> Result<(), QuantumVolumeGenerationError> {
    let theta =
        rng.gen_range(
            0.0..std::f64::consts::PI,
        );

    let phi =
        rng.gen_range(
            0.0..(
                2.0
                    * std::f64::consts::PI
            ),
        );

    let lambda =
        rng.gen_range(
            0.0..(
                2.0
                    * std::f64::consts::PI
            ),
        );

    append_gate(
        circuit,
        GateKind::U3,
        vec![qubit],
        vec![
            theta,
            phi,
            lambda,
        ],
    )
}

/// Appends a logical CNOT to the canonical IR.
fn append_cx(
    circuit: &mut QuantumCircuit,
    control: usize,
    target: usize,
) -> Result<(), QuantumVolumeGenerationError> {
    append_gate(
        circuit,
        GateKind::CX,
        vec![
            control,
            target,
        ],
        Vec::new(),
    )
}

/// Constructs and appends one validated canonical IR gate.
fn append_gate(
    circuit: &mut QuantumCircuit,
    kind: GateKind,
    qubits: Vec<usize>,
    parameter_values: Vec<f64>,
) -> Result<(), QuantumVolumeGenerationError> {
    let mut parameters =
        Vec::with_capacity(
            parameter_values.len(),
        );

    for value in parameter_values {
        if !value.is_finite() {
            return Err(
                QuantumVolumeGenerationError::NonFiniteParameter
            );
        }

        let parameter =
            Parameter::constant(value)
                .map_err(|_| {
                    QuantumVolumeGenerationError::NonFiniteParameter
                })?;

        parameters.push(parameter);
    }

    let qubits =
        qubits
            .into_iter()
            .map(QubitId::new)
            .collect();

    let gate =
        Gate::new(
            kind,
            qubits,
            parameters,
            None,
            None,
        )
        .map_err(|error| {
            QuantumVolumeGenerationError::InvalidCircuit(
                error.to_string(),
            )
        })?;

    circuit
        .push(gate)
        .map_err(|error| {
            QuantumVolumeGenerationError::InvalidCircuit(
                error.to_string(),
            )
        })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn default_limits_are_valid() {
        assert!(
            QuantumVolumeGeneratorLimits::default()
                .validate()
                .is_ok()
        );
    }

    #[test]
    fn rejects_zero_width() {
        let generator =
            QuantumVolumeGenerator::new();

        assert_eq!(
            generator.validate_experiment(
                0,
                4,
                1,
            ),
            Err(
                QuantumVolumeGenerationError
                    ::InvalidQubitCount
            )
        );
    }

    #[test]
    fn rejects_zero_depth() {
        let generator =
            QuantumVolumeGenerator::new();

        assert_eq!(
            generator.validate_experiment(
                4,
                0,
                1,
            ),
            Err(
                QuantumVolumeGenerationError
                    ::InvalidDepth
            )
        );
    }

    #[test]
    fn operation_estimate_matches_even_width_generation() {
        assert_eq!(
            QuantumVolumeGenerator
                ::estimate_operations(
                    4,
                    3,
                )
                .unwrap(),
            30
        );
    }

    #[test]
    fn operation_estimate_matches_odd_width_generation() {
        assert_eq!(
            QuantumVolumeGenerator
                ::estimate_operations(
                    5,
                    3,
                )
                .unwrap(),
            36
        );
    }

    #[test]
    fn same_seed_and_identity_produce_identical_circuits() {
        let generator =
            QuantumVolumeGenerator::new();

        let left =
            generator
                .generate(
                    4,
                    4,
                    42,
                    0,
                    8,
                )
                .unwrap();

        let right =
            generator
                .generate(
                    4,
                    4,
                    42,
                    0,
                    8,
                )
                .unwrap();

        assert_eq!(
            left.circuit,
            right.circuit
        );

        assert_eq!(
            left.circuit_id(),
            right.circuit_id()
        );

        assert_eq!(
            left.operation_count,
            right.operation_count
        );
    }

    #[test]
    fn circuit_index_is_part_of_reproducible_stream() {
        let generator =
            QuantumVolumeGenerator::new();

        let first =
            generator
                .generate(
                    4,
                    4,
                    42,
                    0,
                    8,
                )
                .unwrap();

        let second =
            generator
                .generate(
                    4,
                    4,
                    42,
                    1,
                    8,
                )
                .unwrap();

        assert_ne!(
            first.circuit,
            second.circuit
        );

        assert_ne!(
            first.circuit_id(),
            second.circuit_id()
        );
    }

    #[test]
    fn changing_seed_changes_the_circuit() {
        let generator =
            QuantumVolumeGenerator::new();

        let first =
            generator
                .generate(
                    4,
                    4,
                    42,
                    0,
                    8,
                )
                .unwrap();

        let second =
            generator
                .generate(
                    4,
                    4,
                    43,
                    0,
                    8,
                )
                .unwrap();

        assert_ne!(
            first.circuit,
            second.circuit
        );
    }

    #[test]
    fn generated_circuit_is_canonical_ir_valid() {
        let generator =
            QuantumVolumeGenerator::new();

        let generated =
            generator
                .generate(
                    5,
                    3,
                    42,
                    0,
                    4,
                )
                .unwrap();

        assert_eq!(
            generated.width,
            5
        );

        assert_eq!(
            generated.depth,
            3
        );

        assert_eq!(
            generated.circuit.num_qubits(),
            5
        );

        assert_eq!(
            generated.circuit.len(),
            36
        );

        assert_eq!(
            generated.two_qubit_blocks,
            6
        );

        assert!(
            generated.validate().is_ok()
        );
    }

    #[test]
    fn generated_operations_have_expected_kinds() {
        let generator =
            QuantumVolumeGenerator::new();

        let generated =
            generator
                .generate(
                    4,
                    2,
                    42,
                    0,
                    1,
                )
                .unwrap();

        assert_eq!(
            generated.circuit.len(),
            20
        );

        assert!(
            generated
                .circuit
                .operations()
                .iter()
                .any(
                    |gate| {
                        gate.kind()
                            == GateKind::CX
                    }
                )
        );

        assert!(
            generated
                .circuit
                .operations()
                .iter()
                .all(
                    |gate| {
                        matches!(
                            gate.kind(),
                            GateKind::U3
                                | GateKind::CX
                        )
                    }
                )
        );
    }

    #[test]
    fn resource_limit_prevents_excessive_generation() {
        let limits =
            QuantumVolumeGeneratorLimits {
                max_qubits: 4,
                max_depth: 4,
                max_operations: 10,
                max_circuits: 2,
            };

        let generator =
            QuantumVolumeGenerator
                ::with_limits(
                    limits,
                )
                .unwrap();

        let error =
            generator
                .generate(
                    4,
                    4,
                    1,
                    0,
                    1,
                )
                .unwrap_err();

        assert!(matches!(
            error,
            QuantumVolumeGenerationError
                ::OperationLimitExceeded {
                    ..
                }
        ));
    }

    #[test]
    fn circuit_count_is_validated_before_allocation() {
        let limits =
            QuantumVolumeGeneratorLimits {
                max_qubits: 8,
                max_depth: 8,
                max_operations: 1_000,
                max_circuits: 2,
            };

        let generator =
            QuantumVolumeGenerator
                ::with_limits(
                    limits,
                )
                .unwrap();

        assert!(matches!(
            generator.generate_all(
                4,
                4,
                1,
                3,
            ),
            Err(
                QuantumVolumeGenerationError
                    ::CircuitLimitExceeded {
                        ..
                    }
            )
        ));
    }

    #[test]
    fn generated_circuit_metadata_contains_generator_identity() {
        let generator =
            QuantumVolumeGenerator::new();

        let generated =
            generator
                .generate(
                    2,
                    2,
                    7,
                    0,
                    1,
                )
                .unwrap();

        assert_eq!(
            generated.generator_id,
            GENERATOR_ID
        );

        assert_eq!(
            generated.generator_version,
            GENERATOR_VERSION
        );

        assert_eq!(
            generated.ensemble_id(),
            "portable-u3-cx.v1"
        );
    }
}