//! Zamani Quantum Routing — Candidate Generation
//!
//! `src/quantum/routing/candidates.rs`
//!
//! Production-grade candidate generation for topology-aware quantum routing.
//!
//! # Architectural responsibility
//!
//! This module generates and deterministically ranks *possible routing moves*
//! from the current physical topology and logical-to-physical mapping.
//!
//! Its primary use cases are:
//!
//! - basic routing;
//! - shortest-path routing;
//! - lookahead routing;
//! - SABRE/LightSABRE-style routing;
//! - noise-aware routing;
//! - dynamic routing;
//! - custom routing algorithms.
//!
//! The central candidate generated by this module is a physical SWAP between
//! two currently adjacent physical qubits.
//!
//! # This module does NOT own
//!
//! - topology storage;
//! - logical-to-physical mapping storage;
//! - shortest-path algorithms;
//! - layout selection;
//! - routing orchestration;
//! - gate decomposition;
//! - hardware execution;
//! - scheduling;
//! - pulse generation;
//! - calibration acquisition;
//! - OpenQASM parsing;
//! - Quantum IR implementation details;
//! - QEC decoding;
//! - simulation.
//!
//! Those responsibilities belong to the corresponding routing/backend
//! subsystems.
//!
//! # Stable dependency direction
//!
//! ```text
//!                         types.rs
//!                            │
//!              ┌─────────────┼─────────────┐
//!              ▼             ▼             ▼
//!         topology.rs    mapping.rs      cost.rs
//!              │             │             │
//!              └─────────────┼─────────────┘
//!                            ▼
//!                      candidates.rs
//!                            │
//!                ┌───────────┼────────────┐
//!                ▼           ▼            ▼
//!             lookahead    SABRE      noise-aware
//!                │           │            │
//!                └───────────┼────────────┘
//!                            ▼
//!                          router
//! ```
//!
//! `candidates.rs` is therefore a middle-layer primitive. It must remain
//! independent of concrete routing algorithms.
//!
//! # Important design rule
//!
//! Candidate generation MUST NOT mutate the caller's mapping.
//!
//! A routing algorithm may evaluate hundreds or millions of possible moves.
//! Each candidate is a hypothetical transition. The real mapping is mutated
//! only after the routing algorithm has selected and committed a move.
//!
//! # Determinism
//!
//! Candidate generation is deterministic for deterministic inputs.
//!
//! Determinism is guaranteed by:
//!
//! - deterministic topology neighbor iteration;
//! - canonical `(a, b)` physical-edge ordering;
//! - duplicate elimination;
//! - stable candidate identifiers;
//! - deterministic score tie-breaking;
//! - no dependence on `HashMap` iteration order;
//! - no random state in this module.
//!
//! If a stochastic algorithm wants multiple trials, the algorithm layer owns
//! the seed and trial policy. This file remains deterministic.
//!
//! # Candidate semantics
//!
//! A candidate represents a *hypothetical physical movement*.
//!
//! For a SWAP candidate:
//!
//! ```text
//! physical a <────SWAP────> physical b
//! ```
//!
//! If:
//!
//! ```text
//! logical q0 -> physical a
//! logical q1 -> physical b
//! ```
//!
//! then after the hypothetical candidate:
//!
//! ```text
//! logical q0 -> physical b
//! logical q1 -> physical a
//! ```
//!
//! No actual mapping mutation occurs during generation.
//!
//! # Distance-provider boundary
//!
//! SABRE/lookahead routing needs physical interaction distances. However,
//! shortest-path computation belongs to `path.rs`, not this file.
//!
//! Therefore this module defines [`CandidateDistanceProvider`].
//!
//! `path.rs` can implement that trait later without changing this file.
//!
//! This avoids the circular dependency:
//!
//! ```text
//! candidates -> path -> candidates
//! ```
//!
//! Instead:
//!
//! ```text
//! path.rs ─────implements────► CandidateDistanceProvider
//! candidates.rs ──consumes────► CandidateDistanceProvider
//! ```
//!
//! # Cost-model boundary
//!
//! Candidate generation can optionally evaluate candidates using the stable
//! [`CostModel`] trait from `cost.rs`.
//!
//! The candidate generator constructs [`CostCandidate`] values but does not
//! implement routing objectives itself.
//!
//! # Resource safety
//!
//! Candidate generation is explicitly bounded by a maximum candidate count.
//! This prevents a malformed or unexpectedly large topology from causing an
//! unbounded allocation.
//!
//! # Rust compatibility
//!
//! Target:
//!
//! - Rust 1.97;
//! - Rust 1.97.1;
//! - Rust 2021;
//! - stable Rust;
//! - no nightly features.
//!
//! # Safety
//!
//! Unsafe Rust is forbidden.
//!
//! ```text
//! #![deny(unsafe_code)]
//! #![deny(unsafe_op_in_unsafe_fn)]
//! #![deny(unused_must_use)]
//! ```
//!
//! # File completion invariant
//!
//! This file is complete when:
//!
//! 1. candidates use typed physical identifiers;
//! 2. candidate generation never mutates the caller's mapping;
//! 3. candidate endpoints are canonicalized;
//! 4. duplicate physical edges cannot create duplicate candidates;
//! 5. unavailable qubits are excluded;
//! 6. one-way directed edges cannot silently become SWAPs;
//! 7. candidate generation is bounded;
//! 8. candidate ordering is deterministic;
//! 9. candidate identity is stable;
//! 10. front-layer and extended-layer distances can be supplied by a path
//!     provider;
//! 11. cost models can evaluate candidates without coupling to algorithms;
//! 12. arithmetic cannot silently overflow;
//! 13. empty candidate sets are represented explicitly;
//! 14. the caller's mapping remains unchanged;
//! 15. the public API does not depend on future algorithm implementations;
//! 16. no unsafe code exists;
//! 17. the file is compatible with Rust 1.97/1.97.1.

#![deny(unsafe_code)]
#![deny(unsafe_op_in_unsafe_fn)]
#![deny(unused_must_use)]

use crate::quantum::routing::cost::{
    CostCandidate,
    CostModel,
    RoutingCost,
    RoutingMetrics,
    WEIGHT_SCALE,
};
use crate::quantum::routing::errors::{
    CandidateError,
    RoutingResult,
};
use crate::quantum::routing::mapping::QubitMapping;
use crate::quantum::routing::topology::PhysicalTopology;
use crate::quantum::routing::types::{
    LogicalQubitId,
    PhysicalQubitId,
    QubitInteraction,
};

use std::cmp::Ordering;
use std::collections::BTreeSet;
use std::fmt;

// =============================================================================
// Constants
// =============================================================================

/// Conservative default maximum number of candidates returned by one
/// generation request.
///
/// The routing configuration layer also defines a candidate limit. This local
/// constant is intentionally useful for direct users of `CandidateGenerator`
/// that do not construct a full `RoutingConfig`.
pub const DEFAULT_MAX_CANDIDATES: usize = 64;

/// Maximum candidate count accepted by the candidate-generation API.
///
/// This protects direct callers from accidentally requesting an effectively
/// unbounded candidate set.
pub const MAX_CANDIDATES: usize = 1_000_000;

/// Default decay factor representing 1.0 in the fixed-point representation
/// used by `cost.rs`.
pub const DEFAULT_DECAY_FACTOR: u64 = WEIGHT_SCALE;

/// Maximum number of interactions that may be accumulated into one candidate
/// evaluation without an explicit larger caller-controlled bound.
///
/// This prevents pathological input from silently overflowing counters.
pub const DEFAULT_MAX_INTERACTIONS: usize = 1_000_000;

// =============================================================================
// Candidate kind
// =============================================================================

/// Physical movement represented by a routing candidate.
///
/// Routing currently treats SWAP as the fundamental movement primitive.
/// Future movement types can be added here without changing the candidate
/// identity, ranking, or generation contracts.
///
/// The candidate generator deliberately does not turn a SWAP into CX gates.
/// That is the responsibility of the movement/lowering stage.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum CandidateMove {
    /// Exchange the quantum states occupying two physical qubits.
    Swap {
        /// First physical endpoint.
        a: PhysicalQubitId,

        /// Second physical endpoint.
        b: PhysicalQubitId,
    },
}

impl CandidateMove {
    /// Creates a canonical SWAP candidate.
    ///
    /// Physical endpoints are normalized so that:
    ///
    /// ```text
    /// Swap(a, b)
    /// ```
    ///
    /// and:
    ///
    /// ```text
    /// Swap(b, a)
    /// ```
    ///
    /// represent the same movement.
    #[must_use]
    pub fn swap(
        a: PhysicalQubitId,
        b: PhysicalQubitId,
    ) -> Option<Self> {
        if a == b {
            return None;
        }

        let (first, second) = canonical_edge(a, b);

        Some(Self::Swap {
            a: first,
            b: second,
        })
    }

    /// Returns the first physical endpoint.
    #[must_use]
    pub const fn a(self) -> PhysicalQubitId {
        match self {
            Self::Swap { a, .. } => a,
        }
    }

    /// Returns the second physical endpoint.
    #[must_use]
    pub const fn b(self) -> PhysicalQubitId {
        match self {
            Self::Swap { b, .. } => b,
        }
    }

    /// Returns the movement kind's stable name.
    #[must_use]
    pub const fn name(self) -> &'static str {
        match self {
            Self::Swap { .. } => "swap",
        }
    }

    /// Returns whether this movement is a SWAP.
    #[must_use]
    pub const fn is_swap(self) -> bool {
        matches!(self, Self::Swap { .. })
    }
}

impl fmt::Display for CandidateMove {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Swap { a, b } => {
                write!(formatter, "swap({a},{b})")
            }
        }
    }
}

// =============================================================================
// Candidate identifier
// =============================================================================

/// Stable identifier for a routing candidate.
///
/// The identifier is intentionally structural rather than hash-randomized.
/// It is therefore stable across executions and suitable for:
///
/// - deterministic tests;
/// - diagnostics;
/// - benchmark reports;
/// - cache keys;
/// - candidate trace output.
///
/// The current representation is sufficient for physical SWAP candidates and
/// leaves room for future movement kinds.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct CandidateId {
    /// First physical endpoint.
    pub a: PhysicalQubitId,

    /// Second physical endpoint.
    pub b: PhysicalQubitId,
}

impl CandidateId {
    /// Creates a canonical candidate identifier.
    #[must_use]
    pub fn new(
        a: PhysicalQubitId,
        b: PhysicalQubitId,
    ) -> Option<Self> {
        if a == b {
            return None;
        }

        let (a, b) = canonical_edge(a, b);

        Some(Self { a, b })
    }

    /// Creates an identifier from a movement.
    #[must_use]
    pub fn from_move(movement: CandidateMove) -> Self {
        match movement {
            CandidateMove::Swap { a, b } => {
                // `CandidateMove::swap` already canonicalizes endpoints.
                Self { a, b }
            }
        }
    }
}

impl fmt::Display for CandidateId {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(formatter, "swap:{}:{}", self.a, self.b)
    }
}

// =============================================================================
// Candidate context
// =============================================================================

/// Immutable routing context used while generating candidates.
///
/// The context deliberately contains references rather than owning routing
/// state. Candidate generation therefore cannot accidentally replace the
/// caller's topology or mapping.
///
/// The front layer is the set of interactions currently eligible for routing.
/// The extended layer contains future interactions used by lookahead/SABRE
/// heuristics.
///
/// The slices may be empty:
///
/// - an empty front layer is useful when generating generic topology moves;
/// - an empty extended layer disables future-lookahead scoring.
pub struct CandidateContext<'a> {
    /// Current physical topology.
    pub topology: &'a PhysicalTopology,

    /// Current logical-to-physical mapping.
    pub mapping: &'a QubitMapping,

    /// Interactions currently at the routing front layer.
    pub front_layer: &'a [QubitInteraction],

    /// Future interactions considered by lookahead.
    pub extended_layer: &'a [QubitInteraction],
}

impl<'a> CandidateContext<'a> {
    /// Creates a candidate-generation context.
    #[must_use]
    pub const fn new(
        topology: &'a PhysicalTopology,
        mapping: &'a QubitMapping,
        front_layer: &'a [QubitInteraction],
        extended_layer: &'a [QubitInteraction],
    ) -> Self {
        Self {
            topology,
            mapping,
            front_layer,
            extended_layer,
        }
    }

    /// Returns the number of front-layer interactions.
    #[must_use]
    pub const fn front_layer_len(&self) -> usize {
        self.front_layer.len()
    }

    /// Returns the number of extended-layer interactions.
    #[must_use]
    pub const fn extended_layer_len(&self) -> usize {
        self.extended_layer.len()
    }
}

// =============================================================================
// Distance provider
// =============================================================================

/// Provides physical interaction distance to candidate generation.
///
/// The concrete shortest-path implementation belongs in `path.rs`.
///
/// A distance provider MUST:
///
/// 1. return `Some(0)` for identical physical qubits;
/// 2. return `Some(d)` for connected physical qubits;
/// 3. return `None` for disconnected/unreachable physical qubits;
/// 4. be deterministic for deterministic topology input;
/// 5. never mutate the topology or routing state.
///
/// `candidates.rs` does not implement shortest paths because that would create
/// an architectural overlap with `path.rs`.
pub trait CandidateDistanceProvider: Send + Sync {
    /// Returns the physical distance between two qubits.
    fn distance(
        &self,
        topology: &PhysicalTopology,
        from: PhysicalQubitId,
        to: PhysicalQubitId,
    ) -> Option<u64>;
}

/// Simple callback-backed distance provider.
///
/// This adapter lets path-finding code supply a function without having to
/// create a dedicated type.
pub struct FnDistanceProvider<F> {
    function: F,
}

impl<F> FnDistanceProvider<F> {
    /// Creates a callback-backed distance provider.
    #[must_use]
    pub const fn new(function: F) -> Self {
        Self { function }
    }
}

impl<F> CandidateDistanceProvider for FnDistanceProvider<F>
where
    F: Fn(
            &PhysicalTopology,
            PhysicalQubitId,
            PhysicalQubitId,
        ) -> Option<u64>
        + Send
        + Sync,
{
    fn distance(
        &self,
        topology: &PhysicalTopology,
        from: PhysicalQubitId,
        to: PhysicalQubitId,
    ) -> Option<u64> {
        (self.function)(topology, from, to)
    }
}

// =============================================================================
// Candidate projection
// =============================================================================

/// Result of applying a candidate *hypothetically* to one physical location.
///
/// This type is internal to candidate scoring and does not mutate the real
/// mapping.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
struct PhysicalProjection {
    physical: PhysicalQubitId,
}

impl PhysicalProjection {
    /// Returns the physical location after a hypothetical SWAP.
    #[must_use]
    fn after_swap(
        physical: PhysicalQubitId,
        a: PhysicalQubitId,
        b: PhysicalQubitId,
    ) -> Self {
        let projected = if physical == a {
            b
        } else if physical == b {
            a
        } else {
            physical
        };

        Self {
            physical: projected,
        }
    }
}

// =============================================================================
// Candidate
// =============================================================================

/// Immutable routing candidate.
///
/// A candidate contains:
///
/// - its stable identity;
/// - its physical movement;
/// - the predicted routing metrics;
/// - optional evaluated cost.
///
/// It contains no mutable mapping and no topology-owned state.
///
/// # Important semantic property
///
/// A `SwapCandidate` is a *proposal*, not an already-applied SWAP.
///
/// The actual routing algorithm decides whether to commit it.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SwapCandidate {
    /// Stable structural candidate identifier.
    id: CandidateId,

    /// Physical movement represented by this candidate.
    movement: CandidateMove,

    /// Predicted metrics after applying the movement.
    metrics: RoutingMetrics,

    /// Optional cost-model evaluation.
    cost: Option<RoutingCost>,

    /// Front-layer heuristic distance after the hypothetical movement.
    front_layer_distance: u64,

    /// Extended/lookahead heuristic distance after the hypothetical movement.
    extended_layer_distance: u64,

    /// Fixed-point decay factor associated with this candidate.
    decay_factor: u64,
}

impl SwapCandidate {
    /// Creates a candidate without cost-model evaluation.
    ///
    /// This constructor is useful for routing algorithms that perform their
    /// own scoring.
    pub fn new(
        movement: CandidateMove,
        metrics: RoutingMetrics,
        front_layer_distance: u64,
        extended_layer_distance: u64,
        front_layer_size: u64,
        extended_layer_size: u64,
        decay_factor: u64,
    ) -> RoutingResult<Self> {
        let id = CandidateId::from_move(movement);

        let cost_candidate = CostCandidate::new(metrics)
            .with_front_layer(
                front_layer_distance,
                front_layer_size,
            )
            .with_extended_layer(
                extended_layer_distance,
                extended_layer_size,
            )
            .with_decay_factor(decay_factor);

        cost_candidate.validate()?;

        Ok(Self {
            id,
            movement,
            metrics,
            cost: None,
            front_layer_distance,
            extended_layer_distance,
            decay_factor,
        })
    }

    /// Returns the stable candidate identifier.
    #[must_use]
    pub const fn id(&self) -> CandidateId {
        self.id
    }

    /// Returns the physical movement.
    #[must_use]
    pub const fn movement(&self) -> CandidateMove {
        self.movement
    }

    /// Returns the candidate's physical endpoint `a`.
    #[must_use]
    pub const fn a(&self) -> PhysicalQubitId {
        self.movement.a()
    }

    /// Returns the candidate's physical endpoint `b`.
    #[must_use]
    pub const fn b(&self) -> PhysicalQubitId {
        self.movement.b()
    }

    /// Returns predicted routing metrics.
    #[must_use]
    pub const fn metrics(&self) -> RoutingMetrics {
        self.metrics
    }

    /// Returns the evaluated cost, if one has been attached.
    #[must_use]
    pub const fn cost(&self) -> Option<RoutingCost> {
        self.cost
    }

    /// Returns the front-layer heuristic distance.
    #[must_use]
    pub const fn front_layer_distance(&self) -> u64 {
        self.front_layer_distance
    }

    /// Returns the extended-layer heuristic distance.
    #[must_use]
    pub const fn extended_layer_distance(&self) -> u64 {
        self.extended_layer_distance
    }

    /// Returns the fixed-point decay factor.
    #[must_use]
    pub const fn decay_factor(&self) -> u64 {
        self.decay_factor
    }

    /// Returns a candidate with an evaluated routing cost.
    ///
    /// The original candidate remains immutable; this creates a new value.
    pub fn with_cost(
        mut self,
        cost_model: &dyn CostModel,
    ) -> RoutingResult<Self> {
        let cost_candidate = CostCandidate::new(self.metrics)
            .with_front_layer(
                self.front_layer_distance,
                self.metrics.gate_count,
            )
            .with_extended_layer(
                self.extended_layer_distance,
                0,
            )
            .with_decay_factor(self.decay_factor);

        let cost = cost_model.evaluate(&cost_candidate)?;

        self.cost = Some(cost);

        Ok(self)
    }

    /// Returns the `CostCandidate` representation used by `cost.rs`.
    #[must_use]
    pub fn as_cost_candidate(&self) -> CostCandidate {
        CostCandidate::new(self.metrics)
            .with_front_layer(
                self.front_layer_distance,
                self.metrics.gate_count,
            )
            .with_extended_layer(
                self.extended_layer_distance,
                0,
            )
            .with_decay_factor(self.decay_factor)
    }

    /// Validates candidate invariants.
    pub fn validate(&self) -> RoutingResult<()> {
        if self.a() == self.b() {
            return Err(CandidateError::InvalidEdge {
                a: self.a().index(),
                b: self.b().index(),
            }
            .into());
        }

        if self.decay_factor == 0 {
            return Err(CandidateError::ScoreEvaluationFailed {
                detail: "candidate decay factor cannot be zero".to_string(),
            }
            .into());
        }

        self.metrics.validate()?;

        let cost_candidate = self.as_cost_candidate();
        cost_candidate.validate()?;

        Ok(())
    }

    /// Returns a deterministic candidate tie-break key.
    ///
    /// Cost models decide the semantic objective. This key is only used after
    /// objective comparison reports equality.
    #[must_use]
    pub const fn tie_break_key(
        &self,
    ) -> (PhysicalQubitId, PhysicalQubitId) {
        (self.a(), self.b())
    }
}

// =============================================================================
// Candidate set
// =============================================================================

/// Deterministic collection of routing candidates.
///
/// The set owns candidates and guarantees:
///
/// - no duplicate candidate identifier;
/// - deterministic iteration;
/// - deterministic best-candidate selection when a cost model is supplied;
/// - explicit size limits.
#[derive(Debug, Clone, Default)]
pub struct CandidateSet {
    candidates: Vec<SwapCandidate>,
}

impl CandidateSet {
    /// Creates an empty candidate set.
    #[must_use]
    pub const fn new() -> Self {
        Self {
            candidates: Vec::new(),
        }
    }

    /// Creates an empty candidate set with a bounded allocation capacity.
    ///
    /// The requested capacity is clamped to `MAX_CANDIDATES`.
    #[must_use]
    pub fn with_capacity(capacity: usize) -> Self {
        let bounded = capacity.min(MAX_CANDIDATES);

        Self {
            candidates: Vec::with_capacity(bounded),
        }
    }

    /// Returns the number of candidates.
    #[must_use]
    pub fn len(&self) -> usize {
        self.candidates.len()
    }

    /// Returns whether the set is empty.
    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.candidates.is_empty()
    }

    /// Returns the candidates in deterministic order.
    #[must_use]
    pub fn as_slice(&self) -> &[SwapCandidate] {
        &self.candidates
    }

    /// Consumes the set and returns its candidate vector.
    #[must_use]
    pub fn into_vec(self) -> Vec<SwapCandidate> {
        self.candidates
    }

    /// Returns a candidate by stable identifier.
    #[must_use]
    pub fn get(
        &self,
        id: CandidateId,
    ) -> Option<&SwapCandidate> {
        self.candidates.iter().find(|candidate| candidate.id() == id)
    }

    /// Inserts a candidate.
    ///
    /// Duplicate identifiers are rejected rather than silently replacing an
    /// existing candidate.
    pub fn push(
        &mut self,
        candidate: SwapCandidate,
        maximum: usize,
    ) -> RoutingResult<()> {
        let limit = maximum.min(MAX_CANDIDATES);

        if limit == 0 {
            return Err(CandidateError::CandidateLimitExceeded {
                limit: 0,
            }
            .into());
        }

        if self.candidates.iter().any(|existing| {
            existing.id() == candidate.id()
        }) {
            return Ok(());
        }

        if self.candidates.len() >= limit {
            return Err(CandidateError::CandidateLimitExceeded {
                limit,
            }
            .into());
        }

        candidate.validate()?;

        self.candidates.push(candidate);

        Ok(())
    }

    /// Sorts candidates using their deterministic structural identity.
    pub fn sort_deterministically(&mut self) {
        self.candidates.sort_unstable_by_key(|candidate| {
            candidate.tie_break_key()
        });
    }

    /// Sorts candidates using a supplied cost model.
    ///
    /// Candidates without an evaluated cost are evaluated exactly once.
    ///
    /// If two candidates have equal semantic cost, their physical endpoint
    /// ordering is used as the deterministic tie-break.
    pub fn sort_by_cost(
        &mut self,
        cost_model: &dyn CostModel,
    ) -> RoutingResult<()> {
        for candidate in &mut self.candidates {
            if candidate.cost.is_none() {
                let evaluated = cost_model.evaluate(
                    &candidate.as_cost_candidate(),
                )?;

                candidate.cost = Some(evaluated);
            }
        }

        let mut comparison_error: Option<CandidateError> = None;

        self.candidates.sort_unstable_by(|left, right| {
            let left_cost = match left.cost {
                Some(cost) => cost,
                None => {
                    comparison_error =
                        Some(CandidateError::ScoreEvaluationFailed {
                            detail:
                                "candidate has no evaluated cost after cost-model evaluation"
                                    .to_string(),
                        });

                    return Ordering::Equal;
                }
            };

            let right_cost = match right.cost {
                Some(cost) => cost,
                None => {
                    comparison_error =
                        Some(CandidateError::ScoreEvaluationFailed {
                            detail:
                                "candidate has no evaluated cost after cost-model evaluation"
                                    .to_string(),
                        });

                    return Ordering::Equal;
                }
            };

            match cost_model.compare(&left_cost, &right_cost) {
                Ok(Ordering::Equal) => {
                    left.tie_break_key()
                        .cmp(&right.tie_break_key())
                }

                Ok(ordering) => ordering,

                Err(error) => {
                    comparison_error =
                        Some(CandidateError::ScoreEvaluationFailed {
                            detail: error.to_string(),
                        });

                    Ordering::Equal
                }
            }
        });

        if let Some(error) = comparison_error {
            return Err(error.into());
        }

        Ok(())
    }

    /// Returns the best candidate according to the supplied cost model.
    ///
    /// The set does not need to be sorted first.
    pub fn best(
        &self,
        cost_model: &dyn CostModel,
    ) -> RoutingResult<Option<&SwapCandidate>> {
        let mut best: Option<&SwapCandidate> = None;

        for candidate in &self.candidates {
            let candidate_cost = match candidate.cost {
                Some(cost) => cost,
                None => cost_model.evaluate(
                    &candidate.as_cost_candidate(),
                )?,
            };

            match best {
                None => {
                    best = Some(candidate);
                }

                Some(current) => {
                    let current_cost = match current.cost {
                        Some(cost) => cost,
                        None => cost_model.evaluate(
                            &current.as_cost_candidate(),
                        )?,
                    };

                    match cost_model.compare(
                        &candidate_cost,
                        &current_cost,
                    )? {
                        Ordering::Less => {
                            best = Some(candidate);
                        }

                        Ordering::Equal => {
                            if candidate.tie_break_key()
                                < current.tie_break_key()
                            {
                                best = Some(candidate);
                            }
                        }

                        Ordering::Greater => {}
                    }
                }
            }
        }

        Ok(best)
    }

    /// Returns the candidate with the lowest deterministic structural key.
    ///
    /// This is useful for deterministic baseline routing without a cost model.
    #[must_use]
    pub fn first_deterministic(&self) -> Option<&SwapCandidate> {
        self.candidates.iter().min_by_key(|candidate| {
            candidate.tie_break_key()
        })
    }
}

impl<'a> IntoIterator for &'a CandidateSet {
    type Item = &'a SwapCandidate;
    type IntoIter = std::slice::Iter<'a, SwapCandidate>;

    fn into_iter(self) -> Self::IntoIter {
        self.candidates.iter()
    }
}

// =============================================================================
// Candidate generator configuration
// =============================================================================

/// Candidate-generation policy.
///
/// This configuration is intentionally narrower than `RoutingConfig`.
///
/// `RoutingConfig` controls the complete routing algorithm.
/// `CandidateGenerationConfig` controls only the generation primitive.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct CandidateGenerationConfig {
    /// Maximum number of candidates to generate.
    pub max_candidates: usize,

    /// Whether a SWAP must connect two mutually reachable physical endpoints.
    ///
    /// For a physical SWAP, both directions must be executable as movement.
    /// Therefore this should normally remain `true`.
    pub require_bidirectional_edge: bool,

    /// Whether an empty physical endpoint may participate in a candidate.
    ///
    /// Allowing this is useful for movement into an unoccupied physical
    /// location if a future movement implementation supports it. For actual
    /// SWAP semantics, both endpoints normally represent physical resources,
    /// so the default is `true`.
    pub allow_unoccupied_endpoint: bool,

    /// Whether the candidate generator should evaluate candidates using a
    /// supplied cost model.
    ///
    /// The generator can still be used without a model; the algorithm may
    /// evaluate candidates later.
    pub evaluate_cost: bool,

    /// Fixed-point decay factor passed to `CostCandidate`.
    pub decay_factor: u64,

    /// Maximum number of front/extended interactions used during scoring.
    ///
    /// This bounds work for hostile or accidentally enormous inputs.
    pub max_interactions: usize,
}

impl Default for CandidateGenerationConfig {
    fn default() -> Self {
        Self {
            max_candidates: DEFAULT_MAX_CANDIDATES,
            require_bidirectional_edge: true,
            allow_unoccupied_endpoint: true,
            evaluate_cost: false,
            decay_factor: DEFAULT_DECAY_FACTOR,
            max_interactions: DEFAULT_MAX_INTERACTIONS,
        }
    }
}

impl CandidateGenerationConfig {
    /// Validates the generation policy.
    pub fn validate(self) -> RoutingResult<()> {
        if self.max_candidates == 0 {
            return Err(CandidateError::CandidateLimitExceeded {
                limit: 0,
            }
            .into());
        }

        if self.max_candidates > MAX_CANDIDATES {
            return Err(CandidateError::CandidateLimitExceeded {
                limit: MAX_CANDIDATES,
            }
            .into());
        }

        if self.decay_factor == 0 {
            return Err(CandidateError::ScoreEvaluationFailed {
                detail: "decay factor cannot be zero".to_string(),
            }
            .into());
        }

        if self.max_interactions == 0 {
            return Err(CandidateError::ScoreEvaluationFailed {
                detail: "maximum interaction count cannot be zero".to_string(),
            }
            .into());
        }

        Ok(())
    }
}

// =============================================================================
// Candidate generator
// =============================================================================

/// Production candidate generator.
///
/// `CandidateGenerator` is intentionally stateless.
///
/// This is important because:
///
/// - routing algorithms may reuse one generator across iterations;
/// - parallel trials must not share mutable candidate state;
/// - deterministic behavior is easier to guarantee;
/// - topology/mapping remain the source of truth.
///
/// All routing state is supplied through [`CandidateContext`].
#[derive(Debug, Clone, Copy, Default)]
pub struct CandidateGenerator;

impl CandidateGenerator {
    /// Creates a stateless candidate generator.
    #[must_use]
    pub const fn new() -> Self {
        Self
    }

    /// Generates all legal SWAP candidates touching at least one currently
    /// occupied physical qubit.
    ///
    /// This is the general-purpose candidate-generation entry point.
    ///
    /// # Important
    ///
    /// The mapping is never mutated.
    pub fn generate(
        &self,
        context: &CandidateContext<'_>,
        config: CandidateGenerationConfig,
        distance_provider: &dyn CandidateDistanceProvider,
        cost_model: Option<&dyn CostModel>,
    ) -> RoutingResult<CandidateSet> {
        config.validate()?;

        validate_context(context)?;

        let mut candidate_edges = BTreeSet::new();

        self.collect_mapping_adjacent_edges(
            context,
            config,
            &mut candidate_edges,
        )?;

        if candidate_edges.is_empty() {
            return Err(CandidateError::EmptyCandidateSet.into());
        }

        let mut candidates = CandidateSet::with_capacity(
            candidate_edges.len().min(config.max_candidates),
        );

        for (a, b) in candidate_edges {
            if candidates.len() >= config.max_candidates {
                break;
            }

            let movement = match CandidateMove::swap(a, b) {
                Some(movement) => movement,
                None => {
                    return Err(CandidateError::InvalidEdge {
                        a: a.index(),
                        b: b.index(),
                    }
                    .into());
                }
            };

            if !self.is_legal_swap(
                context.topology,
                a,
                b,
                config,
            ) {
                continue;
            }

            let candidate = self.build_candidate(
                context,
                movement,
                config,
                distance_provider,
            )?;

            let candidate = if config.evaluate_cost {
                match cost_model {
                    Some(model) => candidate.with_cost(model)?,

                    None => {
                        return Err(
                            CandidateError::ScoreEvaluationFailed {
                                detail:
                                    "candidate cost evaluation was requested but no cost model was supplied"
                                        .to_string(),
                            }
                            .into(),
                        );
                    }
                }
            } else {
                candidate
            };

            candidates.push(
                candidate,
                config.max_candidates,
            )?;
        }

        if candidates.is_empty() {
            return Err(CandidateError::EmptyCandidateSet.into());
        }

        candidates.sort_deterministically();

        Ok(candidates)
    }

    /// Generates candidates touching the physical locations occupied by the
    /// logical qubits in the front layer.
    ///
    /// This is the preferred entry point for SABRE/lookahead-style routing.
    pub fn generate_for_front_layer(
        &self,
        context: &CandidateContext<'_>,
        config: CandidateGenerationConfig,
        distance_provider: &dyn CandidateDistanceProvider,
        cost_model: Option<&dyn CostModel>,
    ) -> RoutingResult<CandidateSet> {
        config.validate()?;
        validate_context(context)?;

        let mut physical_frontier = BTreeSet::new();

        for interaction in context.front_layer {
            for &logical in interaction.operands() {
                let physical = context
                    .mapping
                    .physical_of(logical)
                    .ok_or_else(|| {
                        CandidateError::MappingConflict {
                            a: logical.index(),
                            b: logical.index(),
                        }
                    })?;

                physical_frontier.insert(physical);
            }
        }

        if physical_frontier.is_empty() {
            return Err(CandidateError::EmptyCandidateSet.into());
        }

        let mut candidate_edges = BTreeSet::new();

        for physical in physical_frontier {
            for neighbour in context.topology.neighbors(physical) {
                let (a, b) = canonical_edge(physical, neighbour);

                candidate_edges.insert((a, b));

                if candidate_edges.len() >= MAX_CANDIDATES {
                    return Err(
                        CandidateError::CandidateLimitExceeded {
                            limit: MAX_CANDIDATES,
                        }
                        .into(),
                    );
                }
            }
        }

        self.materialize_candidates(
            context,
            config,
            distance_provider,
            cost_model,
            candidate_edges,
        )
    }

    /// Generates candidates touching both operands of a specific interaction.
    ///
    /// This is particularly useful for greedy and shortest-path routing.
    pub fn generate_for_interaction(
        &self,
        context: &CandidateContext<'_>,
        interaction: &QubitInteraction,
        config: CandidateGenerationConfig,
        distance_provider: &dyn CandidateDistanceProvider,
        cost_model: Option<&dyn CostModel>,
    ) -> RoutingResult<CandidateSet> {
        config.validate()?;
        validate_context(context)?;

        if interaction.arity() != 2 {
            return Err(CandidateError::ScoreEvaluationFailed {
                detail: format!(
                    "candidate generation for a single interaction requires \
                     exactly two logical operands; received {}",
                    interaction.arity()
                ),
            }
            .into());
        }

        let logical_a = interaction.operands()[0];
        let logical_b = interaction.operands()[1];

        let physical_a = context
            .mapping
            .physical_of(logical_a)
            .ok_or_else(|| CandidateError::MappingConflict {
                a: logical_a.index(),
                b: logical_b.index(),
            })?;

        let physical_b = context
            .mapping
            .physical_of(logical_b)
            .ok_or_else(|| CandidateError::MappingConflict {
                a: logical_a.index(),
                b: logical_b.index(),
            })?;

        let mut candidate_edges = BTreeSet::new();

        for neighbour in context.topology.neighbors(physical_a) {
            let (a, b) = canonical_edge(physical_a, neighbour);
            candidate_edges.insert((a, b));
        }

        for neighbour in context.topology.neighbors(physical_b) {
            let (a, b) = canonical_edge(physical_b, neighbour);
            candidate_edges.insert((a, b));
        }

        self.materialize_candidates(
            context,
            config,
            distance_provider,
            cost_model,
            candidate_edges,
        )
    }

    /// Returns whether a physical edge can represent a SWAP movement.
    ///
    /// A directed physical connection is not sufficient for a symmetric SWAP.
    /// Unless a future movement/lowering layer explicitly provides a directed
    /// SWAP decomposition, candidate generation requires bidirectional
    /// structural adjacency.
    #[must_use]
    pub fn is_legal_swap(
        &self,
        topology: &PhysicalTopology,
        a: PhysicalQubitId,
        b: PhysicalQubitId,
        config: CandidateGenerationConfig,
    ) -> bool {
        if a == b {
            return false;
        }

        if !topology.contains(a) || !topology.contains(b) {
            return false;
        }

        if !topology.is_available(a)
            || !topology.is_available(b)
        {
            return false;
        }

        if config.require_bidirectional_edge {
            topology.is_bidirectionally_adjacent(a, b)
        } else {
            topology.is_adjacent(a, b)
                || topology.is_adjacent(b, a)
        }
    }

    /// Hypothetically applies a SWAP to a logical qubit's physical location.
    ///
    /// This method never mutates the mapping.
    #[must_use]
    pub fn project_logical_location(
        &self,
        mapping: &QubitMapping,
        logical: LogicalQubitId,
        a: PhysicalQubitId,
        b: PhysicalQubitId,
    ) -> Option<PhysicalQubitId> {
        let physical = mapping.physical_of(logical)?;

        Some(
            PhysicalProjection::after_swap(
                physical,
                a,
                b,
            )
            .physical,
        )
    }

    /// Computes the distance of one interaction after a hypothetical SWAP.
    ///
    /// `None` means at least one logical operand is unmapped or the projected
    /// physical qubits are disconnected.
    pub fn projected_interaction_distance(
        &self,
        mapping: &QubitMapping,
        interaction: &QubitInteraction,
        a: PhysicalQubitId,
        b: PhysicalQubitId,
        topology: &PhysicalTopology,
        distance_provider: &dyn CandidateDistanceProvider,
    ) -> Option<u64> {
        if interaction.arity() != 2 {
            return None;
        }

        let logical_a = interaction.operands()[0];
        let logical_b = interaction.operands()[1];

        let physical_a = mapping.physical_of(logical_a)?;
        let physical_b = mapping.physical_of(logical_b)?;

        let projected_a =
            PhysicalProjection::after_swap(
                physical_a,
                a,
                b,
            )
            .physical;

        let projected_b =
            PhysicalProjection::after_swap(
                physical_b,
                a,
                b,
            )
            .physical;

        distance_provider.distance(
            topology,
            projected_a,
            projected_b,
        )
    }

    // =========================================================================
    // Internal generation
    // =========================================================================

    fn collect_mapping_adjacent_edges(
        &self,
        context: &CandidateContext<'_>,
        config: CandidateGenerationConfig,
        output: &mut BTreeSet<(
            PhysicalQubitId,
            PhysicalQubitId,
        )>,
    ) -> RoutingResult<()> {
        let mut occupied = BTreeSet::new();

        for logical in context.mapping.logical_qubits() {
            if let Some(physical) =
                context.mapping.physical_of(logical)
            {
                occupied.insert(physical);
            }
        }

        for physical in occupied {
            for neighbour in context.topology.neighbors(physical) {
                let (a, b) = canonical_edge(
                    physical,
                    neighbour,
                );

                if !self.is_legal_swap(
                    context.topology,
                    a,
                    b,
                    config,
                ) {
                    continue;
                }

                output.insert((a, b));

                if output.len() >= MAX_CANDIDATES {
                    return Err(
                        CandidateError::CandidateLimitExceeded {
                            limit: MAX_CANDIDATES,
                        }
                        .into(),
                    );
                }
            }
        }

        Ok(())
    }

    fn materialize_candidates(
        &self,
        context: &CandidateContext<'_>,
        config: CandidateGenerationConfig,
        distance_provider: &dyn CandidateDistanceProvider,
        cost_model: Option<&dyn CostModel>,
        candidate_edges: BTreeSet<(
            PhysicalQubitId,
            PhysicalQubitId,
        )>,
    ) -> RoutingResult<CandidateSet> {
        let mut candidates = CandidateSet::with_capacity(
            candidate_edges
                .len()
                .min(config.max_candidates),
        );

        for (a, b) in candidate_edges {
            if candidates.len() >= config.max_candidates {
                break;
            }

            if !self.is_legal_swap(
                context.topology,
                a,
                b,
                config,
            ) {
                continue;
            }

            let movement = CandidateMove::swap(a, b)
                .ok_or_else(|| CandidateError::InvalidEdge {
                    a: a.index(),
                    b: b.index(),
                })?;

            let candidate = self.build_candidate(
                context,
                movement,
                config,
                distance_provider,
            )?;

            let candidate = if config.evaluate_cost {
                let model = cost_model.ok_or_else(|| {
                    CandidateError::ScoreEvaluationFailed {
                        detail:
                            "cost evaluation requested without a cost model"
                                .to_string(),
                    }
                })?;

                candidate.with_cost(model)?
            } else {
                candidate
            };

            candidates.push(
                candidate,
                config.max_candidates,
            )?;
        }

        if candidates.is_empty() {
            return Err(CandidateError::EmptyCandidateSet.into());
        }

        candidates.sort_deterministically();

        Ok(candidates)
    }

    fn build_candidate(
        &self,
        context: &CandidateContext<'_>,
        movement: CandidateMove,
        config: CandidateGenerationConfig,
        distance_provider: &dyn CandidateDistanceProvider,
    ) -> RoutingResult<SwapCandidate> {
        let (a, b) = match movement {
            CandidateMove::Swap { a, b } => (a, b),
        };

        let front_layer_distance =
            self.aggregate_layer_distance(
                context,
                context.front_layer,
                a,
                b,
                distance_provider,
                config.max_interactions,
            )?;

        let extended_layer_distance =
            self.aggregate_layer_distance(
                context,
                context.extended_layer,
                a,
                b,
                distance_provider,
                config.max_interactions,
            )?;

        let front_size = checked_len_to_u64(
            context.front_layer.len(),
            "front-layer interaction count",
        )?;

        let extended_size = checked_len_to_u64(
            context.extended_layer.len(),
            "extended-layer interaction count",
        )?;

        let interaction_distance =
            front_layer_distance
                .checked_add(extended_layer_distance)
                .ok_or_else(|| {
                    CandidateError::ScoreEvaluationFailed {
                        detail:
                            "candidate interaction-distance accumulation overflowed"
                                .to_string(),
                    }
                })?;

        let metrics = RoutingMetrics {
            swap_count: 1,
            movement_count: 1,
            gate_count: front_size
                .checked_add(extended_size)
                .ok_or_else(|| {
                    CandidateError::ScoreEvaluationFailed {
                        detail:
                            "candidate gate-count accumulation overflowed"
                                .to_string(),
                    }
                })?,
            depth: 1,
            duration_ns: 0,
            error_ppb: 0,
            fidelity_ppb: 0,
            interaction_distance,
        };

        SwapCandidate::new(
            movement,
            metrics,
            front_layer_distance,
            extended_layer_distance,
            front_size,
            extended_size,
            config.decay_factor,
        )
    }

    fn aggregate_layer_distance(
        &self,
        context: &CandidateContext<'_>,
        interactions: &[QubitInteraction],
        a: PhysicalQubitId,
        b: PhysicalQubitId,
        distance_provider: &dyn CandidateDistanceProvider,
        maximum: usize,
    ) -> RoutingResult<u64> {
        if interactions.len() > maximum {
            return Err(
                CandidateError::CandidateLimitExceeded {
                    limit: maximum,
                }
                .into(),
            );
        }

        let mut total = 0u64;

        for interaction in interactions {
            if interaction.arity() != 2 {
                // Candidate generation does not silently reinterpret a
                // multi-qubit interaction as a pair. Unsupported multi-qubit
                // decomposition belongs to another compiler stage.
                continue;
            }

            let distance =
                self.projected_interaction_distance(
                    context.mapping,
                    interaction,
                    a,
                    b,
                    context.topology,
                    distance_provider,
                );

            let distance = match distance {
                Some(value) => value,
                None => {
                    // An unreachable future interaction must not create an
                    // artificial finite score. Treating it as zero would make
                    // an impossible candidate look optimal.
                    continue;
                }
            };

            total = total.checked_add(distance).ok_or_else(|| {
                CandidateError::ScoreEvaluationFailed {
                    detail:
                        "interaction-distance accumulation overflowed"
                            .to_string(),
                }
            })?;
        }

        Ok(total)
    }
}

// =============================================================================
// Context validation
// =============================================================================

fn validate_context(
    context: &CandidateContext<'_>,
) -> RoutingResult<()> {
    context.topology.validate()?;

    for logical in context.mapping.logical_qubits() {
        let physical = context
            .mapping
            .physical_of(logical)
            .ok_or_else(|| CandidateError::MappingConflict {
                a: logical.index(),
                b: logical.index(),
            })?;

        if !context.topology.contains(physical) {
            return Err(
                CandidateError::MappingConflict {
                    a: physical.index(),
                    b: physical.index(),
                }
                .into(),
            );
        }

        if !context.topology.is_available(physical) {
            return Err(
                CandidateError::MappingConflict {
                    a: physical.index(),
                    b: physical.index(),
                }
                .into(),
            );
        }
    }

    validate_interactions(
        context.mapping,
        context.front_layer,
    )?;

    validate_interactions(
        context.mapping,
        context.extended_layer,
    )?;

    Ok(())
}

fn validate_interactions(
    mapping: &QubitMapping,
    interactions: &[QubitInteraction],
) -> RoutingResult<()> {
    for interaction in interactions {
        for &logical in interaction.operands() {
            if !mapping.contains_logical(logical) {
                return Err(
                    CandidateError::MappingConflict {
                        a: logical.index(),
                        b: logical.index(),
                    }
                    .into(),
                );
            }
        }
    }

    Ok(())
}

// =============================================================================
// Deterministic helpers
// =============================================================================

/// Returns a canonical physical-edge representation.
///
/// The smaller physical identifier is always placed first.
#[must_use]
pub const fn canonical_edge(
    a: PhysicalQubitId,
    b: PhysicalQubitId,
) -> (PhysicalQubitId, PhysicalQubitId) {
    if a <= b {
        (a, b)
    } else {
        (b, a)
    }
}

/// Checked conversion from `usize` to `u64`.
///
/// On all supported Rust platforms this is normally infallible, but keeping
/// the conversion checked makes the contract explicit and avoids depending on
/// target-width assumptions.
fn checked_len_to_u64(
    value: usize,
    description: &str,
) -> RoutingResult<u64> {
    u64::try_from(value).map_err(|_| {
        CandidateError::ScoreEvaluationFailed {
            detail: format!(
                "{description} exceeds u64 representable range"
            ),
        }
        .into()
    })
}

// =============================================================================
// Tests
// =============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    use crate::quantum::routing::mapping::QubitMapping;
    use crate::quantum::routing::topology::{
        PhysicalQubitProperties,
        TopologyMetadata,
    };
    use crate::quantum::routing::types::{
        GateIdentity,
    };

    fn logical(index: usize) -> LogicalQubitId {
        LogicalQubitId::new(index)
    }

    fn physical(index: usize) -> PhysicalQubitId {
        PhysicalQubitId::new(index)
    }

    fn line_topology(
        count: usize,
    ) -> PhysicalTopology {
        let mut builder = PhysicalTopology::builder();

        for index in 0..count {
            builder = builder
                .qubit(
                    physical(index),
                    PhysicalQubitProperties::default(),
                )
                .expect("valid qubit");
        }

        for index in 0..count.saturating_sub(1) {
            builder = builder
                .undirected_edge(
                    physical(index),
                    physical(index + 1),
                )
                .expect("valid edge");
        }

        builder
            .metadata(TopologyMetadata::named("candidate-test"))
            .build()
            .expect("valid topology")
    }

    fn mapping_two() -> QubitMapping {
        QubitMapping::from_assignments([
            (logical(0), physical(0)),
            (logical(1), physical(1)),
        ])
        .expect("valid mapping")
    }

    fn interaction(
        a: usize,
        b: usize,
    ) -> QubitInteraction {
        QubitInteraction::new(
            vec![logical(a), logical(b)],
            GateIdentity::Cx,
        )
    }

    struct TestDistance;

    impl CandidateDistanceProvider for TestDistance {
        fn distance(
            &self,
            topology: &PhysicalTopology,
            from: PhysicalQubitId,
            to: PhysicalQubitId,
        ) -> Option<u64> {
            if from == to {
                return Some(0);
            }

            // Small deterministic BFS used only by this test provider.
            let mut frontier =
                std::collections::VecDeque::new();
            let mut visited =
                BTreeSet::new();

            frontier.push_back((from, 0u64));
            visited.insert(from);

            while let Some((current, distance)) =
                frontier.pop_front()
            {
                for neighbour in topology.neighbors(current) {
                    if neighbour == to {
                        return distance.checked_add(1);
                    }

                    if visited.insert(neighbour) {
                        frontier.push_back((
                            neighbour,
                            distance.checked_add(1)?,
                        ));
                    }
                }
            }

            None
        }
    }

    #[test]
    fn canonical_edge_is_order_independent() {
        assert_eq!(
            canonical_edge(physical(0), physical(1)),
            (physical(0), physical(1))
        );

        assert_eq!(
            canonical_edge(physical(1), physical(0)),
            (physical(0), physical(1))
        );
    }

    #[test]
    fn candidate_move_canonicalizes_endpoints() {
        let candidate =
            CandidateMove::swap(physical(2), physical(0))
                .expect("valid swap");

        assert_eq!(
            candidate,
            CandidateMove::Swap {
                a: physical(0),
                b: physical(2),
            }
        );
    }

    #[test]
    fn self_swap_is_rejected() {
        assert!(
            CandidateMove::swap(
                physical(1),
                physical(1)
            )
            .is_none()
        );

        assert!(
            CandidateId::new(
                physical(1),
                physical(1)
            )
            .is_none()
        );
    }

    #[test]
    fn candidate_generation_is_deterministic() {
        let topology = line_topology(4);
        let mapping = mapping_two();

        let front = vec![interaction(0, 1)];
        let extended = Vec::new();

        let context = CandidateContext::new(
            &topology,
            &mapping,
            &front,
            &extended,
        );

        let generator = CandidateGenerator::new();

        let candidates_a = generator
            .generate(
                &context,
                CandidateGenerationConfig::default(),
                &TestDistance,
                None,
            )
            .expect("candidate generation succeeds");

        let candidates_b = generator
            .generate(
                &context,
                CandidateGenerationConfig::default(),
                &TestDistance,
                None,
            )
            .expect("candidate generation succeeds");

        assert_eq!(
            candidates_a.as_slice(),
            candidates_b.as_slice()
        );
    }

    #[test]
    fn candidate_generation_does_not_mutate_mapping() {
        let topology = line_topology(4);
        let mapping = mapping_two();
        let before = mapping.snapshot();

        let front = vec![interaction(0, 1)];

        let context = CandidateContext::new(
            &topology,
            &mapping,
            &front,
            &[],
        );

        CandidateGenerator::new()
            .generate(
                &context,
                CandidateGenerationConfig::default(),
                &TestDistance,
                None,
            )
            .expect("candidate generation succeeds");

        assert_eq!(mapping.snapshot(), before);
    }

    #[test]
    fn candidate_generation_deduplicates_edges() {
        let topology = line_topology(3);

        let mapping = QubitMapping::from_assignments([
            (logical(0), physical(0)),
            (logical(1), physical(1)),
            (logical(2), physical(2)),
        ])
        .expect("valid mapping");

        let front = vec![
            interaction(0, 1),
            interaction(1, 2),
        ];

        let context = CandidateContext::new(
            &topology,
            &mapping,
            &front,
            &[],
        );

        let candidates =
            CandidateGenerator::new()
                .generate(
                    &context,
                    CandidateGenerationConfig::default(),
                    &TestDistance,
                    None,
                )
                .expect("candidate generation succeeds");

        let ids: BTreeSet<_> = candidates
            .as_slice()
            .iter()
            .map(SwapCandidate::id)
            .collect();

        assert_eq!(ids.len(), candidates.len());
    }

    #[test]
    fn candidate_limit_is_enforced() {
        let topology = line_topology(8);

        let mut assignments = Vec::new();

        for index in 0..8 {
            assignments.push((
                logical(index),
                physical(index),
            ));
        }

        let mapping =
            QubitMapping::from_assignments(assignments)
                .expect("valid mapping");

        let front = vec![interaction(0, 1)];

        let context = CandidateContext::new(
            &topology,
            &mapping,
            &front,
            &[],
        );

        let mut config =
            CandidateGenerationConfig::default();

        config.max_candidates = 2;

        let candidates =
            CandidateGenerator::new()
                .generate(
                    &context,
                    config,
                    &TestDistance,
                    None,
                )
                .expect("candidate generation succeeds");

        assert!(candidates.len() <= 2);
    }

    #[test]
    fn front_layer_generation_only_uses_frontier_edges() {
        let topology = line_topology(6);

        let mapping =
            QubitMapping::from_assignments([
                (logical(0), physical(0)),
                (logical(1), physical(1)),
            ])
            .expect("valid mapping");

        let front = vec![interaction(0, 1)];

        let context = CandidateContext::new(
            &topology,
            &mapping,
            &front,
            &[],
        );

        let candidates =
            CandidateGenerator::new()
                .generate_for_front_layer(
                    &context,
                    CandidateGenerationConfig::default(),
                    &TestDistance,
                    None,
                )
                .expect("candidate generation succeeds");

        for candidate in candidates.as_slice() {
            assert!(
                candidate.a() == physical(0)
                    || candidate.b() == physical(0)
                    || candidate.a() == physical(1)
                    || candidate.b() == physical(1)
            );
        }
    }

    #[test]
    fn interaction_generation_uses_both_operands() {
        let topology = line_topology(5);

        let mapping =
            QubitMapping::from_assignments([
                (logical(0), physical(0)),
                (logical(1), physical(4)),
            ])
            .expect("valid mapping");

        let front = vec![interaction(0, 1)];

        let context = CandidateContext::new(
            &topology,
            &mapping,
            &front,
            &[],
        );

        let candidates =
            CandidateGenerator::new()
                .generate_for_interaction(
                    &context,
                    &front[0],
                    CandidateGenerationConfig::default(),
                    &TestDistance,
                    None,
                )
                .expect("candidate generation succeeds");

        assert!(!candidates.is_empty());

        for candidate in candidates.as_slice() {
            let touches_a =
                candidate.a() == physical(0)
                    || candidate.b() == physical(0);

            let touches_b =
                candidate.a() == physical(4)
                    || candidate.b() == physical(4);

            assert!(touches_a || touches_b);
        }
    }

    #[test]
    fn projected_interaction_distance_changes_after_swap() {
        let topology = line_topology(4);

        let mapping =
            QubitMapping::from_assignments([
                (logical(0), physical(0)),
                (logical(1), physical(3)),
            ])
            .expect("valid mapping");

        let interaction = interaction(0, 1);

        let distance =
            CandidateGenerator::new()
                .projected_interaction_distance(
                    &mapping,
                    &interaction,
                    physical(0),
                    physical(1),
                    &topology,
                    &TestDistance,
                )
                .expect("distance exists");

        assert_eq!(distance, 2);
    }

    #[test]
    fn unavailable_qubit_is_not_a_legal_swap_endpoint() {
        let mut builder =
            PhysicalTopology::builder();

        builder = builder
            .qubit(
                physical(0),
                PhysicalQubitProperties {
                    available: false,
                    ..PhysicalQubitProperties::default()
                },
            )
            .expect("valid qubit");

        builder = builder
            .qubit(
                physical(1),
                PhysicalQubitProperties::default(),
            )
            .expect("valid qubit");

        builder = builder
            .undirected_edge(
                physical(0),
                physical(1),
            )
            .expect("valid edge");

        let topology = builder
            .metadata(TopologyMetadata::named("unavailable-test"))
            .build()
            .expect("valid topology");

        assert!(
            !CandidateGenerator::new()
                .is_legal_swap(
                    &topology,
                    physical(0),
                    physical(1),
                    CandidateGenerationConfig::default(),
                )
        );
    }

    #[test]
    fn candidate_set_rejects_zero_limit() {
        let candidate =
            SwapCandidate::new(
                CandidateMove::swap(
                    physical(0),
                    physical(1),
                )
                .expect("valid movement"),
                RoutingMetrics::from_swap_count(1),
                1,
                1,
                1,
                0,
                DEFAULT_DECAY_FACTOR,
            )
            .expect("valid candidate");

        let mut set =
            CandidateSet::new();

        let result =
            set.push(candidate, 0);

        assert!(result.is_err());
    }

    #[test]
    fn candidate_id_is_stable() {
        let first =
            CandidateId::new(
                physical(0),
                physical(3),
            )
            .expect("valid id");

        let second =
            CandidateId::new(
                physical(3),
                physical(0),
            )
            .expect("valid id");

        assert_eq!(first, second);
    }
}