//! Zenith Semantic Analyzer
//!
//! This module performs semantic analysis on the Abstract Syntax Tree (AST)
//! generated by the parser. It checks for type correctness, resolves symbols,
//! enforces language rules (including Zenith's advanced type system features
//! like linear/affine types, quantum state constraints, and EVAS policies),
//! and prepares the AST for Intermediate Representation (IR) generation.

use crate::ast::{Program, Statement, Expression, Literal, Identifier, TypeExpr, Parameter, MatchCase};
use crate::compiler_types::{Type, Symbol, SymbolKind, EvasPolicy};
use crate::source_map::Span; // Corrected Span import
use std::collections::HashMap;

/// Represents an error found during semantic analysis.
#[derive(Debug, Clone, PartialEq)]
pub struct SemanticError {
    pub message: String,
    pub span: Span,
}

/// The main Semantic Analyzer structure.
pub struct SemanticAnalyzer {
    /// Global symbol table (or current scope's view into it)
    symbol_table: HashMap<String, Symbol>,
    /// Stack of active scopes (conceptual for now, a real impl would use scope IDs)
    scope_stack: Vec<HashMap<String, Symbol>>,
    errors: Vec<SemanticError>,
    /// The EVAS policy governing this compilation context.
    evas_policy: EvasPolicy,
    /// Stack to track if we are inside an 'unsafe!' block
    in_unsafe_context: Vec<bool>,
}

impl SemanticAnalyzer {
    /// Creates a new SemanticAnalyzer instance with a given EVAS policy.
    pub fn new(evas_policy: EvasPolicy) -> Self {
        SemanticAnalyzer {
            symbol_table: HashMap::new(),
            scope_stack: vec![HashMap::new()], // Start with a global scope
            errors: Vec::new(),
            evas_policy,
            in_unsafe_context: Vec::new(),
        }
    }

    /// Entry point for semantic analysis.
    pub fn analyze(&mut self, program: &ast::Program) -> Result<HashMap<String, Symbol>, Vec<SemanticError>> {
        println!("Starting semantic analysis...");

        for stmt in &program.statements {
            self.analyze_statement(stmt);
        }

        if !self.errors.is_empty() {
            Err(self.errors.clone())
        } else {
            Ok(self.symbol_table.clone()) // Return the fully populated symbol table
        }
    }

    /// Analyzes a single statement.
    fn analyze_statement(&mut self, stmt: &ast::Statement) {
        match stmt {
            Statement::Let(span, name, type_expr_opt, expr) => {
                let expr_type = self.analyze_expression(expr);
                let declared_type = type_expr_opt.as_ref().map(|te| self.resolve_type_expr(te)).transpose().unwrap_or(None);

                let final_type = match declared_type {
                    Some(t) => {
                        if !self.is_assignable(&expr_type, &t, span.clone()) {
                            self.add_error(format!("Type mismatch: cannot assign {:?} to type {:?}.", expr_type, t), span.clone());
                        }
                        t
                    },
                    None => expr_type, // Type inference
                };

                self.define_symbol(name.clone(), final_type, true, SymbolKind::Variable, span.clone());
            }
            Statement::Return(span, expr) => {
                let _ = self.analyze_expression(expr); // Analyze the expression, but return type check happens at function level
            }
            Statement::Expression(expr) => {
                let _ = self.analyze_expression(expr);
            }
            Statement::Function(span, name, params, return_type_expr_opt, body) => {
                // Resolve return type
                let resolved_return_type = return_type_expr_opt.as_ref().map(|te| self.resolve_type_expr(te)).transpose().unwrap_or(Some(Type::Unit));
                
                // Create a new scope for function parameters and body
                self.enter_scope();

                let mut param_types = Vec::new();
                for param in params {
                    let param_type = self.resolve_type_expr(&param.param_type);
                    // Handle linear/affine modifiers on parameters
                    let final_param_type = if param.is_linear { Type::Linear(Box::new(param_type.clone())) } else if param.is_affine { Type::Affine(Box::new(param_type.clone())) } else { param_type.clone() };
                    self.define_symbol(param.name.clone(), final_param_type.clone(), false, SymbolKind::Variable, param.span.clone());
                    param_types.push(final_param_type);
                }

                // Define the function symbol (recursive calls)
                self.define_symbol(
                    name.clone(),
                    Type::Function(param_types.clone(), Box::new(resolved_return_type.clone().unwrap())),
                    false,
                    SymbolKind::Function,
                    span.clone(),
                );

                // Analyze function body (will check last expression type against return type)
                let body_type = self.analyze_expression(body);
                if let Some(expected_return) = resolved_return_type {
                    if !self.is_assignable(&body_type, &expected_return, body.get_span()) {
                        self.add_error(format!("Function '{}' body returns {:?}, but declared return type is {:?}.", name, body_type, expected_return), body.get_span());
                    }
                }

                self.exit_scope();
            }
            Statement::QuantumCircuit(span, name, body) => {
                // Quantum circuits often have implicit `Unit` return type
                self.enter_scope();
                self.analyze_expression(body);
                self.exit_scope();
                self.define_symbol(name.clone(), Type::Unit, false, SymbolKind::QuantumRegister, span.clone()); // Placeholder
            }
            Statement::NanoAgent(span, name, body) => {
                self.enter_scope();
                self.analyze_expression(body);
                self.exit_scope();
                self.define_symbol(name.clone(), Type::NanoParticle, false, SymbolKind::NanoAgent, span.clone()); // Placeholder
            }
            Statement::SankofaMemory(span, name, expr) => {
                let expr_type = self.analyze_expression(expr);
                // Sankofa memory keys store History<T>
                self.define_symbol(name.clone(), Type::History(Box::new(expr_type)), true, SymbolKind::SankofaMemoryKey, span.clone());
            }
            Statement::TypeDeclaration(span, name, type_expr) => {
                // Resolve and register the new type alias
                let resolved_type = self.resolve_type_expr(type_expr);
                self.define_symbol(name.clone(), resolved_type, false, SymbolKind::TypeAlias, span.clone());
            }
            Statement::EffectDeclaration(span, name) => {
                // Register the declared effect
                self.define_symbol(name.clone(), Type::Unit, false, SymbolKind::Effect, span.clone()); // Effects don't have a runtime type themselves
            }
            Statement::LanguageDeclaration(span, name, grammar_expr) => {
                // These are meta-compiler directives; semantic analysis would validate the grammar_expr's structure
                let _ = self.analyze_expression(grammar_expr);
            }
            Statement::While(span, cond, body) => {
                let cond_type = self.analyze_expression(cond);
                if cond_type != Type::Bool {
                    self.add_error(format!("While loop condition must be boolean, found {:?}.", cond_type), span.clone());
                }
                self.analyze_expression(body);
            }
            Statement::For(span, iterator_var_id, iterable, body) => {
                let iterable_type = self.analyze_expression(iterable);
                // Conceptual: Check if iterable_type implements Iterator trait or is an array
                // For now, assume it's valid.
                self.enter_scope(); // Scope for iterator variable
                // Conceptual: Determine element type from iterable_type
                let element_type = match iterable_type {
                    Type::QubitArray(_) => Type::Qubit,
                    _ => Type::Unknown, // Fallback
                };
                self.define_symbol(iterator_var_id.0.clone(), element_type, false, SymbolKind::Variable, iterator_var_id.1);
                self.analyze_expression(body);
                self.exit_scope();
            }
            Statement::Break(span) | Statement::Continue(span) => {
                // Contextual check: ensure these are within a loop or switch (handled during parsing/control flow analysis)
            }
            Statement::Match(span, matched_expr, cases) => {
                let matched_type = self.analyze_expression(matched_expr);
                let mut arm_types = Vec::new();
                for case in cases {
                    let pattern_type = self.analyze_expression(&case.pattern);
                    // Conceptual: pattern_type must be assignable from matched_type (or vice versa for destructuring)
                    if !self.is_assignable(&matched_type, &pattern_type, case.span.clone()) {
                        self.add_error(format!("Match pattern type {:?} is incompatible with matched expression type {:?}.", pattern_type, matched_type), case.span.clone());
                    }
                    arm_types.push(self.analyze_expression(&case.body));
                }
                // Conceptual: All match arm types must unify
                if !arm_types.is_empty() {
                    let first_type = &arm_types[0];
                    for i in 1..arm_types.len() {
                        if first_type != &arm_types[i] {
                            self.add_error(format!("Match arms must have consistent types, found {:?} and {:?}.", first_type, arm_types[i]), span.clone());
                            break;
                        }
                    }
                }
            }
            Statement::Unsafe(span, proof_opt, inner_block_expr) => {
                // --- EVAS Policy Enforcement --- 
                if !self.evas_policy.allow_unsafe_without_proof && proof_opt.is_none() {
                    self.add_error("'unsafe' block requires an EVAS proof string, but none was provided.".to_string(), span.clone());
                }
                if let Some(proof) = proof_opt {
                    if !self.evas_policy.approved_proofs.get(proof).map_or(false, |&valid| valid) {
                        self.add_error(format!("EVAS proof '{}' is not approved or invalid for this 'unsafe' block.", proof), span.clone());
                    }
                }

                // Enter unsafe context (potentially relaxes some checks)
                self.in_unsafe_context.push(true);
                self.analyze_expression(inner_block_expr);
                self.in_unsafe_context.pop();
            }
        }
    }

    /// Analyzes a single expression and returns its resolved Type.
    fn analyze_expression(&mut self, expr: &ast::Expression) -> Type {
        match expr {
            Expression::Literal(literal) => self.analyze_literal(literal),
            Expression::Identifier(ident) => self.lookup_symbol(&ident.0, ident.1).map_or(Type::Error, |s| s.symbol_type.clone()),
            Expression::Prefix(span, op, right) => {
                let right_type = self.analyze_expression(right);
                self.check_prefix_operator(*op, &right_type, span.clone())
            }
            Expression::Infix(span, left, op, right) => {
                let left_type = self.analyze_expression(left);
                let right_type = self.analyze_expression(right);
                self.check_infix_operator(*op, &left_type, &right_type, span.clone())
            }
            Expression::If(span, cond, then_block, else_block_opt) => {
                let cond_type = self.analyze_expression(cond);
                if cond_type != Type::Bool {
                    self.add_error(format!("If condition must be boolean, found {:?}.", cond_type), span.clone());
                }
                let then_type = self.analyze_expression(then_block);
                if let Some(else_block) = else_block_opt {
                    let else_type = self.analyze_expression(else_block);
                    // Types of then and else blocks must unify
                    if then_type != else_type {
                        self.add_error(format!("If-else branches must return consistent types, found {:?} and {:?}.", then_type, else_type), span.clone());
                        return Type::Error;
                    }
                    then_type
                } else {
                    then_type // If no else, result is type of then block, potentially Unit
                }
            }
            Expression::Block(span, statements) => {
                self.enter_scope();
                let mut last_type = Type::Unit;
                for stmt in statements {
                    last_type = self.analyze_statement_or_expression(stmt);
                }
                self.exit_scope();
                last_type
            }
            Expression::Call(span, func_expr, args) => {
                let func_type = self.analyze_expression(func_expr);
                match func_type {
                    Type::Function(param_types, return_type) => {
                        if param_types.len() != args.len() {
                            self.add_error(format!("Function expects {} arguments, but received {}.", param_types.len(), args.len()), span.clone());
                            return Type::Error;
                        }
                        for (i, arg_expr) in args.iter().enumerate() {
                            let arg_type = self.analyze_expression(arg_expr);
                            if !self.is_assignable(&arg_type, &param_types[i], arg_expr.get_span()) {
                                self.add_error(format!("Argument {} type mismatch: expected {:?}, found {:?}.", i, param_types[i], arg_type), arg_expr.get_span());
                            }
                        }
                        *return_type
                    },
                    _ => {
                        self.add_error(format!("Attempted to call non-function type {:?}.", func_type), span.clone());
                        Type::Error
                    }
                }
            }
            Expression::Index(span, array_expr, index_expr) => {
                let array_type = self.analyze_expression(array_expr);
                let index_type = self.analyze_expression(index_expr);

                if index_type != Type::Int {
                    self.add_error(format!("Array index must be an integer, found {:?}.", index_type), span.clone());
                    return Type::Error;
                }
                match array_type {
                    Type::QubitArray(_) => Type::Qubit,
                    Type::Linear(inner) | Type::Affine(inner) => *inner, // Indexing a linear/affine array yields a linear/affine element
                    _ => Type::Unknown, // For regular arrays, this would be `inner_type`
                }
            }
            Expression::MemberAccess(span, object_expr, member_id) => {
                let object_type = self.analyze_expression(object_expr);
                match object_type {
                    Type::Struct(_, fields) => {
                        if let Some(member_type) = fields.get(&member_id.0) {
                            member_type.clone()
                        } else {
                            self.add_error(format!("Member '{}' not found in struct type {:?}.", member_id.0, object_type), member_id.1);
                            Type::Error
                        }
                    },
                    _ => {
                        self.add_error(format!("Attempted to access member '{}' on non-struct type {:?}.", member_id.0, object_type), span.clone());
                        Type::Error
                    }
                }
            }
            Expression::QuantumGateApplication(span, gate_name, args) => {
                // Conceptual: validate gate_name and argument types (must be Qubit/QubitArray)
                for arg_expr in args {
                    let arg_type = self.analyze_expression(arg_expr);
                    if arg_type != Type::Qubit && !matches!(arg_type, Type::QubitArray(_)) {
                        self.add_error(format!("Quantum gate argument must be Qubit or QubitArray, found {:?}.", arg_type), arg_expr.get_span());
                    }
                }
                Type::Unit // Gates typically return Unit, modifying state implicitly
            }
            Expression::NanoAction(span, action_name, args) => {
                // Conceptual: validate action_name and argument types for nano-agents
                Type::Unit
            }
            Expression::MtsOperation(span, op_name, args) => {
                // Conceptual: validate op_name and args for MTS operations
                Type::Unknown // Return type depends on operation
            }
            Expression::PerformEffect(span, effect_name, args) => {
                // Conceptual: Check if effect_name is declared and args match its signature
                if self.lookup_symbol(effect_name, span.clone()).map_or(false, |s| s.kind == SymbolKind::Effect) {
                    Type::Unknown // The type of a 'perform' is the type of the continuation
                } else {
                    self.add_error(format!("Undeclared effect '{}'.", effect_name), span.clone());
                    Type::Error
                }
            }
        }
    }

    /// Analyzes a literal and returns its Type.
    fn analyze_literal(&mut self, literal: &ast::Literal) -> Type {
        match literal {
            Literal::Integer(_, _) => Type::Int,
            Literal::Float(_, _) => Type::Float,
            Literal::String(_, _) => Type::String,
            Literal::Char(_, _) => Type::Char,
            Literal::Boolean(_, _) => Type::Bool,
            Literal::Quantum(_, _) => Type::Qubit, // A quantum literal represents a qubit in a state
            Literal::MTS(_, _) => Type::MtsSlice(Box::new(Type::Unknown)), // MTS literal implies a slice
        }
    }

    /// Resolves an AST TypeExpr into a canonical Type.
    fn resolve_type_expr(&mut self, type_expr: &ast::TypeExpr) -> Type {
        match type_expr {
            TypeExpr::Base(ident) => {
                match ident.0.as_str() {
                    "int" => Type::Int,
                    "float" => Type::Float,
                    "bool" => Type::Bool,
                    "char" => Type::Char,
                    "string" => Type::String,
                    "unit" => Type::Unit,
                    "Qubit" => Type::Qubit,
                    "NanoAgent" => Type::NanoParticle,
                    "Zamani" => Type::Zamani,
                    "Sasa" => Type::Sasa,
                    _ => {
                        // Look up in symbol table for type aliases
                        self.lookup_symbol(&ident.0, ident.1).map_or_else(
                            || {
                                self.add_error(format!("Undefined type '{}'.", ident.0), ident.1);
                                Type::Error
                            },
                            |s| {
                                if s.kind == SymbolKind::TypeAlias {
                                    s.symbol_type.clone()
                                } else {
                                    self.add_error(format!("Symbol '{}' is not a type.", ident.0), ident.1);
                                    Type::Error
                                }
                            }
                        )
                    }
                }
            }
            TypeExpr::Array(element_type_expr, size_opt) => {
                let element_type = self.resolve_type_expr(element_type_expr);
                if let Some(size_str) = size_opt {
                    if let Ok(size) = size_str.parse::<usize>() {
                        if element_type == Type::Qubit {
                            return Type::QubitArray(size);
                        }
                    }
                }
                // For generic arrays, this would typically be a `Type::Array(Box<Type>)` or similar
                Type::Unknown // Placeholder
            }
            TypeExpr::FunctionType(param_type_exprs, return_type_expr) => {
                let param_types = param_type_exprs.iter().map(|te| self.resolve_type_expr(te)).collect();
                let return_type = self.resolve_type_expr(return_type_expr);
                Type::Function(param_types, Box::new(return_type))
            }
            TypeExpr::Tuple(elem_type_exprs) => {
                let elem_types = elem_type_exprs.iter().map(|te| self.resolve_type_expr(te)).collect();
                Type::Tuple(elem_types)
            }
            TypeExpr::Generic(ident, generic_arg_exprs) => {
                let base_type = self.resolve_type_expr(&ast::TypeExpr::Base(ident.clone()));
                let generic_args = generic_arg_exprs.iter().map(|te| self.resolve_type_expr(te)).collect::<Vec<Type>>();

                match base_type {
                    Type::Superposition(_) => Type::Superposition(Box::new(generic_args[0].clone())),
                    Type::Entangled(_) => Type::Entangled(generic_args),
                    Type::QMeasured(_) => Type::QMeasured(Box::new(generic_args[0].clone())),
                    Type::History(_) => Type::History(Box::new(generic_args[0].clone())),
                    Type::MtsSlice(_) => Type::MtsSlice(Box::new(generic_args[0].clone())),
                    Type::InterMemory(_, _) => Type::InterMemory(generic_args[0].to_string(), Box::new(generic_args[1].clone())),
                    // Handle other generic types and ensure correct number of arguments
                    _ => {
                        self.add_error(format!("Type '{}' is not a generic type or used incorrectly.", ident.0), ident.1);
                        Type::Error
                    }
                }
            }
            TypeExpr::Linear(inner_type_expr) => Type::Linear(Box::new(self.resolve_type_expr(inner_type_expr))),
            TypeExpr::Affine(inner_type_expr) => Type::Affine(Box::new(self.resolve_type_expr(inner_type_expr))),
            TypeExpr::Effectful(inner_type_expr, effects) => {
                // Validate effect names
                for effect_ident in effects {
                    if self.lookup_symbol(&effect_ident.0, effect_ident.1).map_or(false, |s| s.kind == SymbolKind::Effect) == false {
                        self.add_error(format!("Undeclared effect '{}'.", effect_ident.0), effect_ident.1);
                    }
                }
                Type::Effectful(Box::new(self.resolve_type_expr(inner_type_expr)), effects.clone())
            }
            TypeExpr::Dependent(base_type_expr, constraint_expr) => {
                let base_type = self.resolve_type_expr(base_type_expr);
                // Conceptual: constraint_expr should analyze to a boolean type, possibly with type variables
                let _ = self.analyze_expression(constraint_expr); 
                base_type // Dependent type usually resolves to its base type with a compile-time check
            }
            TypeExpr::PiType(name, binder_type_expr, return_type_expr) => {
                self.enter_scope();
                let binder_type = self.resolve_type_expr(binder_type_expr);
                self.define_symbol(name.clone(), binder_type.clone(), false, SymbolKind::Variable, Span::dummy()); // Bind name for return type scope
                let return_type = self.resolve_type_expr(return_type_expr);
                self.exit_scope();
                Type::Pi(name.clone(), Box::new(binder_type), Box::new(return_type))
            }
            TypeExpr::SigmaType(name, first_type_expr, second_type_expr) => {
                self.enter_scope();
                let first_type = self.resolve_type_expr(first_type_expr);
                self.define_symbol(name.clone(), first_type.clone(), false, SymbolKind::Variable, Span::dummy()); // Bind name for second type scope
                let second_type = self.resolve_type_expr(second_type_expr);
                self.exit_scope();
                Type::Sigma(name.clone(), Box::new(first_type), Box::new(second_type))
            }
            TypeExpr::Proof(assertion_type_expr, proof_expr) => {
                let assertion_type = self.resolve_type_expr(assertion_type_expr);
                // Conceptual: proof_expr must be a valid proof term that satisfies assertion_type
                let _ = self.analyze_expression(proof_expr);
                Type::Proof(Box::new(assertion_type))
            }
            TypeExpr::TypeFamily(ident, arg_type_exprs) => {
                // Conceptual: Lookup type family and apply arguments. Returns concrete type.
                Type::Unknown
            }
            TypeExpr::QuantumReg(element_type_expr, size_str) => {
                 let element_type = self.resolve_type_expr(element_type_expr);
                 if element_type != Type::Qubit {
                     self.add_error("Quantum register must contain Qubit elements.".to_string(), element_type_expr.get_span());
                     return Type::Error;
                 }
                 if let Ok(size) = size_str.parse::<usize>() {
                     Type::QubitArray(size)
                 } else {
                     self.add_error(format!("Invalid size for quantum register: '{}'.", size_str), element_type_expr.get_span());
                     Type::Error
                 }
            }
            TypeExpr::Superposition(inner_type_expr) => {
                Type::Superposition(Box::new(self.resolve_type_expr(inner_type_expr)))
            }
            TypeExpr::Entangled(type_exprs) => {
                Type::Entangled(type_exprs.iter().map(|te| self.resolve_type_expr(te)).collect())
            }
            TypeExpr::QMeasured(inner_type_expr) => {
                Type::QMeasured(Box::new(self.resolve_type_expr(inner_type_expr)))
            }
            TypeExpr::NanoAgentType(inner_type_expr) => {
                Type::NanoParticle // For simplicity, nano-agent type is just NanoParticle for now
            }
            TypeExpr::ArchaeveType(inner_type_expr) => {
                // Archaeve is a specialized memory type, conceptually holding any data
                Type::Unknown // Can be refined later
            }
            TypeExpr::MtsSlice(inner_type_expr, size_opt) => {
                 Type::MtsSlice(Box::new(self.resolve_type_expr(inner_type_expr)))
            }
            TypeExpr::HistoryType(inner_type_expr, years_opt) => {
                Type::History(Box::new(self.resolve_type_expr(inner_type_expr)))
            }
            TypeExpr::ConsensusTrueType(inner_type_expr) => {
                Type::Unknown // Represents a proven consensus on inner_type
            }
            TypeExpr::InterMemoryType(lang_id_expr, data_type_expr) => {
                // lang_id_expr would be resolved to a string literal (language ID)
                let lang_id = match lang_id_expr {
                    ast::TypeExpr::Base(Identifier(s, _)) => s.clone(),
                    _ => { self.add_error("InterMemory language ID must be an identifier.".to_string(), lang_id_expr.get_span()); "unknown".to_string() }
                };
                Type::InterMemory(lang_id, Box::new(self.resolve_type_expr(data_type_expr)))
            }
            TypeExpr::Error(span) => Type::Error,
        }
    }

    /// Determines if `from_type` can be assigned to `to_type`.
    /// This includes basic type equality, subtyping, and special Zenith rules.
    fn is_assignable(&mut self, from_type: &Type, to_type: &Type, span: Span) -> bool {
        if from_type == to_type {
            return true;
        }

        // --- Zenith-specific type compatibility rules ---

        // Implicit conversions (e.g., int to float)
        if (*from_type == Type::Int && *to_type == Type::Float) {
            return true;
        }

        // Linear/Affine type checks (strict ownership and usage rules)
        match (from_type, to_type) {
            (Type::Linear(from_inner), Type::Linear(to_inner)) => {
                // If strict management is on, enforce one-to-one assignment.
                if self.evas_policy.strict_resource_management {
                    // This is where actual consumption tracking would happen
                    // For now, just check inner types
                    return self.is_assignable(from_inner, to_inner, span);
                } else {
                    // Less strict, might allow copying for non-unique resources (if allowed by policy)
                    return self.is_assignable(from_inner, to_inner, span);
                }
            },
            (Type::Affine(from_inner), Type::Affine(to_inner)) => {
                 if self.evas_policy.strict_resource_management {
                    // Affine can be dropped or consumed once
                    return self.is_assignable(from_inner, to_inner, span);
                } else {
                    return self.is_assignable(from_inner, to_inner, span);
                }
            },
            // Cannot implicitly convert between linear/affine and regular types without explicit operations.
            (Type::Linear(_), _) | (_, Type::Linear(_)) => {
                self.add_error(format!("Cannot implicitly convert between linear/affine and non-linear/affine types. Found {:?} to {:?}.", from_type, to_type), span);
                return false;
            },
            (Type::Affine(_), _) | (_, Type::Affine(_)) => {
                self.add_error(format!("Cannot implicitly convert between linear/affine and non-linear/affine types. Found {:?} to {:?}.", from_type, to_type), span);
                return false;
            },
            _ => (),
        }

        // Quantum type checks
        match (from_type, to_type) {
            (Type::Qubit, Type::QubitArray(_)) => {
                // A single qubit can be assigned to a QubitArray if size 1, or added to it. (Semantic context needed)
                // For now, disallow implicit conversion
                false
            },
            // Other quantum specific rules
            (Type::QMeasured(from_inner), to_t) if *from_inner == *to_t => {
                // A measured quantum type collapses to its classical equivalent
                return true;
            }
            _ => (),
        }

        // Relaxed checks in unsafe context (e.g., raw pointer casts)
        if self.in_unsafe_context.last().map_or(false, |&b| b) {
            // Conceptual: Allow more relaxed type checks here, e.g., numeric conversions, pointer casts.
            // This would be governed by the specific proof provided in 'unsafe!'
            println!("  (Unsafe context) Relaxing assignability check for {:?} to {:?}", from_type, to_type);
            return true; // Very permissive for conceptual demo
        }

        // Default: types are not assignable
        false
    }

    /// Checks the validity of a prefix operator with its operand type.
    fn check_prefix_operator(&mut self, op: TokenType, operand_type: &Type, span: Span) -> Type {
        match op {
            TokenType::Minus => {
                if *operand_type == Type::Int || *operand_type == Type::Float {
                    operand_type.clone()
                } else {
                    self.add_error(format!("Unary '-' operator not applicable to type {:?}.", operand_type), span);
                    Type::Error
                }
            }
            TokenType::Bang => {
                if *operand_type == Type::Bool {
                    Type::Bool
                } else {
                    self.add_error(format!("Unary '!' operator not applicable to type {:?}.", operand_type), span);
                    Type::Error
                }
            }
            _ => {
                self.add_error(format!("Unsupported prefix operator {:?}.", op), span);
                Type::Error
            }
        }
    }

    /// Checks the validity of an infix operator with its operand types.
    fn check_infix_operator(&mut self, op: TokenType, left_type: &Type, right_type: &Type, span: Span) -> Type {
        match op {
            TokenType::Plus | TokenType::Minus | TokenType::Star | TokenType::Slash => {
                if (*left_type == Type::Int && *right_type == Type::Int) || (*left_type == Type::Float && *right_type == Type::Float) {
                    left_type.clone()
                } else if (*left_type == Type::Int && *right_type == Type::Float) || (*left_type == Type::Float && *right_type == Type::Int) {
                    Type::Float // Promote to float
                } else {
                    self.add_error(format!("Arithmetic operator {:?} not applicable to types {:?} and {:?}.", op, left_type, right_type), span);
                    Type::Error
                }
            }
            TokenType::Equals | TokenType::NotEquals | TokenType::LT | TokenType::GT | TokenType::LTE | TokenType::GTE => {
                if left_type == right_type {
                    Type::Bool
                } else {
                    self.add_error(format!("Comparison operator {:?} not applicable to types {:?} and {:?}.", op, left_type, right_type), span);
                    Type::Error
                }
            }
            _ => {
                self.add_error(format!("Unsupported infix operator {:?}.", op), span);
                Type::Error
            }
        }
    }

    /// Defines a new symbol in the current scope.
    fn define_symbol(&mut self, name: String, symbol_type: Type, is_mutable: bool, kind: SymbolKind, span: Span) {
        let current_scope_idx = self.scope_stack.len() - 1;
        if self.scope_stack[current_scope_idx].contains_key(&name) {
            self.add_error(format!("Symbol '{}' already defined in this scope.", name), span);
        } else {
            self.scope_stack[current_scope_idx].insert(name.clone(), Symbol {
                name,
                symbol_type,
                is_mutable,
                span,
                kind,
            });
            self.symbol_table.insert(name.clone(), self.scope_stack[current_scope_idx][&name].clone()); // Also update global view
        }
    }

    /// Looks up a symbol, searching parent scopes if necessary.
    fn lookup_symbol(&mut self, name: &str, span: Span) -> Option<Symbol> {
        for i in (0..self.scope_stack.len()).rev() {
            if let Some(symbol) = self.scope_stack[i].get(name) {
                return Some(symbol.clone());
            }
        }
        self.add_error(format!("Undeclared symbol '{}'.", name), span);
        None
    }

    /// Enters a new scope.
    fn enter_scope(&mut self) {
        self.scope_stack.push(HashMap::new());
    }

    /// Exits the current scope.
    fn exit_scope(&mut self) {
        self.scope_stack.pop();
        // In a real compiler, symbols removed from stack scope would be removed from global view
    }

    /// Adds a semantic error to the list.
    fn add_error(&mut self, message: String, span: Span) {
        self.errors.push(SemanticError { message, span });
    }

    /// Helper to analyze either a statement or the last expression in a block.
    fn analyze_statement_or_expression(&mut self, stmt: &ast::Statement) -> Type {
        match stmt {
            ast::Statement::Expression(expr) => self.analyze_expression(expr),
            _ => {
                self.analyze_statement(stmt);
                Type::Unit // Statements typically yield Unit type
            }
        }
    }

    pub fn get_errors(&self) -> &[SemanticError] {
        &self.errors
    }
}
