
//! Zenith Universal Meta-Compiler (UMC) Semantic Analyzer
//!
//! This module implements the semantic analysis phase of the Zenith compiler.
//! It takes the Abstract Syntax Tree (AST) generated by the parser and performs
//! checks for type correctness, variable scope, linearity, effect handling,
//! and other language-specific rules that cannot be enforced by the grammar alone.
//!
//! Key responsibilities include:
//! - **Symbol Table Management:** Tracking declared variables, functions, types, and effects.
//! - **Type Checking:** Ensuring all operations are performed on compatible types, including
//!   classical, quantum, nano, multi-timeline, and Sankofa-specific types.
//! - **Scope Management:** Resolving identifiers based on their lexical scope.
//! - **Linearity/Affinity Enforcement:** Verifying unique usage constraints for linear/affine types.
//! - **Effect System Verification:** Ensuring effects are handled correctly.
//! - **Error Reporting:** Collecting semantic errors with precise source locations.

use crate::ast::{Program, Statement, Expression, Literal, Identifier, TypeExpr, Parameter, MatchCase};
use crate::compiler_types::{Type, Symbol, IntWidth, FloatWidth};
use crate::tokens::{Span, TokenType};
use std::collections::HashMap;

/// Represents a conceptual scope in the program, holding symbols.
#[derive(Debug, Clone)]
pub struct Scope {
    symbols: HashMap<String, Symbol>,
    parent: Option<Box<Scope>>, // For nested scopes
}

impl Scope {
    pub fn new(parent: Option<Box<Scope>>) -> Self {
        Scope { symbols: HashMap::new(), parent }
    }

    pub fn define(&mut self, symbol: Symbol) -> Result<(), SemanticError> {
        if self.symbols.contains_key(&symbol.name) {
            return Err(SemanticError {
                message: format!("Redeclaration of symbol '{}'".to_string(), symbol.name),
                span: symbol.span.clone(),
            });
        }
        self.symbols.insert(symbol.name.clone(), symbol);
        Ok(())
    }

    pub fn resolve(&self, name: &str) -> Option<&Symbol> {
        self.symbols.get(name).or_else(|| self.parent.as_ref()?.resolve(name))
    }
}


/// Semantic Analyzer structure.
pub struct SemanticAnalyzer {
    current_scope: Scope,
    errors: Vec<SemanticError>,
    // Add context for linear/affine analysis, effect context, etc.
    linear_resource_usage: HashMap<String, usize>, // Tracks how many times a linear resource is used
    current_effect_context: Vec<Vec<Identifier>>, // Stack of effects handled by current scope
}

/// Semantic Error structure.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SemanticError {
    pub message: String,
    pub span: Span,
}

impl SemanticAnalyzer {
    pub fn new() -> Self {
        SemanticAnalyzer {
            current_scope: Scope::new(None), // Global scope
            errors: Vec::new(),
            linear_resource_usage: HashMap::new(),
            current_effect_context: Vec::new(),
        }
    }

    /// Entry point for semantic analysis.
    pub fn analyze(&mut self, program: &Program) -> Result<(), Vec<SemanticError>> {
        println!("Performing semantic analysis...");

        // Pre-populate global scope with built-in types and functions
        self.define_builtin_symbols();

        for stmt in program.statements.iter() {
            self.analyze_statement(stmt);
        }

        if !self.errors.is_empty() {
            Err(self.errors.clone())
        } else {
            Ok(())
        }
    }

    fn define_builtin_symbols(&mut self) {
        // Conceptual built-in types
        self.current_scope.define(Symbol::new("int".to_string(), Type::Int(IntWidth::I32), Span::dummy(), false)).unwrap();
        self.current_scope.define(Symbol::new("float".to_string(), Type::Float(FloatWidth::F64), Span::dummy(), false)).unwrap();
        self.current_scope.define(Symbol::new("bool".to_string(), Type::Bool, Span::dummy(), false)).unwrap();
        self.current_scope.define(Symbol::new("string".to_string(), Type::String, Span::dummy(), false)).unwrap();
        self.current_scope.define(Symbol::new("char".to_string(), Type::Char, Span::dummy(), false)).unwrap();
        self.current_scope.define(Symbol::new("Qubit".to_string(), Type::Qubit, Span::dummy(), false)).unwrap();
        self.current_scope.define(Symbol::new("QReg".to_string(), Type::QReg(0), Span::dummy(), false)).unwrap(); // Placeholder size
        self.current_scope.define(Symbol::new("NanoAgent".to_string(), Type::NanoAgent(None), Span::dummy(), false)).unwrap();
        self.current_scope.define(Symbol::new("MtsSlice".to_string(), Type::MtsSlice(Box::new(Type::Unknown)), Span::dummy(), false)).unwrap();
        self.current_scope.define(Symbol::new("ZamaniFact".to_string(), Type::ZamaniFact(Box::new(Type::Unknown)), Span::dummy(), false)).unwrap();
        self.current_scope.define(Symbol::new("SasaKnowledge".to_string(), Type::SasaKnowledge(Box::new(Type::Unknown)), Span::dummy(), false)).unwrap();
        self.current_scope.define(Symbol::new("evas".to_string(), Type::Prop, Span::dummy(), false)).unwrap(); // For unsafe!(evas:proof) context
        
        // Built-in functions (simplified, actual types would be complex Function types)
        self.current_scope.define(Symbol::new("stdlib::core::println".to_string(), Type::Function(vec![Type::String], Box::new(Type::Unit)), Span::dummy(), false)).unwrap();
        self.current_scope.define(Symbol::new("stdlib::core::to_string".to_string(), Type::Function(vec![Type::Unknown], Box::new(Type::String)), Span::dummy(), false)).unwrap();
        self.current_scope.define(Symbol::new("H".to_string(), Type::Function(vec![Type::Qubit], Box::new(Type::Qubit)), Span::dummy(), false)).unwrap(); // Quantum gate
        self.current_scope.define(Symbol::new("cnot".to_string(), Type::Function(vec![Type::Qubit, Type::Qubit], Box::new(Type::Tuple(vec![Type::Qubit, Type::Qubit]))), Span::dummy(), false)).unwrap(); // Quantum gate
        self.current_scope.define(Symbol::new("measure".to_string(), Type::Function(vec![Type::Qubit], Box::new(Type::Bool)), Span::dummy(), false)).unwrap(); // Quantum measure
        self.current_scope.define(Symbol::new("assemble".to_string(), Type::Function(vec![Type::String, Type::Array(Box::new(Type::String), None)], Box::new(Type::NanoAgent(None))), Span::dummy(), false)).unwrap();
        self.current_scope.define(Symbol::new("perform".to_string(), Type::Function(vec![Type::Effect(Identifier("".to_string(), Span::dummy())), Type::Unknown], Box::new(Type::Unknown)), Span::dummy(), false)).unwrap();
    }

    fn analyze_statement(&mut self, stmt: &Statement) {
        match stmt {
            Statement::Let(span, name, type_expr_opt, expr) => {
                let expr_type = self.analyze_expression(expr);
                let declared_type = type_expr_opt.as_ref().map_or(Type::Unknown, |te| self.resolve_type_expr(te));

                // Type inference/checking
                let final_type = if declared_type != Type::Unknown { // If type explicitly declared
                    if !self.is_assignable(&declared_type, &expr_type) {
                        self.errors.push(SemanticError {
                            message: format!("Mismatched types for let statement: expected {:?}, found {:?}", declared_type, expr_type),
                            span: span.clone(),
                        });
                        Type::Error
                    } else {
                        declared_type
                    }
                } else { // Type inference from expression
                    expr_type
                };
                self.current_scope.define(Symbol::new(name.clone(), final_type, span.clone(), true)).unwrap_or_else(|e| self.errors.push(e));
            }
            Statement::Return(span, expr) => {
                self.analyze_expression(expr); // Just check expr type for now
            }
            Statement::Expression(expr) => {
                self.analyze_expression(expr);
            }
            Statement::Function(span, name, params, return_type_expr_opt, body) => {
                // Save current scope and enter new scope for function
                let original_scope = std::mem::replace(&mut self.current_scope, Scope::new(Some(Box::new(self.current_scope.clone()))));

                let mut param_types = Vec::new();
                for param in params.iter() {
                    let param_type = self.resolve_type_expr(param.typ.as_ref().unwrap_or_else(|| {
                        self.errors.push(SemanticError{ message: format!("Parameter '{}' must have a type annotation.", param.name.0), span: param.name.1.clone() });
                        &TypeExpr::Base(Identifier("Unknown".to_string(), Span::dummy()))
                    }));
                    self.current_scope.define(Symbol::new(param.name.0.clone(), param_type.clone(), param.name.1.clone(), true)).unwrap_or_else(|e| self.errors.push(e));
                    param_types.push(param_type);
                }
                let return_type = return_type_expr_opt.as_ref().map_or(Type::Unit, |te| self.resolve_type_expr(te));

                // Register function in the *original* scope (parent scope) to allow recursion and external calls
                let func_symbol = Symbol::new(name.clone(), Type::Function(param_types.clone(), Box::new(return_type.clone())), span.clone(), false);
                if let Some(mut p_scope) = original_scope.parent { // original_scope now has no parent
                    if let Err(e) = p_scope.define(func_symbol) {
                        self.errors.push(e);
                    }
                    self.current_scope.parent = Some(p_scope); // Restore correct parent link for nested analysis
                } else { // Handle global function definition
                     if let Err(e) = self.current_scope.define(func_symbol) { // Should technically define in the parent_scope before replace.
                        self.errors.push(e);
                    }
                }

                // Analyze function body
                let body_type = self.analyze_expression(body);
                if !self.is_assignable(&return_type, &body_type) && return_type != Type::Unit { // If function is not Unit and body type does not match
                    self.errors.push(SemanticError { message: format!("Function '{}' body returns {:?}, but declared return type is {:?}", name, body_type, return_type), span: body.span().clone() });
                }

                // Exit function scope
                self.current_scope = *self.current_scope.parent.take().unwrap();
            }
            Statement::QuantumCircuit(span, name, body) => {
                let original_scope = std::mem::replace(&mut self.current_scope, Scope::new(Some(Box::new(self.current_scope.clone()))));
                let qcirc_symbol = Symbol::new(name.clone(), Type::Function(vec![], Box::new(Type::Unit)), span.clone(), false);
                if let Some(mut p_scope) = original_scope.parent {
                    if let Err(e) = p_scope.define(qcirc_symbol) {
                        self.errors.push(e);
                    }
                    self.current_scope.parent = Some(p_scope);
                } else {
                    if let Err(e) = self.current_scope.define(qcirc_symbol) {self.errors.push(e);}
                }
                self.analyze_expression(body);
                self.current_scope = *self.current_scope.parent.take().unwrap();
            }
            Statement::NanoAgent(span, name, body) => {
                let original_scope = std::mem::replace(&mut self.current_scope, Scope::new(Some(Box::new(self.current_scope.clone()))));
                let nano_agent_symbol = Symbol::new(name.clone(), Type::NanoAgent(Some(Identifier(name.clone(), span.clone()))), span.clone(), false);
                if let Some(mut p_scope) = original_scope.parent {
                    if let Err(e) = p_scope.define(nano_agent_symbol) {
                        self.errors.push(e);
                    }
                    self.current_scope.parent = Some(p_scope);
                } else {
                     if let Err(e) = self.current_scope.define(nano_agent_symbol) {self.errors.push(e);}
                }
                self.analyze_expression(body);
                self.current_scope = *self.current_scope.parent.take().unwrap();
            }
            Statement::SankofaMemory(span, name, expr) => {
                let expr_type = self.analyze_expression(expr);
                self.current_scope.define(Symbol::new(name.clone(), Type::SasaKnowledge(Box::new(expr_type)), span.clone(), true)).unwrap_or_else(|e| self.errors.push(e));
            }
            Statement::TypeDeclaration(span, name, type_expr) => {
                let resolved_type = self.resolve_type_expr(type_expr);
                self.current_scope.define(Symbol::new(name.clone(), resolved_type, span.clone(), false)).unwrap_or_else(|e| self.errors.push(e));
            }
            Statement::EffectDeclaration(span, effect_id) => {
                self.current_scope.define(Symbol::new(effect_id.0.clone(), Type::Effect(effect_id.clone()), span.clone(), false)).unwrap_or_else(|e| self.errors.push(e));
            }
            Statement::LanguageDeclaration(_, _, _) => { /* Handled at higher level */ }
            Statement::While(span, cond, body) => {
                let cond_type = self.analyze_expression(cond);
                if cond_type != Type::Bool && cond_type != Type::Error { // Check if condition is boolean
                    self.errors.push(SemanticError { message: "While condition must be of type bool".to_string(), span: cond.span().clone() });
                }
                // Enter new scope for loop body
                let original_scope = std::mem::replace(&mut self.current_scope, Scope::new(Some(Box::new(self.current_scope.clone()))));
                self.analyze_expression(body);
                self.current_scope = *self.current_scope.parent.take().unwrap(); // Exit loop body scope
            }
            Statement::For(span, iter_var, iterable, body) => {
                // Conceptual: Resolve iterable type and infer iter_var type
                let iterable_type = self.analyze_expression(iterable);
                let iter_var_type = match iterable_type {
                    Type::Array(elem_type, _) => *elem_type,
                    // Add other iterable types like List, Map keys/values, etc.
                    _ => {
                        self.errors.push(SemanticError { message: format!("For loop iterable must be an array or similar collection, found {:?}", iterable_type), span: iterable.span().clone() });
                        Type::Error
                    }
                };
                
                // Enter new scope for loop body, defining iterator variable
                let original_scope = std::mem::replace(&mut self.current_scope, Scope::new(Some(Box::new(self.current_scope.clone()))));
                self.current_scope.define(Symbol::new(iter_var.0.clone(), iter_var_type, iter_var.1.clone(), true)).unwrap_or_else(|e| self.errors.push(e));
                self.analyze_expression(body);
                self.current_scope = *self.current_scope.parent.take().unwrap(); // Exit loop body scope
            }
            Statement::Break(span) => { /* Control flow handled by IR/Optimizer, semantic check is context */ }
            Statement::Continue(span) => { /* Control flow handled by IR/Optimizer, semantic check is context */ }
            Statement::Match(span, matched_expr, cases) => {
                let matched_type = self.analyze_expression(matched_expr);
                let mut case_body_types = Vec::new();

                for case in cases.iter() {
                    let pattern_type = self.analyze_expression(&case.pattern);
                    if !self.is_assignable(&matched_type, &pattern_type) && pattern_type != Type::Error {
                         self.errors.push(SemanticError { message: format!("Match pattern type {:?} incompatible with matched expression type {:?}", pattern_type, matched_type), span: case.pattern.span().clone() });
                    }
                    // Enter new scope for match case body
                    let original_scope = std::mem::replace(&mut self.current_scope, Scope::new(Some(Box::new(self.current_scope.clone()))));
                    case_body_types.push(self.analyze_expression(&case.body));
                    self.current_scope = *self.current_scope.parent.take().unwrap(); // Exit case body scope
                }

                // Ensure all case bodies return compatible types
                if !case_body_types.is_empty() {
                    let first_type = &case_body_types[0];
                    for other_type in case_body_types.iter().skip(1) {
                        if !self.is_assignable(first_type, other_type) && !self.is_assignable(other_type, first_type) {
                            self.errors.push(SemanticError { message: "Match arms have incompatible types.".to_string(), span: span.clone() });
                            break;
                        }
                    }
                }
            }
            Statement::Unsafe(span, proof_opt, block) => {
                // Conceptual: The presence of `unsafe` is a semantic flag. The `proof_opt` (e.g., `evas:MyProofId`) 
                // would be checked against a formal verification system or security context at a later stage, 
                // or if the proof_id is a known built-in. For now, we check if proof_id is defined.
                if let Some(proof_id_ident) = proof_opt {
                    if self.current_scope.resolve(&proof_id_ident.0).is_none() {
                        self.errors.push(SemanticError { message: format!("Unrecognized safety proof ID '{}'.", proof_id_ident.0), span: proof_id_ident.1.clone() });
                    }
                }
                // Enter new scope for unsafe block
                let original_scope = std::mem::replace(&mut self.current_scope, Scope::new(Some(Box::new(self.current_scope.clone()))));
                self.analyze_expression(block);
                self.current_scope = *self.current_scope.parent.take().unwrap(); // Exit unsafe block scope
            }
            Statement::Handle(span, effect_id, body_expr, handler_expr) => {
                // Check if the effect is declared
                if self.current_scope.resolve(&effect_id.0).is_none() {
                    self.errors.push(SemanticError { message: format!("Undeclared effect '{}'.", effect_id.0), span: effect_id.1.clone() });
                }
                
                // Enter new effect context, adding this effect to the list of handled effects
                let mut new_effect_set = self.current_effect_context.last().cloned().unwrap_or_default();
                new_effect_set.push(effect_id.clone());
                self.current_effect_context.push(new_effect_set);

                // Analyze the body expression within this new effect context
                self.analyze_expression(body_expr);

                // Analyze the handler expression (which will also have its own scope for handler parameters)
                self.analyze_expression(handler_expr);

                // Exit effect context
                self.current_effect_context.pop();
            }
        }
    }

    fn analyze_expression(&mut self, expr: &Expression) -> Type {
        match expr {
            Expression::Identifier(Identifier(name, span)) => {
                if let Some(symbol) = self.current_scope.resolve(name) {
                    // For linear/affine types, track usage
                    if matches!(symbol.typ, Type::Linear(_) | Type::Affine(_)) {
                        *self.linear_resource_usage.entry(name.clone()).or_insert(0) += 1;
                        // Later checks: linear = exactly 1 use, affine = at most 1 use.
                        // This current implementation just counts, actual enforcement is more complex.
                    }
                    symbol.typ.clone()
                } else {
                    self.errors.push(SemanticError {
                        message: format!("Unresolved identifier '{}'".to_string(), name),
                        span: span.clone(),
                    });
                    Type::Error
                }
            }
            Expression::Literal(literal) => {
                match literal {
                    Literal::Integer(_, _) => Type::Int(IntWidth::I32), // Default
                    Literal::Float(_, _) => Type::Float(FloatWidth::F64), // Default
                    Literal::String(_, _) => Type::String,
                    Literal::Boolean(_, _) => Type::Bool,
                    Literal::Char(_, _) => Type::Char,
                    Literal::Quantum(_, _) => Type::Qubit, // Simplified: actual type depends on state
                    Literal::Nano(_, _) => Type::NanoAgent(None), // Simplified
                    Literal::MTS(_, _) => Type::MtsSlice(Box::new(Type::Unknown)), // Simplified
                }
            }
            Expression::Prefix(span, op, right) => {
                let right_type = self.analyze_expression(right);
                match op {
                    TokenType::Minus => {
                        if matches!(right_type, Type::Int(_) | Type::Float(_)) { right_type } else { Type::Error }
                    }
                    TokenType::Bang => {
                        if right_type == Type::Bool { Type::Bool } else { Type::Error }
                    }
                    _ => {
                        self.errors.push(SemanticError { message: format!("Unhandled prefix operator {:?} during type checking", op), span: span.clone() });
                        Type::Error
                    }
                }
            }
            Expression::Infix(span, left, op, right) => {
                let left_type = self.analyze_expression(left);
                let right_type = self.analyze_expression(right);

                // Handle string concatenation
                if matches!(op, TokenType::Plus) && left_type == Type::String && right_type == Type::String {
                    return Type::String;
                }

                // Basic type compatibility for arithmetic/comparison
                if left_type == right_type && left_type != Type::Error && left_type != Type::Unknown {
                    match op {
                        // Arithmetic ops return same type
                        TokenType::Plus | TokenType::Minus | TokenType::Star | TokenType::Slash => {
                            if matches!(left_type, Type::Int(_) | Type::Float(_)) { left_type } else { Type::Error }
                        }
                        // Comparison ops return bool
                        TokenType::Equals | TokenType::NotEquals | TokenType::LT | TokenType::GT | TokenType::LTE | TokenType::GTE => {
                            if matches!(left_type, Type::Int(_) | Type::Float(_) | Type::Bool) { Type::Bool } else { Type::Error }
                        }
                        TokenType::LogicalAnd | TokenType::LogicalOr => {
                            if left_type == Type::Bool { Type::Bool } else { Type::Error }
                        }
                        _ => {
                            self.errors.push(SemanticError { message: format!("Unhandled infix operator {:?} during type checking", op), span: span.clone() });
                            Type::Error
                        }
                    }
                } else {
                    self.errors.push(SemanticError { message: format!("Incompatible types for operator {:?}: {:?} and {:?}", op, left_type, right_type), span: span.clone() });
                    Type::Error
                }
            }
            Expression::If(span, cond, then_block, else_block_opt) => {
                let cond_type = self.analyze_expression(cond);
                if cond_type != Type::Bool && cond_type != Type::Error {
                    self.errors.push(SemanticError { message: "If condition must be of type bool".to_string(), span: cond.span().clone() });
                }
                let then_type = self.analyze_expression(then_block);
                let else_type = else_block_opt.as_ref().map_or(Type::Unit, |eb| self.analyze_expression(eb));
                
                // If expressions must have a consistent return type (or unit)
                if self.is_assignable(&then_type, &else_type) {
                    then_type
                } else if self.is_assignable(&else_type, &then_type) {
                    else_type
                } else {
                    self.errors.push(SemanticError { message: format!("If expression branches have inconsistent types: {:?} and {:?}", then_type, else_type), span: span.clone() });
                    Type::Error
                }
            }
            Expression::Block(span, statements) => {
                // Enter new scope for block
                let original_scope = std::mem::replace(&mut self.current_scope, Scope::new(Some(Box::new(self.current_scope.clone()))));
                let mut last_type = Type::Unit;
                for stmt in statements.iter() {
                    if let Statement::Expression(expr) = stmt {
                        last_type = self.analyze_expression(expr);
                    } else {
                        self.analyze_statement(stmt);
                    }
                }
                // Exit block scope
                self.current_scope = *self.current_scope.parent.take().unwrap();
                last_type
            }
            Expression::Call(span, func_expr, args) => {
                let func_type = self.analyze_expression(func_expr);
                let arg_types: Vec<Type> = args.iter().map(|arg| self.analyze_expression(arg)).collect();

                match func_type {
                    Type::Function(param_types, return_type) => {
                        if param_types.len() != arg_types.len() {
                            self.errors.push(SemanticError { message: format!("Function call expects {} arguments, but found {}", param_types.len(), arg_types.len()), span: span.clone() });
                            return Type::Error;
                        }
                        for (i, (expected, actual)) in param_types.iter().zip(arg_types.iter()).enumerate() {
                            if !self.is_assignable(expected, actual) && actual != &Type::Error {
                                self.errors.push(SemanticError { message: format!("Argument {} type mismatch: expected {:?}, found {:?}", i, expected, actual), span: args[i].span().clone() });
                                return Type::Error;
                            }
                        }
                        *return_type
                    }
                    Type::Effect(effect_id) => {
                        // Conceptual: check if effect is handled in current context
                        let mut is_handled = false;
                        for handler_effects in self.current_effect_context.iter().rev() {
                            if handler_effects.iter().any(|id| id == &effect_id) {
                                is_handled = true;
                                break;
                            }
                        }
                        if !is_handled {
                            self.errors.push(SemanticError { message: format!("Effect '{}' is performed but not handled in this scope.", effect_id.0), span: span.clone() });
                        }
                        Type::Unit // Effects don't return a direct value in this simplified model, often resume with unit or a specific value
                    }
                    _ => {
                        self.errors.push(SemanticError { message: format!("Cannot call non-function type: {:?}", func_type), span: span.clone() });
                        Type::Error
                    }
                }
            }
            Expression::Index(span, array_expr, index_expr) => {
                let array_type = self.analyze_expression(array_expr);
                let index_type = self.analyze_expression(index_expr);

                if index_type != Type::Int(IntWidth::I32) && index_type != Type::Error {
                    self.errors.push(SemanticError { message: format!("Array index must be an integer, found {:?}", index_type), span: index_expr.span().clone() });
                    return Type::Error;
                }
                match array_type {
                    Type::Array(elem_type, _) => *elem_type,
                    Type::QReg(_) => Type::Qubit, // Indexing a QReg yields a Qubit
                    _ => {
                        self.errors.push(SemanticError { message: format!("Cannot index non-array type: {:?}", array_type), span: array_expr.span().clone() });
                        Type::Error
                    }
                }
            }
            Expression::MemberAccess(span, object_expr, member_id) => {
                let object_type = self.analyze_expression(object_expr);
                match object_type {
                    // Built-in types with conceptual methods (like stdlib types in example source)
                    Type::Qubit => {
                        match member_id.0.as_str() {
                            "h" | "cnot" | "measure" => Type::Function(vec![Type::Qubit], Box::new(Type::Unit)), // Simplified signatures
                            _ => {
                                self.errors.push(SemanticError { message: format!("Qubit type has no member '{}'".to_string(), member_id.0), span: member_id.1.clone() });
                                Type::Error
                            }
                        }
                    }
                    Type::NanoAgent(_) => {
                        match member_id.0.as_str() {
                            "assemble" => Type::Function(vec![Type::String, Type::Array(Box::new(Type::String), None)], Box::new(Type::NanoAgent(None))), // Simplified
                            "communicate" => Type::Function(vec![Type::NanoAgent(None), Type::NanoAgent(None), Type::String], Box::new(Type::Unit)),
                            "replicate" => Type::Function(vec![Type::NanoAgent(None)], Box::new(Type::NanoAgent(None))), 
                            "perform_action" => Type::Function(vec![Type::NanoAgent(None), Type::String], Box::new(Type::Unit)),
                            _ => {
                                self.errors.push(SemanticError { message: format!("NanoAgent type has no member '{}'".to_string(), member_id.0), span: member_id.1.clone() });
                                Type::Error
                            }
                        }
                    }
                    Type::MtsSlice(_) => {
                        match member_id.0.as_str() {
                            "new" => Type::Function(vec![Type::Unknown], Box::new(Type::MtsSlice(Box::new(Type::Unknown)))),
                            "load" => Type::Function(vec![Type::MtsSlice(Box::new(Type::Unknown)), Type::Int(IntWidth::I32)], Box::new(Type::Unknown)),
                            "store" => Type::Function(vec![Type::MtsSlice(Box::new(Type::Unknown)), Type::Unknown, Type::Int(IntWidth::I32)], Box::new(Type::Unit)),
                            "synchronize" => Type::Function(vec![Type::MtsSlice(Box::new(Type::Unknown)), Type::MtsSlice(Box::new(Type::Unknown))], Box::new(Type::MtsSlice(Box::new(Type::Unknown)))),
                            _ => {
                                self.errors.push(SemanticError { message: format!("MtsSlice type has no member '{}'".to_string(), member_id.0), span: member_id.1.clone() });
                                Type::Error
                            }
                        }
                    }
                    Type::ZamaniFact(_) => {
                        match member_id.0.as_str() {
                            "access" => Type::Function(vec![Type::String], Box::new(Type::ZamaniFact(Box::new(Type::Unknown)))),
                            "get_content" => Type::Function(vec![Type::ZamaniFact(Box::new(Type::Unknown))], Box::new(Type::Unknown)),
                            _ => {
                                self.errors.push(SemanticError { message: format!("ZamaniFact type has no member '{}'".to_string(), member_id.0), span: member_id.1.clone() });
                                Type::Error
                            }
                        }
                    }
                    // Generic struct/enum member access
                    Type::Struct(_, fields) => {
                        if let Some(field_type) = fields.get(&member_id.0) {
                            field_type.clone()
                        } else {
                            self.errors.push(SemanticError { message: format!("Struct has no member '{}'".to_string(), member_id.0), span: member_id.1.clone() });
                            Type::Error
                        }
                    }
                    _ => {
                        self.errors.push(SemanticError { message: format!("Cannot access member '{}' on type {:?}".to_string(), member_id.0, object_type), span: member_id.1.clone() });
                        Type::Error
                    }
                }
            }
        }
    }

    /// Resolves an AST TypeExpr into a compiled Type.
    fn resolve_type_expr(&mut self, type_expr: &TypeExpr) -> Type {
        match type_expr {
            TypeExpr::Base(Identifier(name, span)) => {
                if let Some(symbol) = self.current_scope.resolve(name) {
                    symbol.typ.clone()
                } else {
                    self.errors.push(SemanticError { message: format!("Unresolved type name '{}'".to_string(), name), span: span.clone() });
                    Type::Error
                }
            }
            TypeExpr::Array(elem_type_expr, size_opt) => {
                let elem_type = self.resolve_type_expr(elem_type_expr);
                let size = size_opt.as_ref().and_then(|s| s.parse::<usize>().ok());
                Type::Array(Box::new(elem_type), size)
            }
            TypeExpr::Generic(base_type_expr, generic_args_exprs) => {
                let base_type = self.resolve_type_expr(base_type_expr);
                let generic_args: Vec<Type> = generic_args_exprs.iter().map(|arg_te| self.resolve_type_expr(arg_te)).collect();
                // Conceptual: Handle specific generics like Superposition<T>, Entangled<A,B>
                match base_type {
                    Type::Superposition(_) => Type::Superposition(Box::new(generic_args.first().cloned().unwrap_or(Type::Unknown))),
                    Type::Entangled(_,_) => Type::Entangled(Box::new(generic_args.get(0).cloned().unwrap_or(Type::Unknown)), Box::new(generic_args.get(1).cloned().unwrap_or(Type::Unknown))),
                    Type::QReg(_) => Type::QReg(generic_args.first().cloned().map_or(0, |t| if let Type::Int(IntWidth::I32) = t { 0 } else {0})), // Simplified, should get size from Generic
                    _ => {
                        self.errors.push(SemanticError { message: format!("Unsupported generic type: {:?}", base_type), span: type_expr.span().clone() });
                        Type::Error
                    }
                }
            }
            TypeExpr::FunctionType(param_type_exprs, return_type_expr) => {
                let param_types = param_type_exprs.iter().map(|te| self.resolve_type_expr(te)).collect();
                let return_type = self.resolve_type_expr(return_type_expr);
                Type::Function(param_types, Box::new(return_type))
            }
            TypeExpr::DependentPi(binder, bindee, body) => {
                Type::DependentPi(binder.clone(), Box::new(self.resolve_type_expr(bindee)), Box::new(self.resolve_type_expr(body)))
            }
            TypeExpr::DependentSigma(binder, bindee, body) => {
                Type::DependentSigma(binder.clone(), Box::new(self.resolve_type_expr(bindee)), Box::new(self.resolve_type_expr(body)))
            }
            TypeExpr::Linear(inner) => Type::Linear(Box::new(self.resolve_type_expr(inner))),
            TypeExpr::Affine(inner) => Type::Affine(Box::new(self.resolve_type_expr(inner))),
            TypeExpr::Effectful(base_type_expr, effects) => {
                let base_type = self.resolve_type_expr(base_type_expr);
                Type::Effectful(Box::new(base_type), effects.clone())
            }
            TypeExpr::Universe(level) => Type::TypeUniverse(*level),
            TypeExpr::SankofaHistory(base_type_expr, _) => {
                let base_type = self.resolve_type_expr(base_type_expr);
                Type::History(Box::new(base_type), Box::new(Expression::Literal(Literal::Integer("0".to_string(), Span::dummy())))) // Simplified expr
            }
            TypeExpr::SankofaConsensus(base_type_expr) => {
                let base_type = self.resolve_type_expr(base_type_expr);
                Type::ConsensusTrue(Box::new(base_type))
            }
            TypeExpr::SankofaInterMemory(lang, base_type_expr) => {
                let base_type = self.resolve_type_expr(base_type_expr);
                Type::InterMemory(lang.clone(), Box::new(base_type))
            }
        }
    }

    /// Checks if a 'value_type' can be assigned to a 'target_type'.
    fn is_assignable(&self, target_type: &Type, value_type: &Type) -> bool {
        // Simple equality check for now, a real compiler would have subtyping, coercions, etc.
        target_type == value_type || target_type == &Type::Unknown || value_type == &Type::Error || target_type == &Type::Error
    }

    pub fn get_global_symbols(&self) -> &HashMap<String, Symbol> {
        &self.current_scope.symbols
    }
}
